### ISSUE TITLE
ImportError: /usr/lib/libtcmalloc.so.4: cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by wingsuit** [kyuupichan/electrumx#1010]
Hi,

This is not an issue with electrumx, I am just looking for a bit of insight into my own issue.

I took a working electrumx and migrated it to a Raspberry Pi 4 4GB. After setting it up as it was before, I am unable to run it due to this error:

> May 24 05:19:20 alarmpi electrumx-server[469]: INFO:electrumx:ElectrumX server starting
May 24 05:19:20 alarmpi electrumx-server[469]: INFO:electrumx:logging level: INFO
May 24 05:19:20 alarmpi electrumx-server[469]: INFO:Controller:Python version: 3.8.3 (default, May 19 2020, 23:52:23)  [GCC 9.3.0]
May 24 05:19:20 alarmpi electrumx-server[469]: INFO:Controller:software version: ElectrumX 1.14.0
May 24 05:19:20 alarmpi electrumx-server[469]: INFO:Controller:aiorpcX version: 0.18.4
May 24 05:19:20 alarmpi electrumx-server[469]: INFO:Controller:supported protocol versions: 1.4-1.4.2
May 24 05:19:20 alarmpi electrumx-server[469]: INFO:Controller:event loop policy: None
May 24 05:19:20 alarmpi electrumx-server[469]: INFO:Controller:reorg limit is 200 blocks
May 24 05:19:20 alarmpi electrumx-server[469]: INFO:Daemon:daemon #1 at 127.0.0.1:8332/ (current)
May 24 05:19:20 alarmpi electrumx-server[469]: INFO:DB:switching current directory to /srv/electrumx
May 24 05:19:20 alarmpi electrumx-server[469]: INFO:Controller:shutting down
May 24 05:19:20 alarmpi electrumx-server[469]: INFO:Controller:shutdown complete
May 24 05:19:20 alarmpi electrumx-server[469]: ERROR:electrumx:ElectrumX server terminated abnormally
May 24 05:19:20 alarmpi electrumx-server[469]: Traceback (most recent call last):
May 24 05:19:20 alarmpi electrumx-server[469]:   File "/usr/bin/electrumx-server", line 35, in main
May 24 05:19:20 alarmpi electrumx-server[469]:     asyncio.run(controller.run())
May 24 05:19:20 alarmpi electrumx-server[469]:   File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
May 24 05:19:20 alarmpi electrumx-server[469]:     return loop.run_until_complete(main)
May 24 05:19:20 alarmpi electrumx-server[469]:   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
May 24 05:19:20 alarmpi electrumx-server[469]:     return future.result()
May 24 05:19:20 alarmpi electrumx-server[469]:   File "/usr/lib/python3.8/site-packages/electrumx/lib/server_base.py", line 125, in run
May 24 05:19:20 alarmpi electrumx-server[469]:     await server_task
May 24 05:19:20 alarmpi electrumx-server[469]:   File "/usr/lib/python3.8/site-packages/electrumx/lib/server_base.py", line 98, in serve
May 24 05:19:20 alarmpi electrumx-server[469]:     await self.serve(shutdown_event)
May 24 05:19:20 alarmpi electrumx-server[469]:   File "/usr/lib/python3.8/site-packages/electrumx/server/controller.py", line 101, in serve
May 24 05:19:20 alarmpi electrumx-server[469]:     db = DB(env)
May 24 05:19:20 alarmpi electrumx-server[469]:   File "/usr/lib/python3.8/site-packages/electrumx/server/db.py", line 79, in __init__
May 24 05:19:20 alarmpi electrumx-server[469]:     self.db_class = db_class(self.env.db_engine)
May 24 05:19:20 alarmpi electrumx-server[469]:   File "/usr/lib/python3.8/site-packages/electrumx/server/storage.py", line 20, in db_class
May 24 05:19:20 alarmpi electrumx-server[469]:     db_class.import_module()
May 24 05:19:20 alarmpi electrumx-server[469]:   File "/usr/lib/python3.8/site-packages/electrumx/server/storage.py", line 76, in import_module
May 24 05:19:20 alarmpi electrumx-server[469]:     import plyvel
May 24 05:19:20 alarmpi electrumx-server[469]:   File "/usr/lib/python3.8/site-packages/plyvel/__init__.py", line 6, in <module>
May 24 05:19:20 alarmpi electrumx-server[469]:     from ._plyvel import (  # noqa
May 24 05:19:20 alarmpi electrumx-server[469]: ImportError: /usr/lib/libtcmalloc.so.4: cannot allocate memory in static TLS block
May 24 05:19:21 alarmpi systemd[1]: electrumx.service: Succeeded.`

Could anyone tell me what they think I've missed during the migration?

The Pi is running Archlinux Arm and electrumx was installed from the AUR. Resource limits were changed appropriately to suit the Pi.

**Comment by kyuupichan** [comment]
Forget RPIs, they don't have enough memory / swap

**Comment by wingsuit** [comment]
With the release of the 8GB (RAM) Pi 4, do you feel that it will now be possible to run Electrumx on one of these devices or do you foresee other limitations getting in the way?

**Comment by wingsuit** [comment]
To anyone else who experiences this, it can be solved by switching to RocksDB and building jemalloc with --disable-initial-exec-tls as seen in [this jemalloc issue](https://github.com/jemalloc/jemalloc/issues/1237).
