### ISSUE TITLE
BitcoinSegwit missing from coins.py in 1.15.0?

### ISSUE THREAD

**Issue by rmwb** [kyuupichan/electrumx#1012]
I just update to the new release and it looks like only BitcoinSV is supported by this project now?
Is that correct? Have all other coins been removed?

Error: electrumx.lib.coins.CoinError: unknown coin BitcoinSegwit and network mainnet combination

From Commit: 2ac23a29ab51fbfbb2b36a28dad36934819ddea0
https://github.com/kyuupichan/electrumx/commit/2ac23a29ab51fbfbb2b36a28dad36934819ddea0

-- 
Ross M. W. Bennetts
https://rossbennetts.com/

**Comment by rmwb** [comment]
Nevermind, I just found the new 'altcoin' branch.
https://github.com/kyuupichan/electrumx/tree/altcoin
Still, these seem to be some major changes with little to no documentation nor communication... #changemanagement

**Comment by benma** [comment]
How to kill a good project in one day.
