### ISSUE TITLE
BSV is trash.

### ISSUE THREAD

**Issue by BTCCRDZ** [kyuupichan/electrumx#1013]
why...

**Comment by BTCCRDZ** [comment]
Use BTC

**Comment by sketron1** [comment]
BSV is total trash

**Comment by h2o10** [comment]
developer received funds from BSV to take this step.

**Comment by sketron1** [comment]
Well I'll be switching to another wallet now...

**Comment by h2o10** [comment]
@sketron1  you don't have to do that.  Theres a fork at https://github.com/spesmilo/electrumx
