### ISSUE TITLE
Error in Changelog

### ISSUE THREAD

**Issue by accumulator** [kyuupichan/electrumx#1014]
The Note at the top of the changelog

https://electrumx.readthedocs.io/en/latest/changelog.html

.. erroneously claims that future releases are Bitcoin-only. This should be BitcoinSV only.

At least, that is what I conclude from the commit in https://github.com/kyuupichan/electrumx/commit/2ac23a29ab51fbfbb2b36a28dad36934819ddea0

**Comment by MalkavianBilbao** [comment]
BitcoinSV uses Bitcoin protocol defined in the whitepaper of Satoshi Nakamoto in 2008. BTC forked that protocol to other thing.

**Comment by DanielKrawisz** [comment]
Congratulations!
