### ISSUE TITLE
Litcoin support ?

### ISSUE THREAD

**Issue by iangregsondev** [kyuupichan/electrumx#1019]
Hi,

I was reading the docs and it seems going forward there will be no support for altcoins ?

So it will be bitcoin only plus bitcoin SV - is this correct?

So I was wondering if litecoin will no longer be supported ?

If it is supported, if I need to run both litcoin and bitcoin, should I run 2 different electrumx server to support the 2 different coins ?

is there any documentation of how to run it with litecoin - I presume there is some config to setup - but I couldn't find it

Thanks in advance.

**Comment by smmalis37** [comment]
The maintainer of this repo has decided that going forward this repo will only support Bitcoin SV, and no other coins. If you want support for Bitcoin, Litecoin, and others, you can switch to https://github.com/spesmilo/electrumx.

**Comment by iangregsondev** [comment]
Thanks @smmalis37.
