### ISSUE TITLE
ERROR:electrumx:ElectrumX server terminated abnormally

### ISSUE THREAD

**Issue by starinacool** [kyuupichan/electrumx#1035]
```
Oct 10 15:55:55 sphinx1 systemd[1]: Started Electrumx.
Oct 10 15:55:57 sphinx1 electrumx_server[7060]: INFO:electrumx:ElectrumX server starting
Oct 10 15:55:57 sphinx1 electrumx_server[7060]: INFO:electrumx:logging level: INFO
Oct 10 15:55:57 sphinx1 electrumx_server[7060]: INFO:Controller:Python version: 3.7.3 (default, Mar 27 2019, 22:11:17)  [GCC 7.3.0]
Oct 10 15:55:57 sphinx1 electrumx_server[7060]: INFO:Controller:software version: ElectrumX 1.15.0
Oct 10 15:55:57 sphinx1 electrumx_server[7060]: INFO:Controller:aiorpcX version: 0.18.3
Oct 10 15:55:57 sphinx1 electrumx_server[7060]: INFO:Controller:supported protocol versions: 1.4-1.4.2
Oct 10 15:55:57 sphinx1 electrumx_server[7060]: INFO:Controller:event loop policy: None
Oct 10 15:55:57 sphinx1 electrumx_server[7060]: INFO:Controller:reorg limit is 200 blocks
Oct 10 15:55:57 sphinx1 electrumx_server[7060]: INFO:Daemon:daemon #1 at 127.0.0.1:8332/ (current)
Oct 10 15:55:57 sphinx1 electrumx_server[7060]: INFO:DB:switching current directory to /home/bitcoin/electrumdb2
Oct 10 15:55:57 sphinx1 electrumx_server[7060]: INFO:DB:using rocksdb for DB backend
Oct 10 15:55:57 sphinx1 electrumx_server[7060]: INFO:DB:opened UTXO DB (for sync: True)
Oct 10 15:55:57 sphinx1 electrumx_server[7060]: INFO:DB:UTXO DB version: 8
Oct 10 15:55:57 sphinx1 electrumx_server[7060]: INFO:DB:coin: BitcoinSegwit
Oct 10 15:55:57 sphinx1 electrumx_server[7060]: INFO:DB:network: mainnet
Oct 10 15:55:57 sphinx1 electrumx_server[7060]: INFO:DB:height: 647,293
Oct 10 15:55:57 sphinx1 electrumx_server[7060]: INFO:DB:tip: 00000000000000000006a344bfc2c005cfd04c7968e3a4a3cd5cba135b1e6f44
Oct 10 15:55:57 sphinx1 electrumx_server[7060]: INFO:DB:tx count: 566,257,103
Oct 10 15:55:57 sphinx1 electrumx_server[7060]: INFO:DB:flushing DB cache at 1,200 MB
Oct 10 15:55:58 sphinx1 electrumx_server[7060]: INFO:History:history DB version: 1
Oct 10 15:55:58 sphinx1 electrumx_server[7060]: INFO:History:flush count: 65,535
Oct 10 15:56:05 sphinx1 electrumx_server[7060]: INFO:Controller:shutting down
Oct 10 15:56:05 sphinx1 electrumx_server[7060]: INFO:Controller:shutdown complete
Oct 10 15:56:05 sphinx1 electrumx_server[7060]: ERROR:electrumx:ElectrumX server terminated abnormally
Oct 10 15:56:05 sphinx1 electrumx_server[7060]: Traceback (most recent call last):
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:   File "/usr/local/bin/electrumx_server", line 35, in main
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:     asyncio.run(controller.run())
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:   File "/opt/python/lib/python3.7/asyncio/runners.py", line 43, in run
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:     return loop.run_until_complete(main)
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:   File "/opt/python/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:     return future.result()
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:   File "/opt/python/lib/python3.7/site-packages/electrumx/lib/server_base.py", line 125, in run
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:     await server_task
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:   File "/opt/python/lib/python3.7/site-packages/electrumx/lib/server_base.py", line 98, in serve
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:     await self.serve(shutdown_event)
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:   File "/opt/python/lib/python3.7/site-packages/electrumx/server/controller.py", line 134, in serve
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:     await group.spawn(wait_for_catchup())
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:   File "/opt/python/lib/python3.7/site-packages/aiorpcx/curio.py", line 242, in __aexit__
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:     await self.join()
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:   File "/opt/python/lib/python3.7/site-packages/aiorpcx/curio.py", line 211, in join
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:     raise task.exception()
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:   File "/opt/python/lib/python3.7/site-packages/electrumx/server/block_processor.py", line 677, in fetch_and_process_blocks
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:     await self._first_open_dbs()
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:   File "/opt/python/lib/python3.7/site-packages/electrumx/server/block_processor.py", line 657, in _first_open_dbs
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:     await self.db.open_for_sync()
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:   File "/opt/python/lib/python3.7/site-packages/electrumx/server/db.py", line 165, in open_for_sync
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:     await self._open_dbs(True, False)
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:   File "/opt/python/lib/python3.7/site-packages/electrumx/server/db.py", line 153, in _open_dbs
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:     await self._read_tx_counts()
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:   File "/opt/python/lib/python3.7/site-packages/electrumx/server/db.py", line 121, in _read_tx_counts
Oct 10 15:56:05 sphinx1 electrumx_server[7060]:     assert len(tx_counts) == size
Oct 10 15:56:05 sphinx1 electrumx_server[7060]: AssertionError
```
bitcoin-0.20.0
 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux

**Comment by kobrien** [comment]
Also seeing a similar this issue on our Litecoin nodes 

`INFO:electrumx:ElectrumX server starting
INFO:electrumx:logging level: INFO
INFO:Controller:Python version: 3.7.9 (default, Oct 22 2020, 05:22:26)  [GCC 9.3.0]
INFO:Controller:software version: ElectrumX 1.15.0
INFO:Controller:aiorpcX version: 0.18.4
INFO:Controller:supported protocol versions: 1.4-1.4.2
INFO:Controller:event loop policy: None
INFO:Controller:reorg limit is 4,000 blocks
INFO:Daemon:daemon #1 at litecoind:19332/ (current)
INFO:DB:switching current directory to /data
INFO:DB:using leveldb for DB backend
INFO:DB:opened UTXO DB (for sync: True)
INFO:DB:UTXO DB version: 8
INFO:DB:coin: Litecoin
INFO:DB:network: testnet
INFO:DB:height: 1,278,592
INFO:DB:tip: f8d9e00d283edb64143188c3d0df85383225e98f65ef0740e7aa5ee006ff6fdc
INFO:DB:tx count: 3,091,986
INFO:DB:flushing DB cache at 1,200 MB
INFO:History:history DB version: 1
INFO:History:flush count: 65,535
INFO:Controller:shutting down
INFO:Controller:shutdown complete
ERROR:electrumx:ElectrumX server terminated abnormally
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/electrumX-1.15.0-py3.7.egg/EGG-INFO/scripts/electrumx_server", line 35, in main
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/electrumX-1.15.0-py3.7.egg/electrumx/lib/server_base.py", line 125, in run
    await server_task
  File "/usr/local/lib/python3.7/site-packages/electrumX-1.15.0-py3.7.egg/electrumx/lib/server_base.py", line 98, in serve
    await self.serve(shutdown_event)
  File "/usr/local/lib/python3.7/site-packages/electrumX-1.15.0-py3.7.egg/electrumx/server/controller.py", line 134, in serve
    await group.spawn(wait_for_catchup())
  File "/usr/local/lib/python3.7/site-packages/aiorpcX-0.18.4-py3.7.egg/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/usr/local/lib/python3.7/site-packages/aiorpcX-0.18.4-py3.7.egg/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/usr/local/lib/python3.7/site-packages/electrumX-1.15.0-py3.7.egg/electrumx/server/block_processor.py", line 678, in fetch_and_process_blocks
    await self._first_open_dbs()
  File "/usr/local/lib/python3.7/site-packages/electrumX-1.15.0-py3.7.egg/electrumx/server/block_processor.py", line 658, in _first_open_dbs
    await self.db.open_for_sync()
  File "/usr/local/lib/python3.7/site-packages/electrumX-1.15.0-py3.7.egg/electrumx/server/db.py", line 159, in open_for_sync
    await self._open_dbs(True, False)
  File "/usr/local/lib/python3.7/site-packages/electrumX-1.15.0-py3.7.egg/electrumx/server/db.py", line 147, in _open_dbs
    await self._read_tx_counts()
  File "/usr/local/lib/python3.7/site-packages/electrumX-1.15.0-py3.7.egg/electrumx/server/db.py", line 115, in _read_tx_counts
    assert len(tx_counts) == size
AssertionError`

LTC v0.18.1
ElectrumX 1.15.0
Ubuntu 18.04 LTS

**Comment by ZacharyACoon** [comment]
This issue seems to be the same as this one:

https://github.com/spesmilo/electrumx/issues/92

**Comment by kyuupichan** [comment]
You need to run the electrumx_compact_history script.  Sorry the exception is lost.  I think this is fixed in git HEAD.
