### ISSUE TITLE
use tor for broadcast transactions while using clearnet for all others - possible?

### ISSUE THREAD

**Issue by monkey-jsun** [kyuupichan/electrumx#1036]
I have set up EPS (electrum personal server before) and now am migrating to ElectrumX for possibly better privacy by not using wallet feature inside bitcoin core.

One feature in EPS is to use Tor and only use Tor for broadcasting transactions (broadcast_method = tor).  This is a great feature as it disables any tracing my transaction back to my IP address.  Meanwhile we can keep bitcoin core connected with clear internet for full benefit and efficiency.

Is there a way to achieve the same with ElectrumX?   Or ElectrumX must broadcast transactions via its associated full node?  If the later is true, is there a config option in bitcoin core to broadcast our own transactions via tor only?

**Comment by kyuupichan** [comment]
It only broadcasts via the full node so that is the configuration that matters.  I am not familiar with your full node's broadcast options.
