### ISSUE TITLE
How to query blockchain.scripthash.listunspent

### ISSUE THREAD

**Issue by ashishchandr70** [kyuupichan/electrumx#1051]
Hi,

I am trying to invoke blockchain.scripthash.listunspent using` @mempool/electrum-client` for Node.js. The scripthash I am passing is `b8632325baef139001de769c9e2267d2c9d6e8140bb63e8f02bcff08809c579d`.

Using this scripthash, I am able to query the balance on our local test electrum node, as well as from test.whatsonchain.com. However, the moment I try to call `blockchain.scripthash.listunspent`, I get this error.

![image](https://user-images.githubusercontent.com/41921015/116951483-9e1b9880-ac4d-11eb-9488-bf61a8c8436d.png)

Furthermore, calling the whatsonchain.com API `curl --request GET "https://api.whatsonchain.com/v1/bsv/main/script/b8632325baef139001de769c9e2267d2c9d6e8140bb63e8f02bcff08809c579d/unspent"` also draws a blank.

What am I doing wrong?

Thanks

**Comment by kyuupichan** [comment]
From the message it seems you're passing 9 as a scripthash.

**Comment by kyuupichan** [comment]
Or perhaps you simply have too many UTXOs?

**Comment by kyuupichan** [comment]
Can you please clarify what network and coin you are using

**Comment by ashishchandr70** [comment]
Hi - it turns out it was an issue on my part. I was calling a batch function which was expecting an array of scripthashes vs. calling a non-batch version of the electrum-client.

Thanks for your prompt response.

Just FYI - this is on testnet and using BSV.
