### ISSUE TITLE
Support Prune mode

### ISSUE THREAD

**Issue by baryon** [kyuupichan/electrumx#1062]
I dont know Electrum's vision. but just worry that ElectrumX’s services may be interrupted next year because of the size of the block of BSV.

Would you have plan to support prune mode, reduce storage?
I wrote [a article](https://chainbow.medium.com/counterproductive-bitcoin-127940200d25) about the issue.

**Comment by kyuupichan** [comment]
ElectrumX doesn't store the transactions, bitcoind does.  It doesn't index unspendable outputs, so it's as efficient as it can be.  ElectrumX needs to be able to serve arbitrary transactions though, so the bitcoind it uses needs to store the whole chain.

**Comment by baryon** [comment]
I know ElectrumX don't store data just index it. Do ElectrumX support prune mode of node? Or must full mode?

**Comment by kyuupichan** [comment]
It doesn't care - but has no control over what your node prunes.  Electrum SV expects to be able to request any transaction in its wallet history so wouldn't work in many cases I expect
