### ISSUE TITLE
blockchain.transaction.get not working

### ISSUE THREAD

**Issue by dimdelizonas** [kyuupichan/electrumx#1065]
I try to use blockchain.transaction.get method but returns error {"jsonrpc": "2.0", "error": {"code": -32601, "message": "unknown method \"blockchain.transaction.get\""}, "id": 0}

what I use is 
import socket
import json
from time import sleep

port = 16520
host = 'localhost'

content = {
    "method": "blockchain.transaction.get",
    "params": ["af6df685465a42b753bf72dfdf36c43ea3c2931025411940609da6f2404b00c4", True],
    "id": 0
}

def electrumx(host, port, content):
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect((host, port))
    sock.sendall(json.dumps(content).encode('utf-8')+b'\n')
    sleep(0.5)
    sock.shutdown(socket.SHUT_WR)
    res = ""
    while True:
        data = sock.recv(1024)
        if (not data):
            break
        res += data.decode()
    print(res)
    sock.close()

electrumx(host, port, content)

**Comment by kralverde** [comment]
you are missing "jsonrpc":"2.0" in your `content` dictionary, though i don't think that would cause this error. do other methods give you the same error?

**Comment by kyuupichan** [comment]
You have to first do the connection handshake

**Comment by dimdelizonas** [comment]
how can I do the handshake?

**Comment by kyuupichan** [comment]
Please read the documentation https://electrumx.readthedocs.io/en/latest/
