### ISSUE TITLE
initial sync from genesis stopped

### ISSUE THREAD

**Issue by lahlor** [kyuupichan/electrumx#107]
Hi,

setting up a new electrumx node with external bitcoind in the same network the initial sync does stopped with the following error

Jan 21 12:06:18 electrumnode01 electrumx_server.py[2499]: INFO:BlockProcessor:tx/sec since genesis: 6,174, since last flush: 11,090
Jan 21 12:06:18 electrumnode01 electrumx_server.py[2499]: INFO:BlockProcessor:sync time: 0d 00h 43m 20s  ETA: 0d 06h 38m 57s
Jan 21 12:06:49 electrumnode01 electrumx_server.py[2499]: INFO:BlockProcessor:our height: 232,350 daemon: 449,302 UTXOs 962MB hist 109MB
Jan 21 12:07:19 electrumnode01 electrumx_server.py[2499]: INFO:BlockProcessor:our height: 233,118 daemon: 449,303 UTXOs 996MB hist 164MB
Jan 21 12:07:50 electrumnode01 electrumx_server.py[2499]: INFO:BlockProcessor:our height: 234,303 daemon: 449,303 UTXOs 1,060MB hist 249MB
Jan 21 12:07:50 electrumnode01 electrumx_server.py[2499]: INFO:BlockProcessor:flushed to FS in 0.1s
Jan 21 12:07:54 electrumnode01 electrumx_server.py[2499]: INFO:BlockProcessor:flushed history in 3.6s for 1,084,311 addrs
Jan 21 12:08:02 electrumnode01 systemd[1]: electrumx.service: Main process exited, code=killed, status=6/ABRT
Jan 21 12:08:02 electrumnode01 systemd[1]: electrumx.service: Unit entered failed state.
Jan 21 12:08:02 electrumnode01 systemd[1]: electrumx.service: Failed with result 'signal'.

Does anyone know why? Running Electrumx 0.10.9 on Ubuntu with 3.3 Ghz and 4 GB RAM on SSD.

cheers
lahlor

**Comment by kyuupichan** [comment]
I assume it works if you restart?  

systemd[1]: electrumx.service: Main process exited, code=killed, status=6/ABRT

not sure what systemd logging means, but that seems to day it had a SIGABRT.  They aren't generated by the Python process to the best of my knowledge

**Comment by lahlor** [comment]
Yes it worked after restart. But never seens this before so I thought it could be an issue with electrumx 0.10.9.
If it is system related I think we can close it.

**Comment by kyuupichan** [comment]
OK, I'll close it
