### ISSUE TITLE
having a hard time getting electrumx working

### ISSUE THREAD

**Issue by taspenwall** [kyuupichan/electrumx#1072]
I've compiled elecrumx and I'm having a hard time getting it to run.  I've been specifying env vars with export.  I'm trying to use my bitcoin node thats on mainnet.  I'm using COIN=BitcoinSegwit and NET=mainnet.  I'm getting an error `electrumx.lib.coins.CoinError: unknown coin BitcoinSegwit and network mainnet combination'  I've also tried just using COIN=Bitcoin and that doesn't work either.

I'm running a raspberry pi with debain sid.  I had to build electrumx in a venv.  I'm still not sure about using electrumx as a service but I'm pretty sure you can launch a python venv with systemd, just haven't learned the final points yet.  That means I'm trying to launch elecrtumx just using electrumx_server command.  My thinking was to get the program running 1st then figure out the systemd side of things.   Thanks Tom

**Comment by kyuupichan** [comment]
You're looking for https://github.com/spesmilo/electrumx/
