### ISSUE TITLE
Wrong Litecoin mainnet genesis block hash

### ISSUE THREAD

**Issue by petrkr** [kyuupichan/electrumx#108]
Coins.py uses bitcoin's genesis hash instead Litecoin's one, so new version will refuse catch up due bad genesis block hash.

https://hastebin.com/avihopoyar.diff

Petr

**Comment by santzi** [comment]
I just noticed same issue.
I started LTC electrumx from scratch, due to 0.10.9 version and the ElectrumX server jammed same issue.

**Comment by petrkr** [comment]
I forgot mention I made patch for it (that link) and it works after apply

**Comment by kyuupichan** [comment]
Yes I tightened the sanity checks. Can someone make a pull request?

**Comment by kyuupichan** [comment]
Applied, thanks.
