### ISSUE TITLE
How to configure ElectrumX to avoid fetching full history on subscription?

### ISSUE THREAD

**Issue by cuongd86** [kyuupichan/electrumx#1080]
Hi there,

I installed ElectrumX Server (v1.16.0) on my VPS. When I call a method `blockchain.scripthash.subscribe` to get notified about updates of specific address. I get an error below

`Error: {
    code: 1,
    message: "history too large"
}`

The address I'm subscribing to has more historical transactions than ElectrumX is configured to handle in a single request.
I checked environment variables in this page https://electrumx.readthedocs.io/en/latest/environment.html
But I dont know which one I should use to solve this problem.

**Comment by kyuupichan** [comment]
See the help for MAX_SEND

**Comment by cuongd86** [comment]
Dear Kyuupichan,

I also changed value to 350k but I still got the same error message.

values in conf file:

DB_DIRECTORY= /db_folder
DAEMON_URL= xxx:xxxx:xxxxx
SERVICES = tcp://127.0.0.1:500001
COIN = Bitcoin
PEER_DISCOVERY = off
COST_SOFT_LIMIT= 0
COST_HARD_LIMIT = 0
MAX_SEND = 350000

Everything looks good?

**Comment by kyuupichan** [comment]
Try making it like 10 million or something.  I have no idea how large your history is.

**Comment by cuongd86** [comment]
> Try making it like 10 million or something. I have no idea how large your history is.

Thank You, This way could bypass this problem
