### ISSUE TITLE
Allow switching of bitcoind (back to primary if on secondary)

### ISSUE THREAD

**Issue by SuBPaR42** [kyuupichan/electrumx#111]
If ElectrumX currently fails over to a secondary bitcoind (if configured) the only method to easily return to the primary bitcoind is restarting the ElectrumX server.  It would be nice to have a method that would force it to proceed to the next bitcoind in the .conf (assuming just 2 - would switch to first listed if a fail-over occurs).

**Comment by kyuupichan** [comment]
Thanks; I've updated the title.

**Comment by SuBPaR42** [comment]
Yes - better (more clear) title now

**Comment by kyuupichan** [comment]
Not really 😐 - no point being so precise with an RPC. I'll just provide one that replaces daemonurl that was in the env at startup, and starts from the beginning again round Robin. And if it defaults to the original daemonurl then it will have the effect of returning to primary. But far more flexible in general.
