### ISSUE TITLE
Client says server is lagging blocks but it is really not

### ISSUE THREAD

**Issue by DaSpawn** [kyuupichan/electrumx#115]
I have seen this issue a couple times now with 2 different version clients on 2 machines.  If I leave a client open and connected to manually specified server it will may see some lagging blocks but then it never updates to say it is not lagging anymore.  Restarting the client and reconnecting to same server shows green/synced.  There is no server or client errors.

**Comment by kyuupichan** [comment]
Let me know if you see it with a server running 0.10.16

**Comment by DaSpawn** [comment]
updated and running now, will keep an eye on. I will close this issue and reopen if issue again

Thanks!
