### ISSUE TITLE
Transaction with multiple inputs: error: Server did not answer

### ISSUE THREAD

**Issue by nomnombtc** [kyuupichan/electrumx#116]
Hello,

Somehow I can't send a transaction with multiple (small) inputs over my electrumx server (0.10.16).
The same transaction was sucessfully send via fireducks server (h.1209k.com).

Here is the transaction, not sure what the problem could be:
2caab0b9c6fab861aa70e305f1e3f00b0e4db9182ab8c89f6ad98ccf1ae1eda9

I've also seen someone on reddit with the same error message: https://www.reddit.com/r/Bitcoin/comments/5raxqs/electrum_error_server_did_not_answer/

**Comment by kyuupichan** [comment]
This will be down to differing configs of your bitcoind systems.  fireduck runs Bitcoin Unlimited FWIW

**Comment by nomnombtc** [comment]
Hmm, my server also runs BU, if it gets rejected by bitcoind would the error message not be different, it just says "error: Server did not answer" - the only uncommon config option I have is `whitelist=127.0.0.1/8, whitelistforcerelay=0` because I noticed nodes connected via tor (127.0.0.1) relaying dust tx, maybe this is causing it somehow?

But yeah okay, I just thought it might possibly be a bug, even better if it is not :) 
Anyway thanks for the very quick response.

**Comment by kyuupichan** [comment]
Perhaps, not sure. But I am certain this is happening on the bitcoind side, nothing to do with ElectrumX. Thanks.
