### ISSUE TITLE
Port error in parser?

### ISSUE THREAD

**Issue by emanuelelaface** [kyuupichan/electrumx#123]

**Comment by kyuupichan** [comment]
Hi, I assume you resolved this and that it was a problem in your configurtion.  If you give me details of what was wrong I might improve sanity checking somewhere to fail more clearly.

**Comment by emanuelelaface** [comment]
Sorry, I solved the second I sent the ticket.
The issue was that I haven’t bitcoind installed and running.
In the manual of Electrumx it is not mentioned that you have to connect to a bitcoind server. I assumed that the daemon was included and started by Electrumx. Maybe you can add it in the pre-requisites. I know it is obvious and stupid (now that I know) but maybe for a noob it can be helpful to know.
Thank anyway.
e.

On 12 Feb 2017, at 23:08, Neil <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I assume you resolved this and that it was a problem in your configurtion. If you give me details of what was wrong I might improve sanity checking somewhere to fail more clearly.
