### ISSUE TITLE
script.subscribe

### ISSUE THREAD

**Issue by ecdsa** [kyuupichan/electrumx#124]
add blockchain.script.subscribe to protocol

**Comment by kyuupichan** [comment]
@ecdsa - any interest in subscribing to the sha256 of the script instead?  It puts a limit on the subscription size.

You could do this for normal addresses for greater privacy of the user.  ElectrumX indexes via truncated sha256 so it's compatible without rebuilding the DB.

**Comment by ecdsa** [comment]
thanks!
