### ISSUE TITLE
AuxPow coins don't sync !

### ISSUE THREAD

**Issue by Infernoman** [kyuupichan/electrumx#127]
AuxCoins based off of namecoin, which should be almost all of them... Are unable to sync using electrumx. This doesn't concern verifying POW, but downloading the blockchain in general. I would love to use electrumx rather than electrum-server, considering the speed difference. If there is anything I can do to help along the way, I'll do my best to accommodate.

**Comment by kyuupichan** [comment]
Closing as redundant with #128 and #83.  As mentioned elsewhere; I will not implement this but am happy to accept a clean implementation from someone else.
