### ISSUE TITLE
Notify correctly if parent confirmed status of mempool txs changes

### ISSUE THREAD

**Issue by kyuupichan** [kyuupichan/electrumx#129]
If a mempool transaction touches an address, Electrum requires the address status to be a function of the confirmed / unconfirmed status of the transaction inputs.

In general this makes the address status a function of the confirmed state of transactions not touching the address itself, and hence it can potentially change as each new block is found. 

I don't believe electrum-server gets this subtlety correct either.  Fortunately it's not too hard to fix in ElectrumX.

**Comment by kyuupichan** [comment]
Fixing this I've just noticed ElectrumX had a bug and would always report parents as confirmed

**Comment by kyuupichan** [comment]
Confirmed fixed on testnet, where I sent myself some coins, and then sent those on to myself again but with 0 fee.  They correctly showed up as unconfirmed parent, and with the next block they didn't confirm but the parent did, and the status was updated from "unconfirmed parent" to "unconfirmed".

**Comment by gits7r** [comment]
I guess the result is the same if you send some coins from 2 inputs, (one confirmed, and one unconfirmed)? Because that was the problem originally thought (however after more testing confirmed to be a non synced mempool on server side at that particular case).

**Comment by gits7r** [comment]
Also, after the parent got confirmed the child switched to only Unconfirmed, but with 0 fee shouldn't it report Low fee / No fee?

**Comment by kyuupichan** [comment]
I believe ElectrumX works correctly. Please try connecting to one running version 0.99 on testnet or mainnet and try for yourself
