### ISSUE TITLE
Crash while handling RPC commands

### ISSUE THREAD

**Issue by bauerj** [kyuupichan/electrumx#13]
Nov 09 17:56:39 helicarrier electrumx_server.py[18592]: INFO:LocalRPC:connection from ('::1', 35076, 0, 0)
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]: Traceback (most recent call last):
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/home/electrumx/electrumx/server/protocol.py", line 125, in run_tasks
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:     await task.job
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/usr/lib/python3.5/asyncio/futures.py", line 363, in __iter__
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:     return self.result()  # May raise too.
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:     raise self._exception
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:     result = coro.send(None)
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/home/electrumx/electrumx/server/protocol.py", line 193, in request_handler
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:     result = await handler()
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/home/electrumx/electrumx/server/protocol.py", line 615, in getinfo
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:     'watched': ElectrumX.watched_address_count(),
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/home/electrumx/electrumx/server/protocol.py", line 334, in watched_address_count
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:     sessions = self.SESSION_MGR.sessions
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]: NameError: name 'self' is not defined
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]: Traceback (most recent call last):
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/home/electrumx/electrumx/electrumx_server.py", line 59, in main
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:     main_loop()
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/home/electrumx/electrumx/electrumx_server.py", line 46, in main_loop
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:     loop.run_until_complete(future)
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:     return future.result()
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:     raise self._exception
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:     result = coro.send(None)
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/home/electrumx/electrumx/server/block_processor.py", line 383, in main_loop
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:     await self._wait_for_update()
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/home/electrumx/electrumx/server/block_processor.py", line 401, in _wait_for_update
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:     await self.caught_up(mempool_hashes)
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/home/electrumx/electrumx/server/protocol.py", line 48, in caught_up
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:     ElectrumX.notify(self.height, self.touched)
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/home/electrumx/electrumx/server/protocol.py", line 353, in notify
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:     if height != session.notified_height:
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]: AttributeError: 'LocalRPC' object has no attribute 'notified_height'
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]: CRITICAL:root:ElectrumX server terminated abnormally
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]: ERROR:asyncio:Task was destroyed but it is pending!
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]: task: <Task pending coro=<SessionManager.run_tasks() running at /home/electrumx/electrumx/server/protocol.py:121> wait_for=<Future pending cb=[Task._wakeup()]>>
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]: Exception ignored in: <coroutine object SessionManager.run_tasks at 0x7f4510961678>
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]: Traceback (most recent call last):
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/home/electrumx/electrumx/server/protocol.py", line 121, in run_tasks
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/usr/lib/python3.5/asyncio/queues.py", line 170, in get
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/usr/lib/python3.5/asyncio/futures.py", line 227, in cancel
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/usr/lib/python3.5/asyncio/base_events.py", line 497, in call_soon
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]:   File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
	Nov 09 17:56:44 helicarrier electrumx_server.py[18592]: RuntimeError: Event loop is closed
	Nov 09 17:57:06 helicarrier systemd[1]: Stopped Electrumx.

**Comment by kyuupichan** [comment]
Thanks.  I was wondering whether to get rid of the RPC thing but I think I'll keep it as it's better than a log for detailed stats (which we don't have yet)
