### ISSUE TITLE
Enhancement: Client with testnet/mainnet confusion should be disconnected

### ISSUE THREAD

**Issue by shsmith** [kyuupichan/electrumx#132]
The client side of this issue is here:
https://github.com/spesmilo/electrum/issues/2149

Here is an example of the request sequence seen at the server:
```
INFO:ElectrumX:[15] processing {'params': [2], 'method': 'blockchain.block.get_chunk', 'id': 6676}
INFO:ElectrumX:[15] processing {'params': [1], 'method': 'blockchain.block.get_chunk', 'id': 6677}
INFO:ElectrumX:[15] processing {'params': [2], 'method': 'blockchain.block.get_chunk', 'id': 6678}
INFO:ElectrumX:[15] processing {'params': [1], 'method': 'blockchain.block.get_chunk', 'id': 6679}
INFO:ElectrumX:[15] processing {'params': [2], 'method': 'blockchain.block.get_chunk', 'id': 6680}
INFO:ElectrumX:[15] processing {'params': [1], 'method': 'blockchain.block.get_chunk', 'id': 6681}
INFO:ElectrumX:[15] processing {'params': [2], 'method': 'blockchain.block.get_chunk', 'id': 6682}
```
On the server side it should be possible to recognize a client requesting block 1 multiple times and consider this an "error" that will lead to disconnection.  As it is, clients can continue doing this forever, and though they are slowed by bandwidth limits, it still continues until the user realizes something is wrong and closes electrum.

Note that this doesn't happen on the "main" connection, as that is quickly disconnected due to incompatible address subscriptions.  It seems to happen only on "headers" connections that do not request data about specific addresses.

**Comment by kyuupichan** [comment]
What does a correct client without the headers code do? Start at 0, or at the end? If it starts at zero, we just nuke any client stepping backwards more than 2 or 3 chunks.

**Comment by kyuupichan** [comment]
I'm pretty sure clients build forwards, and only back up when confused

**Comment by shsmith** [comment]
You are correct. I loaded a testnet wallet that was a few days unused and it requested chunks going forward:
```
[Blockchain] validated chunk 539
[Blockchain] validated chunk 540

```
A client without any blockchain_headers does not use normal servers for the initial download.
So cutting off a client that is backing up seems sensible.

**Comment by kyuupichan** [comment]
So I propose to keep a per-session list of chunks requested. If it's length
is at least 2 and the requested chunk number is <= the maximum, drop the
connection with a log output.

**Comment by shsmith** [comment]
I just spotted this traceback with 0.9.1:
```
Feb 26 09:38:06 vps electrum: ERROR:ElectrumX:[9514] Traceback (most recent call last):
Feb 26 09:38:06 vps electrum:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.99.1-py3.5.egg/lib/jsonrpc.py", line 527, in process_single_request
Feb 26 09:38:06 vps electrum:     result = await self.handle_payload(payload, self.request_handler)
Feb 26 09:38:06 vps electrum:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.99.1-py3.5.egg/lib/jsonrpc.py", line 609, in handle_payload
Feb 26 09:38:06 vps electrum:     return handler(**kw_args)
Feb 26 09:38:06 vps electrum:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.99.1-py3.5.egg/server/session.py", line 278, in block_get_chunk
Feb 26 09:38:06 vps electrum:     raise RPCError(msg, JSONRPC.INVALID_REQUEST)
Feb 26 09:38:06 vps electrum: NameError: name 'JSONRPC' is not defined
```
