### ISSUE TITLE
Enhancement: Report daemon version in peers RPC

### ISSUE THREAD

**Issue by shsmith** [kyuupichan/electrumx#134]
On testnet if you have a segwit wallet and are connected to a non-segwit server, transactions are rejected with a cryptic error message:
```
---------------------------
Error
---------------------------
error: The transaction was rejected by network rules.  (16: bad-txns-vin-empty)
[01000000000101f35beb9abf489f8067147c867c5835ef8a665f55340c82b49a285cc20f8b0dd901000000171600147b4d0fb0278d7a14924f0794dd3177c0cad4f3b300000000014c8efa020000000017a914860183b7e27965f6782a1039afc1e64d56d7f38f870247304402202cc2c552b57c24b1dc2ae7638f394cb9d99d6eaad5be7aa51494842c2e1cc61e022035c2dbaa2863d94e1a92bca27a8c36e1c68b61336a4644428d576b592ab252800121039698fb8b17e4090f84188aebf0c9984437bfde8172c7eefea60e2c8d4ae6e9b200000000]
---------------------------
OK   
---------------------------
```
The same transaction goes through when connected to a server using bitcoin 0.13.2.
This is really a client issue, but servers do not currently give clients enough information to handle this in a better way.

**Comment by kyuupichan** [comment]
Well the client can and should interpret that error message and provide a better one. I don't want to do that server side. 

If you mean connecting to a server accepting Segwit txs, I'm happy to put that in the server.features and / or the data returned in server.peers.subscribe, but @ecdsa needs to let us know what he wants it to be. 

I'm not willing to put the daemon version in those places. This should be a simple boolean - I don't want features to change without an ElectrumX restart.

**Comment by shsmith** [comment]
Maybe a more generic way is to return the localservices value from the getnetworkinfo RPC. The client can parse that into bits to see if the segwit bit is set and that will continue to work as additional service bits are added in future versions.
```
bitcoin-cli getnetworkinfo
  "localservices": "000000000000000d",
```
The service bits are defined here: 
https://github.com/bitcoin/bitcoin/blob/c0ddd32bf629bb48426b0651def497ca1a78e6b1/src/protocol.h#L249-L270

**Comment by kyuupichan** [comment]
I can add that, sure.  The real name stuff uses a single prefix and unfortunately s and v are taken.  I could put this after lower case L I guess, for local services.  We could still do with some kind of flag to indicate RBF acceptance :(

**Comment by bauerj** [comment]
> The real name stuff uses a single prefix

I don't think this should support IRC at all. Servers would need to update to use this value so they would already have the new peer discovery.

**Comment by kyuupichan** [comment]
Fair enough, you're assuming existing software won't be updated. My assumption was that it might be.

**Comment by kyuupichan** [comment]
And also, this is how the current client receives everything, so they're isn't much of an alternative.

**Comment by bauerj** [comment]
Is there a way to extend that format in a backwards-compatible way?

**Comment by bauerj** [comment]
Apparently, that's possible.

**Comment by zzzyzy1** [comment]
what does "0xd"refers to?
bitcoin-cli getnetworkinfo 
    "localservices": "000000000000000d"

**Comment by zzzyzy1** [comment]
what does "0xd" mean?
bitcoin-cli getnetworkinfo
        "localservices": "000000000000000d"
I see 0xd, 0x9, 0x5 for ServiceFlags in peers.dat. What do these mean?
Is it the combination of ServiceFlags?(1+4, 1+8 or 1+4+8)?

**Comment by kyuupichan** [comment]
@shsmith I'm going to close this as I don't think this is a worthwhile change, and seems to have been mainly motivated by Segwit which is now in the past.  If you disagree feel free to re-open.
