### ISSUE TITLE
electrumx don't start 

### ISSUE THREAD

**Issue by freshonline** [kyuupichan/electrumx#143]
root@serv:~# systemctl start electrumx
Job for electrumx.service failed. See 'systemctl status electrumx.service' and 'journalctl -xn' for details.
root@serv:~# systemctl status electrumx.service
? electrumx.service - Electrumx
   Loaded: loaded (/etc/systemd/system/electrumx.service; disabled)
   Active: failed (Result: resources)

Feb 27 11:53:43 serv systemd[1]: Starting Electrumx...
Feb 27 11:53:43 serv systemd[1]: Failed to load environment f...y
Feb 27 11:53:43 serv systemd[1]: electrumx.service failed to ...y
Feb 27 11:53:43 serv systemd[1]: Failed to start Electrumx.

**Comment by bauerj** [comment]
Did you create the environment file (e.g. `/etc/electrumx.conf`)?

**Comment by kyuupichan** [comment]
Closing; no useful information
