### ISSUE TITLE
Getting error about REPORT_HOST if HOST is empty

### ISSUE THREAD

**Issue by erasmospunk** [kyuupichan/electrumx#161]
To reproduce, set env variables as normal except REPORT_HOST and `export HOST=`.

It crashes because of `Env::check_report_host(report_host)`:

```
Traceback (most recent call last):
  File "./electrumx_server.py", line 71, in main
    main_loop()
  File "./electrumx_server.py", line 52, in main_loop
    controller = Controller(Env())
  File "/coinomi/electrumx/server/env.py", line 75, in __init__
    self.check_report_host(report_host)
  File "/coinomi/electrumx/server/env.py", line 145, in check_report_host
    raise self.Error('{} is not a valid REPORT_HOST'.format(host))
server.env.Env.Error:  is not a valid REPORT_HOST
```

Similar thing happens when HOST=0.0.0.0, this was working before.

**Comment by kyuupichan** [comment]
John - perhaps I'm confused but REPORT_HOST is how you advertise yourself to others.  Neither 0.0.0.0 nor blank is valid.

Unless you don't wish to be public?

**Comment by erasmospunk** [comment]
I am having a problem with this as I don't easily have the host address (we run on docker).

Having an option for private indexers is nice I think, it should disable all peer functionality.

**Comment by kyuupichan** [comment]
You can set it arbitrarily and set PEER_DISCOVERY to blank. I'm open to an alternative approach if you can suggest one. 
Too many people were misconfiguring their setup that I wanted to catch the obvious ones early.

**Comment by erasmospunk** [comment]
I tried `export PEER_DISCOVERY=` but still see peers connecting.

From the docs I only see `DB_DIRECTORY` and `DAEMON_URL` args as mandatory.

**Comment by kyuupichan** [comment]
If peers are connecting you must have a publicly accessible address, and that was most likely known to the network at one moment, and you're still reachable there.  The network has a memory of reachable peers, and the network won't forget you until you're unreachable for about 3 days.

Those are the only 2 args mandatory for all configurations, yes.  But if you want an SSL server, for example, the SSL-related env vars are mandatory.

**Comment by kyuupichan** [comment]
I think the best thing here might be to merge the functionality of PEER_DISCOVERY into REPORT_HOST; I'll need to think about it.

**Comment by kyuupichan** [comment]
John - I've cleaned up identity handling; in particular REPORT_HOST no longer defaults to anything and needs to be explicitly set.  I will close this; please reopen if you think something could be done better.
