### ISSUE TITLE
AttributeError: module 'aiohttp' has no attribute 'ClientHttpProcessingError'

### ISSUE THREAD

**Issue by coinkraut** [kyuupichan/electrumx#163]
trying to install an electrumx server on vps ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-042stab116.1 x86_64)
thanks for any advice,
root@:~# service electrumx status
● electrumx.service - Electrumx
   Loaded: loaded (/etc/systemd/system/electrumx.service; disabled; vendor preset: enabled)
   Active: active (running) since Mi 2017-03-29 20:54:57 UTC; 22s ago
 Main PID: 30898 (electrumx_serve)
   CGroup: /system.slice/electrumx.service
           └─30898 /usr/bin/python3.6 /usr/local/bin/electrumx_server.py

Mär 29 20:54:58 xxxxx electrumx_server.py[30898]:     if not await self._prefetch_blocks():
Mär 29 20:54:58 xxxxx electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx
Mär 29 20:54:58 xxxxx electrumx_server.py[30898]:     daemon_height = await daemon.height(self.bp.caught_u
Mär 29 20:54:58 xxxxx electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx
Mär 29 20:54:58 xxxxx electrumx_server.py[30898]:     self._height = await self._send_single('getblockcoun
Mär 29 20:54:58xxxx electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx
Mär 29 20:54:58 xxxx electrumx_server.py[30898]:     return await self._send(payload, processor)
Mär 29 20:54:58 xxxx electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx
Mär 29 20:54:58 xxxx electrumx_server.py[30898]:     except aiohttp.ClientHttpProcessingError:
Mär 29 20:54:58 xxxx electrumx_server.py[30898]: AttributeError: module 'aiohttp' has no attribute 'Clien
lines 1-17/17 (END)...skipping...
● electrumx.service - Electrumx
   Loaded: loaded (/etc/systemd/system/electrumx.service; disabled; vendor preset: enabled)
   Active: active (running) since Mi 2017-03-29 20:54:57 UTC; 22s ago
 Main PID: 30898 (electrumx_serve)
   CGroup: /system.slice/electrumx.service
           └─30898 /usr/bin/python3.6 /usr/local/bin/electrumx_server.py

Mär 29 20:54:58 xxx electrumx_server.py[30898]:     if not await self._prefetch_blocks():
Mär 29 20:54:58 xxx electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-
Mär 29 20:54:58 xxx electrumx_server.py[30898]:     daemon_height = await daemon.height(self.bp.caught_up
Mär 29 20:54:58 xxx electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-
Mär 29 20:54:58 e electrumx_server.py[30898]:     self._height = await self._send_single('getblockcount
Mär 29 20:54:58 e electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-
Mär 29 20:54:58 e electrumx_server.py[30898]:     return await self._send(payload, processor)
Mär 29 20:54:58 eu electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-
Mär 29 20:54:58 e electrumx_server.py[30898]:     except aiohttp.ClientHttpProcessingError:
Mär 29 20:54:58 e electrumx_server.py[30898]: AttributeError: module 'aiohttp' has no attribute 'Client
~
root@euve252649:~# tail -f /var/log/syslog | grep -i electrumx
Mar 29 20:54:58 e electrumx_server.py[30898]:     if not await self._prefetch_blocks():
Mar 29 20:54:58 e electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrum-1.0.3-py3.6.egg/server/block_processor.py", line 87, in _prefetch_blocks
Mar 29 20:54:58 e electrumx_server.py[30898]:     daemon_height = await daemon.height(self.bp.caught_up_event.is_set())
Mar 29 20:54:58 e electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrum-1.0.3-py3.6.egg/server/daemon.py", line 226, in height
Mar 29 20:54:58 e electrumx_server.py[30898]:     self._height = await self._send_single('getblockcount')
Mar 29 20:54:58 e electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrum-1.0.3-py3.6.egg/server/daemon.py", line 151, in _send_single
Mar 29 20:54:58 eu electrumx_server.py[30898]:     return await self._send(payload, processor)
Mar 29 20:54:58 eu electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrum-1.0.3-py3.6.egg/server/daemon.py", line 117, in _send
Mar 29 20:54:58 e electrumx_server.py[30898]:     except aiohttp.ClientHttpProcessingError:
Mar 29 20:54:58 e electrumx_server.py[30898]: AttributeError: module 'aiohttp' has no attribute 'ClientHttpProcessingError'

Mär 29 20:54:58 electrumx_server.py[30898]: INFO:root:ElectrumX server starting
Mär 29 20:54:58 e electrumx_server.py[30898]: INFO:Daemon:daemon #1 at 127.0.0.1:8000/ (current)
Mär 29 20:54:58 e electrumx_server.py[30898]: INFO:BlockProcessor:switching current directory to var/electrumx
Mär 29 20:54:58 e electrumx_server.py[30898]: INFO:BlockProcessor:using leveldb for DB backend
Mär 29 20:54:58 e electrumx_server.py[30898]: INFO:BlockProcessor:opened DB for serving
Mär 29 20:54:58 e electrumx_server.py[30898]: INFO:BlockProcessor:closing DB to re-open for sync
Mär 29 20:54:58 e electrumx_server.py[30898]: INFO:BlockProcessor:opened DB for sync
Mär 29 20:54:58 e electrumx_server.py[30898]: INFO:BlockProcessor:software version: ElectrumX 1.0.3
Mär 29 20:54:58 eu electrumx_server.py[30898]: INFO:BlockProcessor:DB version: 5
Mär 29 20:54:58 e electrumx_server.py[30898]: INFO:BlockProcessor:coin: Bitcoin
Mär 29 20:54:58 eu electrumx_server.py[30898]: INFO:BlockProcessor:network: mainnet
Mär 29 20:54:58 e electrumx_server.py[30898]: INFO:BlockProcessor:height: -1
Mär 29 20:54:58 e electrumx_server.py[30898]: INFO:BlockProcessor:tip: 0000000000000000000000000000000000000000000000000000000000000000
Mär 29 20:54:58  electrumx_server.py[30898]: INFO:BlockProcessor:tx count: 0
Mär 29 20:54:58 eu electrumx_server.py[30898]: INFO:BlockProcessor:sync time so far: 00s
Mär 29 20:54:58 eu electrumx_server.py[30898]: INFO:BlockProcessor:reorg limit is 200 blocks
Mär 29 20:54:58 e electrumx_server.py[30898]: INFO:BlockProcessor:flushing DB cache at 1,200 MB
Mär 29 20:54:58 e electrumx_server.py[30898]: INFO:PeerManager:accepted 1/1 new peers of 1 from env
Mär 29 20:54:58 e electrumx_server.py[30898]: INFO:PeerManager:accepted 15/15 new peers of 15 from coins.py
Mär 29 20:54:58  electrumx_server.py[30898]: INFO:Controller:RPC server listening on localhost:8000
Mär 29 20:54:58 eu electrumx_server.py[30898]: INFO:LocalRPC:[0] RPC 127.0.0.1:34819, 1 total
Mär 29 20:54:58 e electrumx_server.py[30898]: INFO:LocalRPC:[1] RPC 127.0.0.1:34820, 2 total
Mär 29 20:54:58 e electrumx_server.py[30898]: INFO:LocalRPC:[0] cannot decode JSON: Expecting value: line 1 column 1 (char 0)
Mär 29 20:54:58 e electrumx_server.py[30898]: INFO:LocalRPC:[1] cannot decode JSON: Expecting value: line 1 column 1 (char 0)
Mär 29 20:54:58 eu electrumx_server.py[30898]: ERROR:Controller:Traceback (most recent call last):
Mär 29 20:54:58 eu electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.3-py3.6.egg/server/daemon.py", line 105, in _send
Mär 29 20:54:58 e electrumx_server.py[30898]:     result = await self._send_data(data)
Mär 29 20:54:58 e electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.3-py3.6.egg/server/daemon.py", line 74, in _send_data
Mär 29 20:54:58 e electrumx_server.py[30898]:     async with session.post(self.url(), data=data) as resp:
Mär 29 20:54:58 e electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/aiohttp-2.0.3-py3.6.egg/aiohttp/client.py", line 626, in __aenter__
Mär 29 20:54:58  electrumx_server.py[30898]:     self._resp = yield from self._coro
Mär 29 20:54:58 e electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/aiohttp-2.0.3-py3.6.egg/aiohttp/client.py", line 235, in _request
Mär 29 20:54:58 e electrumx_server.py[30898]:     yield from resp.start(conn, read_until_eof)
Mär 29 20:54:58 e electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/aiohttp-2.0.3-py3.6.egg/aiohttp/client_reqrep.py", line 528, in start
Mär 29 20:54:58 e electrumx_server.py[30898]:     (message, payload) = yield from self._protocol.read()
Mär 29 20:54:58 e electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/aiohttp-2.0.3-py3.6.egg/aiohttp/streams.py", line 489, in read
Mär 29 20:54:58  electrumx_server.py[30898]:     yield from self._waiter
Mär 29 20:54:58 9 electrumx_server.py[30898]: aiohttp.client_exceptions.ServerDisconnectedError
Mär 29 20:54:58  electrumx_server.py[30898]: During handling of the above exception, another exception occurred:
Mär 29 20:54:58  electrumx_server.py[30898]: Traceback (most recent call last):
Mär 29 20:54:58  electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.3-py3.6.egg/server/controller.py", line 160, in on_future_done
Mär 29 20:54:58  electrumx_server.py[30898]:     future.result()
Mär 29 20:54:58  electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.3-py3.6.egg/server/block_processor.py", line 197, in main_loop
Mär 29 20:54:58  electrumx_server.py[30898]:     await self.prefetcher.reset_height()
Mär 29 20:54:58  electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.3-py3.6.egg/server/block_processor.py", line 71, in reset_height
Mär 29 20:54:58 9 electrumx_server.py[30898]:     daemon_height = await self.bp.daemon.height()
Mär 29 20:54:58  electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.3-py3.6.egg/server/daemon.py", line 226, in height
Mär 29 20:54:58  electrumx_server.py[30898]:     self._height = await self._send_single('getblockcount')
Mär 29 20:54:58 e electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.3-py3.6.egg/server/daemon.py", line 151, in _send_single
Mär 29 20:54:58  electrumx_server.py[30898]:     return await self._send(payload, processor)
Mär 29 20:54:58  electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.3-py3.6.egg/server/daemon.py", line 117, in _send
Mär 29 20:54:58  electrumx_server.py[30898]:     except aiohttp.ClientHttpProcessingError:
Mär 29 20:54:58  electrumx_server.py[30898]: AttributeError: module 'aiohttp' has no attribute 'ClientHttpProcessingError'
Mär 29 20:54:58  electrumx_server.py[30898]: ERROR:Controller:Traceback (most recent call last):
Mär 29 20:54:58  electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.3-py3.6.egg/server/daemon.py", line 105, in _send
Mär 29 20:54:58  electrumx_server.py[30898]:     result = await self._send_data(data)
Mär 29 20:54:58  electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.3-py3.6.egg/server/daemon.py", line 74, in _send_data
Mär 29 20:54:58  electrumx_server.py[30898]:     async with session.post(self.url(), data=data) as resp:
Mär 29 20:54:58  electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/aiohttp-2.0.3-py3.6.egg/aiohttp/client.py", line 626, in __aenter__
Mär 29 20:54:58  electrumx_server.py[30898]:     self._resp = yield from self._coro
Mär 29 20:54:58  electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/aiohttp-2.0.3-py3.6.egg/aiohttp/client.py", line 235, in _request
Mär 29 20:54:58  electrumx_server.py[30898]:     yield from resp.start(conn, read_until_eof)
Mär 29 20:54:58  electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/aiohttp-2.0.3-py3.6.egg/aiohttp/client_reqrep.py", line 528, in start
Mär 29 20:54:58  electrumx_server.py[30898]:     (message, payload) = yield from self._protocol.read()
Mär 29 20:54:58  electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/aiohttp-2.0.3-py3.6.egg/aiohttp/streams.py", line 489, in read
Mär 29 20:54:58  electrumx_server.py[30898]:     yield from self._waiter
Mär 29 20:54:58  electrumx_server.py[30898]: aiohttp.client_exceptions.ServerDisconnectedError
Mär 29 20:54:58  electrumx_server.py[30898]: During handling of the above exception, another exception occurred:
Mär 29 20:54:58  electrumx_server.py[30898]: Traceback (most recent call last):
Mär 29 20:54:58  electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.3-py3.6.egg/server/controller.py", line 160, in on_future_done
Mär 29 20:54:58  electrumx_server.py[30898]:     future.result()
Mär 29 20:54:58  electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.3-py3.6.egg/server/block_processor.py", line 50, in main_loop
Mär 29 20:54:58  electrumx_server.py[30898]:     if not await self._prefetch_blocks():
Mär 29 20:54:58  electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.3-py3.6.egg/server/block_processor.py", line 87, in _prefetch_blocks
Mär 29 20:54:58  electrumx_server.py[30898]:     daemon_height = await daemon.height(self.bp.caught_up_event.is_set())
Mär 29 20:54:58 9 electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.3-py3.6.egg/server/daemon.py", line 226, in height
Mär 29 20:54:58  electrumx_server.py[30898]:     self._height = await self._send_single('getblockcount')
Mär 29 20:54:58 e9 electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.3-py3.6.egg/server/daemon.py", line 151, in _send_single
Mär 29 20:54:58  electrumx_server.py[30898]:     return await self._send(payload, processor)
Mär 29 20:54:58  electrumx_server.py[30898]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.3-py3.6.egg/server/daemon.py", line 117, in _send
Mär 29 20:54:58  electrumx_server.py[30898]:     except aiohttp.ClientHttpProcessingError:
Mär 29 20:54:58  electrumx_server.py[30898]: AttributeError: module 'aiohttp' has no attribute 'ClientHttpProcessingError'

My electrumx.conf is

DB_DIRECTORY = /var/electrumx
DAEMON_URL = http://electrumx:abcde@localhost:8332/
ELECTRUMX = /usr/local/bin/electrumx_server.py
USERNAME = electrumx
COIN = Bitcoin
NET = mainnet
DB_ENGINE = leveldb
REORG_LIMIT = 200
DONATION_ADDRESS = 
HOST =62.75......
TCP_PORT = 50001
SSL_PORT = 50002
SSL_CERTFILE = home/electrumx/server.crt
SSL_KEYFILE = home/electrumx/server.key
IRC =1

# bitcoin-cli getinfo
{
  "version": 140000,
  "protocolversion": 70015,
  "walletversion": 130000,
  "balance": 0.00000000,
  "blocks": 459680,
  "timeoffset": 0,
  "connections": 49,
  "proxy": "",
  "difficulty": 499635929816.6675,
  "testnet": false,
  "keypoololdest": 1489777982,
  "keypoolsize": 100,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": ""

bitcoin.conf

rpcuser=electrumx
rpcpassword=abcde                   
daemon=1
txindex=1
addressindex=1
spentindex=1
server=1

**Comment by bauerj** [comment]
Please install aiohttp 1.3 for now.

**Comment by kyuupichan** [comment]
wow, 2.0 is now the release version.  It was only 5 months ago they released 1.0 it seems.  I'll look into what's needed to support both.
