### ISSUE TITLE
LocalRPC:[251] cannot decode JSON: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by coinkraut** [kyuupichan/electrumx#170]
Hey, 
still trying to install electrumx. Now I get this:

xxxxxx:~# systemctl status --full --no-pager electrumx.service
● electrumx.service - Electrumx
   Loaded: loaded (/etc/systemd/system/electrumx.service; disabled; vendor preset: enabled)
   Active: active (running) since Fr 2017-04-14 17:17:31 UTC; 1min 21s ago
 Main PID: 7484 (electrumx_serve)
   CGroup: /system.slice/electrumx.service
           └─7484 /usr/bin/python3.6 /usr/local/bin/electrumx_server.py
xxxx:~# journalctl -u electrumx -f
-- Logs begin at Sa 2017-04-08 10:35:06 UTC. --
Apr 14 17:19:37 euve252649 electrumx_server.py[7484]: INFO:LocalRPC:[248] cannot decode JSON: Expecting value: line 1 column 1 (char 0)
Apr 14 17:19:37 xxxx electrumx_server.py[7484]: INFO:LocalRPC:[249] cannot decode JSON: Expecting value: line 1 column 1 (char 0)
Apr 14 17:19:38  electrumx_server.py[7484]: INFO:LocalRPC:[250] RPC 127.0.0.1:59696, 1 total
Apr 14 17:19:38  electrumx_server.py[7484]: INFO:LocalRPC:[251] RPC 127.0.0.1:59698, 2 total
Apr 14 17:19:38  electrumx_server.py[7484]: INFO:LocalRPC:[250] cannot decode JSON: Expecting value: line 1 column 1 (char 0)
Apr 14 17:19:38  electrumx_server.py[7484]: INFO:LocalRPC:[251] cannot decode JSON: Expecting value: line 1 column 1 (char 0)
Apr 14 17:19:39  electrumx_server.py[7484]: INFO:LocalRPC:[252] RPC 127.0.0.1:59700, 1 total
Apr 14 17:19:39  electrumx_server.py[7484]: INFO:LocalRPC:[253] RPC 127.0.0.1:59702, 2 total
Apr 14 17:19:39  electrumx_server.py[7484]: INFO:LocalRPC:[252] cannot decode JSON: Expecting value: line 1 column 1 (char 0)
Apr 14 17:19:39  electrumx_server.py[7484]: INFO:LocalRPC:[253] cannot decode JSON: Expecting value: line 1 column 1 (char 0)

thanks for any advice

**Comment by bauerj** [comment]
Set the right port for the coin daemon.

**Comment by coinkraut** [comment]
hey,
I am somehow lost.Electrumx and bitcoin node on the same server. 
electrumx is running.Bitcoin node is running

electrumx_rpc.py getinfo
{
    "closing": 0,
    "daemon": "localhost:8000/",
    "daemon_height": null,
    "db_height": -1,
    "errors": 0,
    "groups": 97,
    "logged": 0,
    "paused": 0,
    "peers": {
        "bad": 0,
        "good": 0,
        "never": 14,
        "stale": 0,
        "total": 14
    },
    "pid": 7771,
    "requests": 0,
    "sessions": 1,
    "subs": 0,
    "txs_sent": 0,
    "uptime": "1d 00h 06m"

etc/electrumx.conf is

DB_DIRECTORY = /var/electrumx
DAEMON_URL = http://electrumx:1234567@localhost:8000/
ELECTRUMX = /usr/local/bin/electrumx_server.py
USERNAME = electrumx
COIN = Bitcoin
NET = mainnet
DB_ENGINE = leveldb
REORG_LIMIT = 200
DONATION_ADDRESS = 
HOST =62.75......
TCP_PORT = 50001
SSL_PORT = 50002
SSL_CERTFILE = home/electrumx/server.crt
SSL_KEYFILE = home/electrumx/server.key
IRC =1

bitcoin.conf is: 
rpcuser=electrumx
rpcpassword=1234567                      
daemon=1
txindex=1
addressindex=1
spentindex=1
server=1
rpcbind=127.0.0.1:8ooo/
rpcallowip=127.0.0.1

getting:
Apr 15 20:08:46 euve252649 electrumx_server.py[7771]: INFO:LocalRPC:[172858] cannot decode JSON: Expecting value: line 1 column 1 (char 0)
Apr 15 20:08:46 euve252649 electrumx_server.py[7771]: INFO:LocalRPC:[172859] cannot decode JSON: Expecting value: line 1 column 1 (char 0)
Apr 15 20:08:47 euve252649 electrumx_server.py[7771]: INFO:LocalRPC:[172860] RPC 127.0.0.1:49924, 1 total
Apr 15 20:08:47 euve252649 electrumx_server.py[7771]: INFO:LocalRPC:[172860] cannot decode JSON: Expecting value: line 1 column 1 (char 0)
Whats the expected value : line 1 column 1 (char 0)??

where is the rub?
thanks

**Comment by bauerj** [comment]
> rpcbind=127.0.0.1:8ooo/

Huh?

**Comment by coinkraut** [comment]
Delated in bitcoin.conf
rpcbind=127.0.0.1:8ooo/
rpcallowip=127.0.0.1l
but still getting 
 INFO:LocalRPC:[xxxxxx] cannot decode JSON: Expecting value: line 1 column 1 (char 0)
I am no coder, so I have to proceed  more or less empirical.

**Comment by bauerj** [comment]
Why do you use an `o` instead of a `0` in the port? Why is there an `l` at the end of rpcallowip?

Please test this:

    export $(cat /etc/electrumx.conf )
    curl $DAEMON_URL
    bitcoin-cli getinfo

**Comment by kyuupichan** [comment]
The messages you are posting are complaining about LocalRPC connections.  I have no idea how you are triggering those, but without your own code it should only be via electrumx_rpc.py.  And I've not heard anyone complain that doesn't work as expected.

From your posted snippets your setup isn't too clear.  You probably have confused port setup in your config so that something is connecting to your e-x RPC port rather than something else it should be, for example your bitcoind RPC port.

**Comment by coinkraut** [comment]
thanks for your advice,checked all 0

root@e.......:~# bitcoin-cli getinfo
{
  "version": 140000,
  "protocolversion": 70015,
  "walletversion": 130000,
  "balance": 0.00000000,
  "blocks": 462291,
  "timeoffset": 0,
  "connections": 42,
  "proxy": "",
  "difficulty": 520808749422.1398,
  "testnet": false,
  "keypoololdest": 1489777982,
  "keypoolsize": 100,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": ""
}

root@e.......:~# cat /etc/electrumx.conf
DB_DIRECTORY = var/electrumx
DAEMON_URL = http://electrumx:1234567@127.0.0.1:8000/
ELECTRUMX = /usr/local/bin/electrumx_server.py
USERNAME = electrumx
COIN = Bitcoin
NET = mainnet
DB_ENGINE = leveldb
REORG_LIMIT = 200
DONATION_ADDRESS = 
HOST =62.......1
TCP_PORT = 50001
SSL_PORT = 50002
SSL_CERTFILE = home/electrumx/server.crt
SSL_KEYFILE = home/electrumx/server.key
IRC =1
MAX_SUBS = 250000
MAX_SESSION_SUBS = 50000
MAX_SEND = 5000000
BANDWIDTH_LIMIT = 100000000
SESSION_TIMEOUT = 1800
MAX_SESSIONS = 2000
  
root@e.......:~# curl http://electrumx:1234567@localhost:8000/
{"jsonrpc": "2.0", "id": null, "error": {"message": "cannot decode JSON: Expecting value: line 1 column 1 (char 0)", "code": -32700}}

root@euve252649:~# export
declare -x BANDWIDTH_LIMIT
declare -x Bitcoin
declare -x COIN
declare -x DAEMON_URL
declare -x DB_DIRECTORY
declare -x DB_ENGINE
declare -x DONATION_ADDRESS
declare -x ELECTRUMX
declare -x HOME="/root"
declare -x HOST
declare -x IRC
declare -x LANG="de_DE.UTF-8"
declare -x LESSCLOSE="/usr/bin/lesspipe %s %s"
declare -x LESSOPEN="| /usr/bin/lesspipe %s"
declare -x LOGNAME="root"
declare -x LS_COLORS=
declare -x MAIL="/var/mail/root"
declare -x MAX_SEND
declare -x MAX_SESSIONS
declare -x MAX_SESSION_SUBS
declare -x MAX_SUBS
declare -x NET
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
declare -x PWD="/root"
declare -x REORG_LIMIT
declare -x SESSION_TIMEOUT
declare -x SHELL="/bin/bash"
declare -x SHLVL="1"
declare -x SSH_CLIENT="9.....2"
declare -x SSH_CONNECTION="92........... 62........2"
declare -x SSH_TTY="/dev/pts/0"
declare -x SSL_CERTFILE
declare -x SSL_KEYFILE
declare -x SSL_PORT
declare -x TCP_PORT
declare -x TERM="xterm"
declare -x USER="root"
declare -x USERNAME
declare -x electrumx
declare -x leveldb
declare -x mainnet

**Comment by bauerj** [comment]
Okay, so electrumx is querying itself for the blockchain data.

That, of course, doesn't work. Please change port 8000 in the URL to the one from bitcoind, e.g. 8332.

**Comment by katty1128** [comment]
I am also facing an error on electrumx_rpc.py getinfo. 
It say error: request timed out (code -102)
