### ISSUE TITLE
CRITICAL:root:ElectrumX server terminated abnormally

### ISSUE THREAD

**Issue by stone212** [kyuupichan/electrumx#172]
I am running an electrumx server on Debian unstable.  It seemed to be working great for a while.  Then I did a somewhat careless apt-get upgrade and I don't know if that is why, but I started having the following problem:

When I restart the server, it initially looks like it's working fine.  If I type "service electrumx status" immediately after "service electrumx restart" then I get happy results.  (However this does not happen all the time, so I can't post the happy results unless you need that, and I will make it happen.)

But in any case, just a few seconds later, it craps out and "$ service electrumx status" produces the following:

> Apr 26 01:45:54 carmen electrumx_server.py[16977]:   File "/home/electrumx/electrumx/electrumx_server.py", line 
Apr 26 01:45:54 carmen electrumx_server.py[16977]:     controller = Controller(Env())
Apr 26 01:45:54 carmen electrumx_server.py[16977]:   File "/home/electrumx/electrumx/server/controller.py", line
Apr 26 01:45:54 carmen electrumx_server.py[16977]:     self.bp = BlockProcessor(env, self, self.daemon)
Apr 26 01:45:54 carmen electrumx_server.py[16977]:   File "/home/electrumx/electrumx/server/block_processor.py",
Apr 26 01:45:54 carmen electrumx_server.py[16977]:     super().__init__(env)
Apr 26 01:45:54 carmen electrumx_server.py[16977]:   File "/home/electrumx/electrumx/server/db.py", line 87, in 
Apr 26 01:45:54 carmen electrumx_server.py[16977]:     assert self.db_tx_count == self.tx_counts[-1]
Apr 26 01:45:54 carmen electrumx_server.py[16977]: AssertionError
Apr 26 01:45:54 carmen electrumx_server.py[16977]: CRITICAL:root:ElectrumX server terminated abnormally

Do those errors make you think of any particular module or library?  If so, then maybe my apt-get upgrade is the culprit.  In any case, any pointers would be appreciated.  If you need any other information, I will provided it.  

Please note that bitcoind seems to be running just fine.

Thank you.

**Comment by kyuupichan** [comment]
This is a startup failure which indicates corruption in the DB + metadata.  I'm afraid I cannot guess at the cause.  You probably need to clear the DB and restart from scratch.

**Comment by stone212** [comment]
Yes, that worked.  Took a couple of days to re-sync and confirm but the server is up and running again.  I wonder what caused the DB error in the first place?
