### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by whizz** [kyuupichan/electrumx#179]
I am trying to initialize electrumx server. It has been running for about a day and it's at height around 421000 now. The issue I have is, I have about 2G RAM available for the process itself. The server starts up, eats about 1G of RAM and then the memory usage keeps increasing, until it crashes, presumably because it runs out of memory (the server has no swap). When it restarts, it takes now about 30 minutes to recover the database. I have deliberately decreased the cache size to 64M, so that I do not lose too much indexed work when it crashes.

I am running ElectrumX 1.0.10 on CentOS 7, Python 3.6.1. This is my config:

DB_DIRECTORY=/home/electrumx/electrumx
DAEMON_URL=rpcuser:***@localhost
ELECTRUMX=/usr/bin/electrumx_server.py
USERNAME=electrumx
HOST=
SSL_PORT=50002
DONATION_ADDRESS=***
CACHE_MB=64

**Comment by kyuupichan** [comment]
What CACHE_MB was it when it was failing?  With 2GB RAM you should be able to get away with 800 as CACHE_MB.  But as the docs say; it's not a hard limit and only checked periodically.  LevelDB, Python overhead and others take up considerable RAM too.

Certainly 64 is way too pessimistic.  Try 500 if cautious.

**Comment by kyuupichan** [comment]
I'm going to close this as I think it's very likely you were just running your machine to close to the bone with no slack owing to no swap space.
