### ISSUE TITLE
Litecoin: assert len(self.binary) >= end

### ISSUE THREAD

**Issue by santzi** [kyuupichan/electrumx#181]
Hi,

I noticed that my ElectrumX Litecoin server was crashed (using LevelDB).
So I thought that DB was corrupted, because it crashed every start.
So I took my couple of days old DB backup and it crashed again to same reason.
I think my backup is also corrupted. So I started DB from scratch...it took about 1 hour, so it's not problem to do it again. (thanks for ElectrumX). When DB is done, it crashed to same think again.

This log is from with original DB:
May 12 18:54:33 ubuntu systemd[1]: Started Electrumx.
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:root:ElectrumX server starting
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:Daemon:daemon #1 at 172.16.238.1:9332/ (current)
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:BlockProcessor:switching current directory to /home/jani/debian_shares/electrumx_db/LTC/
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:BlockProcessor:using leveldb for DB backend
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:BlockProcessor:opened DB for serving
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:BlockProcessor:software version: ElectrumX 1.0.9
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:BlockProcessor:DB version: 5
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:BlockProcessor:coin: Litecoin
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:BlockProcessor:network: mainnet
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:BlockProcessor:height: 1,201,153
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:BlockProcessor:tip: 25f77543e9214b5f6465ff0ede2976dedce2b642ee0711c900c4c9c93b92fa41
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:BlockProcessor:tx count: 9,714,400
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:BlockProcessor:deleted 10 stale undo entries
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:BlockProcessor:reorg limit is 150 blocks
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:PeerManager:accepted new peer 1/1 electrum-ltc.ddns.net from env
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:PeerManager:accepted new peer 1/17 electrum-ltc.wilv.in from peers file
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:PeerManager:accepted new peer 2/17 electrum-ltc.neocrypto.io from peers file
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:PeerManager:accepted new peer 3/17 eywr5eubdbbe2laq.onion from peers file
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:PeerManager:accepted new peer 4/17 5h4tftmqfmav7gp4.onion from peers file
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:PeerManager:accepted new peer 5/17 elec.luggs.co from peers file
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:PeerManager:accepted new peer 6/17 o6nvntbo3qsn36dm.onion from peers file
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:PeerManager:accepted new peer 7/17 luggscoqbymhvnkp.onion from peers file
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:PeerManager:accepted new peer 8/17 electrum-ltc.villocq.com from peers file
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:PeerManager:accepted new peer 9/17 e.anonyhost.org from peers file 
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:PeerManager:accepted new peer 10/17 electrum.ltc.xurious.com from peers file
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:PeerManager:accepted new peer 11/17 laodcltc23nym3vx.onion from peers file 
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:PeerManager:accepted new peer 12/17 fsk2e2ediqjkzkwl.onion from peers file  
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:PeerManager:accepted new peer 13/17 electrum.cryptomachine.com from peers file
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:PeerManager:accepted new peer 14/17 electrum-ltc0.snel.it from peers file
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:PeerManager:accepted new peer 15/17 ltc.ex.laodc.com from peers file
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:PeerManager:accepted new peer 16/17 electrum-ltc.petrkr.net from peers file
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:PeerManager:accepted new peer 17/17 electrum-ltc.bysh.me from peers file
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:Controller:RPC server listening on localhost:8000
May 12 18:54:33 ubuntu electrumx_server.py[15639]: INFO:Prefetcher:catching up to daemon height 1,202,766 (1,613 blocks behind)
May 12 18:54:35 ubuntu electrumx_server.py[15639]: INFO:BlockProcessor:our height: 1,201,163 daemon: 1,202,766 UTXOs 0MB hist 0MB
May 12 18:54:35 ubuntu electrumx_server.py[15639]: INFO:BlockProcessor:processed 10 blocks in 1.8s
May 12 18:54:36 ubuntu electrumx_server.py[15639]: ERROR:Controller:Traceback (most recent call last):
May 12 18:54:36 ubuntu electrumx_server.py[15639]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/server/controller.py", line 160, in on_future_done
May 12 18:54:36 ubuntu electrumx_server.py[15639]:     future.result()
May 12 18:54:36 ubuntu electrumx_server.py[15639]:   File "/usr/local/lib/python3.5/asyncio/futures.py", line 293, in result
May 12 18:54:36 ubuntu electrumx_server.py[15639]:     raise self._exception
May 12 18:54:36 ubuntu electrumx_server.py[15639]:   File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
May 12 18:54:36 ubuntu electrumx_server.py[15639]:     result = coro.send(None)
May 12 18:54:36 ubuntu electrumx_server.py[15639]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/server/block_processor.py", line 201, in main_loop
May 12 18:54:36 ubuntu electrumx_server.py[15639]:     await task()
May 12 18:54:36 ubuntu electrumx_server.py[15639]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/server/block_processor.py", line 236, in check_and_advance_blocks
May 12 18:54:36 ubuntu electrumx_server.py[15639]:     for n, block in enumerate(blocks)]
May 12 18:54:36 ubuntu electrumx_server.py[15639]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/server/block_processor.py", line 236, in <listcomp>
May 12 18:54:36 ubuntu electrumx_server.py[15639]:     for n, block in enumerate(blocks)]
May 12 18:54:36 ubuntu electrumx_server.py[15639]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/lib/coins.py", line 265, in block_full
May 12 18:54:36 ubuntu electrumx_server.py[15639]:     txs = deserializer(block[len(header):]).read_tx_block()
May 12 18:54:36 ubuntu electrumx_server.py[15639]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/lib/tx.py", line 112, in read_tx_block
May 12 18:54:36 ubuntu electrumx_server.py[15639]:     txs = [read_tx() for _ in range(self._read_varint())]
May 12 18:54:36 ubuntu electrumx_server.py[15639]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/lib/tx.py", line 112, in <listcomp>
May 12 18:54:36 ubuntu electrumx_server.py[15639]:     txs = [read_tx() for _ in range(self._read_varint())]
May 12 18:54:36 ubuntu electrumx_server.py[15639]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/lib/tx.py", line 104, in read_tx
May 12 18:54:36 ubuntu electrumx_server.py[15639]:     self._read_inputs(),    # inputs
May 12 18:54:36 ubuntu electrumx_server.py[15639]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/lib/tx.py", line 118, in _read_inputs
May 12 18:54:36 ubuntu electrumx_server.py[15639]:     return [read_input() for i in range(self._read_varint())]
May 12 18:54:36 ubuntu electrumx_server.py[15639]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/lib/tx.py", line 118, in <listcomp>
May 12 18:54:36 ubuntu electrumx_server.py[15639]:     return [read_input() for i in range(self._read_varint())]
May 12 18:54:36 ubuntu electrumx_server.py[15639]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/lib/tx.py", line 124, in _read_input
May 12 18:54:36 ubuntu electrumx_server.py[15639]:     self._read_varbytes(),   # script
May 12 18:54:36 ubuntu electrumx_server.py[15639]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/lib/tx.py", line 145, in _read_varbytes
May 12 18:54:36 ubuntu electrumx_server.py[15639]:     return self._read_nbytes(self._read_varint())
May 12 18:54:36 ubuntu electrumx_server.py[15639]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/lib/tx.py", line 141, in _read_nbytes
May 12 18:54:36 ubuntu electrumx_server.py[15639]:     assert len(self.binary) >= end
May 12 18:54:36 ubuntu electrumx_server.py[15639]: AssertionError

ElectrumX LevelDB started from scratch and crash occurred again:

May 12 19:43:57 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:flushed to FS in 1.3s
May 12 19:43:59 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:flushed history in 2.0s for 249,784 addrs
May 12 19:44:00 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:flush #49 took 3.4s.  Height 1,118,910 txs: 8,996,682
May 12 19:44:00 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:tx/sec since genesis: 3,233, since last flush: 4,491
May 12 19:44:00 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:sync time: 46m 22s  ETA: 03m 23s
May 12 19:44:30 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:our height: 1,135,410 daemon: 1,202,790 UTXOs 95MB hist 34MB
May 12 19:45:04 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:our height: 1,153,910 daemon: 1,202,791 UTXOs 120MB hist 62MB
May 12 19:45:05 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:flushed to FS in 1.5s
May 12 19:45:07 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:flushed history in 2.0s for 262,898 addrs
May 12 19:45:07 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:flush #50 took 3.6s.  Height 1,153,910 txs: 9,233,479
May 12 19:45:07 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:tx/sec since genesis: 3,239, since last flush: 3,494
May 12 19:45:07 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:sync time: 47m 30s  ETA: 02m 28s
May 12 19:45:38 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:our height: 1,172,410 daemon: 1,202,791 UTXOs 140MB hist 44MB
May 12 19:45:39 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:flushed to FS in 0.6s
May 12 19:45:40 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:flushed history in 1.1s for 202,806 addrs
May 12 19:45:40 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:flush #51 took 1.8s.  Height 1,172,410 txs: 9,346,663
May 12 19:45:40 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:tx/sec since genesis: 3,242, since last flush: 3,485
May 12 19:45:40 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:sync time: 48m 02s  ETA: 01m 31s
May 12 19:46:12 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:our height: 1,182,410 daemon: 1,202,792 UTXOs 156MB hist 39MB
May 12 19:46:42 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:our height: 1,192,910 daemon: 1,202,792 UTXOs 169MB hist 71MB
May 12 19:46:43 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:flushed to FS in 1.0s
May 12 19:46:46 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:flushed history in 2.3s for 326,014 addrs
May 12 19:46:49 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:flushed 152,500 blocks with 1,112,373 txs, 581,960 UTXO adds, 440,916 spends in 3.1s, committing...
May 12 19:47:05 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:flush #52 took 22.7s.  Height 1,192,910 txs: 9,577,361
May 12 19:47:05 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:tx/sec since genesis: 3,226, since last flush: 2,710
May 12 19:47:05 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:sync time: 49m 27s  ETA: 37s
May 12 19:47:36 ubuntu electrumx_server.py[15728]: INFO:BlockProcessor:our height: 1,199,410 daemon: 1,202,792 UTXOs 32MB hist 37MB
May 12 19:47:55 ubuntu electrumx_server.py[15728]: ERROR:Controller:Traceback (most recent call last):
May 12 19:47:55 ubuntu electrumx_server.py[15728]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/server/controller.py", line 160, in on_future_done
May 12 19:47:55 ubuntu electrumx_server.py[15728]:     future.result()
May 12 19:47:55 ubuntu electrumx_server.py[15728]:   File "/usr/local/lib/python3.5/asyncio/futures.py", line 293, in result
May 12 19:47:55 ubuntu electrumx_server.py[15728]:     raise self._exception
May 12 19:47:55 ubuntu electrumx_server.py[15728]:   File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
May 12 19:47:55 ubuntu electrumx_server.py[15728]:     result = coro.send(None)
May 12 19:47:55 ubuntu electrumx_server.py[15728]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/server/block_processor.py", line 201, in main_loop
May 12 19:47:55 ubuntu electrumx_server.py[15728]:     await task()
May 12 19:47:55 ubuntu electrumx_server.py[15728]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/server/block_processor.py", line 236, in check_and_advance_blocks
May 12 19:47:55 ubuntu electrumx_server.py[15728]:     for n, block in enumerate(blocks)]
May 12 19:47:55 ubuntu electrumx_server.py[15728]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/server/block_processor.py", line 236, in <listcomp>
May 12 19:47:55 ubuntu electrumx_server.py[15728]:     for n, block in enumerate(blocks)]
May 12 19:47:55 ubuntu electrumx_server.py[15728]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/lib/coins.py", line 265, in block_full
May 12 19:47:55 ubuntu electrumx_server.py[15728]:     txs = deserializer(block[len(header):]).read_tx_block()
May 12 19:47:55 ubuntu electrumx_server.py[15728]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/lib/tx.py", line 112, in read_tx_block
May 12 19:47:55 ubuntu electrumx_server.py[15728]:     txs = [read_tx() for _ in range(self._read_varint())]
May 12 19:47:55 ubuntu electrumx_server.py[15728]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/lib/tx.py", line 112, in <listcomp>
May 12 19:47:55 ubuntu electrumx_server.py[15728]:     txs = [read_tx() for _ in range(self._read_varint())]
May 12 19:47:55 ubuntu electrumx_server.py[15728]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/lib/tx.py", line 104, in read_tx
May 12 19:47:55 ubuntu electrumx_server.py[15728]:     self._read_inputs(),    # inputs
May 12 19:47:55 ubuntu electrumx_server.py[15728]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/lib/tx.py", line 118, in _read_inputs
May 12 19:47:55 ubuntu electrumx_server.py[15728]:     return [read_input() for i in range(self._read_varint())]
May 12 19:47:55 ubuntu electrumx_server.py[15728]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/lib/tx.py", line 118, in <listcomp>
May 12 19:47:55 ubuntu electrumx_server.py[15728]:     return [read_input() for i in range(self._read_varint())]
May 12 19:47:55 ubuntu electrumx_server.py[15728]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/lib/tx.py", line 124, in _read_input
May 12 19:47:55 ubuntu electrumx_server.py[15728]:     self._read_varbytes(),   # script
May 12 19:47:55 ubuntu electrumx_server.py[15728]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/lib/tx.py", line 145, in _read_varbytes
May 12 19:47:55 ubuntu electrumx_server.py[15728]:     return self._read_nbytes(self._read_varint())
May 12 19:47:55 ubuntu electrumx_server.py[15728]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.9-py3.5.egg/lib/tx.py", line 141, in _read_nbytes
May 12 19:47:55 ubuntu electrumx_server.py[15728]:     assert len(self.binary) >= end
May 12 19:47:55 ubuntu electrumx_server.py[15728]: AssertionError

**Comment by santzi** [comment]
I downloaded whole LTC blockchain again and started ElectrumX from scratch. Same crash occurred. So this seems to be ElectrumX problem. So this is very easy to reproduce, if you like to get more debug prints.

**Comment by erasmospunk** [comment]
I haven't had time to check this but it could be related to the latest SegWit activation. Make sure you are running the latest version of ElectrumX that enabled SegWit for the Litecoin main network.

**Comment by santzi** [comment]
I think SegWit is not the issue, because I'm using 1.0.9 version ElectrumX.
SegWit is activated to 1.0.10 version.
LTC Core Daemon version is v0.13.2.1 what I'm using.

**Comment by erasmospunk** [comment]
@santzi try version 1.0.10 where SegWit support was added for Litecoin mainnet.

**Comment by santzi** [comment]
version 1.0.10 working fine...this seems to be the trick. Issue closed.
