### ISSUE TITLE
ERROR:Controller:Traceback (most recent call last)

### ISSUE THREAD

**Issue by microlost** [kyuupichan/electrumx#187]
I now trying build a electrumx for dogecoin,I do it like follows：
1.I had build dogecoind and completely syn the blockchain
2.then I had successfully install the electrumx-installer
3.electrumx.conf like this:

DB_DIRECTORY = /db
DAEMON_URL = http://doge:dogepass@localhost:28345/
DB_ENGINE=rocksdb
SSL_CERTFILE=/etc/electrumx/server.crt
SSL_KEYFILE=/etc/electrumx/server.key
HOST=0.0.0.0
TCP_PORT=50005

then I run the server with:  systemctl start electrumx
when I run: journalctl -u electrumx -f, it return:

-- Logs begin at Mon 2017-05-08 09:50:46 CST. --
May 18 10:33:08 iZwz9fq875i28wy1me24lkZ electrumx_server.py[26038]: ERROR:Controller:Traceback (most recent call last):
May 18 10:33:08 iZwz9fq875i28wy1me24lkZ electrumx_server.py[26038]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.10-py3.6.egg/server/controller.py", line 157, in on_future_done
May 18 10:33:08 iZwz9fq875i28wy1me24lkZ electrumx_server.py[26038]:     future.result()
May 18 10:33:08 iZwz9fq875i28wy1me24lkZ electrumx_server.py[26038]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.10-py3.6.egg/server/block_processor.py", line 50, in main_loop
May 18 10:33:08 iZwz9fq875i28wy1me24lkZ electrumx_server.py[26038]:     if not await self._prefetch_blocks():
May 18 10:33:08 iZwz9fq875i28wy1me24lkZ electrumx_server.py[26038]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.10-py3.6.egg/server/block_processor.py", line 113, in _prefetch_blocks
May 18 10:33:08 iZwz9fq875i28wy1me24lkZ electrumx_server.py[26038]:     blocks[0] = self.bp.coin.genesis_block(blocks[0])
May 18 10:33:08 iZwz9fq875i28wy1me24lkZ electrumx_server.py[26038]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.10-py3.6.egg/lib/coins.py", line 122, in genesis_block
May 18 10:33:08 iZwz9fq875i28wy1me24lkZ electrumx_server.py[26038]:     .format(header_hex_hash, cls.GENESIS_HASH))
May 18 10:33:08 iZwz9fq875i28wy1me24lkZ electrumx_server.py[26038]: lib.coins.CoinError: genesis block has hash 1a91e3dace36e2be3bf030a65679fe821aa1d6ef92e7c9902eb318182c355691 expected 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f

**Comment by thelazier** [comment]
You need ```COIN=Dogecoin``` in your config file else you are trying to run ElectrumX Server for Bitcoin.

**Comment by microlost** [comment]
thanks, I had add COIN=Dogecoin to electrum.conf, now the log as follows,does it work ok now?

May 18 11:38:24 iZwz9fq875i28wy1me24lkZ electrumx_server.py[26100]: ERROR:Controller:RPC server failed to listen on localhost:8000 :[Errno 99] error while attempting to bind on address ('::1', 8000, 0, 0): cannot assign requested address
May 18 11:38:24 iZwz9fq875i28wy1me24lkZ electrumx_server.py[26100]: INFO:Prefetcher:catching up to daemon height 1,719,456 (1,719,457 blocks behind)
May 18 11:38:24 iZwz9fq875i28wy1me24lkZ electrumx_server.py[26100]: INFO:Prefetcher:verified genesis block with hash 1a91e3dace36e2be3bf030a65679fe821aa1d6ef92e7c9902eb318182c355691
May 18 11:38:24 iZwz9fq875i28wy1me24lkZ electrumx_server.py[26100]: INFO:BlockProcessor:our height: 9 daemon: 1,719,456 UTXOs 0MB hist 0MB
May 18 11:38:55 iZwz9fq875i28wy1me24lkZ electrumx_server.py[26100]: INFO:BlockProcessor:our height: 14,610 daemon: 1,719,456 UTXOs 59MB hist 113MB
May 18 11:39:27 iZwz9fq875i28wy1me24lkZ electrumx_server.py[26100]: INFO:BlockProcessor:our height: 20,296 daemon: 1,719,456 UTXOs 118MB hist 245MB
May 18 11:39:27 iZwz9fq875i28wy1me24lkZ electrumx_server.py[26100]: INFO:BlockProcessor:flushed to FS in 0.1s
May 18 11:39:30 iZwz9fq875i28wy1me24lkZ electrumx_server.py[26100]: INFO:BlockProcessor:flushed history in 2.9s for 1,115,567 addrs
May 18 11:39:30 iZwz9fq875i28wy1me24lkZ electrumx_server.py[26100]: INFO:BlockProcessor:flush #1 took 3.1s.  Height 20,296 txs: 969,597
May 18 11:39:30 iZwz9fq875i28wy1me24lkZ electrumx_server.py[26100]: INFO:BlockProcessor:tx/sec since genesis: 14,668, since last flush: 14,669
May 18 11:39:30 iZwz9fq875i28wy1me24lkZ electrumx_server.py[26100]: INFO:BlockProcessor:sync time: 01m 06s  ETA: 01h 05m 18s

**Comment by bauerj** [comment]
Yes.

**Comment by kyuupichan** [comment]
Closing as apparent user misunderstanding.
