### ISSUE TITLE
how to support peercoin?

### ISSUE THREAD

**Issue by microlost** [kyuupichan/electrumx#189]
there is no peercoin in coins.py

**Comment by kyuupichan** [comment]
You've not written the code to support it?

**Comment by microlost** [comment]
Not yet. I don't know what code to write. Is that easy?  I hope you can help me

**Comment by kyuupichan** [comment]
I won't be helping to implement altcoin support.  But if you have a clean PR I will accept it.

**Comment by erasmospunk** [comment]
@microlost test this pull request that adds support for peercoin https://github.com/kyuupichan/electrumx/pull/192

**Comment by kyuupichan** [comment]
I've merged @erasmospunk's changes into master (thanks!). If someone independently confirms they can sync I will close this issue.

**Comment by kyuupichan** [comment]
Closing - lack of feedback from OP.  If someone thinks it doesn't work, re-open it.
