### ISSUE TITLE
WARNING:asyncio:socket.send() raised exception.

### ISSUE THREAD

**Issue by SuBPaR42** [kyuupichan/electrumx#19]
Nov 12 17:11:54.747358 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.747586 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.751002 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.751251 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.751480 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.751701 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.751884 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.755163 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.755394 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.755606 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.755836 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.756104 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.760869 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.765330 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.765623 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.765993 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.766367 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.766639 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.766845 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.767040 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.769331 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.769665 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.769971 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.771440 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.771824 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.772138 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.776474 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.776741 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.777059 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.777344 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.778795 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.779048 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.781157 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.781645 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.784465 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.784699 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.789581 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.789776 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.790003 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.792096 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.792407 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.792731 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.793063 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.793447 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.794666 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.794975 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.795842 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.798113 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.798418 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.798727 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.799161 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.799435 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.799743 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.800111 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.801778 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.802231 electrumx_server.py[15359]: WARNING:asyncio:socket.send() raised exception.
Nov 12 17:11:54.819961 electrumx_server.py[15359]: INFO:ElectrumX:78.56.XXX.XXX:51315 disconnected.  Sent 2,719,624 bytes in 57,826 messages 0 errors

**Comment by kyuupichan** [comment]
I am not certain but I believe this was fixed in the futures handling of 0.5.2, and certainly 0.6.  I've been serving for 16hrs and not seen one instance in my logs, so closing.
