### ISSUE TITLE
How to make coins.py for Altcoin

### ISSUE THREAD

**Issue by fujicoin** [kyuupichan/electrumx#190]
I am trying to set up an electrumx server for Fujicoin.
    https://github.com/fujicoin/fujicoin
I do not know some parameters of coins.py.
     TX_COUNT =
     TX_COUNT_HEIGHT =
     TX_PER_BLOCK =
     REORG_LIMIT =

Have you written somewhere how to set these?

**Comment by kyuupichan** [comment]
You should look at how it's used; it's not hard to understand.

**Comment by fujicoin** [comment]
You're right. Thanks!

**Comment by fujicoin** [comment]
I looked up block_processor.py.
I think
TX_COUNT = Transactions now.
TX_COUNT_HEIGHT = Height now.
TX_PER_BLOCK = Appropriate numerical value around INT(TX_COUNT / TX_COUNT_HEIGHT)

Is it right?

**Comment by kyuupichan** [comment]
The values are used to give ETAs of when an initial blockchain sync will complete.  As the chain is always extending, and processing time is more a function of tx count than block count, I wanted a way to give a sensible estimate.  So TX_COUNT_HEIGHT is just any recent height (10,000 blocks back is fine), TX_COUNT is the count at that height, and TX_PER_BLOCK is a guess at how many txs, on average, subsequent blocks will have.

There is no right answer; it's just used for giving the user feedback on how long they have to wait.  It doesn't work well on bitcoin testnet though as testnet is insanely lumpy - many blocks with few txs, and then several hundred blocks that are swamped.

**Comment by fujicoin** [comment]
Thanks for your comment.
I think this is useful information for Alycoin developers.
