### ISSUE TITLE
Cannot connect from ouside (no localhost) ?

### ISSUE THREAD

**Issue by namuyan** [kyuupichan/electrumx#195]
I tried to connect electrumx from other PCs with no SSL.
But LISTEN PORT is bind to localhost.
`run_elect 10180 electrum   22u  IPv4 17792592      0t0  TCP localhost:5002 (LISTEN)`

How to change the bind?

**Comment by bauerj** [comment]
It's explained in the docs: https://github.com/kyuupichan/electrumx/blob/master/docs/ENVIRONMENT.rst#miscellaneous
