### ISSUE TITLE
Lack of RPC_HOST option results in RPC server failing to listen if IPv6 is disabled

### ISSUE THREAD

**Issue by Thireus** [kyuupichan/electrumx#198]
Hi,

Electrumx provides an option for the listening host to be chosen. This helps specify to listen only on 127.0.0.1 on environments where IPv6 is disabled for example. Without this option available, the following would happen:

```
ERROR:Controller:SSL server failed to listen on localhost:50002 :[Errno 99] error while attempting to bind on address ('::1', 50002, 0, 0): cannot assign requested address
```

Although Electrumx doesn't clearly support host configurations on which IPv6 is disabled, the HOST option provides a quick workaround for it.

However, for the RPC server no such option is available to specify which HOST to listen to... This results in the following:

```
ERROR:Controller:RPC server failed to listen on localhost:8000 :[Errno 99] error while attempting to bind on address ('::1', 8000, 0, 0): cannot assign requested address
```

Since no RPC_HOST option is present, users are left with no option to solve the issue (unless modifying the Electrumx code).

Would it be possible to: either support configurations where IPv6 is disabled OR provide a RPC_HOST option?

Thank you!

Thi.

**Comment by bauerj** [comment]
I'm curious: Why did you disable IPv6 even on the loopback device?

**Comment by kyuupichan** [comment]
Then either you are breaking the assumptions of your libc or Python.  This is not something I can control from ElectrumX.

**Comment by kyuupichan** [comment]
To be clear, your problem is that you've changed your system and "localhost" is not resolving as you intend.  You need to make "localhost" resolve so it works on your system.

**Comment by Thireus** [comment]
Correct, localhost was still defined in /etc/hosts for both IPv4 and IPv6, after removing the /etc/hosts entries Electrumx resolves localhost as its IPv4 address 127.0.0.1 only.

From:

```
127.0.0.1	localhost

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
```

To:

```
127.0.0.1	localhost

# The following lines are desirable for IPv6 capable hosts
# ::1     localhost ip6-localhost ip6-loopback
```

When both IPv4 and IPv6 entries are defined in /etc/hosts, Python resolves localhost as "::1", while in fact it should resolve it as both "127.0.0.1" and "::1" and it should attempt to create a RPC listening port for both interfaces. What we observe here is that when localhost has an IPv6 defined it will try to open a listening port for ::1, but will fail (because there is no IPv6 interface on the system) and will not attempt to create a listening port for 127.0.0.1 (while it should!).

Are you sure this is a libc or Python issue?

For reference, this is how IPv6 is disabled (https://wiki.debian.org/DebianIPv6):

In /etc/sysctl.conf:

```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 1
```

**Comment by kyuupichan** [comment]
https://github.com/kyuupichan/electrumx/blob/master/server/controller.py#L201

Does passing the second argument as None instead of 'localhost' on this line work for you?

**Comment by kyuupichan** [comment]
@Thireus ?

**Comment by kyuupichan** [comment]
Closing owing to lack of feedback.

**Comment by FMCorz** [comment]
I also experienced this issue (with Docker) and resorted to setting `RPC_HOST` to `127.0.0.1`.
