### ISSUE TITLE
Option to anonymize logs?

### ISSUE THREAD

**Issue by tunkaflux** [kyuupichan/electrumx#20]
Is it possible to add an option to anonymize logs so that ip addresses are changed to x.x.x.x or something?

**Comment by kyuupichan** [comment]
I have no objection to that.   It'll be done faster with a pull request :)

What would RPC calls show?

**Comment by tunkaflux** [comment]
I'll see what I can do. My Python knowledge is not yet where I want it to be :)

I have no problem with RPC calls showing ip addresses (for now). I just want to make sure I don't write them to disk.
