### ISSUE TITLE
banner file

### ISSUE THREAD

**Issue by fujicoin** [kyuupichan/electrumx#201]
Please tell me the format of the banner file.
I placed a .png file under DB_DIRECTORY, but it looks like electrumx can not decipher it.

**Comment by kyuupichan** [comment]
Text

**Comment by fujicoin** [comment]
Thanks!

**Comment by fujicoin** [comment]
I modified session.py to display the banner file.
There is something wrong in replaced_banner().

session.py L312:
`
             try:
                 with codecs.open(banner_file, 'r', 'utf-8') as f:
                     banner = f.read()
+                    #banner = await self.replaced_banner(banner)
             except Exception as e:
                 self.log_error('reading banner file {}: {}'
                                .format(banner_file, e))
-            else:
-                banner = await self.replaced_banner(banner)
 
         return banner
`

**Comment by kyuupichan** [comment]
I have no idea what your point is

**Comment by fujicoin** [comment]
The position of "banner = await self.replaced_banner (banner)" is strange

**Comment by fujicoin** [comment]
"Replaced_banner ()" returns a white paper.

**Comment by bauerj** [comment]
> The indent of "else:" is also amusing.

That's just the usual [try/except/else](https://docs.python.org/3.6/tutorial/errors.html#handling-exceptions).

**Comment by fujicoin** [comment]
Ok, I understood what you want to do.

By the way, please tell me how to properly stop ElectrumX.
I am carrying out as follows.

kill [pidof svscan]
svc -dx ~/service/electrumx
svc -dx ~/service/electrumx/log
kill [pid of python]

**Comment by kyuupichan** [comment]
svc -d ~/service/electrumx

is enough
