### ISSUE TITLE
Using json-rpc

### ISSUE THREAD

**Issue by zottirik** [kyuupichan/electrumx#202]
Could you give me an example of json-rpc using?
For example; How can I run this command with curl or ssh: blockchain.address.get_balance(address)

**Comment by kyuupichan** [comment]
It's just JSON text; there is no HTTP wrapper.  Try connecting with nc to a TCP instance; then you can try 

openssl s_client -connect server:port

to experiment with SSL.

**Comment by kyuupichan** [comment]
A JSON message is like

{ "method" : "blockchain.address.get_balance", "params", [ "1YourAddress"], "id": "msg_id"}

**Comment by zottirik** [comment]
Could you give me an SSH command example to send this json message?

**Comment by bauerj** [comment]
There is no SSH interface.

**Comment by zilveer** [comment]
I think that adding a HTTP wrapper would be awesome for ElecteumX.

**Comment by bauerj** [comment]
Can you explain why that would be awesome?

**Comment by askz** [comment]
For web only static clients ?
They can't do pure tcp.
Or maybe websocket would be a good alternative.

**Comment by mdz** [comment]
JSON-RPC over HTTP would be awesome because there are nice client libraries (like jsonrpc_requests) which can be used to communicate with such servers.

**Comment by bauerj** [comment]
There is also a great client library called `aiorpcx` that works perfectly with the electrum protocol:

https://pypi.org/project/aiorpcx/

**Comment by moneroexamples** [comment]
There is also a popular  fork providing extended JSON API over HTTP: https://github.com/Blockstream/electrs
