### ISSUE TITLE
UTF-8 codec: invalid start byte

### ISSUE THREAD

**Issue by mariodian** [kyuupichan/electrumx#204]
Hey, 

when I'm trying to connect to SSL port I see my Electrum wallet disconnected and server outputs this kind of errors:

`electrumx_server.py[4932]: INFO:ElectrumX:[5] cannot decode message: 'utf-8' codec can't decode byte 0xfc in position 8: invalid start byte`

TCP port works flawlessly.

Server:
Intel NUC 7i3, 16GB RAM, Ubuntu 17.04
Bitcoin Core 0.14.2
ElectrumX 1.0.11

Client:
OS X Sierra 10.12.5
Electrum 2.8.3

**Comment by mariodian** [comment]
I was trying to connect on TCP port but had SSL clicked on in my wallet. My Bad.

Either way, SSL connection only works for me if I connect via IP, not via hostname.

**Comment by lichtamberg** [comment]
I have the same problem, but I also use certificates. Did you manage to get SSL running?

**Comment by mariodian** [comment]
@lichtamberg I got it running. Sadly, I can't tell you how I got it working because it "just works" now.

**Comment by startsts** [comment]
@mariodian can you tell me now? I have same problem (without ssl, just TCP)
