### ISSUE TITLE
Handle 100k accounts

### ISSUE THREAD

**Issue by n0n0n0n0** [kyuupichan/electrumx#209]
Need i setup the node if i would like to use 100k addresses in my electrum wallet on debian 8 (not same time ofc, for day about 1k addresses will be used, no more, but will keep others with money) or can use public nodes? Contributor from electrum recommended to setup my private node and use it with some increased limits(what exactly idk) cuz public nodes will reject me (why??). I'm not going to spam network with transactions just will generate a lot of payment addresses for clients and use them in future to transfer coins from them.

**Comment by kyuupichan** [comment]
Electrum scales very badly to large wallets.  Servers may or may not honour your requests, 100,000 addresses can consume a lot of resources.  You should run your own if you want reliability.
