### ISSUE TITLE
Performance numbers

### ISSUE THREAD

**Issue by tunkaflux** [kyuupichan/electrumx#21]
Hello, I've moved one of my Electrum servers (us.electrum.be) to electrumx and I must I'm impressed :) Syncing took roughly 24 hours (Qemu VM + HDD + relatively busy server).

Are there any performance numbers you might be interested in?

**Comment by kyuupichan** [comment]
Please be aware it's not really production ready (no anti-DOS stuff yet) and that the DB format will change.

If you can provide your memory, O/S and CPU that would be interesting.

**Comment by tunkaflux** [comment]
Host CPU: 2x Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
Bitcoin + Electrum Qemu VM: 4 virtual CPUs, 6 GB RAM & 16GB Swap
OS: Debian 8.6

**Comment by kyuupichan** [comment]
Thanks
