### ISSUE TITLE
Unhandled exception on connection time out?

### ISSUE THREAD

**Issue by tunkaflux** [kyuupichan/electrumx#22]
I saw the following error message in my logs:

ERROR:asyncio:Fatal write error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f70c39e5160>
transport: <_SelectorSocketTransport closing fd=25 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/selector_events.py", line 730, in _write_ready
    n = self._sock.send(self._buffer)
TimeoutError: [Errno 110] Connection timed out

**Comment by kyuupichan** [comment]
I am now convinced this is noise an asyncio user has no control over, so I have suppressed it in 0.6
