### ISSUE TITLE
Adding testnet5 support

### ISSUE THREAD

**Issue by Helios-vmg** [kyuupichan/electrumx#221]
I'm trying to add testnet5 support to electrumx and I'm running into some issues.

First, in the is_coinbase() function of class Tx, `self.inputs[0]` is causing an exception because self.inputs has length zero. Why might this be? I patched it momentarily by adding a check for `len(self.inputs) > 1`, but I don't know if this is appropriate.

Second, in spend_utxo() of BlockProcessor, the call to `pack('<H', tx_idx)` is throwing an exception:
> struct.error: ushort format requires 0 <= number <= (0x7fff * 2 + 1)

tx_idx has a value of 2^32-1 at that point. What does this mean?

**Comment by kyuupichan** [comment]
I suspect you need to use the slower DeserializerSegwit; see other examples in the file.
