### ISSUE TITLE
Peer discovery for Electron Cash (BCH) servers

### ISSUE THREAD

**Issue by kokx** [kyuupichan/electrumx#222]
I'm looking into running a server for Electron Cash. I'm using a Bitcoin ABC full node and simply plugging it into ElectrumX (as others seem to have done as well).

One issue I am looking at, is peer discovery. For now, I'm planning to simply disable it (non-BCH electrum nodes should reject my node anyway). However, it does give advantages to use it.

According to the [documentation about peer discovery](https://github.com/kyuupichan/electrumx/blob/master/docs/PEER_DISCOVERY.rst#serverfeatures-rpc-call), the hash for the genesis block is used for peer discovery. Which is the same for both networks. Making it not very useful to quickly dismiss wrong peers.

Am I correct that peer discovery wouldn't work correctly for servers running on bitcoin cash? And would there be a way to enable this that doesn't clash with normal nodes?

**Comment by kyuupichan** [comment]
It should work fine, the documentation is a bit too simplistic.
