### ISSUE TITLE
Wat? If you are on the Segwit chain you should have NET be "bitcoin-segwit", and if on the Bitcoin Cash chain continue to use "mainnet".

### ISSUE THREAD

**Issue by lichtamberg** [kyuupichan/electrumx#228]
From the readme:

> Version 1.0.16
>
>    updated server lists for post-fork. If you are on the Segwit chain you should have NET be "bitcoin-segwit", and if on the Bitcoin Cash chain continue to use "mainnet".

Please fix this, Bitcoin Cash hardforked, not Bitcoin. Sorry, but this is clearly nonsense and I urge you to change this back to the default.

**Comment by fireduck64** [comment]
kyuupichan is clearly expressing his opinion of which chain is more "bitcoin".  I happen to agree with him, you seem to disagree with him.  I agree that it is a little odd to do it this way, but the docs are clear and you can run your electrumx server on your chain of choice.  You are also free to fork electrumx and do what you like ;)

Anyways, changing it would probably create more confusion at this point but I am not in charge so my opinion isn't worth much.

**Comment by JustinTArthur** [comment]
A separate coin for Bitcoin Cash would make most sense. Not processing segwit txes on mainnet will make less and less sense as time goes on.

**Comment by kyuupichan** [comment]
Not a bug

**Comment by lichtamberg** [comment]
This is clearly a bug since the mainnet is activating segwit tomorrow. Bitcoin Cash is not following the mainnet rule so this completely wrong?!?

**Comment by bauerj** [comment]
This is just a convention, no political statement. It would be very confusing if `mainnet` had a different meaning depending on the version of electrumx you are using.

**Comment by lichtamberg** [comment]
How can it be less confusing when "mainnet" is following a hard forked chain with different consensus rules? lol?

**Comment by kyuupichan** [comment]
@lichtamberg you seem confused.  As @bauerj pointed out, nothing has changed in ElectrumX's configuration requirements.

What happened is Bitcoin Core broke backwards-compat of their RPC interface, it sends the same data differently when segwit is activated.  And so it needs a different deserializer in e-x that is less efficient than the one that always worked.

**Comment by mariodian** [comment]
The question is why would you default to a chain which isn't Bitcoin?

**Comment by bauerj** [comment]
Maybe it would make sense to change the default to `bitcoin-segwit` but changing the meaning of `mainnet` would not.

**Comment by mariodian** [comment]
> Maybe it would make sense to change the default to bitcoin-segwit but changing the meaning of mainnet would not.

Given the segwit chain is Bitcoin it should definitely be set as the default option. 

Those that want to have the original behavior back, feel free to use [my fork](https://github.com/mariodian/electrumx-no-bcash) (bcash is removed altogether along with the fork detection which is already done on the client by Electrum wallet) until the issue gets resolved.

**Comment by is55555** [comment]
This is not a bug, it's just fraud.

**Comment by neocogent** [comment]
At very least this should be notated as **bitcoin-segwit** and **bitcoin-cash** and leave mainnet out of it. Using that term is bound to get peoples ire up. And with these two terms is obvious what is intended.

**Comment by SuBPaR42** [comment]
For those who follow in the #electrum chatroom and prefer the segwit chain (i.e., non BCH) there has been a suggestion to run with the NET= bitcoin-segwit for weeks.  I kinda saw this coming as I understood the dev's beliefs on BCH vs BTC...

**Comment by kyuupichan** [comment]
Incompatible Bitcoin forks get a new name.  More so when bundled with performance hits.

**Comment by earonesty** [comment]
"Bitcoin cash" broke consensus rules.   It also has a faster average block time.  It's an incompatible fork.

**Comment by mariodian** [comment]
I fail to see how the SegWit chain which is followed by everyone without a need to upgrade their nodes is "incompatible" while Bcash which forked off the network and is rejected by the majority of nodes is "compatible". 

This is politics at its finest.

**Comment by mariodian** [comment]
Either way, fixed it for you in #229 to clear the confusion. The PR is apolitical so I left `bitcoin-cash` as the default NET since that's where you're heading anyway. It should make everyone "happy".
