### ISSUE TITLE
i lost hourd of my time for this useless sh-t

### ISSUE THREAD

**Issue by ID453543435** [kyuupichan/electrumx#232]
/server/db.py
 def backup_history(self, hashXs):
----------------
1.
 nremoves += len(a) - idx
- never used
2.
break
- it keep only 1 row of history
--------------------
i lost hourd of my time for this useless sh-t

**Comment by ID453543435** [comment]
self.tx_count what is it? it used only in this f-ckung def backup_history(self, hashXs):

**Comment by ID453543435** [comment]
why you put it in databse if you just read it from database?

**Comment by ID453543435** [comment]
f-cking free opensourece sh-t

**Comment by ID453543435** [comment]
everevere f-cking  links to functions
hate lisp_sluts

**Comment by ID453543435** [comment]
spend aloot of time to make code unundestandable

**Comment by ID453543435** [comment]
only i can use from this pack of maind f-ck is
https://github.com/kyuupichan/electrumx/blob/master/lib/coins.py

**Comment by ID453543435** [comment]
24 hours of sinchronisation, lol
it will work 1 week minimum!

**Comment by ID453543435** [comment]
even on SSD

**Comment by ID453543435** [comment]
https://github.com/grondilu/libbitcoin-perl  and f-ck this Phyton

**Comment by ID453543435** [comment]
will never mess again with phyton sh-t

**Comment by ID453543435** [comment]
and pyton "coders"
the new generation of lisp "coders"

**Comment by ID453543435** [comment]
evil sh-t of f-ck

**Comment by erasmospunk** [comment]
@ID453543435 I have been using the server for almost a year and I can report that it is fairly stable, at least order of magnitude faster than the older electrum-server. Furthermore the codebase is clean, documented and easy to follow.

If you can make some improvements to the code or perhaps create some tests, please feel free to make a pull request.

Also, please be nice, you wouldn't speak like that in person.

**Comment by ID453543435** [comment]
"faster than the older electrum-server. Furthermore the codebase is clean, documented and easy to follow."
bull sh-t, 50% of code writen only for make it imposible to undestud.

**Comment by ID453543435** [comment]
and have made nothing for sppedup syncronisation with bitcoind
