### ISSUE TITLE
Support for native SegWit address format, implement BIP 173

### ISSUE THREAD

**Issue by gits7r** [kyuupichan/electrumx#234]
Now that we have SegWit active, we need to take all the advantages that it provides. These include native SegWit address format + new P2WSH (pay-to-witness-script-hash, the legacy P2SH) that provides 256-bit hash vs. 160-bit hash which is quite nice.

The spec is here: https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki

We need to be able to index these new addresses and the legacy addresses at the same time. We should discount the limits for one type of addresses (if an user sent request for 1000 addresses he should be able to get records for both native segwit and legacy without counting both). Maybe a min. height can be added for native segwit addresses (like the height at which segwit locked in).

This is also opened in Electrum client as 2805.

**Comment by kyuupichan** [comment]
ElectrumX will be moving towards eliminating support for any address type.  Instead you will subscribe by script hash.

**Comment by kyuupichan** [comment]
I'll add support for script hashes soon, with docs.
