### ISSUE TITLE
Blockexplorer and Unspent outputs?

### ISSUE THREAD

**Issue by zilveer** [kyuupichan/electrumx#236]
Hello,
can ElextrumX be used as a blockexplorer like blockchain.info ?
If yes, is there any demo out there?

Also I wonder if it is possible to get unspent outputs through the blockexplorer?
Thanks for any reply!
regards Zilveer

**Comment by kyuupichan** [comment]
It would need some changes, but ElectrumX currently does have most of the requirements of a block explorer.  It is not something I'm focussing on though, and in the future it may move away from such a goal.
