### ISSUE TITLE
Using Blackcoin gives me "ModuleNotFoundError: No module named '_scrypt'"

### ISSUE THREAD

**Issue by zilveer** [kyuupichan/electrumx#237]
Hello,
I am using Blackcoin but when I run it I get the following error message:

```
    future.result()
  File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.17-py3.6.egg/
    if not await self._prefetch_blocks():
  File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.17-py3.6.egg/
    blocks[0] = self.bp.coin.genesis_block(blocks[0])
  File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.17-py3.6.egg/
    header_hex_hash = hash_to_str(cls.header_hash(header))
  File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.17-py3.6.egg/
    import scrypt
ModuleNotFoundError: No module named 'scrypt'
```
The "scrypt" module is imported on line 830 in the file /liv/coins.py.

How can I install the scrypt module?

Can someone give me advice about how I can solve this?
regards

**Comment by kyuupichan** [comment]
Try pip3 install scrypt

**Comment by zilveer** [comment]
@kyuupichan Thanks, that made it.
I had to remove pip3 and re-install it since I had python 3.5 earlier. So scrypt attempted to install itself in the python3.5 folder all the time.

regards
