### ISSUE TITLE
Transactions disappear after confirmation

### ISSUE THREAD

**Issue by lemial** [kyuupichan/electrumx#238]
Hello! After transferring coins, a transaction appears in the list, the transfer amount is subtracted from the balance, but after the first confirmation, the transaction disappears from the mobile wallet and the balance returns to the previous value. After the re-indexing of electrumx, the balance shows the correct.

After restart electrumx exit with error:
server.daemon.DaemonError: [{'code': -5, 'message': 'No information available about transaction'}, {'code': -5, 'message': 'No information available about transaction'}]

Coin: Blackcoin fork.

**Comment by kyuupichan** [comment]
Version?

**Comment by lemial** [comment]
git clone from repository https://github.com/kyuupichan/electrumx.git

**Comment by kyuupichan** [comment]
If it's up-to-date I have no idea.  There was an issue around 1.0.14 / 1.0.15 time where that could occur.  This doesn't happen for Bitcoin.

**Comment by lemial** [comment]
Version 1.0.12 worked fine! Tnx!

**Comment by kyuupichan** [comment]
OK; HEAD should be fine too.
