### ISSUE TITLE
No Interface?

### ISSUE THREAD

**Issue by zilveer** [kyuupichan/electrumx#239]
Hello,
isnt there any interface for ElectrumX?

I have got it up and running and get the following message:

```
INFO:BlockProcessor:reorg limit is 5,000 blocks
INFO:BlockProcessor:flushing DB cache at 1,800 MB
INFO:Controller:RPC server listening on ('127.0.0.1', '::1'):8000
INFO:Prefetcher:catching up to daemon height 320,117 (320,118 blocks behin
INFO:Prefetcher:verified genesis block with hash 000001faef25dec4fbcf906e6
INFO:BlockProcessor:our height: 9 daemon: 320,117 UTXOs 0MB hist 0MB
INFO:BlockProcessor:our height: 3,009 daemon: 320,117 UTXOs 0MB hist 0MB
INFO:BlockProcessor:our height: 6,509 daemon: 320,117 UTXOs 1MB hist 0MB
INFO:BlockProcessor:our height: 8,509 daemon: 320,117 UTXOs 1MB hist 0MB
INFO:BlockProcessor:our height: 12,509 daemon: 320,117 UTXOs 3MB hist 1MB
```

But isnt there any interface for the ElectrumX on the server?
How can I access it?

regards

**Comment by kyuupichan** [comment]
I don't understand your question.  The server indexes before it listens for clients.

**Comment by zilveer** [comment]
Oh I think you replied to my question ,
I want clients to be able to connect to the electrumx server.is it port 8000 in this case ?
Right now I cannot access port 8000, is it because of index isn't finished yet ?

**Comment by zilveer** [comment]
In my case it was port 50001 .

I don't get it, how can I send requests to the electrumx ?
Isn't there any webinterface for clients, like a blockexplorer similar to blockchain.info ?
