### ISSUE TITLE
Using JsonRPC with PHP and ElectrumX ?

### ISSUE THREAD

**Issue by zilveer** [kyuupichan/electrumx#244]
Hello,
Is it possible to use JsonRPC with PHP for ElectrumX like 
Https://github.com/spesmilo/electrum/blob/master/lib/www/example.php

Code for the PHP is :
```
<?php
require_once 'jsonRPCClient.php';
$electrum = new jsonRPCClient('http://localhost:7777');
echo '<b>Wallet balance</b><br />'."\n";
try {
    $balance = $electrum->getbalance();
    echo 'confirmed: <i>'.$balance['confirmed'].'</i><br />'."\n";
    echo 'unconfirmed: <i>'.$balance['unconfirmed'].'</i><br />'."\n";
} catch (Exception $e) {
    echo nl2br($e->getMessage()).'<br />'."\n";
}
?>
```

**Comment by anoxxxy** [comment]
Did you solve this?

**Comment by zilveer** [comment]
@anoxxxy 
I am working on it, did you have a solution for PHP?

**Comment by bauerj** [comment]
You need to use TCP sockets instead of HTTP.

**Comment by anoxxxy** [comment]
@bauerj that is correct.
i have setup a TCP socket here: 
`https://gist.github.com/anoxxxy/65d2b12b98eedd8116dd80a0bcfa5702`

hope u can use it @zilveer

**Comment by bauerj** [comment]
I still don't understand why you can't do that in PHP.

**Comment by zilveer** [comment]
@anoxxxy thanks I will check it up.

@bauerj I just wanted to know if it could be done through PHP, I dont know what limits there are since I am new to crypto. But python seems to be the right way to do this since PHP is eating resources.
Thanks for your help guys!

regards Zilveer
