### ISSUE TITLE
electrumx stops during coin sync

### ISSUE THREAD

**Issue by lahlor** [kyuupichan/electrumx#246]
Hi,

Ive got the following error after electrumx was able to sync about 483422 blocks. Can someone help me?

Sep  4 08:17:20 ELEX01 electrumx_server.py[787]: INFO:Prefetcher:catching up to daemon height 483,422 (1,602 blocks behind)
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]: ERROR:Controller:Traceback (most recent call last):
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.17-py3.6.egg/server/controller.py", line 176, in on_future_done
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:     future.result()
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.17-py3.6.egg/server/block_processor.py", line 206, in main_loop
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:     await task()
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.17-py3.6.egg/server/block_processor.py", line 243, in check_and_advance_blocks
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:     for n, raw_block in enumerate(raw_blocks)]
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.17-py3.6.egg/server/block_processor.py", line 243, in <listcomp>
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:     for n, raw_block in enumerate(raw_blocks)]
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.17-py3.6.egg/lib/coins.py", line 276, in block
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:     txs = cls.DESERIALIZER(raw_block, start=len(header)).read_tx_block()
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.17-py3.6.egg/lib/tx.py", line 100, in read_tx_block
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:     txs = [read_tx() for _ in range(self._read_varint())]
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.17-py3.6.egg/lib/tx.py", line 100, in <listcomp>
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:     txs = [read_tx() for _ in range(self._read_varint())]
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.17-py3.6.egg/lib/tx.py", line 92, in read_tx
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:     self._read_inputs(),    # inputs
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.17-py3.6.egg/lib/tx.py", line 106, in _read_inputs
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:     return [read_input() for i in range(self._read_varint())]
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.17-py3.6.egg/lib/tx.py", line 106, in <listcomp>
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:     return [read_input() for i in range(self._read_varint())]
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.17-py3.6.egg/lib/tx.py", line 112, in _read_input
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:     self._read_varbytes(),   # script
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.17-py3.6.egg/lib/tx.py", line 138, in _read_varbytes
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:     return self._read_nbytes(self._read_varint())
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.17-py3.6.egg/lib/tx.py", line 134, in _read_nbytes
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]:     assert len(self.binary) >= end
Sep  4 08:17:21 ELEX01 electrumx_server.py[787]: AssertionError

**Comment by kyuupichan** [comment]
See the docs, just change your NET and restart
