### ISSUE TITLE
1.9.8 clients broken

### ISSUE THREAD

**Issue by fireduck64** [kyuupichan/electrumx#248]
1.9.8 clients send:
{"method":"server.version","id":4,"params":["1.9.8","0.9"]}
to which the server responds:
{"id": 4, "jsonrpc": "2.0", "error": {"message": "unsupported protocol version: 0.9", "code": -103}}

Probably should just assume they want 0.10.

**Comment by kyuupichan** [comment]
Thanks, I'll fix this by changing the protocol min version.
