### ISSUE TITLE
unknown method: 'server.version'

### ISSUE THREAD

**Issue by zilveer** [kyuupichan/electrumx#254]
Hello,
I tried to change the protocol version to 1.1 with server.version method but then I got into problem.
When I run this command I get the following error.
What could the reason be?
```
bitcoin@9eb9:~/bitcoin$ nc 127.0.0.1 9999
{"method" : "server.version", "params": ["1.1", "1.1"], "id": "msg_id"}
{"jsonrpc": "2.0", "id": "msg_id", "error": {"message": "unknown method: 'server.version'", "code": -32601}}
```
Thanks for any help.

**Comment by bauerj** [comment]
Works for me:

```
⚡ bauerj@helicarrier ~ ⇨ nc localhost 50001
{"method" : "server.version", "params": ["1.1", "1.1"], "id": "msg_id"}
{"jsonrpc": "2.0", "id": "msg_id", "result": ["ElectrumX 1.1pre2", "1.1"]}
```

**Comment by zilveer** [comment]
It worked for me earlier as well.. but now I only get
`{"jsonrpc": "2.0", "id": "msg_id", "error": {"message": "unknown method: 'server.version'", "code": -32601}}`
in return, and that goes for all methods I use.
Very strange?

**Comment by bauerj** [comment]
Are you sure you're not talking to the RPC interface?

**Comment by zilveer** [comment]
@bauerj Hmm.. good questions.
The strange thing is that it has worked smoothly until I tried to switch protocol version-.
I havent touched the electrumx.conf file though.
It might actually be the RPC interface I am talking to.

But when I do the following nothing happens:
```
bitcoin@9eb9:~/.electrumx-installer$ nc localhost 50001
bitcoin@9eb9:~/.electrumx-installer$ nc 127.0.0.1 50001
bitcoin@9eb9:~/.electrumx-installer$
```

This is my conf file

```
# default /etc/electrumx.conf for systemd
#http://docs.electrum.org/en/latest/merchant.html

# REQUIRED
DB_DIRECTORY = /db
# Bitcoin Node RPC Credentials
DAEMON_URL = http://user:pass@127.0.0.1:19913/

# See https://github.com/kyuupichan/electrumx/blob/master/docs/ENVIRONMENT.rst for
# information about other configuration settings you probably want to consider.

#DB_ENGINE=rocksdb

USERNAME = electrumx
COIN=Bitcoin
NET=mainnet

SSL_CERTFILE=/etc/electrumx/server.crt
SSL_KEYFILE=/etc/electrumx/server.key
TCP_PORT=50001
SSL_PORT=50002
# Listen on all interfaces:
HOST=

```

What am I doing wrong?

**Comment by bauerj** [comment]
Is it running? What's in the logs?

**Comment by kyuupichan** [comment]
server.version works fine.
