### ISSUE TITLE
unspent is missing "script" key

### ISSUE THREAD

**Issue by anoxxxy** [kyuupichan/electrumx#255]
Hi,
I am comparing unspent between electrumx and [chainz.cryptoid.info](chainz.cryptoid.info) but it seems that ElectrumX is missing the `script key` or perhaps I havent configured electrumx correct?
Does ElectrumX even have unspent info (return information about unspent outputs of an address)?

I have used listunspent on ElectrumX to but I think it is wrong method to use?

[http://195.181.242.206:9998/api?method=blockchain.address.listunspent&params=BLVFNgbSCvodnUhMcCi2HzM16NxFwtXrHb](http://195.181.242.206:9998/api?method=blockchain.address.listunspent&params=BLVFNgbSCvodnUhMcCi2HzM16NxFwtXrHb)

[https://chainz.cryptoid.info/bay/api.dws?q=unspent&active=BLVFNgbSCvodnUhMcCi2HzM16NxFwtXrHb&key=b8d99d015bfd&_=1504991631656](https://chainz.cryptoid.info/bay/api.dws?q=unspent&active=BLVFNgbSCvodnUhMcCi2HzM16NxFwtXrHb&key=b8d99d015bfd&_=1504991631656)

if you compare these outputs then you will see that electrumx is missing `script` key in the data I get.
How can I setup electrumx in a right way to get the `script` key of unspent outputs?

EDIT: I can get the `script` key when I use importaddress in the daemon, but imagine if I do this with thousands of addresses, the wallet will get huge in short time.

Any help is appreciated.
Thanks for any response

**Comment by kyuupichan** [comment]
I have no idea what "script" key means - why do you care?  ElectrumX lists the output in that format because that is what the API says.  If you need something else you need to implement it for your coin.

**Comment by anoxxxy** [comment]
script means scriptPubKey [https://bitcoin.org/en/glossary/pubkey-script](https://bitcoin.org/en/glossary/pubkey-script)

> "A script included in outputs which sets the conditions that must be fulfilled for those satoshis to be spent. Data for fulfilling the conditions can be provided in a signature script. Pubkey Scripts are called a scriptPubKey in code."

`scriptPubKey = OP_DUP OP_HASH160 <pubKeyHash> OP_EQUALVERIFY OP_CHECKSIG`

So, isn't it possible somehow to implement this feature so one can spend the unspent UTXO's?

**Comment by kyuupichan** [comment]
You don't need that in the reply, it just wastes bandwidth.  Given the address you can create the script yourself; Python code to do so is in lib/coins.py with "pay_to_address_script()".

**Comment by anoxxxy** [comment]
@kyuupichan Thank you for the prompt reply.
I am building a block explorer, making it easier for other to get this kind of data, that is why it is needed.

I will check it up, thanks.

**Comment by zilveer** [comment]
@kyuupichan 
I would also like to see a feature in the settings for each coin where I can set if the scriptPubKey should be visible in the API for unspent UTXO.

Is it possible for you to add this ? I would do it if I knew python a Little bit more.

Thanks for your help

**Comment by kyuupichan** [comment]
No I don't want to add this as I said.  We're even phasing out address support which will make this impossible.

**Comment by zilveer** [comment]
@kyuupichan
Hmmm..ok. but why would anyone use electrumx without address support ?

**Comment by zilveer** [comment]
Btw is it possible for you to show me a code of how I can achieve this ?

**Comment by anoxxxy** [comment]
@kyuupichan 
I have modified `async def address_listunspent(self, address):` in server/controller.py to the following:

```
    async def address_listunspent(self, address):
        '''Return the list of UTXOs of an address.'''
        hashX = self.address_to_hashX(address)
        scriptKey = self.pay_to_address_script(address)
        return [{'tx_hash': hash_to_str(utxo.tx_hash), 'tx_pos': utxo.tx_pos,
                 'height': utxo.height, 'value': utxo.value, 'script': scriptKey}
                for utxo in sorted(await self.get_utxos(hashX))]
```

I have also added the following code in server/controller.py

```
    def pay_to_address_script(self, address):
        try:
            return self.coin.pay_to_address_script(address)
        except Exception:
            pass
        raise RPCError('{} is not a valid address'.format(address))
```

Now when I make a request with listunspent I get the following for `scriptPubKey`:

scriptPubKey: `b'\\xa9\\x144\\x96\\xc8\\xd5\\xbe\\x1d\\xf0\\xae\\xbc\\xa3\\xdf\\xab\\xcc\\xdaI\\x96*j\\xdd\\xee\\x87'`

But it should be 
`76a9143496c8d5be1df0aebca3dfabccda49962a6addee88ac`

What am I missing, I suppose that I need to convert it some way, but dont know how?
Thanks for helping me out.

**Comment by kyuupichan** [comment]
>>> from lib.coins import Bitbay as coin
>>> script = coin.pay_to_address_script('BLVFNgbSCvodnUhMcCi2HzM16NxFwtXrHb')
>>> script.hex()
'76a914afeafd767d84aaa0cebc335eeeb5886734e88d9988ac'

This should be done client-side not server side, as subscriptions will be by script not address.

**Comment by zilveer** [comment]
@kyuupichan 
Ok.vhow can I do this on client side ? Any example ?

**Comment by anoxxxy** [comment]
@kyuupichan thanks for your effort and time!
