### ISSUE TITLE
add_peer requests get rejected through Tor interface

### ISSUE THREAD

**Issue by SomberNight** [kyuupichan/electrumx#257]
Running e-x 1.1 (commit 131344715ab753af6fef5bc3b74186f2e4bab9da) in a Docker container.
In my logs, I see a few lines such as:
```
WARNING:PeerManager:rejected add_peer request from 172.19.X.X for erbium1.sytes.net (source-destination mismatch)
```
That `172.19.X.X` IP is the address of another Docker container hosting the Tor hidden service and doing Tor proxying.
Is this normal behaviour?

**Comment by kyuupichan** [comment]
That means that erbium1.sytes.net doesn't resolve to 172.19.x.x.  If it were a Tor service it should end in .onion right?

**Comment by SomberNight** [comment]
You misunderstood.
I have e-x running in docker container1, and the Tor service (with hidden service and proxying) running in container2. So container1 uses container2 for all the Tor stuff.
In container1, e-x sees as if the add_peer request came from container2 because it passes through container2.

**Comment by kyuupichan** [comment]
If you run complex setups you need to be able to manage them yourself.  The logic is simple - to verify a peer, e-x checks that it can connect to it at its advertised address or host name, that it has basic functionality, and that the IP address the IP address of the remote peer requesting peering.

If it doesn't match then it is not valid.  If your proxying layers break this then there is not much I can do about it; the check is necessary to avoid advertising fake peers to clients.
