### ISSUE TITLE
COIN error

### ISSUE THREAD

**Issue by zhiyan114** [kyuupichan/electrumx#263]
Sep 15 19:35:23 btc electrumx_server.py[14456]: INFO:root:ElectrumX server starting
Sep 15 19:35:23 btc electrumx_server.py[14456]: Traceback (most recent call last):
Sep 15 19:35:23 btc electrumx_server.py[14456]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/EGG-INFO/scripts/electrumx_server.py", line 24, i
Sep 15 19:35:23 btc electrumx_server.py[14456]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/env.py", line 34, in __init__
Sep 15 19:35:23 btc electrumx_server.py[14456]:     coin_name = self.required('COIN').strip()
Sep 15 19:35:23 btc electrumx_server.py[14456]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/env.py", line 91, in required
Sep 15 19:35:23 btc electrumx_server.py[14456]:     raise self.Error('required envvar {} not set'.format(envvar))
Sep 15 19:35:23 btc electrumx_server.py[14456]: server.env.Env.Error: required envvar COIN not set
Sep 15 19:35:23 btc electrumx_server.py[14456]: CRITICAL:root:ElectrumX server terminated abnormally

i dont know what happened here.

**Comment by zhiyan114** [comment]
nvm i got it

**Comment by zilveer** [comment]
@zhiyan114 why dont you write the solution?

**Comment by zhiyan114** [comment]
@zilveer 
I forgot what to add to it but you set the network type (ex. testnet, mainnet)
and add coin type (have to be the name that have on file like swegitbitcoin)
