### ISSUE TITLE
lib.coins.CoinError: unknown coin Bitcoin and network mainnet combination

### ISSUE THREAD

**Issue by hopitas** [kyuupichan/electrumx#265]
Why doesn't this work? My electrumx.conf looks like this:

#
#MISC
#
    COIN = Bitcoin
    NET = mainnet
    DB_ENGINE = leveldb

**Comment by bauerj** [comment]
You want to use `BitcoinSegwit` instead of `Bitcoin`.

More information: https://github.com/kyuupichan/electrumx/blob/8cfa42ed9cc7c46f9a4fde49854c7710b2863484/README.rst#version-11

**Comment by hopitas** [comment]
Thank you!
