### ISSUE TITLE
cannot decode JSON error

### ISSUE THREAD

**Issue by Mirobit** [kyuupichan/electrumx#266]
Using electrumx_rpc.py works fine but I get an error message when using curl or Json-RPC PHP despit using valid jsonrpc 2.0.

`curl -H "Content-Type: application/json" -X POST --data-binary '{"jsonrpc": "2.0", "id": null, "method": "getinfo", "params": []}' http://127.0.0.1:8000/`

Result:
`Sep 17 21:01:43 vps electrumx_server.py[25036]: INFO:LocalRPC:[43] cannot decode JSON: Expecting value: line 1 column 1 (char 0)`

**Comment by fr3aker** [comment]
The electrum rpc does not use http.
