### ISSUE TITLE
doc update - blockchain.address.get_history 0 vs -1

### ISSUE THREAD

**Issue by fireduck64** [kyuupichan/electrumx#269]
For  blockchain.address.get_history and presumably scripthash as well,
electeumx is doing 
height 0 = pending with all inputs confirmed
height -1 = pending with inputs from pending transactions

ThomasV has confirmed that the client does care about that distinction.  The protocol docs should be updated to reflect that.

**Comment by ecdsa** [comment]
the client uses it to display the "unconfirmed parent" warning

**Comment by kyuupichan** [comment]
Hmm, I thought this was documented.  Perhaps just in the code comments. Let me take a look.
