### ISSUE TITLE
history ordering?

### ISSUE THREAD

**Issue by fireduck64** [kyuupichan/electrumx#270]
It looks like one of us has an ordering bug with regard to pending transactions.

My understanding is the ordering in the history should be:
height, ascending
tx_hash, ascending

So in this case with a79 and e22 both pending, a79 should come first, which is what jelectrum is doing.
Electrumx seems to have it reversed.

`$ ./getaddr.sh 1oJo6SskCJTzqM4kA7z5n4fS3XH2LUy7s
--------------------------- jelectrum
{"result":{"unconfirmed":0,"transactions":2,"confirmed":0},"id":"bal","jsonrpc":"2.0"}
{"result":"949b5fb3151769c95fa48f29acce17d4b05b3fab9c1ad0f4c464f51b6b3cb257","id":"sub","jsonrpc":"2.0"}
{"result":[],"id":"unsp","jsonrpc":"2.0"}
{"result":[{"tx_hash":"a79fe380eb5067c4eef465e2892d32e9b72d670f3aff9622ab9338333541ddc0","height":-1},{"tx_hash":"e226c63cccc44821adc3840101204256ab970af9d05bba1287b2f6888820b49f","height":-1}],"id":"hist","jsonrpc":"2.0"}

--------------------------- electrumx
{"jsonrpc": "2.0", "result": {"unconfirmed": 0, "confirmed": 0}, "id": "bal"}
{"jsonrpc": "2.0", "result": "55080ade52508959bcbe8cc6935bc7c34e8bf6dd7e10c8b96e1d9c519c7bb330", "id": "sub"}
{"jsonrpc": "2.0", "result": [], "id": "unsp"}
{"jsonrpc": "2.0", "result": [{"fee": 3390, "height": -1, "tx_hash": "e226c63cccc44821adc3840101204256ab970af9d05bba1287b2f6888820b49f"}, {"fee": 3390, "height": -1, "tx_hash": "a79fe380eb5067c4eef465e2892d32e9b72d670f3aff9622ab9338333541ddc0"}], "id": "hist"}

$ cat getaddr.txt 
{ "id": "bal", "method": "blockchain.address.get_balance", "params": ["ADDR"] }
{ "id": "sub", "method": "blockchain.address.subscribe", "params": ["ADDR"] }
{ "id": "unsp", "method": "blockchain.address.listunspent", "params": ["ADDR"] }
{ "id": "hist", "method": "blockchain.address.get_history", "params": ["ADDR"] }
`

**Comment by kyuupichan** [comment]
I believe that is incorrect; electrum wants txs in the same block ordered by position in block, which is what ElectrumX does.  Perhaps ThomasV can confirm?  I assume this is about checking the history hash?

**Comment by kyuupichan** [comment]
@ecsda any idea?

**Comment by kyuupichan** [comment]
I'll close this as fireduck has agreed to do the same as e-x.
