### ISSUE TITLE
Core dump during initial sync

### ISSUE THREAD

**Issue by aesedepece** [kyuupichan/electrumx#276]
During initial blockchain synchronization using RocksDB and local daemon `bitcoind 0.15.0`, the following core dump happens after a while, halting synchronization.
```
kernel: traps: electrumx_serve[75818] general protection ip:4407cd sp:7ffc88457a20 error:0 in python3.6[400000+3a0000]
systemd[1]: electrumx.service: Main process exited, code=dumped, status=11/SEGV
systemd[1]: electrumx.service: Unit entered failed state.
systemd[1]: electrumx.service: Failed with result 'core-dump'.
```
OS is `Ubuntu 16.04 LTS x86_64 GNU/Linux 4.11.0-1011` on Azure.
Python version is `3.6.2`.

**Comment by kyuupichan** [comment]
Is this reproducible?  As you can see from other issues there are some Linux distros with library problems (probably leveldb).  A pure Python program itself cannot cause core dumps, of course.

**Comment by kyuupichan** [comment]
I'm closing these as I have just done an initial sync without issues.  It seems there is something wrong with the setup of your O/S or libraries.
