### ISSUE TITLE
What should I do if db_height is delayed relative to daemon_height?

### ISSUE THREAD

**Issue by fujicoin** [kyuupichan/electrumx#281]
Hi,

Although the cause is unknown, two servers of Electrumx have the following symptoms.
electrumx@: ~/deps/electrumx$ ./electrumx_rpc.py getinfo
{
    "daemon_height": 1704304,
    "db_height": 1704219,
}

Should I rebuild the DB from scratch?
Or is there any other correct procedure?

The server is in Japan and the United States, each referring to a different daemon.
What are the possible causes of the delay?

Thanks,
motty

**Comment by bauerj** [comment]
Is there anything relevant in the logs?

**Comment by fujicoin** [comment]
After rebuilding DB of two servers sequentially, it became normal.
It may have received some kind of attack near height 1704219.
Because I was in a hurry, I erased the log at reboot.
Next time the same symptoms occur, I investigate in detail.
Thanks.

**Comment by fujicoin** [comment]
The phenomenon recurred.
After examining log, it was the same error as Issue # 286 .
https://github.com/kyuupichan/electrumx/issues/286

Since Fujicoin has a short block interval of 1 minute, the limitation of 65535 will come in 1.5 months.

So as a result of running the compact_history script, I was able to restart electrumX safely.

So there is a question.
In db.py, compact_history (self, loop) is defined.
Once I run the above compact_history script, can I think that the compact_history will be executed automatically afterwards and will not cause the above error?
Or should I run the compact_history script monthly?

Thanks, 
motty
