### ISSUE TITLE
"blockchain.headers.subscribe" version return

### ISSUE THREAD

**Issue by alieslam** [kyuupichan/electrumx#288]
Hey guys, i have noticed the version number returned by the blockchain.headers.subscribe is not correct even that it seems to be extracted from the block header in these lines 
`version, = struct.unpack('<I', header[:4])` under the electrum_header methods in coin.py but the json comes with extremely different version.
## Json response:
Received: {
	"jsonrpc": "2.0",
	"id": 3,
	"result": {
		"block_height": 1210057,
		"version": 536870912,
		"prev_block_hash": "0000000064ebe505f9869a13bf25322759e4111bc440df4f318be6e1ffcf5ea8",
		"merkle_root": "c4816ff3dd5ee631b2cbcd6089f6215991b5965277f48c56ae30cd7411563476",
		"timestamp": 1507809814,
		"bits": 486604799,
		"nonce": 4270299834
	}
}
## Json Message:
Received: {
	"jsonrpc": "2.0",
	"method": "blockchain.headers.subscribe",
	"params": [{
		"block_height": 1210057,
		"version": 536870912,
		"prev_block_hash": "0000000064ebe505f9869a13bf25322759e4111bc440df4f318be6e1ffcf5ea8",
		"merkle_root": "c4816ff3dd5ee631b2cbcd6089f6215991b5965277f48c56ae30cd7411563476",
		"timestamp": 1507809814,
		"bits": 486604799,
		"nonce": 4270299834
	}]
}

I am using bitcoin testnet, Do i miss something?

**Comment by kyuupichan** [comment]
Why do you think it's incorrect?

**Comment by kyuupichan** [comment]
https://testnet.smartbit.com.au/block/1210057

**Comment by alieslam** [comment]
what a silly mistake, am sorry i got confused while requesting older block headers returning versions not more than (02). I  have been switching a lot between the main net and the testnet lately.
