### ISSUE TITLE
Implement auto-upgrade from v5 to v6 DBs

### ISSUE THREAD

**Issue by martinschwarz** [kyuupichan/electrumx#289]
[Recently](https://github.com/kyuupichan/electrumx/commit/56d03625f669fda0744ab49fa5e404be67d9b7a0) the DB version has been increased from 5 to 6. Electrumx v1.2 can't read v5 DBs, though. Some (one-time?) importer from v5 to v6 should be provided as rebuilding the DB can be a very slow process, discouraging many users.

**Comment by kyuupichan** [comment]
Not possible.
