### ISSUE TITLE
Synced btc database for v1.2

### ISSUE THREAD

**Issue by fr3aker** [kyuupichan/electrumx#290]
I'm not sure this is a good place to post this at all but since a fair bunch of people will have to resync when upgrading to v1.2 I created a torrent magnet link for a synced btc leveldb (up to block 490153).

    magnet:?xt=urn:btih:caa804f48a319b061be3884ac011656c27121a6f&dn=electrumx_1.2_btc_leveldb_490153

Not sure if this is worth adding to the docs or somewhere.

If you don't want this around please close the issue.

Note: since electrum can validate any transaction through SPV this should not cause any trust issues with an externally acquired database as far as I can think.

**Comment by kyuupichan** [comment]
I'd accept a PR to add it to the docs.  Thanks.
