### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by knkrth** [kyuupichan/electrumx#291]
I got the following error immediately after 

root@ubuntu:~/electrumx# python3 electrumx_rpc.py getinfo
cannot connect - is ElectrumX catching up, not running, or is 8000 the wrong RPC port?

I have followed the installation on https://freedomnode.com/blog/69/how-to-install-an-electrum-server-using-full-bitcoin-node-and-electrumx for ubuntu 16.04

I have installed https://packages.ubuntu.com/xenial/libleveldb-dev & unable to install rocksDB.

**Comment by kyuupichan** [comment]
Well, what is in your logs?

**Comment by knkrth** [comment]
ubuntu@root:/tmp/electrumx$ cat /var/log/syslog | grep electrumx
Oct 17 04:25:27 ip-172-31-36-220 electrumx_server.py[9834]: INFO:root:ElectrumX server starting
Oct 17 04:25:27 ip-172-31-36-220 electrumx_server.py[9834]: Traceback (most recent call last):
Oct 17 04:25:27 ip-172-31-36-220 electrumx_server.py[9834]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/EGG-INFO/scripts/electrumx_server.py", line 24, in main
Oct 17 04:25:27 ip-172-31-36-220 electrumx_server.py[9834]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/server/env.py", line 35, in __init__
Oct 17 04:25:27 ip-172-31-36-220 electrumx_server.py[9834]:     coin_name = self.required('COIN').strip()
Oct 17 04:25:27 ip-172-31-36-220 electrumx_server.py[9834]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/lib/env_base.py", line 39, in required
Oct 17 04:25:27 ip-172-31-36-220 electrumx_server.py[9834]:     raise self.Error('required envvar {} not set'.format(envvar))
Oct 17 04:25:27 ip-172-31-36-220 electrumx_server.py[9834]: lib.env_base.EnvBase.Error: required envvar COIN not set
Oct 17 04:25:27 ip-172-31-36-220 electrumx_server.py[9834]: CRITICAL:root:ElectrumX server terminated abnormally

**Comment by kyuupichan** [comment]
So the server isn't running for the reason given in the logs
