### ISSUE TITLE
start error

### ISSUE THREAD

**Issue by zottirik** [kyuupichan/electrumx#298]
I was using electrumx as version 1.017, when I upgrade it I got this error:

Oct 25 06:40:37 server electrumx_server.py[12626]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/server/block_processor.py", line 144, in __init__
Oct 25 06:40:37 server electrumx_server.py[12626]:     super().__init__(env)
Oct 25 06:40:37 server electrumx_server.py[12626]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/server/db.py", line 67, in __init__
Oct 25 06:40:37 server electrumx_server.py[12626]:     self.open_dbs()
Oct 25 06:40:37 server electrumx_server.py[12626]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/server/db.py", line 127, in open_dbs
Oct 25 06:40:37 server electrumx_server.py[12626]:     self.read_utxo_state()
Oct 25 06:40:37 server electrumx_server.py[12626]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/server/db.py", line 311, in read_utxo_state
Oct 25 06:40:37 server electrumx_server.py[12626]:     .format(self.db_version, self.DB_VERSIONS))
Oct 25 06:40:37 server electrumx_server.py[12626]: server.db.DB.DBError: your DB version is 5 but this software only handles versions [6]
Oct 25 06:40:37 server electrumx_server.py[12626]: CRITICAL:root:ElectrumX server terminated abnormally

When I select leveldb, I got this error:

Oct 25 07:06:27 server electrumx_server.py[14353]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/server/db.py", line 115, in open_dbs
Oct 25 07:06:27 server electrumx_server.py[14353]:     self.utxo_db = self.db_class('utxo', for_sync)
Oct 25 07:06:27 server electrumx_server.py[14353]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/server/storage.py", line 31, in __init__
Oct 25 07:06:27 server electrumx_server.py[14353]:     self.open(name, create=self.is_new)
Oct 25 07:06:27 server electrumx_server.py[14353]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/server/storage.py", line 83, in open
Oct 25 07:06:27 server electrumx_server.py[14353]:     max_open_files=mof)
Oct 25 07:06:27 server electrumx_server.py[14353]:   File "_plyvel.pyx", line 236, in plyvel._plyvel.DB.__init__ (plyvel/_plyvel.cpp:3129)
Oct 25 07:06:27 server electrumx_server.py[14353]:   File "_plyvel.pyx", line 83, in plyvel._plyvel.raise_for_status (plyvel/_plyvel.cpp:1733)
Oct 25 07:06:27 server electrumx_server.py[14353]: plyvel._plyvel.CorruptionError: b'Corruption: VersionEdit: unknown tag'
Oct 25 07:06:27 server electrumx_server.py[14353]: CRITICAL:root:ElectrumX server terminated abnormally

**Comment by kyuupichan** [comment]
Please read the changelog
