### ISSUE TITLE
get_merkle fails for some altcoins

### ISSUE THREAD

**Issue by Durendal** [kyuupichan/electrumx#305]
I've noticed that, at least for rubycoin the get_merkle command fails, I traced this to the following snippet:
```
   async def deserialised_block(self, hex_hash):
        '''Return the deserialised block with the given hex hash.'''
        return await self._send_single('getblock', (hex_hash, True))
```
the second parameter, True, tells the daemon to return a list of dicts representing deserialized tx's rather than simply a list of tx hashes. Im not sure if changing this would break things for other coins so I propose the following solution in controller.py:
```
    async def tx_merkle(self, tx_hash, height):
        '''tx_hash is a hex string.'''
        hex_hashes = await self.daemon_request('block_hex_hashes', height, 1)
        block = await self.daemon_request('deserialised_block', hex_hashes[0])
        tx_hashes = [tx['txid'] for tx in block['tx']] if (isinstance(block['tx'][0], dict) and 'txid' in block['tx'][0].keys()) else block['tx']

        try:
            pos = tx_hashes.index(tx_hash)
        except ValueError:
            raise RPCError('tx hash {} not in block {} at height {:,d}'
                           .format(tx_hash, hex_hashes[0], height))

        idx = pos
        hashes = [hex_str_to_hash(txh) for txh in tx_hashes]
        merkle_branch = []
        while len(hashes) > 1:
            if len(hashes) & 1:
                hashes.append(hashes[-1])
            idx = idx - 1 if (idx & 1) else idx + 1
            merkle_branch.append(hash_to_str(hashes[idx]))
            idx //= 2
            hashes = [double_sha256(hashes[n] + hashes[n + 1])
                      for n in range(0, len(hashes), 2)]

        return {"block_height": height, "merkle": merkle_branch, "pos": pos}
```
rather than assigning block['tx'] to tx_hashes it first checks whether it is a dict or a list, and handles it accordingly. this should maintain compatability with any other daemons. I would have issued a pull request however my fork of the code contains other changes that probably arent desireable for you.

**Comment by kyuupichan** [comment]
Fixing this is what LegacyRPCDaemon was written for.  Use that, though there is another issue open saying it doesn't work properly.  I don't run these altcoins so cannot test / fix.
