### ISSUE TITLE
Single CPU core 100% usage

### ISSUE THREAD

**Issue by erasmospunk** [kyuupichan/electrumx#312]
I have noticed with Bitcoin Gold that when electrumx loses connection with the daemon it is stuck with 100% single core usage.

From the logs:
```
2017-11-13 23:23:47,519:Daemon:ERROR:timeout error.  Retrying occasionally...
2017-11-13 23:25:59,258:ElectrumX:INFO:[2765] SSL XXX.XXX.XXX.XXX:YYYYY, 572 total
```

There is a gap of 2 minutes that the server is unresponsive to RPC calls, getting `request timed out after 15s`

I noticed this a couple of times with some altcoins but with BTG, they did something and it happens more often.

Have you noticed anything similar?

Edit: forgot to mention that the `getinfo` RPC of the daemon works without an issue while ElectrumX is burning CPU cycles.

**Comment by kyuupichan** [comment]
There's a silly bug in the daemon fail loop in daemon.py (there is a secs variable that's updated but not used properly IIRC).  I've not gotten round to fixing it, it's truly trivial; can you see if that helps?

I'm about to board a flight so can't look.

**Comment by erasmospunk** [comment]
Sorry, forgot to answer. That code is a bit confusing and I get some warnings with intellij. I am not sure how to go about fixing and testing this, without breaking it.

**Comment by kyuupichan** [comment]
If you have a way to repro this I can take a look.  I think I fixed the daemon loop at some stage so the issue I refer to above is gone.

**Comment by kyuupichan** [comment]
Oh, I have an idea what it is.  The async codepaths for a single client will all be waiting on the daemon.  That can make it unresponsive to RPC calls from those clients (are these RPC calls on the same connection, or new connections?)

**Comment by kyuupichan** [comment]
@erasmospunk I don't think we're going to figure this one out.  However leveldb/rocksdb do go into high CPU usage sessions at random when they decided to compact / reorganise / move data beween levels.  It's very likely it's related to that.  I see it occasionally on my server, where blocks sometimes are processed in under a second; sometimes it takes 90s.  I suspect that may be it.  Unfortunately it's not something I think we can control, but I may be wrong.

**Comment by erasmospunk** [comment]
Agreed, closing this.

**Comment by kyuupichan** [comment]
@erasmospunk if something similar happens again, check the DB logs in the DB directory.  I have and they show the DBs can suck up a crazy amount of time moving data between levels.
