### ISSUE TITLE
Indexing slows down over time requiring service restart

### ISSUE THREAD

**Issue by mzarglis** [kyuupichan/electrumx#327]
I noticed that while indexing the bitcoin blockchain the process gradually slows down requiring a service restart. Anything i can look into as to why it slows down as time goes on.

Ubuntu 16.04

Core i7-2600
2x HDD 3,0 TB  raid-0
16 gb ram

been indexing for about 2 days now about 10k blocks left

Before restart

<pre><code>Dec 07 15:48:53 titan.elysium.is electrumx_server.py[14233]: INFO:BlockProcessor:flushed to FS in 0.1s
Dec 07 15:48:56 titan.elysium.is electrumx_server.py[14233]: INFO:BlockProcessor:flushed history in 2.4s for 1,226,038 addr
Dec 07 15:48:56 titan.elysium.is electrumx_server.py[14233]: INFO:BlockProcessor:flush #397 took 2.5s.  Height 491,429 txs:
Dec 07 15:48:56 titan.elysium.is electrumx_server.py[14233]: INFO:BlockProcessor:tx/sec since genesis: 1,368, since last fl
Dec 07 15:48:56 titan.elysium.is electrumx_server.py[14233]: INFO:BlockProcessor:sync time: 2d 05h 47m  ETA: 11h 02m 03s
Dec 07 15:51:43 titan.elysium.is electrumx_server.py[14233]: INFO:BlockProcessor:our height: 491,439 daemon: 498,091 UTXOs 
Dec 07 16:00:50 titan.elysium.is electrumx_server.py[14233]: INFO:BlockProcessor:our height: 491,449 daemon: 498,091 UTXOs 
Dec 07 16:19:06 titan.elysium.is electrumx_server.py[14233]: INFO:BlockProcessor:our height: 491,458 daemon: 498,091 UTXOs 
Dec 07 16:38:46 titan.elysium.is electrumx_server.py[14233]: INFO:BlockProcessor:our height: 491,468 daemon: 498,091 UTXOs 
Dec 07 16:46:02 titan.elysium.is electrumx_server.py[14233]: INFO:BlockProcessor:our height: 491,478 daemon: 498,095 UTXOs 
lines 1-17/17 (END)...skipping...</code></pre>

After Restart:

<pre><code>
Dec 07 17:03:30 titan.elysium.is electrumx_server.py[12430]: INFO:BlockProcessor:our height: 492,834 daemon: 498,095 UTXOs 680MB hist 108MB
Dec 07 17:04:04 titan.elysium.is electrumx_server.py[12430]: INFO:BlockProcessor:our height: 492,937 daemon: 498,095 UTXOs 738MB hist 231MB
Dec 07 17:04:35 titan.elysium.is electrumx_server.py[12430]: INFO:BlockProcessor:our height: 493,031 daemon: 498,095 UTXOs 788MB hist 332MB
Dec 07 17:04:35 titan.elysium.is electrumx_server.py[12430]: INFO:BlockProcessor:flushed to FS in 0.1s
Dec 07 17:04:39 titan.elysium.is electrumx_server.py[12430]: INFO:BlockProcessor:flushed history in 3.5s for 1,667,737 addrs
Dec 07 17:04:39 titan.elysium.is electrumx_server.py[12430]: INFO:BlockProcessor:flush #404 took 3.7s.  Height 493,031 txs: 268,395,684
Dec 07 17:04:39 titan.elysium.is electrumx_server.py[12430]: INFO:BlockProcessor:tx/sec since genesis: 1,354, since last flush: 6,547
Dec 07 17:04:39 titan.elysium.is electrumx_server.py[12430]: INFO:BlockProcessor:sync time: 2d 07h 02m  ETA: 24m 13s
Dec 07 17:05:12 titan.elysium.is electrumx_server.py[12430]: INFO:BlockProcessor:our height: 493,112 daemon: 498,095 UTXOs 813MB hist 99MB
Dec 07 17:06:10 titan.elysium.is electrumx_server.py[12430]: INFO:BlockProcessor:our height: 493,142 daemon: 498,095 UTXOs 823MB hist 133MB
</code></pre>

**Comment by kyuupichan** [comment]
Yes, more transactions and segwit make it slow.
