### ISSUE TITLE
genesis block hash comparing failed

### ISSUE THREAD

**Issue by daja0923** [kyuupichan/electrumx#328]
Trying to install electrumx for Innovacoin. The following is the coin class:
class Innovacoin(Coin):
    NAME = "Innovacoin"
    SHORTNAME = "INN"
    NET = "mainnet"
    P2PKH_VERBYTE = bytes.fromhex("66") # Address starts with i
    P2SH_VERBYTES = [bytes.fromhex("14")]
    WIF_BYTE = bytes.fromhex("C3") #WIF - Wallet Information Format
    GENESIS_HASH = ('000003841e9ad6096539e5a6a0c3a0d3'
                    'a3f71b96da0c1ecf744052e6ee3cc2cd')
    DESERIALIZER = lib_tx.DeserializerTxTime
    DAEMON = daemon.LegacyRPCDaemon
    TX_COUNT = 10030 #gettxoutsetinfo
    TX_COUNT_HEIGHT = 33074
    TX_PER_BLOCK = 1
    RPC_PORT = 14519
    REORG_LIMIT = 5000

But getting this exception:
ERROR:Controller:Traceback (most recent call last):
Dec 07 23:47:00 electrumx electrumx_server.py[7679]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2.1-py3.6.egg/server/controller.py", line 177, in on_future_done
Dec 07 23:47:00 electrumx electrumx_server.py[7679]:     future.result()
Dec 07 23:47:00 electrumx electrumx_server.py[7679]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2.1-py3.6.egg/server/block_processor.py", line 50, in main_loop
Dec 07 23:47:00 electrumx electrumx_server.py[7679]:     if not await self._prefetch_blocks():
Dec 07 23:47:00 electrumx electrumx_server.py[7679]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2.1-py3.6.egg/server/block_processor.py", line 113, in _prefetch_blocks
Dec 07 23:47:00 electrumx electrumx_server.py[7679]:     blocks[0] = self.bp.coin.genesis_block(blocks[0])
Dec 07 23:47:00 electrumx electrumx_server.py[7679]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2.1-py3.6.egg/lib/coins.py", line 123, in genesis_block
Dec 07 23:47:00 electrumx electrumx_server.py[7679]:     .format(header_hex_hash, cls.GENESIS_HASH))
Dec 07 23:47:00 electrumx electrumx_server.py[7679]: lib.coins.CoinError: genesis block has hash 6c84e4af8d6fa7a6dde8e9111c8aead215eada7709d4529ef90330eafd452612 expected 000003841e9ad6096539e5a6a0c3a0d3a3f71b96da0c1ecf744052e6ee3cc2cd

**Comment by kyuupichan** [comment]
I have no idea what the correct hash is but it looks like ElectrumX is correct as it starts with zeroes.  Whoever setup the coin provided the parameters.

**Comment by daja0923** [comment]
I think it is the second one starting with zeros that is configured that starts with zeros. It was queried from wallet. The first hash is what Electrumx is calculating. What params affect that?

**Comment by kyuupichan** [comment]
Yes it calculates it from data given by your daemon.  It's just a hash of the header. So either:

a) your daemon is serving corrupt data
b) ElectrumX has the wrong hash algo implemented by whoever started your coin

I don't know which is the case, but it's one of them.

**Comment by daja0923** [comment]
Innovacoin uses Neoscrypt algorithm. Do we need to make changes in Electrumx to calculate the header hash?

**Comment by kyuupichan** [comment]
Lol.  I thought you were asking about an existing coin.  Yes, you need to implement the hash function or import the library.  This isn't a help forum; please look at the wealth of examples already existing in coins.py.

**Comment by daja0923** [comment]
Lol. Sorry for the confusing questions. Thanks for the help
