### ISSUE TITLE
Adding multiple bitcoin daemons as a backup

### ISSUE THREAD

**Issue by bauerj** [kyuupichan/electrumx#33]
Currently, if your bitcoin daemon goes offline, electrumx is basically offline too.

It would be nice if one could specify multiple bitcoin daemons as a failsafe.

The biggest problem about this is probably how to configure more than one daemon. 

This is just confusing:

    DAEMON_HOST=a.bitcoind.com;b.bitcoind.com
    DAEMON_PORT=1234;54321
    ....

This isn't great either:

    DAEMON_HOST.1=a.bitcoind.com
    DAEMON_HOST.2=b.bitcoind.com
    DAEMON_PORT.1=1234
    DAEMON_PORT.2=54321
    ...

**Comment by kyuupichan** [comment]
I think this is a good idea.  

Specifying lists of hosts, passwords in the split form seems confusing; perhaps the split form should only be usable for a single daemon, or should be deprecated.

But DAEMON_URL env var could become a comma-separated list of URLs; I don't think a comma is valid in the non-filename part of the URL, and if it is it is easily avoidable.

What do you think?  Fancy implementing it?

**Comment by bauerj** [comment]
Should we drop the separate vars for host, port, user and password then?

I think that would be the cleanest solution.

**Comment by kyuupichan** [comment]
I'm not opposed to that

**Comment by SuBPaR42** [comment]
I like this idea as well - Jelectrum allowed multiple bitcoinds...

**Comment by zilveer** [comment]
@kyuupichan it would be a great idea to have the backup daemons as comma separated on the config file.
