### ISSUE TITLE
Link to newer Docker image in the readme

### ISSUE THREAD

**Issue by lukechilds** [kyuupichan/electrumx#331]
I created my own Docker image ([`lukechilds/electrumx`](https://github.com/lukechilds/docker-electrumx)) due to some issues I had with the current image recommended in the readme ([`followtheart/electrumx`](https://github.com/followtheart/electrumx-docker)).

The followtheart image doesn't follow Docker best practices and is also quite large and out of date. I believe my image is better because:

**Size**

`lukechilds/electrumx`: 40MB
`followtheart/electrumx`: 175MB

**Follows Docker conventions**

- All settings are passed in as ENV vars (no need for ENV folder)
- Runs ElectrumX directly as PID 1 instead of bash -> daemon
  - Interactive Docker sessions attach directly meaning `Control-C` works
  - Interactive Docker sessions get ElectrumX output to STDOUT
  - ElectrumX output will be piped to normal Docker logging tools
  - You shouldn't dockerize a daemon, the Docker image itself should be daemonized
- Reproducible builds: separate branch for each release (followtheart container builds current master)

**Up to date**

Pulling from Docker Hub will pull the latest ElectrumX release. You can also specify a tag to pull specific older ElectrumX releases.

The latest followtheart build on Docker Hub is 6 months out of date.

**Secure**

If no SSL cert is provided one will be automatically generated on first boot.

---

Following these rules makes the image much easier to orchestrate in other Docker projects (e.g [Dockerized Vertcoin Electrum Server](https://github.com/lukechilds/docker-electrum-vertcoin/blob/master/docker-compose.yml)), it's also currently the most used ElectrumX image on Docker Hub.

Let me know if you'd like to link to this image instead and I'll happily submit a PR.

**Comment by kyuupichan** [comment]
As I don't user Docker and @followtheart initially added this to the repo, I'd his/her thoughts.  

Yes a PR would be nice.  Please mention in the commit log it closes this issue.

**Comment by lukechilds** [comment]
Of course, opened a PR.
