### ISSUE TITLE
server accepts connections before memorypool is imported

### ISSUE THREAD

**Issue by ecdsa** [kyuupichan/electrumx#335]
it should wait until the memorypool has been processed.

**Comment by kyuupichan** [comment]
Why is this a problem?  I'm willing to make it wait but I'm wondering what issues it causes, if any.

**Comment by kyuupichan** [comment]
@ecdsa is this problematic because of the histogram thing?  I guess I'm not averse to turning it off; I'd need to figure out how.

**Comment by ecdsa** [comment]
no, it is problematic because the server is returning an incomplete history to the client during the time it takes to import the memory pool. this may take several minutes with the Bitcoin chain.
