### ISSUE TITLE
Initial sync fails with ChainError: UTXO not found in "h" table

### ISSUE THREAD

**Issue by dgaus** [kyuupichan/electrumx#343]
Hi. While doing the initial sync on 1.2.1 BitcoinSegwit main net I am getting 
```
INFO:BlockProcessor:flushed to FS in 0.1s
INFO:BlockProcessor:flushed history in 5.4s for 1,798,908 addrs
INFO:BlockProcessor:flushed 9,131 blocks with 12,405,991 txs, 4,927,465 UTXO adds, 3,814,928 spends in 22.3s, committing...
INFO:BlockProcessor:flush #103 took 62.8s.  Height 405,409 txs: 119,830,914
INFO:BlockProcessor:tx/sec since genesis: 5,068, since last flush: 2,028
INFO:BlockProcessor:sync time: 06h 34m 03s  ETA: 1d 03h 46m
ERROR:Controller:Traceback (most recent call last):
  File "/home/diego/bin/electrumx/server/controller.py", line 177, in on_future_done
    future.result()
  File "/home/diego/bin/electrumx/server/block_processor.py", line 206, in main_loop
    await task()
  File "/home/diego/bin/electrumx/server/block_processor.py", line 250, in check_and_advance_blocks
    await self.controller.run_in_executor(self.advance_blocks, blocks)
  File "/home/diego/bin/electrumx/server/controller.py", line 157, in run_in_executor
    return await self.loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/diego/bin/electrumx/server/block_processor.py", line 500, in advance_blocks
    undo_info = self.advance_txs(block.transactions)
  File "/home/diego/bin/electrumx/server/block_processor.py", line 542, in advance_txs
    cache_value = spend_utxo(txin.prev_hash, txin.prev_idx)
  File "/home/diego/bin/electrumx/server/block_processor.py", line 727, in spend_utxo
    .format(hash_to_str(tx_hash), tx_idx))
server.block_processor.ChainError: UTXO 0ff6e199bd5523c63ea726146de782582f7038616183feda56713f3f2228275d / 0 not found in "h" table
```

However querying bitcoind I get a response that looks reasonable: https://gist.github.com/dgaus/5a58b7f6ba9139647c135bd9140b8b99

which is a very large transaction: https://blockchain.info/tx/0ff6e199bd5523c63ea726146de782582f7038616183feda56713f3f2228275d?show_adv=true

Is anyone getting a similar error? I first thought my hardware was faulty, but I tried on a different computer (and downloaded the entire blockchain again) and I still get this error. I am not entirely sure if the failing transaction was the same before (I didn't write it down) but the exception raised was the same. Thanks.

**Comment by kyuupichan** [comment]
This means your DB is corrupt.  It could be ElectrumX or bitcoind's, in most cases it is bitcoind.  You should reindex bitcoind and then restart your ElectrumX sync after deleting your ElectrumX DB.

**Comment by dgaus** [comment]
If bitcoind were corrupt it could not return that response? please take a look at the attached gist.

I did try it twice on different hardware.

**Comment by kyuupichan** [comment]
Is your bitcoind a freshly synced instance in both cases?  I doubt it.  Which points to bitcoind being the problem.  We've seen this at least 3 times, no reason to believe it's different this time.

**Comment by kyuupichan** [comment]
The problem is not when it fails, the problem is earlier data that is being proven inconsistent later.

**Comment by dgaus** [comment]
Freshly synced in both instances, may be bad luck but it would be against the odds. First time on a debian arm64 board and second time on archlinux intel i5 with an ssd. Both machines are very stable.

I have seen the other tickets... I will do a reindex and try again. If I can check anything let me know, I can debug Python.

**Comment by shaileshnift** [comment]
do you find any solution?
