### ISSUE TITLE
transaction type

### ISSUE THREAD

**Issue by erfan007p** [kyuupichan/electrumx#349]
wallet didnt accept scripthash transaction type with asm : OP_HASH160 pubKeyHash OP_EQUAL and only accept pubkeyhash transaction type with asm : OP_DUP OP_HASH160 pubKeyHash OP_EQUALVERIFY OP_CHECKSIG, idk if it hash anything todo with electrum server itself, but i kinda stuck,,,
is there any method to make it pubkeyhash type instead of scripthash ?
thanks

**Comment by kyuupichan** [comment]
I don't really understand your question.  The server doesn't care - it deals in the hash of the script, whatever the script is.  It sounds like you have a client problem somewhere.
