### ISSUE TITLE
electrumX 1.1.x: ERROR:FakeEstimateFeeDaemon:HTTP error code 404

### ISSUE THREAD

**Issue by fujicoin** [kyuupichan/electrumx#351]
I am trying to upgrade Electrum-FJC-2.9.3 to 3.0.5.
Looking at servers.json of electrum-3.0.5, the version of electrumX is written as 1.1.
Is electrumX 1.2.x still not used?
When I start the electrumX 1.1.x server and connect with electrum-FJC-2.9.3 or 3.0.5, the following errors are displayed consecutively.
```
2018-01-18 17:08:37.544457500 ERROR:FakeEstimateFeeDaemon:HTTP error code 404: Not Found  Retrying occasionally...
2018-01-18 17:08:42.336269500 INFO:FakeEstimateFeeDaemon:connection restored
```
What could not be found?
Where should I fix it?

This problem does not occur in ElectrumX 1.2.x.
However, in 1.2.x, transactions are rejected at a probability of 80% assuming that network rules are violated during remittance processing.

**Comment by kyuupichan** [comment]
Your daemon was either not started or not responding.  It then came back (connection restored)

**Comment by fujicoin** [comment]
You wrote in the "Version 1.2" section of the README  "However Electrum didn't handle P2PK  spends correctly ・・・"
Would you tell me a little more specifically what kind of problem this is referring to?

**Comment by kyuupichan** [comment]
It would create P2PKH spends; it could not spend a P2PK output.

**Comment by fujicoin** [comment]
I am continuing to investigate "HTTP error code 404: Not Found".
Currently, I am investigating with the conventional version electrum-FJC-2.9.x.
"HTTP error" does not occur in electrumX 1.0.11, but it occurs in 1.0.17.
I think that I can see which changes are affected with a little more investigating, but is there something to come up with?

**Comment by fujicoin** [comment]
The cause of the error was found out.
https://github.com/fujicoin/electrumx/blob/master/server/session.py#L304
I think there is a bug in "async def banner (self)".
If the following two lines are deleted, no error occurs.
```
             else:
                 banner = await self.replaced_banner (banner)
```
The banner file is as follows and variables are not used.
```
Welcome to Electrum & server ElectrumX 1.0.11 for FujiCoin.

The electrum system of Fujicoin is operated by donation.
Please consider donating FJC equivalent of 5 USD.
Thank you! -> [Help] -> [Donate to server]
```

How do you deal with it?

**Comment by kyuupichan** [comment]
Well if you look in the replaced_banner function you might find there's a daemon call....  Perhaps that's a clue...

**Comment by fujicoin** [comment]
The cause is this.
https://github.com/kyuupichan/electrumx/blob/master/server/session.py#L282
Fujicoin's daemon does not have the command "getnetworkinfo".
Is it enough to get version by "getinfo" command? "getinfo" is a very basic command and exists in any coin.
https://chainquery.com/bitcoin-api/getinfo
https://chainquery.com/bitcoin-api/getnetworkinfo
Do not you want to change it?

Also, are the major, minor, and revision calculations ambiguous?
I think the next calculation is correct.
```
         major, minor = divmod (ni_version, 10000)
         minor, revision = divmod (minor, 100)
         revision // = 1
```

Please consider.

**Comment by kyuupichan** [comment]
No, getnetworkinfo is correct; getinfo is deprecated.  You need to figure out how to implement it for your coin.

**Comment by fujicoin** [comment]
According to your advice I rebuilt Fujicoin on Bitcoin v0.15.1 base. I made a pull request earlier. 
Thanking you in advance.
