### ISSUE TITLE
new Bitcoin Cash address format not supported

### ISSUE THREAD

**Issue by cipig** [kyuupichan/electrumx#352]
when trying to use the new address format of Bitcoin Cash, the electrum servers answers with
`{"jsonrpc": "2.0", "id": 1, "error": {"message": "qq2x9s7a87fk6k2unt64j7qq8vnuy5zyru4m3ty8hc is not a valid address", "code": -1}}`

the wallet is updated and supports the new format
```
{
  "isvalid": true,
  "address": "bitcoincash:qq2x9s7a87fk6k2unt64j7qq8vnuy5zyru4m3ty8hc",
  "scriptPubKey": "76a9141462c3dd3f936d595c9af55978003b27c250441f88ac"
}
```

**Comment by kyuupichan** [comment]
Not a bug; only legacy addresses are supported.  Maybe check how it works for Electron Cash?

**Comment by mjwaddell** [comment]
Will the new address format be supported by ElectrumX in the future?

**Comment by kyuupichan** [comment]
No, instead all address support will be removed in future
