### ISSUE TITLE
Relay fee sometimes ignored when broadcasting

### ISSUE THREAD

**Issue by youssefgh** [kyuupichan/electrumx#359]
Version: ElectrumX 1.2.1
Bitcoin core version: 15.1
Relayfee: 1e-05
Network: testnet
When broadcasting this transaction : 7b77676fc80cac722ab4dd1dd7f4ac1f7f86aaf75ac15516ac39d7351a66e7b5 the broadcast call should return an error due to fees 0.00000446 less than relayfee advertised by the blockchaine.relayfee
However when paying 0.00000223 i get the broadcast error as it should be

**Comment by kyuupichan** [comment]
This is nothing to do with ElectrumX; it knows nothing about relay fees.

**Comment by youssefgh** [comment]
Then is it Bitcoin core that should enforce this rule ?
Because ElectrumX doc says:

> blockchain.relayfee
Return the minimum fee a low-priority tx must pay in order to be accepted to the daemon's memory pool.

Do you thinks that this should be reported to Core ?
Thanks

**Comment by kyuupichan** [comment]
Well that's just an RPC call passed on to bitcoind. ElectrumX doesn't enforce transaction policies

**Comment by youssefgh** [comment]
Then i'll try to report this to Bitcoin core
Thanks
