### ISSUE TITLE
blockchain.address.get_history limit transactions number

### ISSUE THREAD

**Issue by goodProjects** [kyuupichan/electrumx#364]
can you support limit parameter? 

why? 
- Some servers taking too long to get all transactions of an address that has more than (e.g) 100 transaction.
- if an address has transactions more than what we allowed getting from a server, we will become not able to fetch the recent transactions.

**Comment by kyuupichan** [comment]
What is your use case? You can always run your own server...

**Comment by goodProjects** [comment]
I have some address with 1000 transaction, and I want to get just the last 10 transactions.

getting all transactions is bad for the bandwidth and for performance.

**Comment by kyuupichan** [comment]
What software are you using?

**Comment by goodProjects** [comment]
I programmed my own interface on PHP. I'm sending commands to public electrum servers beside my own server.

**Comment by kyuupichan** [comment]
Closing this as a duplicate of #28 which wants the same thing
