### ISSUE TITLE
blockchain.address.listunspent don't show zero confirmations inputs

### ISSUE THREAD

**Issue by goodProjects** [kyuupichan/electrumx#365]

**Comment by kyuupichan** [comment]
The original electrum-server did not include such items.  The docs indicate this should include them but that's from a generic update to the docs a while ago.  I'm not sure whether this should be done.

What is your usecase, again?

**Comment by goodProjects** [comment]
Sorry for too many issues, but we're a group of programmers coding new innovative cryptocurrencies wallet and electrum is part of it. 

get an address with an unconfirmed transaction, call blockchain.address.get_history you will see that transaction but not when calling blockchain.address.listunspent

**Comment by erasmospunk** [comment]
The protocol cannot change as it affects existing clients.

A backward-compatible protocol addition can be an additional parameter `confirmations`:

```
{"id": 1, "method": "blockchain.address.listunspent", "params": ["1ADDR..", "0"]}
```

If `confirmations` is set to `1` we get the same result of the existing protocol.

**Comment by goodProjects** [comment]
I would be a good additional parameter!

**Comment by kyuupichan** [comment]
@erasmospunk I'm inclined to simply change the behaviour of this method to include mempool txs.  Would this break anything you depend on?  It returns enough information for you to be able to filter them (the height would be 0 or -1).  I already changed this method about 4 months ago to remove mempool spends so it seems natural to include mempool receipts.

**Comment by kyuupichan** [comment]
I've updated this function.  Note the height returned for unconfirmed receipts is 0.  It is presently never -1 (whether inputs are confirmed or not is not considered).
