### ISSUE TITLE
blockchain.address.listunspent sending array of addresses

### ISSUE THREAD

**Issue by goodProjects** [kyuupichan/electrumx#366]
blockchain.address.listunspent accept only one address. sending more than one address in the same call would much better for performance.

why we have to make 5 requests if we can send one request with an array of parameters? 

before
`blockchain.address.listunspent( (string) $address)`
after
`blockchain.address.listunspent( (array) $addresses)`

**Comment by kyuupichan** [comment]
That is the protocol.  you can send batch requests if you want.

**Comment by goodProjects** [comment]
Sorry, but what is the batch requests?

**Comment by kyuupichan** [comment]
http://www.jsonrpc.org/specification

**Comment by goodProjects** [comment]
Thank you, it was exactly what I looking for.

**Comment by zilveer** [comment]
> http://www.jsonrpc.org/specification

Hi,
I would like to know if electrumx api supports batch requests for:
* Balance
* Listunspent

How is it possible to send batch requests using the electrumx api?

Any guidance is appreciated. 

Regards Zilveer

**Comment by kyuupichan** [comment]
Batch requests are supported as per the JSON spec for any method
