### ISSUE TITLE
 Server "testnet.hsmiths.com" hops headers and never send them

### ISSUE THREAD

**Issue by alieslam** [kyuupichan/electrumx#368]
Server skips headers and never send them, so the next one will never be valid since chain lags with single/multiple headers. I have tested it with simple nodeJs script with two servers (testnetnode.arihanc.com&testnet.hsmiths.com), watched them at the same time, the first server sent the headers respectively while the second sometimes hops. Shouldn't the server saves last header sent to clients and start within? 

Would this happen on MainNet!?

Below is the script along with attached screenshots from my cmd shell.
```
var net = require('net');

var client = new net.Socket();
client.connect(53011, 'testnet.hsmiths.com', function() {
console.log('Connected');
client.write("{\"id\":0,\"method\":\"server.version\",\"params\":[\"2.7.11\"]}\n");
client.write("{ \"id\": 3, \"method\": \"blockchain.headers.subscribe\", \"params\": []}\n");
client.write("{ \"id\": 0, \"method\": \"blockchain.numblocks.subscribe\", \"params\": []}\n");
setInterval(function(){
	client.write("{\"id\":0,\"method\":\"server.version\",\"params\":[\"2.7.11\"]}\n");
},55000);
});


client.on('data', function(data) {
console.log(data.toString());
});


client.on('close', function() {
console.log('Connection closed');
});
```
_Next screenshot log showing "testnet.hsmiths.com" hopping multiple headers_
![missingheader2](https://user-images.githubusercontent.com/8179651/35910570-aec3fe44-0bff-11e8-991e-078a749ee0c7.PNG)
_Next screenshot log showing "testnet.hsmiths.com" hopping single header vs Last screenshot log showing "testnetnode.arihanc.com" correctly sending headers_ 
![inkedhsmithserror1_li](https://user-images.githubusercontent.com/8179651/35910637-eb96a4e8-0bff-11e8-92ca-0239d3ef0137.jpg)

![correctheaders png](https://user-images.githubusercontent.com/8179651/35910701-1897823c-0c00-11e8-9943-e0bd734cc804.jpg)

**Comment by kyuupichan** [comment]
If new blocks arrive whilst previous ones are being processed, the notifications are essentially elided and only the most recent one sent.  I'm not sure whether to consider this a bug or not.  Why do you need each one?  How are you using the information?  Electrum client has no issue with this behaviour.

**Comment by alieslam** [comment]
Aha got it..! Am creating a SPV client on a an embedded hardware (ESP8266), connecting to 2 Electrum servers (unfortunately due to limited TCP connection),and when the difficulty went down to 1, the servers started sending headers rapidly, and because i am validating the headers at my side it takes both computational and memory resources. Then the server sent the last validated header (differs in height with my local height >1) which ofcourse force the system to make extra calls and consuming memory, especially that there were no chain reorganization occurred at the servers side.

I have already handled the case, still working to get it to the most optimum for my system, but i think it would be better if the servers send the headers sequentially saving the effort on such less powered systems, what do you think?

**Comment by kyuupichan** [comment]
The project doesn't have a goal of supporting small clients, so I don't think that is a good reason.  

As you mention, a reorg would also have this issue.  If there were a reorg for 10 blocks, as frequently happens on testnet, I believe ElectrumX would simply send the new tip on the reorged chain.  It can't unsend the 10 old headers, and I don't believe it sends all 10 new headers on the new branch.  So I don't really think I want to change anything, as it wouldn't help in the reorg case anyway.

I think a light client can just keep track of what the server tells it is the most recent header with this RPC, and recursively request missing ones until it gets a previous header hash it knows about (the join point).  A client needs similar functionality anyway for re-orgs.  No?

**Comment by alieslam** [comment]
Yup you do have a point.. and i already handled the remote reorg using the same recursively way, anyway in the near future the system will be working on the mainnet (ofcourse after further testing on testnet) so i think (and hopefully) it will be handling such cases smoothly.
Thanks for the discussion 👍closing the issue

**Comment by kyuupichan** [comment]
I will update the docs to point this out.  It's a bit more work software-wise but it's possible to bisect on the fork height and then get headers in a forward direction, rather than recursing backwards.  If you recurse backwards and the server is evil it could easily send you on a goose chase back to genesis block.

**Comment by alieslam** [comment]
Yes i am already handling forward direction forks, but there's a problem in the case if my connected Electrum servers send all equally same current header wrt (height) but unfortunately it was their already solved fork tip (new header is not built over the old same equal header they sent me before), so in this way the case of "goose chase back " would happen (maybe this case will also be handled by connecting to as much multiple Electrum servers as possible, but in my case it won't work as i mentioned i have limitation on TCP connections)
Do you think servers should inform their connected clients with immediate current header forks by sending them to their clients just to make them aware and start forward forking?
