### ISSUE TITLE
Example of Python request

### ISSUE THREAD

**Issue by superoleg421** [kyuupichan/electrumx#369]
Hello! I launched your code on my server and it seems to be working properly. But can you please give an example of Python code which sends some request to it? In my program I need to use blockchain.address.get_balance function. Is there any simple solution? Thank you for answer.

**Comment by kyuupichan** [comment]
It is JSON over an SSL or TCP connection.  Beyond that this project is not a tutorial on programming.  People could request examples in any number of languages and I have no desire to maintain such examples.  However, should someone submit an example for the docs directory I wouldn't be averse to including it.
