### ISSUE TITLE
Crash after reorg

### ISSUE THREAD

**Issue by bauerj** [kyuupichan/electrumx#37]
I don't really know what the issue is but the database seems to be broken:

	Nov 21 21:29:02 helicarrier electrumx_server.py[31020]: INFO:BlockServer:backing up 1 blocks
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]: Traceback (most recent call last):
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:   File "/home/electrumx/electrumx/server/block_processor.py", line 228, in _wait_for_update
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:     self.advance_block(block, self.caught_up)
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:   File "/home/electrumx/electrumx/server/block_processor.py", line 576, in advance_block
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:     raise ChainReorg
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]: server.block_processor.ChainReorg
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]: During handling of the above exception, another exception occurred:
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]: Traceback (most recent call last):
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:   File "/home/electrumx/electrumx/electrumx_server.py", line 67, in main
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:     main_loop()
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:   File "/home/electrumx/electrumx/electrumx_server.py", line 58, in main_loop
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:     loop.run_until_complete(future)
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:   File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:     return future.result()
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:     raise self._exception
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:     result = coro.send(None)
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:   File "/home/electrumx/electrumx/server/block_processor.py", line 195, in main_loop
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:     await self._wait_for_update()
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:   File "/home/electrumx/electrumx/server/block_processor.py", line 231, in _wait_for_update
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:     await self.handle_chain_reorg()
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:   File "/home/electrumx/electrumx/server/block_processor.py", line 269, in handle_chain_reorg
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:     self.backup_blocks(blocks)
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:   File "/home/electrumx/electrumx/server/block_processor.py", line 648, in backup_blocks
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:     self.backup_txs(tx_hashes, txs, touched)
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:   File "/home/electrumx/electrumx/server/block_processor.py", line 679, in backup_txs
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:     cache_value = spend_utxo(tx_hash, idx)
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:   File "/home/electrumx/electrumx/server/block_processor.py", line 788, in spend_utxo
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]:     .format(hash_to_str(tx_hash), tx_idx))
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]: server.block_processor.ChainError: UTXO d46f7dc5c2e41918bbe84fa933a497d9f61a640f90aabea433313889ea7d4e7d / 0 not found in "h" table
	Nov 21 21:29:03 helicarrier electrumx_server.py[31020]: CRITICAL:root:ElectrumX server terminated abnormally
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: Traceback (most recent call last):
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]:   File "/usr/lib/python3.5/asyncio/base_events.py", line 431, in __del__
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]:   File "/usr/lib/python3.5/asyncio/unix_events.py", line 58, in close
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]:   File "/usr/lib/python3.5/asyncio/unix_events.py", line 139, in remove_signal_handler
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]:   File "/usr/lib/python3.5/signal.py", line 47, in signal
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: ERROR:asyncio:Task was destroyed but it is pending!
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: task: <Task pending coro=<Session.serve_requests() running at /home/electrumx/electrumx/server/protocol.py:466> wait_for=<Future finished result=None>>
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: ERROR:asyncio:Task was destroyed but it is pending!
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: task: <Task pending coro=<Session.serve_requests() running at /home/electrumx/electrumx/server/protocol.py:466> wait_for=<Future finished result=None>>
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: ERROR:asyncio:Task was destroyed but it is pending!
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: task: <Task pending coro=<Session.serve_requests() running at /home/electrumx/electrumx/server/protocol.py:466> wait_for=<Future finished result=None>>
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: ERROR:asyncio:Task was destroyed but it is pending!
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: task: <Task pending coro=<Session.serve_requests() running at /home/electrumx/electrumx/server/protocol.py:466> wait_for=<Future finished result=None>>
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: ERROR:asyncio:Task was destroyed but it is pending!
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: task: <Task pending coro=<Session.serve_requests() running at /home/electrumx/electrumx/server/protocol.py:466> wait_for=<Future finished result=None>>
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: ERROR:asyncio:Task was destroyed but it is pending!
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: task: <Task pending coro=<Session.serve_requests() running at /home/electrumx/electrumx/server/protocol.py:466> wait_for=<Future finished result=None>>
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: ERROR:asyncio:Task was destroyed but it is pending!
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: task: <Task pending coro=<Prefetcher.main_loop() running at /home/electrumx/electrumx/server/block_processor.py:84> wait_for=<Future pending cb=[Task._wakeup()]>>
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: ERROR:asyncio:Task was destroyed but it is pending!
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: task: <Task pending coro=<MemPool.main_loop() running at /home/electrumx/electrumx/server/protocol.py:111> wait_for=<Future pending cb=[Task._wakeup()]>>
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: ERROR:asyncio:Task was destroyed but it is pending!
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: task: <Task pending coro=<IRC.start() running at /home/electrumx/electrumx/server/irc.py:55> wait_for=<Future pending cb=[Task._wakeup()]>>
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: ERROR:asyncio:Fatal write error on socket transport
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: protocol: <asyncio.sslproto.SSLProtocol object at 0x7f9f1b806da0>
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: transport: <_SelectorSocketTransport fd=71>
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: Traceback (most recent call last):
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]:   File "/usr/lib/python3.5/asyncio/selector_events.py", line 700, in write
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]:     n = self._sock.send(data)
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: OSError: [Errno 9] Bad file descriptor
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: ERROR:asyncio:Fatal error on SSL transport
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: protocol: <asyncio.sslproto.SSLProtocol object at 0x7f9f1b806da0>
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: transport: <_SelectorSocketTransport closing fd=71>
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: Traceback (most recent call last):
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]:   File "/usr/lib/python3.5/asyncio/selector_events.py", line 700, in write
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]:     n = self._sock.send(data)
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: OSError: [Errno 9] Bad file descriptor
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: During handling of the above exception, another exception occurred:
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]: Traceback (most recent call last):
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]:   File "/usr/lib/python3.5/asyncio/sslproto.py", line 632, in _process_write_backlog
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]:     self._transport.write(chunk)
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]:   File "/usr/lib/python3.5/asyncio/selector_events.py", line 704, in write
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]:     self._fatal_error(exc, 'Fatal write error on socket transport')
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]:   File "/usr/lib/python3.5/asyncio/selector_events.py", line 589, in _fatal_error
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]:     self._force_close(exc)
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]:   File "/usr/lib/python3.5/asyncio/selector_events.py", line 601, in _force_close
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]:     self._loop.call_soon(self._call_connection_lost, exc)
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]:   File "/usr/lib/python3.5/asyncio/base_events.py", line 497, in call_soon
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]:     handle = self._call_soon(callback, args)
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]:   File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]:     self._check_closed()
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]:   File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
	Nov 21 21:29:06 helicarrier electrumx_server.py[31020]:     raise RuntimeError('Event loop is closed')

**Comment by kyuupichan** [comment]
Thanks, fixed in 0.7.3 I believe, just released.
