### ISSUE TITLE
shutdown via daemontools contrib code broken on debian and devuan

### ISSUE THREAD

**Issue by jkister** [kyuupichan/electrumx#374]
newer versions of Debian use dash as sh, i.e., /bin/sh -> /bin/dash

this causes svc -d /service/electrumx to not stop the electrumx_server.py

replacing "sh -c" in the run script with "bash -c" is one way to fix this issue.

**Comment by kyuupichan** [comment]
Yes, I've noticed this.  Do you understand what is different about bash and dash's handling of child processes and signal handling?  Clearly it's something to do with the /bin/sh -c invocation, which I do in order to be able to use environment variables from the envdir.
