### ISSUE TITLE
Incorrect genesis hash

### ISSUE THREAD

**Issue by nosferatu500** [kyuupichan/electrumx#375]
Hi! I try to integrate own crypto currency into electrumx. I setup abstraction class inside `lib/crypto.py`. But when I start `electrumx_server.py`  I get this message  `genesis block has hash b5ab78c9e5dfbc1fd1f0b8a469737ada600d7a8736eae756c7eb2b8bcda3c040 expected 0000000032fe677166d54963b62a4677d8957e87c508eaa4fd7eb1c880cd27e3` but second hash  is correct and I don't  known how it  get first hash. And  yet I get message that `WARNING:BlockProcessor:ignoring 500 blocks starting height 500, expected 0` and I dont't understand why. Can you help me please?

**Comment by nosferatu500** [comment]
I really  want to understand how your  project  work. Can we  discuss some questions from my side through Facebook or Skype call or some one else?

**Comment by kyuupichan** [comment]
This is supposed to be for bugs.  The line you're failing at is comparing the hash you provided as the genesis hash to the one it calculates from the header.  If it's not calculating it correctly you need to override the header hash calculation.  There are many examples in coins.py.

**Comment by nosferatu500** [comment]
Hmm.... I thought about this. Thank you for your answer.
