### ISSUE TITLE
cant start with torrent db

### ISSUE THREAD

**Issue by BlackSnow98** [kyuupichan/electrumx#376]
Hi, i cant start server with db, what i download via torrent...
here is error:

> Feb 15 19:46:45 Alpha electrumx_server.py[13447]: INFO:root:ElectrumX server starting
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]: INFO:Controller:event loop policy: None
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]: INFO:Daemon:daemon #1 at 127.0.0.1:19332/ (current)
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]: INFO:BlockProcessor:switching current directory to /mnt/electrum/electrumx_1.2_btc_leveldb_490153
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]: INFO:BlockProcessor:using rocksdb for DB backend
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]: INFO:BlockProcessor:opened DB for serving
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]: INFO:BlockProcessor:software version: ElectrumX 1.2
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]: INFO:BlockProcessor:DB version: 6
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]: INFO:BlockProcessor:coin: BitcoinSegwit
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]: INFO:BlockProcessor:network: mainnet
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]: INFO:BlockProcessor:height: 490,153
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]: INFO:BlockProcessor:tip: 000000000000000000c2a6ef80cb5d6f7c68a24f494eba5988144c045432a228
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]: INFO:BlockProcessor:tx count: 262,597,729
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]: INFO:BlockProcessor:flush count: 196
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]: Traceback (most recent call last):
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/EGG-INFO/scripts/electrumx_server.py", line 24, in main
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/server/controller.py", line 78, in __init__
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]:     self.bp = self.coin.BLOCK_PROCESSOR(env, self, self.daemon)
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/server/block_processor.py", line 144, in __init__
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]:     super().__init__(env)
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/server/db.py", line 68, in __init__
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]:     self.clean_db()
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/server/db.py", line 158, in clean_db
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]:     self.clear_excess_undo_info()
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/server/db.py", line 278, in clear_excess_undo_info
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]:     for key, hist in self.utxo_db.iterator(prefix=prefix):
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/server/storage.py", line 121, in iterator
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]:     return RocksDBIterator(self.db, prefix, reverse)
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/server/storage.py", line 157, in __init__
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]:     self.iterator.seek(prefix)
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]:   File "rocksdb/_rocksdb.pyx", line 1705, in rocksdb._rocksdb.BaseIterator.seek
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]:   File "rocksdb/_rocksdb.pyx", line 1709, in rocksdb._rocksdb.BaseIterator.seek
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]:   File "rocksdb/_rocksdb.pyx", line 82, in rocksdb._rocksdb.check_status
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]: rocksdb.errors.RocksIOError: b'IO error: utxo/016645.sst: No such file or directory'
> Feb 15 19:46:45 Alpha electrumx_server.py[13447]: CRITICAL:root:ElectrumX server terminated abnormally

but here is not file utxo/016645.sst in torrent... It db corrupt or i do somethink wrong?

**Comment by fr3aker** [comment]
As indicated at several places this database is for the leveldb backend.

**Comment by BlackSnow98** [comment]
> As indicated at several places this database is for the leveldb backend.
so i have to use DB_ENGINE=leveldb and install with  --leveldb ?

**Comment by BlackSnow98** [comment]
why you close this? any answer for me pls?

**Comment by kyuupichan** [comment]
If you choose to run with pre-initialised databases you need to be able to support yourself
