### ISSUE TITLE
blockchain.address.listunspent doesn't show mempool opt-in rbf (discrepancy from listunspent from full node)

### ISSUE THREAD

**Issue by greenaddress** [kyuupichan/electrumx#377]
While testing https://github.com/kyuupichan/electrumx/commit/76f4969a9840a5918e70b6ffd3a0b1e5b0fd9686 I noticed that while the fix works for things in mempool it seems to miss opt-in rbf updates.

I've tested this against listunspent (set for 0 conf) from full node and that's the only discrepancy I found compared to master (there are more with 1.2.1 , those are all fixed by https://github.com/kyuupichan/electrumx/commit/76f4969a9840a5918e70b6ffd3a0b1e5b0fd9686 as referenced in #365 )

To reproduce the issue in master: 
  - create an opt-in rbf enabled transaction (let's call it tx1) and broadcast.
  - broadcast a replacement (call that tx2) that say bumps the fee and is compliant with opt-in rbf propagation rules.
  - call listunspent on the full node set to 0 confirm) and compare against listunspent, full node will have the replacement (tx2) electrumx will show the original one (tx1)  

I'll see if I can find a fix however don't have much experience with electrumx since it is the first time I played with it. If you have a potential fix I can also help test it.

**Comment by kyuupichan** [comment]
ElectrumX merely mirrors your node so this is not an ElectrumX issue. It knows nothing aboutRBF.
