### ISSUE TITLE
Bech32 Support

### ISSUE THREAD

**Issue by goodProjects** [kyuupichan/electrumx#390]
Does electrumx support bech32 addresses and consider it as valid bitcoin address?

**Comment by kyuupichan** [comment]
New address formats are out of scope.  I want to lose the old ones too,

**Comment by erasmospunk** [comment]
@goodProjects the project moved from using addresses to output script hashes, using the `blockchain.scripthash.*` methods.

**Comment by erasmospunk** [comment]
@goodProjects no, you need the output script for that address that is:
`00149f3ff993794f55e8dd1086a3662d83783d1f7ad2`
then SHA256 hash it and reverse the bytes:
`a40e67a13f08cafbca39b6d9aa644c9e38af56eabbc36784cd6fb2bc2eada360`
finally:
```
{"id": 0, "method": "server.version", "params": ["1.0.0", "1.1"]}
{"id": 1, "method": "blockchain.scripthash.get_history", "params": ["a40e67a13f08cafbca39b6d9aa644c9e38af56eabbc36784cd6fb2bc2eada360"]}
```
You need the first call to let the ElectrumX server know that you support the "1.1" protocol. Read the [docs](https://github.com/kyuupichan/electrumx/blob/master/docs/PROTOCOL.rst#script-hashes) for more info.

**Comment by goodProjects** [comment]
Thanks a bunch!

**Comment by goodProjects** [comment]
is it the same steps for non-segwit addresses?

**Comment by kyuupichan** [comment]
You should think of addresses as a GUI only use facing thing, witness the 3 address formats of Bitcoin Cash. They are not a property of the protocol so really should not be a property of indexers either. The script is a more natural way of describing what you want.

**Comment by goodProjects** [comment]
@kyuupichan its really a good move, Dealing with scripts seems to be much more effective.

**Comment by m-schmoock** [comment]
**Note:** As already noted, the 'scripthash' in the API refers to the hex representation of the bytereverse order sha256hash of the complete scriptPubKey (locking script).

It took me some time to construct a working Bech32 SegWit example:

- TX: `87a01561b278a62b9f1d71e18b3fe7b78b9ccb4664f03e8692667a5f823e6e7e`
- Second Output is a SegWit Locking script to the Bech32 address: `bc1qz57h534r7q9thrnp3zar4r682hvye2gjhssjh2`
- The Hex representation of the complete locking script (including pushdata OPs and Length) is: 0014153d7a46a3f00abb8e6188ba3a8f4755d84ca912
- To get the sha256sum of this hex string you can do: `echo -n -e "\x00\x14\x15\x3d\x7a\x46\xa3\xf0\x0a\xbb\x8e\x61\x88\xba\x3a\x8f\x47\x55\xd8\x4c\xa9\x12" | sha256sum`
- This gives you the hex representation of the hash: `fb78a728e14c17ed56cb978443c56648578f89d92b062c6e2bbaf303b5a1bb7c`
- The reverse byte order of this is: `7cbba1b503f3ba2b6e2c062b9d898f574866c5438497cb56ed174ce128a778fb`
- You can use this as scripthash in your API request as follows:

```
echo '[{"jsonrpc":"2.0", "id":1337, "method" : "server.version", "params" : { "client_name" : "foo 1.4", "protocol_version" : "1.4" } }, {"jsonrpc":"2.0", "id":1337, "method" : "blockchain.scripthash.get_history", "params" : { "scripthash" : "7cbba1b503f3ba2b6e2c062b9d898f574866c5438497cb56ed174ce128a778fb" } }]' | nc electrumx.schmoock.net 50001
```

Response:
```
[
  {
    "jsonrpc": "2.0",
    "result": [
      "ElectrumX 1.8.12",
      "1.4"
    ],
    "id": 1337
  },
  {
    "jsonrpc": "2.0",
    "result": [
      {
        "tx_hash": "87a01561b278a62b9f1d71e18b3fe7b78b9ccb4664f03e8692667a5f823e6e7e",
        "height": 554474
      },
      {
        "tx_hash": "5d9d583813fba5a59442232048564262414c8d04f2a7896843886ec57519dd22",
        "height": 554481
      }
    ],
    "id": 1337
  }
]
```

And yes, it actually makes sense to use the scripthashes, as it does not include address formats and different networks. Why the byteorder has to be reversed is another topic, but that is not a hard thing to do :>

cheers

**Comment by EugZol** [comment]
Can you point me to the instruction on how to convert various bitcoin address types to script hashes?

**Comment by SomberNight** [comment]
@EugZol https://github.com/spesmilo/electrum/blob/fc97181aa554a3f7bc0a50068f68a830286f8796/electrum/bitcoin.py#L503-L509

**Comment by EugZol** [comment]
@SomberNight thank you!
