### ISSUE TITLE
 invalid parameter names: <verbose> 

### ISSUE THREAD

**Issue by askz** [kyuupichan/electrumx#406]
when I do blockchain.transaction.get, I get : 
` invalid parameter names: <verbose> ` error in client and server.
My server has been updated: 
`2018-03-08 17:40:39,093 INFO    software version: ElectrumX 1.3                                                                      [db.py:133]`

any ideas?

Also when I negotiate version : 
```
2018-03-08 18:01:27,173 INFO    [90] unsupported protocol version request 1.3                                                        [util.py:57]
2018-03-08 18:01:27,174 INFO    [90] unsupported protocol version: 1.3                                                               [util.py:57]
```

EDIT: 
When I negotiate version 1.2 it works....

**Comment by kyuupichan** [comment]
Why are you "negotiating" 1.3?  1.2 is the highest protocol version:  http://electrumx.readthedocs.io/en/latest/protocol-changes.html

1.3 is the server version and is independent of the protocol version; it's just a coincidence they are close.

**Comment by kyuupichan** [comment]
I assume the client is proprietary?

**Comment by askz** [comment]
Oh! I'm sorry, indeed I misunderstood that.

The client is under heavy development and will be open-sourced very soon! Why?

**Comment by kyuupichan** [comment]
I've not seen a client that requests by name, which is the only way to get the error you did.

**Comment by askz** [comment]
That requests what by name ?

**Comment by askz** [comment]
Oh, it was a test. Even with array it was failing...
