### ISSUE TITLE
Add spent transaction ID to blockchain.transaction.get

### ISSUE THREAD

**Issue by junderw** [kyuupichan/electrumx#411]
The new verbose mode is amazing!

It would be even better if the vouts contained a spent_tx attribute with None if unspent and txid string of the spending transaction if spent.

**Comment by junderw** [comment]
hehe, a guy can dream... lol

ElectrumXplorer!!!! (TM)

**Comment by kyuupichan** [comment]
So a realistic plan would be nice, otherwise I don't see much value here.

**Comment by junderw** [comment]
I understand it would add an extra index, so it could be disabled by default, but while parsing transaction inputs, create a mapping of the spent utxo (`txid:vout`) to the current txid spending it...

Then in the `blockchain.transaction.get` verbose call look up each output in the index to find the txid of the spending tx.

Though I guess this is more of a question of: "Is ElectrumX only intended (and will only ever be intended) for use with Electrum Clients?" If the answer is yes, I think this issue can be closed.

If no, I think this could open up the possibility of ElectrumX backed block explorers that can also be connected using Electrum Client. (which could have privacy benefits if Electrum client calls and blockexplorer perusers)

I know a few people who could work on a front end and REST interface, and Bitbank could host it for BTC, BCH, MONA, and LTC. (We already host one of the main servers for electrum-mona using ElectrumX.)

**Comment by gdassori** [comment]
Unfortunatly bitcoind doesn't give informations about the spending transaction, so adding the feature I guess would be hard, because it implies to track spendings on the python side.

If @kyuupichan agrees, I would write an endpoint for electrumx to query the gettxout API, instead, I already planned to open a PR for that.

**Comment by kyuupichan** [comment]
I'm considering making changes to the block processor that would enable this, but it's far from certain I will do it.  I think it would add about 15-20% to the DB size, but that's just a guess.

**Comment by SomberNight** [comment]
Being able to query what transaction spent a txo or if it's still unspent would be useful for lightning too. Currently the client does quite a dance to figure this out.

**Comment by kyuupichan** [comment]
No chance of working with this now
