### ISSUE TITLE
querying database seems to be very slow 

### ISSUE THREAD

**Issue by GiorgosK** [kyuupichan/electrumx#415]
From a python script we query `method=blockchain.address.get_balance` on a synched electrumx leveldb database and after some stress tests the best throughput we can achieve is about 30 requests / minute

The script is not a fault as if we just make it echo back a simple message without querying the database we can achieve a throughput of about 2500 requests / minute 

I understand from the docs that electrumx is single threaded so I guess this is the bottleneck 

Is there any way to have a better performance or do you think we can query the levedb directly asynchronously at least for balances

any pointers ?

NOTE: we have done tests with servers of different sizes and the results are actually the same even for the upgraded servers.

**Comment by kyuupichan** [comment]
Do the addresses have long histories? Balances are calculated from history not stored so if your history is long it will be slow

**Comment by kyuupichan** [comment]
Rather from the UTXO set and mempool.  If the utxo set is large is will be slow. But I believe many requests per second is normal and 1 every 2 seconds means your address is special or something is wrong

**Comment by GiorgosK** [comment]
@kyuupichan thanks for looking into this 
I don't think the addresses are special and nor do they have long transaction history 

I had the feeling that balances/address are indexed and the balance was a fast request

what does constitute a special addres ? 
or what part do you think is wrong ?  where should I be looking ?

**Comment by erasmospunk** [comment]
@GiorgosK can you post your script to test it?

**Comment by GiorgosK** [comment]
Yes sure https://gist.github.com/GiorgosK/9e295dc504d0c942a4f7b5e92a4e7c29
hopefully the format is not changed by github gist

**Comment by kyuupichan** [comment]
Hmm, I was hoping for a script I could run against my own server.  What has HTTP got to do with anything ElectrumX?  It doesn't use HTTP.

**Comment by GiorgosK** [comment]
we are using this script to accept http connections and query electrumx and send back the result to the requester in json format.  This is the script that I referred to on the first post.  What script did you want ?

**Comment by kyuupichan** [comment]
Well, it's more levels of indirection.  I don't want to be debugging your HTTP server...

**Comment by kyuupichan** [comment]
I've just synced a large wallet from a client in HKG to a server in Tokyo that runs on an HDD, so no reason to expect it to be fast.  ElectrumX is serving over 1,500 requests a minute.

I'm not sure what is different about your setup but as you're using HTTP I can't help but think that is part of the problem.  So I'm closing this.
