### ISSUE TITLE
`electrumx_rpc.py` does not implement ` server.features`?

### ISSUE THREAD

**Issue by JamesCropcho** [kyuupichan/electrumx#417]
Hello,

I am trying to use the `server.features` method (https://github.com/kyuupichan/electrumx/blob/master/docs/PEER_DISCOVERY.rst#serverfeatures). AFAIK, the best way _would_  be to use `electrumx_rpc.py`. However:

```
electrumx_rpc.py  server.features
error: unknown method: 'server.features' (code -32601)
```

(`electrumx electrumx_rpc.py getinfo` works fine, just as expected.)

I'm on Electrum v1.3.

I've been banding my head against the proverbial wall here. I assume I'm making some silly mistake, but what is it?

Thanks,
James

**Comment by kyuupichan** [comment]
No, it connects to the RPC server for admin tasks.  See http://electrumx.readthedocs.io/en/latest/rpc-interface.html

Essentially there are 2 protocols - a public one and an admin one. You see the error because that message is for querying the Electrum server not the admin server. They run on different ports

**Comment by kyuupichan** [comment]
There is no simple interface other than telnet for querying the Electrum servers. When I complete http://aiorpcx.readthedocs.io/en/latest/ it will be easy to write a short python program to do it.

**Comment by JamesCropcho** [comment]
Although aiorpcX will quite likely be a superior route, in the meantime, here for all future seekers is a complete working command, albeit using `netcat` over `telnet`:

```
$ echo '{"id": null, "method": "server.features"}' | nc localhost 50001 -i 1
{"jsonrpc": "2.0", "id": null, "result": {/* assorted server features */}}
```
