### ISSUE TITLE
what the purpose of sending scripthash instead of address if every address has different script hash?

### ISSUE THREAD

**Issue by goodProjects** [kyuupichan/electrumx#418]
```
Array
(
    [0] => Array
        (
            [address] => mjLQ4dr3P44KJC9uYTrX6zq7Vkn6zxKihq
            [script] => f150e615b282836aee6a7cf5480e79c2d911b5771900162f9d1446488f19838e
            [type] => P2PKH
        )

    [1] => Array
        (
            [address] => 2N82AmCatmDJJLjiWSrQy8QZUc832CZPb9t
            [script] => accfdd0a4fbd8cb4e4b01a71cbf190ccc71b9edfe516a629248fbb84b3775550
            [type] => P2SH
        )

    [2] => Array
        (
            [address] => tltc1q98shq2japphaqu0qfp4kh374f7xwynuwpazspr
            [script] => 55ba1110d7ed4443406654bff3570faea3ad3534d9105bc41e445b955ca5068c
            [type] => P2WSH
        )

    [3] => Array
        (
            [address] => tltc1q36p3nr6ggc2f6tckqqvh0dg3m8p8jrjg747x4mn2swpty90x2rcsw73vhv
            [script] => a98430e66ad76add999866ec7088cb6f6f424b977b83f43103e3d3f30b07e28d
            [type] => P2SH|P2WSH
        )

)
```
I have created those addresses with each address script.

Now if I send some `litecoin` to `mjLQ4dr3P44KJC9uYTrX6zq7Vkn6zxKihq` other scripts will never know about that transaction except `f150e615b282836aee6a7cf5480e79c2d911b5771900162f9d1446488f19838e`
even though all created using the same address.

scripts above are the output scripts of the address -> SHA256 -> flipped.

Main PublicKey output script (SHA256->flipped): `5a225f4f92cb63cbc93797645ed9ebe8e50d5951d47dd4edbb8680bd11c4795f`

I should be able to fetch transactions were made to the main script since all addresses were created using that, but it didn't work. I would appreciate any help.

**Comment by SomberNight** [comment]
The purpose of using scripthashes is that
- the server does not need to know about the different address formats
- output scripts (scriptPubKeys) without corresponding addresses can also be monitored (e.g. pay-to-pubkey, but also any arbitrary script)
- as a bonus, it makes it a bit harder for server operators to spy on users

**Comment by SomberNight** [comment]
btw this address you mention `tltc1q98shq2japphaqu0qfp4kh374f7xwynuwpazspr` is p2wpkh, not p2wsh, based on length
