### ISSUE TITLE
Example telnet command for querying an Electrum server?

### ISSUE THREAD

**Issue by JamesCropcho** [kyuupichan/electrumx#419]
Hello,

Regarding `electrumx_rpc.py`, @kyuupichan commented (https://github.com/kyuupichan/electrumx/issues/417#issuecomment-373964141):

> No, it connects to the RPC server for admin tasks. See http://electrumx.readthedocs.io/en/latest/rpc-interface.html
> 
> Essentially there are 2 protocols - a public one and an admin one. You see the error because that message is for querying the Electrum server not the admin server. They run on different ports

Could someone kindly give me an example of a query to the ElectrumX server, via telnet?

Here is what I have tried:

```
[uuu@ssssss ~]$ telnet localhost 50001
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
{"jsonrpc": "2.0", "method": "getinfo"}^C
Connection closed by foreign host.
[uuu@ssssss ~]$
```

I'm probably (once again) making a silly mistake, but what is it?

Thank You,
James

**Comment by goodProjects** [comment]
They're dealing with JSON-RPC v2, your request should looks like:
`{"id": 1, "method": "blockchain.address.get_balance", "params": ["1BWwXJH3q6PRsizBkSGm2Uw4Sz1urZ5sCj"]}`

**Comment by JamesCropcho** [comment]
That absolutely works, @goodProjects. Thank you.

**Comment by JamesCropcho** [comment]
This is an example of a complete command that actually worked for me, albeit using `netcat` over `telnet`:

```
$ echo '{"id": 1, "method": "blockchain.address.get_balance", "params": ["1BWwXJH3q6PRsizBkSGm2Uw4Sz1urZ5sCj"]}' | nc localhost 50001 -i 1
{"jsonrpc": "2.0", "id": 1, "result": {"confirmed": 20000000, "unconfirmed": 0}}
```

`netcat` command-line parameters seem to vary across distributions, e.g. my distribution did not permit the `-q` parameter which seems quite common.

**Comment by kyuupichan** [comment]
Anyone fancy doing a PR to update the docs, if this is a common issue?
