### ISSUE TITLE
Server Died

### ISSUE THREAD

**Issue by SuBPaR42** [kyuupichan/electrumx#42]
Nov 23 15:08:51 ElectrumX systemd[1]: electrumx.service: Main process exited, code=killed, status=9/KILL
Nov 23 15:08:51 ElectrumX systemd[1]: electrumx.service: Unit entered failed state.
Nov 23 15:08:51 ElectrumX systemd[1]: electrumx.service: Failed with result 'signal'.

**Comment by kyuupichan** [comment]
So it got a kill 9 signal - from you?  That's not something the process can control or handle.  What did you expect to see?

**Comment by kyuupichan** [comment]
Closing.  We've discovered this is deliberate abuse and are attempting to mitigate in 0-7.7 with MAX_HIST.

But Python isn't itself the direct cause of KILL-9s and cannot do anything to prevent them.
