### ISSUE TITLE
Verbose mode doesn't work on btc testnet

### ISSUE THREAD

**Issue by askz** [kyuupichan/electrumx#420]
```
   blockchain.transaction.get 
[ '39a42f6c0aa64cbd07fd052f82be7d9342a4dcc3579052d99ad5e8951b3c18ef', 1 ]
```
(with true or 1 the same result is happening, I only get raw hex)

**Comment by gdassori** [comment]
Is the electrumx server your ? I mean, it looks like you're connected to a non-updated electrumx version which doesn't wrap the gettransaction verbose mode, which is pretty new.

**Comment by askz** [comment]
Yes it is ! Running ElectrumX 1.3 on docker !

**Comment by gdassori** [comment]
I wrote the patch and @kyuupichan merged it on protocol version 1.2, which is, AFAIK, the latest supported by this repo.

so 1.3 must come from another source, and they should merge the latest changes from here to enable the verbose mode.

**Comment by askz** [comment]
The fact is, with the same docker image, it runs smoothly with other currencies.

**Comment by gdassori** [comment]
Is the docker repo public ? I may try to reproduce

**Comment by kyuupichan** [comment]
You are calling server.version and asking for protocol 1.2 right?

**Comment by askz** [comment]
Yup. It works for all the others except this one (BitcoinSegwit testnet)

**Comment by kyuupichan** [comment]
@askz @Kiruel and why do you think this is an ElectrumX problem?

**Comment by askz** [comment]
After many debug time, its clear that it isn't ElectrumX problem.

Sorry for the noise! And thanks for your time !
