### ISSUE TITLE
infinity loop resetting the prefetcher

### ISSUE THREAD

**Issue by xziy** [kyuupichan/electrumx#423]
This not bug, just i dont know where asks?? I make electrum server for https://github.com/RoverCoin/Rovercoin and i have infinity loop 

`WARNING:BlockProcessor:daemon blocks do not form a chain; resetting the prefetcher`
 i use DESERIALIZER = lib_tx.DeserializerTxTime 

And i dont know why this line not true.  

`block_processor line 249: if hprevs == chain:`

I think problem in deserialization. any ideas?

class Rover(Coin):
    NAME = "Rover"
    SHORTNAME = "ERC"
    NET = "mainnet"
    XPUB_VERBYTES = bytes.fromhex("0488b21e")
    XPRV_VERBYTES = bytes.fromhex("0488ade4")
    GENESIS_HASH = ('000032661a7011e49ee28d45efce8208a9820a96ba9daf74d9a36451a740043d')
    P2PKH_VERBYTE = bytes.fromhex("3c")
    P2SH_VERBYTES = bytes.fromhex("55")
    WIF_BYTE = bytes.fromhex("99")
    DAEMON = daemon.LegacyRPCDaemon
    DESERIALIZER = lib_tx.DeserializerTxTime
    PEER_DEFAULT_PORTS = {'t': '28218', 's': '28217'}
    PEERS = [
        '159.65.245.18 s t',
        '159.203.43.8 s t',
        '138.68.180.33 s t',
        '188.166.226.48 s t',
        '174.138.6.72 s t',
        '138.68.49.146 s t',
    ]
    TX_COUNT_HEIGHT = 10000
    TX_COUNT = 10000
    TX_PER_BLOCK = 4
    REORG_LIMIT = 1000
    RPC_PORT = 28217

    @classmethod
    def header_hash(cls, header):
        '''Given a header return the hash.'''
        import x11_hash
        return x11_hash.getPoWHash(header)

**Comment by kyuupichan** [comment]
I don't know why either; you are clearly not calculating block hashes correctly, or something similar.  It has nothing to do with transaction hashes.

**Comment by josephnicholas** [comment]
@kyuupichan I just got the same error on this, but we have made changes on adding an additional field in block header, might as well getting the hashes as raw?

**Comment by kyuupichan** [comment]
It just means you are not calculating block hashes correctly in ElectrumX because they do not form a chain with those stored in the block headers themselves, i.e. the prevhash field does not match what is calculated by your code.  Only you can figure out why.

**Comment by turcol** [comment]
I do have the same message: 
```WARNING:BlockProcessor:daemon blocks do not form a chain; resetting the prefetcher) ```

Only the header hashes for the the first 2 blocks are the same. After that, the header hash for the chain is the correct, however the hprevs value is different and their values are the double_sha256(header) and not the X13 hash

I already added the x13_hash in the Coin description.

I am not sure what I am missing 
```    class CivX(Coin): 
    NAME = "CivX"
    SHORTNAME = "CIVX"
    NET = "mainnet"
    XPUB_VERBYTES = bytes.fromhex("0488b21e")
    XPRV_VERBYTES = bytes.fromhex("0488ade4")
    GENESIS_HASH = ('00000036090a68c523471da7a4f0f958'
                    'c1b4403fef74a003be7f71877699cab7')
    P2PKH_VERBYTE = bytes.fromhex("1C")
    P2SH_VERBYTE = [bytes.fromhex("57")]
    WIF_BYTE = bytes.fromhex("9C")
    RPC_PORT = 4561
    TX_COUNT = 1000
    TX_COUNT_HEIGHT = 10000
    TX_PER_BLOCK = 4
    DAEMON = daemon.LegacyRPCDaemon
    DESERIALIZER = lib_tx.DeserializerTxTime

    @classmethod
    def header_hash(cls, header):
        import x13_hash
        print ('------------------------------------------------------------------')
        print ('    Header:', bytes(header).hex())
        print (' DHash 256:', bytes(reversed(double_sha256(header))).hex())
        print ('  Hash X13:', bytes(reversed(x13_hash.getPoWHash(header))).hex())
        return x13_hash.getPoWHash(header)
```

The values for hprevs and chain before the line that compare them are: (`if hprevs == chain:`)
https://github.com/kyuupichan/electrumx/blob/master/electrumx/server/block_processor.py#L206
```print ('{} -- hprevs[]: {} \n  --  chain[]: {}'.format(cnt, bytes(reversed(hprevs[cnt])).hex(), bytes(reversed(chain[cnt])).hex()))```

```
0 -- hprevs[]: 0000000000000000000000000000000000000000000000000000000000000000
  --  chain[]: 0000000000000000000000000000000000000000000000000000000000000000
1 -- hprevs[]: 00000036090a68c523471da7a4f0f958c1b4403fef74a003be7f71877699cab7
  --  chain[]: 00000036090a68c523471da7a4f0f958c1b4403fef74a003be7f71877699cab7
2 -- hprevs[]: 9ab22ac61699a211fbfadf1871889d47e744f3bf886b2f912a4ebb87a8babd6d
  --  chain[]: 00000a80105acaed2f69ec12dd3a229089918741032c5f8ad2139364491bb786
3 -- hprevs[]: 892f74fe6b462ec612dc745f19b7f299ffb94aabb17a0826a03092c0eb6f83ec
  --  chain[]: 00000314027973426018b290004e151fea0612e0fbc754126b7b28bf2233ca11
4 -- hprevs[]: 69771a27610ee399654dc83864c542be0c566c72246506be638a3b12a5a95ed1
  --  chain[]: 00000e27943efe55c34ce0500f8d92ada0d48b27e016522154638cae954318dd
5 -- hprevs[]: b1506e84870794f3be1132347f73cc3a66b94fd2b830ed06c59d3dbd6b1f4147
  --  chain[]: 000003d6afe19759c0a69a18ecf9ce3df43499a2ec65914bf7e1d0a35dc1033f
```

**Comment by kyuupichan** [comment]
hprevs is being extracted from the block headers themselves (there should be a 32-byte field holding it).
For example, your header # 1: `b7ca997687717fbe03a074ef3f40b4c158f9f0a4a71d4723c5680a0936000000` is the hex after 4 bytes.  If you reverse that you get he hprev being reported.
The next header `6dbdbaa887bb4e2a912f6b88bff344e7479d887118dffafb11a29916c62ab29a` is likewise.

So the first thing to understand is why are you block headers chaining using double_sha256 but calculating their hashes using X13 for PoW?  Is my statement correct?

**Comment by kyuupichan** [comment]
And if this is indeed how your coin works, then the hash you should be using is double_sha256 not X13.  ElectrumX doesn't care about the PoW hash.

**Comment by turcol** [comment]
The CivX Coin is PoW+PoS ... it is a clone from Stratis Project
```https://github.com/exofoundation/CivX-Qt```

Correct about your statement. Shouldn't be working with X13?

**Comment by turcol** [comment]
Using the double_sha256 may work, except for the second block, as the genesis is calculated based on X13

**Comment by kyuupichan** [comment]
Ok so you need your header hash function to handle the one exception

**Comment by turcol** [comment]
Thanks... With the following header hash function it was able to process all blocks:
```
    @classmethod
    def header_hash(cls, header):
        '''
        Given a header return the hash for CivX.
        Need to download `x13_hash` module
        Source code: https://github.com/MaruCoinOfficial/x13-hash"
        '''
        import x13_hash
        version, = util.unpack_le_uint32_from(header)

        if version > 2:
            return double_sha256(header)
        else:
            return x13_hash.getPoWHash(header)
```
I would have liked to use the block height to handle the exception, however the header do not have the height value

**Comment by kyuupichan** [comment]
You could just hardcode the hash

**Comment by 2infinity-gh** [comment]
Hi,
I've simular issues and would like to see the detailed log like 
`0 -- hprevs[]: 0000000000000000000000000000000000000000000000000000000000000000
  --  chain[]: 0000000000000000000000000000000000000000000000000000000000000000`

adding `print ('{} -- hprevs[]: {} \n -- chain[]: {}'.format(cnt, bytes(reversed(hprevs[cnt])).hex(), bytes(reversed(chain[cnt])).hex()))` to block_processor.py gives an namerror for cnt.
 
We've successfully merged 2 coins before but unfortunately our third project isn't going as smooth as we were hoping.

**Comment by turcol** [comment]
@2infinity-gh define (and increase) the var cnt
