### ISSUE TITLE
[SOLVED]: ERROR:Controller:SSL server failed to listen on xxx.xxx.xxx.xxx:995 :[Errno 13] error while attempting to bind on address ('xxx.xxx.xxx.xxx', 995): permission denied

### ISSUE THREAD

**Issue by gabridome** [kyuupichan/electrumx#430]
I couldn't connect to my electrumx, so, looking at the log I found the error in the title.

I tried the remedy I found:

`````
sudo setcap 'cap_net_bind_service=+ep' /usr/bin/python3.6
`````
I restarted the server and it worked. I hope this to be useful to other.

To be more detailed I had to set the env:
COIN  DAEMON_URL  DB_DIRECTORY  ELECTRUMX  HOST  NET  SSL_CERTFILE  SSL_KEYFILE  SSL_PORT  TCP_PORT  USERNAME

I followed howto.rst document but I had to set up in particular the HOST env and TCP_PORT.

**Comment by kyuupichan** [comment]
Thanks.  This an OS/distro-specific permission issue and not an electrumX issue.

**Comment by gabridome** [comment]
I see. I'm using Contabo VPS platform, in case someone incurs in the same issue.
