### ISSUE TITLE
missing notification due to MissingUTXOError

### ISSUE THREAD

**Issue by benma** [kyuupichan/electrumx#433]
I ran into this bug, which you already helpfully documented in the code:

```
                    # DBError can happen when flushing a newly processed
                    # block.  MissingUTXOError typically happens just
                    # after the daemon has accepted a new block and the
                    # new mempool has deps on new txs in that block.
```

https://github.com/kyuupichan/electrumx/blob/02ab8e5742688196d966c1e554e2ea98fca8e824/server/mempool.py#L266-L269

This makes me miss a notification to a subscribed scripthash.

Also, the log says that the blocks are processed and flushed before I run into this issue, which is surprising,

I have a few questions about this edge case. I hope you can help.

1. What is the reason that you don't wait for the flushing to be finished and retry, or requeue the item to be tried again?
2. What is the suggested workaround to not miss it? Periodically call the scripthash.subscribe method for all my scripthashes?

Thanks.

**Comment by kyuupichan** [comment]
Which one happened?  Why does it make you miss a notification?  I need more information.

**Comment by benma** [comment]
So here is the workflow that produces my issue:

In bitcoin regtest:

1. scripthash.subscribe to a scripthash of address X
2. `bitcoin-cli generate 101` to generate some blocks
3. immediately after, `bitcoin-cli sendtoaddress X 1` to send a coin to the address.

ElectrumX fails to send a notification of the status change of the script hash. I pinpointed that it runs into the exception I linked above (`except (self.db.MissingUTXOError, self.db.DBError):`), in which case the notification is skipped.

If I wait a few seconds between step 2 and 3 above, the error does not happen and the notification is sent.

The comment you wrote in the exception also fits: the mempool tx depends on a block that was just created (a coinbase coin is spent in step 3).

**Comment by benma** [comment]
Thanks.

> Can you test if changing "continue" to "mempool_missing = True" fixes it for you locally?

Unfortunately not. Putting a loop around the try/catch block and retrying does fix it, but I imagine this is not the right fix and could have other bad effects.

**Comment by kyuupichan** [comment]
Shame.  I will fix this properly but it will come out the wash of later changes; I'll leave this open in the meantime.  When I think it's fixed I'll ping you; I'd appreciate your re-testing then.

**Comment by benma** [comment]
Thx! Appreciate it.

It is an edge case that is very unlikely to hit in mainnet, and if it does, I think the client would just miss out on an unconfirmed balance change, which fixes itself after confirmation or restart, so in that sense, this one is not a big deal.

**Comment by kyuupichan** [comment]
Hey - can you test git HEAD?  I'm almost certain this is fixed
