### ISSUE TITLE
"Unspoorted protocol version" - Electrum Protocol v1.2

### ISSUE THREAD

**Issue by 4oo4** [kyuupichan/electrumx#436]
Just tried upgrading my Electrum client to the latest 3.1.2, but got this error with docker logs about not having the right Electrum protocol version (also happened with 3.1.0 and 3.1.1):
```
INFO:Controller:SSL server listening on :50002
INFO:ElectrumX:[0] SSL 10.10.99.105:50312, 1 total
INFO:ElectrumX:[0] unsupported protocol version request 1.2
INFO:ElectrumX:[0] unsupported protocol version: 1.2
```
Running ElectrumX 1.3 from the docker image. Is there a timeframe when 1.2 will be supported?

**Comment by kyuupichan** [comment]
You've missed the line from the logs showing the server version. Of course it already supports it.

**Comment by 4oo4** [comment]
@kyuupichan That makes sense, I was thinking I was doing something wrong. Just upgraded to version 1.4 of the docker image and that fixed it.
