### ISSUE TITLE
P2PKH and P2SH altcoin add

### ISSUE THREAD

**Issue by Alaxel12** [kyuupichan/electrumx#438]
P2PKH_VERBYTE = bytes.fromhex("30")
P2SH_VERBYTES = [bytes.fromhex("32"), bytes.fromhex("05")]
My altcoin have two letters of address, how i can add it?

**Comment by AgenorZ** [comment]
Same question

**Comment by kyuupichan** [comment]
I don't understand your question

**Comment by Alaxel12** [comment]
On coins.py need that information:
P2PKH_VERBYTE = bytes.fromhex("30")
P2SH_VERBYTES = [bytes.fromhex("32"), bytes.fromhex("05")]
Where i can get that information for add my altcoin?

**Comment by Alaxel12** [comment]
My Altcoin have two letters of addresses L or M
