### ISSUE TITLE
Crash while idle (no clients)

### ISSUE THREAD

**Issue by zaventh** [kyuupichan/electrumx#44]
Running 0.7.6

> Nov 24 06:31:57 electrum electrumx_server.py[8385]: INFO:BlockProcessor:chain reorg detected
Nov 24 06:31:57 electrum electrumx_server.py[8385]: INFO:BlockProcessor:finding common height...
Nov 24 06:31:57 electrum electrumx_server.py[8385]: INFO:BlockProcessor:chain was reorganised for 1 blocks over heights 440,364-440,364 inclusive
Nov 24 06:31:57 electrum electrumx_server.py[8385]: INFO:MemPool:50,168 txs touching 194,297 addresses
Nov 24 06:31:57 electrum electrumx_server.py[8385]: INFO:BlockProcessor:backing up 1 blocks
Nov 24 06:31:59 electrum electrumx_server.py[8385]: INFO:BlockProcessor:backed up to height 440,363
Nov 24 06:31:59 electrum electrumx_server.py[8385]: INFO:BlockProcessor:backing up history to height 440,363  tx_count 173,355,460
Nov 24 06:33:04 electrum electrumx_server.py[8385]: INFO:BlockProcessor:removed 5,131 history entries from 4,626 addresses
Nov 24 06:33:05 electrum electrumx_server.py[8385]: INFO:BlockProcessor:flush #568 took 65.5s.  Height 440,363 txs: 173,355,460
Nov 24 06:33:05 electrum electrumx_server.py[8385]: INFO:BlockProcessor:prefetcher reset
Nov 24 06:33:05 electrum electrumx_server.py[8385]: Traceback (most recent call last):
Nov 24 06:33:05 electrum electrumx_server.py[8385]:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.7.6-py3.5.egg/EGG-INFO/scripts/electrumx_server.py", line 67, in main
Nov 24 06:33:05 electrum electrumx_server.py[8385]:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.7.6-py3.5.egg/EGG-INFO/scripts/electrumx_server.py", line 58, in main_loop
Nov 24 06:33:05 electrum electrumx_server.py[8385]:   File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
Nov 24 06:33:05 electrum electrumx_server.py[8385]:     return future.result()
Nov 24 06:33:05 electrum electrumx_server.py[8385]:   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
Nov 24 06:33:05 electrum electrumx_server.py[8385]:     raise self._exception
Nov 24 06:33:05 electrum electrumx_server.py[8385]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
Nov 24 06:33:05 electrum electrumx_server.py[8385]:     result = coro.send(None)
Nov 24 06:33:05 electrum electrumx_server.py[8385]:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.7.6-py3.5.egg/server/protocol.py", line 263, in main_loop
Nov 24 06:33:05 electrum electrumx_server.py[8385]:     await future  # Note: future is not one of self.futures
Nov 24 06:33:05 electrum electrumx_server.py[8385]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 492, in _wait_for_one
Nov 24 06:33:05 electrum electrumx_server.py[8385]:     return f.result()  # May raise f.exception().
Nov 24 06:33:05 electrum electrumx_server.py[8385]:   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
Nov 24 06:33:05 electrum electrumx_server.py[8385]:     raise self._exception
Nov 24 06:33:05 electrum electrumx_server.py[8385]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
Nov 24 06:33:05 electrum electrumx_server.py[8385]:     result = coro.send(None)
Nov 24 06:33:05 electrum electrumx_server.py[8385]:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.7.6-py3.5.egg/server/block_processor.py", line 195, in main_loop
Nov 24 06:33:05 electrum electrumx_server.py[8385]:     await self._wait_for_update()
Nov 24 06:33:05 electrum electrumx_server.py[8385]:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.7.6-py3.5.egg/server/block_processor.py", line 228, in _wait_for_update
Nov 24 06:33:05 electrum electrumx_server.py[8385]:     self.flush(True)
Nov 24 06:33:05 electrum electrumx_server.py[8385]:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.7.6-py3.5.egg/server/block_processor.py", line 368, in flush
Nov 24 06:33:05 electrum electrumx_server.py[8385]:     self.assert_flushed()
Nov 24 06:33:05 electrum electrumx_server.py[8385]:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.7.6-py3.5.egg/server/block_processor.py", line 356, in assert_flushed
Nov 24 06:33:05 electrum electrumx_server.py[8385]:     assert self.tx_count == self.fs_tx_count == self.db_tx_count
Nov 24 06:33:05 electrum electrumx_server.py[8385]: AssertionError
Nov 24 06:33:05 electrum electrumx_server.py[8385]: CRITICAL:root:ElectrumX server terminated abnormally
Nov 24 06:33:05 electrum electrumx_server.py[8385]: Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Nov 24 06:33:05 electrum electrumx_server.py[8385]: Traceback (most recent call last):
Nov 24 06:33:05 electrum electrumx_server.py[8385]:   File "/usr/lib/python3.5/asyncio/base_events.py", line 431, in __del__
Nov 24 06:33:05 electrum electrumx_server.py[8385]:   File "/usr/lib/python3.5/asyncio/unix_events.py", line 58, in close
Nov 24 06:33:05 electrum electrumx_server.py[8385]:   File "/usr/lib/python3.5/asyncio/unix_events.py", line 139, in remove_signal_handler
Nov 24 06:33:05 electrum electrumx_server.py[8385]:   File "/usr/lib/python3.5/signal.py", line 47, in signal
Nov 24 06:33:05 electrum electrumx_server.py[8385]: TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
Nov 24 06:33:05 electrum electrumx_server.py[8385]: ERROR:asyncio:Task was destroyed but it is pending!
Nov 24 06:33:05 electrum electrumx_server.py[8385]: task: <Task pending coro=<MemPool.main_loop() running at /usr/local/lib/python3.5/dist-packages/electrumx-0.7.6-py3.5.egg/server/protocol.py:63> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:431, Task._wakeup()]> cb=[as_completed.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:478]>
Nov 24 06:33:05 electrum electrumx_server.py[8385]: ERROR:asyncio:Task was destroyed but it is pending!
Nov 24 06:33:05 electrum electrumx_server.py[8385]: task: <Task pending coro=<Prefetcher.main_loop() running at /usr/local/lib/python3.5/dist-packages/electrumx-0.7.6-py3.5.egg/server/block_processor.py:80> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:431, Task._wakeup()]> cb=[as_completed.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:478]>

**Comment by SuBPaR42** [comment]
Looks like reorgs are still not 100% fixed.

**Comment by shsmith** [comment]
What version bitcoind are you using?
I did not get a reorg on block 440,364 using bitcoin core 13.1.0

> INFO:Prefetcher:new block height 440,364 hash 00000000000000000321aadc8a4bd853f45fa9449a32f373889a86f419de9ff7
INFO:BlockProcessor:flush #689 took 0.0s.  Height 440,364 txs: 173,356,705

**Comment by SuBPaR42** [comment]
Same here - no re-org with 0.13.1

> Nov 24 14:31:05 ElectrumX electrumx_server.py[13877]: INFO:Prefetcher:new block height 440,364 hash 00000000000000000321aadc8a4bd853f45fa9449a32f373889a86f419de9ff7
>Nov 24 14:31:05 ElectrumX electrumx_server.py[13877]: INFO:BlockProcessor:flush #942 took 0.1s.  Height 440,364 txs: 173,356,705

**Comment by kyuupichan** [comment]
https://blockchain.info/orphaned-blocks shows 2 happened in the last 12 hrs

Thanks for the report, taking a look.  

zaventh - can you confirm everything was fine restarting?  I don't think anything is corrupt, just yet another assertion error

**Comment by kyuupichan** [comment]
Fixed in 0.7.8

**Comment by zaventh** [comment]
Yes, restarting seemed to restore normal operation. For reference, this was running against a 0.12.1 node. Thanks.
