### ISSUE TITLE
setup.py shoud not import Controller first!

### ISSUE THREAD

**Issue by john-shine** [kyuupichan/electrumx#442]
In setup.py, server.controller require aiorpcx, pylru, aiohttp modules, but U import it first. So before it goes to setuptools.setup(), it will return error:
> ModuleNotFoundError: No module named 'aiorpcx'

Even there`s install_requires=[......], it never work as expect. So version info should read from file content or something else, not include like this.

**Comment by kyuupichan** [comment]
Lol, that's true
