### ISSUE TITLE
Tor only operations?

### ISSUE THREAD

**Issue by randomnonsense** [kyuupichan/electrumx#445]
Basically to mimic what Core does with onlynet=onion. There are plenty Tor servers out there, so this shouldn't be an actual practical problem. Also likely implementing this will be fairy easy.

In such mode Electrum**X** could only work with .onion resources, both clients and peers, and perhaps without SSL since Tor is already encrypted. This way a Tor-only server would provide clients with .onion only servers and announce itself and connect to only to other Tor-only servers. Exactly the same way Core does it.

I believe this could be a useful feature. Thanks for consideration.

**Comment by randomnonsense** [comment]
With FORCE_PROXY and clearnet ports completely disabled Electrum treats Tor as a standard socks5 proxy and connects to other peers (both .onion and clearnet) through it and since it does so, it also servers a list of peers obtained this way to clients. The idea with onlynet=onion is to keep all comms Tor-only.

My config (relevant variables)
PEER_ANNOUNCE on
PEER_DISCOVERY on
REPORT_HOST <unset>
REPORT_SSL_PORT 0
REPORT_TCP_PORT 0
REPORT_HOST_TOR <set to an onion address>
REPORT_SSL_PORT_TOR  50002
REPORT_TCP_PORT_TOR  50001
SSL_PORT 50002
TCP_PORT 50001
FORCE_PROXY on

The point is to allow only Tor comms, i.e. connecting and announcing only to other Tor-only servers and accepting Tor-only clients and serving them only other Tor-only peers.

**Comment by randomnonsense** [comment]
Please compare how Bitcoin Core does this. With SOCKS5 proxy set to Tor and onlynet=onion, it does exactly so. Only connects to other Tor-only servers, and only shares other .onion servers with connecting clients.

**Comment by randomnonsense** [comment]
I think it would be enough to add a new variable, e.g. TOR_ONLY, and if that is set e.g. to "on" (along with other relevant variables like FORCE_PROXY), Electrum could only attempt to talk to other .onion peers. That's up to you how this works.

**Comment by kyuupichan** [comment]
Sorry I can't really understand what you're saying is different.  Is it that ElectrumX (note the X; you kept referring to Electrum which makes it confusing and hard to know if you really mean it) also connects to clearnet peers via Tor, and you don't want that?

Why is that important and something to care about?

I'm not against changing something here but I don't want to make setup more confusing than it already is without a solid justification.

**Comment by randomnonsense** [comment]
By "Electrum" I meant "ElectrumX". Corrected and sorry for the confusion.

The main difference is that it is currently not possible to only use Tor servers if a user wants to connect to more than one. The only option to connect only to hidden services is forcing Electrum (client) to connect to a single server, as described here: http://docs.electrum.org/en/latest/tor.html. So either a user chooses 1 particular hidden service (which is impractical due to Tor instability/overload sometimes), or uses "mixed" mode, connecting to hidden services and normal servers. 

Firstly, this is inconvenient. A Tor user cannot currently simply roam between hidden services without connecting to clearnet servers at all. No hidden server is able to return a Tor-only peerlist and some clearnet servers are always included. A Tor user is much more likely to choose a well known Tor server to connect to (some are hardcoded in coins.py)... only to receive another 6-8 clearnet servers in the peerlist from it. What's the point of that? Why can't a hidden service serve only other hidden services in its peerlists? If a user wants Tor, why involve clearnet at all?

Secondly, there is a practical security impact to this: A user connecting through Tor who chooses the plaintext TCP port assuming (correctly) connection remains encrypted because of how Tor works, if they don't force Electrum (client) to connect only to a single server, their connections to any clearnet servers, after leaving a Tor-exit, will travel further on in plaintext. This may sound trivial, but for example if a Tor-exit is compromised, this becomes an actual problem: https://www.torproject.org/docs/faq.html.en#CanExitNodesEavesdrop

Thirdly, it's impossible to run a dedicated hidden service (strictly Tor-only, no clearnet) enjoying all the possibilities ElectrumX provides, i.e. a) finding other hidden services (without trying to reach any clearnet peer), b) announcing itself only to other hidden services (again, without trying to reach any clearnet peers), and finally, c) including only .onion addresses in peerlists sent to clients. Or put differently, it is now currently not possible to create a Tor-only network of ElectrumX servers.

For example, my server is now connected to 111 peers, including only 24 Tor hidden services. When I connect to it (over Tor), I rarely receive more than one another hidden services in the peerlist. I end up forcing Electrum (client) to connect to the single server only. And if my broadband reconnects, or Tor circuit collapses, I end up disconnected. I'd love to be able to automatically reconnect to another hidden service **without touching any clearnet server**.

In overall, I imagine this so: An ElectrumX server operates as a strict hidden service (e.g. if TOR_ONLY variable is set), and contacts only other .onion peers, looking them up and announcing itself to them. It also accepts Tor-only client connections and provides the clients with only .onion peerlist. A Tor user this way simply selects a known Tor-only server and communicates only with other .onion servers, roaming between them if necessary.

Also I don't think configuration will be much more difficult because of this. It would be enough to make it conditional (tor_only would work only if e.g. force_proxy is set and report_host is unset). Best would be probably to make a new chapter e.g. "Tor hidden services" in environment.rst and describe all of this more plainly. I would be happy to do this for you.

**Comment by randomnonsense** [comment]
If think if you would be kind enough to consider, it would make sense to request a similar Tor-only feature for Electrum (client). This way both the server would run on its own as a strict hidden servers, and clients independently could only chose to connect to .onion addresses. I will start a similar discussion at Electrum's end.

**Comment by kyuupichan** [comment]
For the reasons I mention above I don't see any value here, and so am closing this.
