### ISSUE TITLE
Version negotiation fails: unknown method \"server.version\"

### ISSUE THREAD

**Issue by atteeela** [kyuupichan/electrumx#458]
Hello,

I'm running latest electrumx server and have successfully sync'ed the blockchain. However when connecting to the RPC interface, I'm unable to complete version negotiation or send any commands.

`telnet localhost 8000`
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
`{"method" : "server.version", "params": ["nc","1.2"], "id": "msg_id"}`
`{"jsonrpc": "2.0", "error": {"code": -32601, "message": "unknown method \"server.version\""}, "id": "msg_id"}`

I've stumbled across this previous issue https://github.com/kyuupichan/electrumx/issues/439 which exhibits a similar problem, but it does not present a solution.

Trying to run additional commands, same thing:

`{"id": 1, "method": "blockchain.address.listunspent", "params": ["1BWwXJH3q6PRsizBkSGm2Uw4Sz1urZ5sCj"]}
{"jsonrpc": "2.0", "error": {"code": -32601, "message": "unknown method \"blockchain.address.listunspent\""}, "id": 1}`

My electrumx server is fully synced up with Bitcoind (Bitcoin ABC) latest version as of writing.

Thank you in advance!

**Comment by kyuupichan** [comment]
You have confused the TCP/SSL interface with the RPC interface.  Use electrumx_rpc.py to connect to  local RPC.  See the docs for the RPC commands; most are a single word on the command line.

**Comment by atteeela** [comment]
@kyuupichan Thanks for the quick reply. 

I'm surprised it's taking me this long to be a understand how to `listunspent`.

I'm trying to query the unspent utxos for an address (I'll be hooking up a nodejs app to be able to get utxos for an address).

The RPC interface supports commands such as `getinfo` and connecting/disconnecting peers.

Do you know where I can look to be able to call this method (either from command line or RPC?): `blockchain.address.listunspent`

Thank you,

**Comment by kyuupichan** [comment]
You need to connect to your TCP port once the blockchain and mempool have synced.  The port is in your logs, and typically 50001
