### ISSUE TITLE
API question with the regard to the block height of a transaction

### ISSUE THREAD

**Issue by MaxSavenkov** [kyuupichan/electrumx#459]
I'm writing a wallet that should be able to interact with ElectrumX server. Here's my problem:

I'd like to store transaction history locally, so not to overburden the server with requests. Suppose I just sent a new transaction to server. I store it locally, and then I want to keep an eye one it until it gets enough confirmation that the user won't have to worry about chain reorg happening.

Suppose the transaction got included in the blockchain at height X1. So far, so good - I write down X1 in my own database (to be able to display number of confirmations to user, and as a piece of detailed information to display on request). Then, reorg happens, and now my transaction is actually included in block at height X2. I want to know about that! And now, things begin to get hairy.

I can call transaction.get to query the current status of transaction. But it doesn't contain block height with either verbose=true or false. The verbose response does contain block hash - great, I can use *that* to compare with my stored transaction and notice that something has changed (though that means I need to always query transactions with verbose=true, which is a waste of bandwidth, and I don't even need the rest of the information). But now, I'd like to find out height X2 somehow, to update my record in the database (and display the correct number of confirmations to the user). Yet, the only way to do it is to call get_history for the address that is used with the transaction - which is a bit cumbersome IMO.

Alternatively, I can subscribe to notifications for one of the addresses involved in the transaction - but that seem to be perfectly useless, as these notifications only tell me "something" happened, but not "what" happened, so I basically need to pull all information about the address from server to find out.

Am I missing some obvious way to do it in a simpler manner? If not, is it possible to modify the API to report the block height in tansaction.get response - or, better yet, introduce a new API call that only returns transaction's block height/hash and timestamp?

**Comment by kyuupichan** [comment]
I think the wallet needs to record for each address the last height where there was a tx.  If the chain ever reorgs back before that height then the history should be invalidated.

Yes the fact tx history can only be served as a whole is poor protocol design.  The way subscribing returns a status is not good either, as for a busy address it forces the server (and the client) to load all the history.

I want to move to a better yet still simple protocol for address history, perhaps only returning the most recent confirmed transaction and the block hash it is in.  If you have good ideas please let me know.

**Comment by MaxSavenkov** [comment]
I think this syntax for get_history call would be nice ```scripthash.get_history( address, from_index, count )```. "from_index" and "count" can be used for pagination, and if the client only wants one transaction (for example, when it is scanning for active accounts during wallet recovery) he can make the process more efficient by specifying that just 1 address should be returned. For more flexibility, Python convention might be adopted that used negative indices as indices from the end of the array/list, though it's not a very useful idea as far as mempool is concerned... Maybe a boolean flag specifying whether mempool transactions should be also returned can be added.

Now, to make this work, as far as I understand, you'd need to store a snapshot of address' history in memory on the first call to get_history for that address (probably in a LRU cache). Because transactions, especially mempool ones, can be returned in any order by the daemon, as far as I understand, and also because a reorg might happen between two paginated calls. In this case, reorg won't be reflected in the results, but at least the client would get a consistent result.

I saw a suggestion to paginate the results based on block height, but I don't think this would work nicely with the "count" parameter - which is important for reducing network load - because several transactions could happen with one address in the same block, and the pagination won't be able to handle this case correctly, and mempool transactions don't have block height anyway.

If you want get_history call to return block hash instead of block height, then there is a great need for a call that returns block header by block hash. Currently, block hash is only usable for some local checks, but it can't be used to get anything out of server (like block time) - this requires block height, which we won't have in this case.

Also, do you think it would be possible/desirable to add "batch" versions of API calls that work on arrays of addresses or transaction hashes? Often, clients needs informations about many addresses or transactions at the same time. Currently, this requires making many API calls, which might be less efficient, both in terms of network overhead and server-side processing. Another server I worked with accepted arrays in both its version of get_history and transaction.get, and it was very convenient. It also simplifies client code, because it's easier to wait for a single response than for a group of them (if you want them all to be completed before moving on).

**Comment by kyuupichan** [comment]
A few points:

- in any rework of the API, the mempool and confirmed transaction calls would be entirely separate.  get_history would only return confirmed transactions.  Subscribing to an address would probably return the most recent confirmed tx_hash, and all mempool tx hashes, perhaps as 2 keys in a dictionary, or something
- height would work fine; but the server would return results for a complete block or none of it, no partial block results.  But I'm not sure if height or index is the best start indicator - I assume your index is simply a 0-based index into the history?  I'm not sure if there is any value in the count?  If you don't have the history you're going to want all of it.  The server needn't return it all in one response though if it's large, just an indicator that there is more.
- batches are already handled by ElectrumX; they follow the JSON RPC 2.0 spec.  The problem with asking for several in a single request is that it is then impossible to return individual errors.  I prefer the JSON RPC 2.0 approach
