### ISSUE TITLE
Critical database crash during ChainReorg

### ISSUE THREAD

**Issue by mdilai** [kyuupichan/electrumx#46]
Hi,
I'm using ElectrumX with Dash Core github master branch. It get fully indexed only for a 1.5 hours on 2 core Intel Atom (took ~4 days on original code), but after ~1 hour ElectrumX are crashing with error (attached log).
[electrumx.txt](https://github.com/kyuupichan/electrumx/files/614055/electrumx.txt)

The only what help is full database remove and reindex, but it crashing again soon after complete.
I did not tried with original Dash Core binaries because them are incompatible with my server, but, according to "README.md", Dash team consider their git master branch as stable, so this issue may be mostly in ElecturmX.
Also never seen this on original Electrum-Server with the same daemon.

OS Ubuntu 16.04
RocksDB database

**Comment by kyuupichan** [comment]
Hello,

What version were you using when the very first crash happened?  Should be reported on start up and when catching up.  I'm not asking what you're using now.

**Comment by kyuupichan** [comment]
Unfortunately I don't think that DB is going to be recoverable; you will need to start again.  But I would like to know which software you first synchronized with.

**Comment by kyuupichan** [comment]
It's odd, your reorg limit is 200 blocks but it couldn't find the undo information.  And your daemon height is less than 200 higher.  I have not seen that before - could you perhaps also try leveldb instead of rocksdb?  LevelDB is better tested.

**Comment by kyuupichan** [comment]
If you have the log from the initial crash, instead of when restarting after the initial crash, that would be very helpful too.

**Comment by kyuupichan** [comment]
You got stuck on block 576,606 which is about 10hrs old.  Your logs show version 0.7.10 which is 5hrs old so you were using an older version of the software initially.

TheLazier is mostly contributing dash-specific fixes and his latest fix to block hashes was in 0.7.10, which may be why your DB from an earlier version is corrupt.  Anyway if you can answer the questions I pose above it would help.  But I recommend you restart with the 0.7.10 version you now have.

**Comment by thelazier** [comment]
This orphanned block does not have undo information which is possibly
normal for many dash's block which only has coinbase but no txs where this
should not happen on bitcoin so The exception is raised.
Quick fix is comment the exception , the reorg will work fine. I'm not sure
how proper fix should be so I didn't create the pr.

**Comment by kyuupichan** [comment]
Thanks.  I don't see anything in the codebase that would not write undo information, even if empty, so that is still a mystery to me.  Unless you can see something I'm missing?

**Comment by kyuupichan** [comment]
Ah got it!  you're right, thanks. 

if not undo_info:

should be 

if undo_info is None:

That's the fix!

**Comment by kyuupichan** [comment]
A fix for this will be in 0.7.11

**Comment by kyuupichan** [comment]
@mdilai If you still have your DB it is recoverable, all you need to do is change 1 line of code.  If you could test this it would be good.  In 0.7.10

https://github.com/kyuupichan/electrumx/blob/master/server/block_processor.py#L660

should be changed to:

    if undo_info is None:

If you could confirm that works that would be very helpful.  Your DB should be fine if you still have it.

**Comment by mdilai** [comment]
@kyuupichan Thanks. As i said, full synchronization take only 1.5 hours on my pretty low end server, and i already did this several times and ready again with your fix, just for fun :)
I will let you know about result.

**Comment by kyuupichan** [comment]
Restarting from genesis is fine but will not tell us if your problem was resolved, it will merely join the longest chain.  Ideally you'd restart from your DB that was in need-to-reorg state.

Still, I'm reasonably confident this will be fixed with the change I indicated.

**Comment by mdilai** [comment]
I can confirm that with fix i did not got any crash for the last 8 hours, while before it was crashed every time during first re-org. Also i forgot to say - the same dash daemon is used by P2Pool, i think that's why i got this orphaned blocks from miners.

**Comment by thelazier** [comment]
Confirmed , fixed
```
INFO:Prefetcher:new block height 577,083 hash 00000000000134bfa1fa96659218b12f615c6f5646a8902b4e3a328f11d1c0a1
INFO:BlockProcessor:flush #506 took 0.0s.  Height 577,083 txs: 2,183,678
INFO:MemPool:0 txs touching 0 addresses
INFO:Prefetcher:new block height 577,084 hash 000000000000a92bb6af4064c3f41523f9413a5a56f081779bd809cae615103b
INFO:BlockProcessor:chain reorg detected
INFO:BlockProcessor:finding common height...
INFO:BlockProcessor:chain was reorganised: 1 blocks at heights 577,083-577,083 were replaced
INFO:BlockProcessor:backing up 1 blocks
INFO:BlockProcessor:backed up to height 577,082
INFO:BlockProcessor:backing up history to height 577,082  tx_count 2,183,677
INFO:BlockProcessor:removed 2 history entries from 2 addresses
INFO:BlockProcessor:flush #507 took 0.0s.  Height 577,082 txs: 2,183,677
INFO:BlockProcessor:prefetcher reset
INFO:BlockProcessor:flush #508 took 0.0s.  Height 577,084 txs: 2,183,680
```

**Comment by mdilai** [comment]
If you interested, here is a full log of my experiments with ElectrumX in last 3 days. It's very large but there you can find anything - three different versions, few starting from scratch, different librocksdb versions, system-wide and virtualenv python etc.
[electrumx.log.gz](https://github.com/kyuupichan/electrumx/files/614487/electrumx.log.gz)
