### ISSUE TITLE
How to request verbose=True for blockchain.transaction.get?

### ISSUE THREAD

**Issue by atteeela** [kyuupichan/electrumx#460]
Hello,
I'm looking to get the extended transaction data (as json) as outlined here:
http://electrumx.readthedocs.io/en/latest/protocol-methods.html#blockchain-transaction-get

However, when I make JSON RPC over TCP calls, none of them work to return the extended data (it always only returns the tx hex)

I have made sure to negotiate protocol version to `1.2` successfully up front for each of the examples below as well:
`{"method" : "server.version", "params": ["nc", "1.2"], "id": "msg_id"}`
==> `[ 'ElectrumX 1.4.3', '1.2' ]`

Here is what I've tried:

`{"method" : "blockchain.transaction.get", "params": ["14c21c4fd94d75b18c452b9f3f9471697c787f00662fe4af996d8e7f9646d016", true], "id": "msg_id"}`

`{"method" : "blockchain.transaction.get", "params": ["14c21c4fd94d75b18c452b9f3f9471697c787f00662fe4af996d8e7f9646d016", 1], "id": "msg_id"}`

`{"method" : "blockchain.transaction.get", "params": ["14c21c4fd94d75b18c452b9f3f9471697c787f00662fe4af996d8e7f9646d016", 'true'], "id": "msg_id"}`

`{"method" : "blockchain.transaction.get", "params": ["14c21c4fd94d75b18c452b9f3f9471697c787f00662fe4af996d8e7f9646d016", 'True'], "id": "msg_id"}`

`{"method" : "blockchain.transaction.get", "params": ["14c21c4fd94d75b18c452b9f3f9471697c787f00662fe4af996d8e7f9646d016", 'TRUE'], "id": "msg_id"}`

`{"method" : "blockchain.transaction.get", "params": ["14c21c4fd94d75b18c452b9f3f9471697c787f00662fe4af996d8e7f9646d016", 'verbose'], "id": "msg_id"}`

`{"method" : "blockchain.transaction.get", "params": ["14c21c4fd94d75b18c452b9f3f9471697c787f00662fe4af996d8e7f9646d016", 'Verbose'], "id": "msg_id"}`

I have also verified that the bitcoind server (Bitcoin ABC) correctly returns the full json object when requesting `getrawtransaction` as well

Thanks again

**Comment by kyuupichan** [comment]
Your first effort works fine for me.  However what you have with ===> is not what is returned:

{"method" : "server.version", "params": ["nc", "1.2"], "id": "msg_id"}
{"jsonrpc": "2.0", "result": ["ElectrumX 1.4.3", "1.2"], "id": "msg_id"}
{"method" : "blockchain.transaction.get", "params": ["14c21c4fd94d75b18c452b9f3f9471697c787f00662fe4af996d8e7f9646d016", true], "id": "msg_id"}
{"jsonrpc": "2.0", "result": {"hex": "0200000006975fdde5393dfe98435e5aad7c3def717f53fc2553a4c2b03793c4ef96fd9dc4010000006a47304402202dd69466684ef94e2a9ae7ced7d4787a6f82a876e4fb44d243a93f7ea2bc8e7c0220313662ba598b613d6e63700

and I truncated the result as it's too long

**Comment by buttha** [comment]
uhm... documentation is talking about *decoded* raw transaction when verbose is true...

https://electrumx.readthedocs.io/en/latest/protocol-methods.html#blockchain-transaction-get

but in electrumx's response I see raw hex tx.
Documentation is wrong or I'm missing something?

**Comment by kyuupichan** [comment]
@buttha some information would be nice - what protocol version you requested, what your coinis, and what you sent, and what you got, for example

**Comment by buttha** [comment]
@kyuupichan  excuse, my fault. I was misunderstanding this commit
https://github.com/kyuupichan/electrumx/issues/385
Everything works fine and now I obtain decoded tx.
There was a problem in my protocol negotiation, now it's all ok.
thank you!
