### ISSUE TITLE
Can't Start/Connect Electrumx

### ISSUE THREAD

**Issue by Rspigler** [kyuupichan/electrumx#461]
When starting electrum, I can't find my .onion advertised on the server list even though PEER_ANNOUNCE is set to non 0.  (PEER_ANNOUNCE = 1).  Specifically, all my environmental variables are:

COIN = BitcoinSegwit
DB_DIRECTORY = /root/electrum
DAEMON_URL = (not released for obvious reasons)
ELECTRUMX = /root/electrumx/electrumx_server.py
USERNAME = rspigler
ALLOW_ROOT = 1
NET = mainnet
DB_ENGINE = leveldb
HOST = localhost
SSL_PORT = 50002
BANNER_FILE = /root/electrumx/ElectrumBannerFile.txt
ANON_LOGS = 1
MAX_SUBS = 500,000
MAX_SESSION_SUBS = 100,000
PEER_DISCOVERY = on
PEER_ANNOUNCE = 1
FORCE_PROXY = 1
TOR_PROXY_HOST = localhost
TOR_PROXY_PORT = 9050
REPORT_TCP_PORT = 0
REPORT_SSL_PORT = 0
REPORT_HOST_TOR = 7ebps47wb7mr3s5d.onion
REPORT_TCP_PORT_TOR = 0
REPORT_SSL_PORT_TOR = 50002
SSL_CERTFILE = /root/electrumx/server.crt
SSL_KEYFILE = /root/electrumx/server.key

I am running Debian 9.4

When I open electrum as root, under 'Connection', I check 'Use SSL", 'Use Tor proxy at port 9050', and 'Use proxy' - where SOCKS5 127.0.0.1 9050 is filled.

Under the server tab however, my .onion (7ebps47wb7mr3s5d.onion) is never visible, even though my bitcoin full node is fully synced (I have incoming and outgoing connections with port 8333 open) and electrum is connected to 10 nodes, all with the same height as my bitcoin node.

When I check the log output, I get the following:

root@debian2:~# journalctl -u electrumx -f
-- Logs begin at Fri 2018-04-27 18:26:00 EDT. --
Apr 28 01:03:30 debian2 electrumx_server.py[8122]:   File "<frozen importlib._bootstrap_external>", line 1104, in _legacy_get_spec
Apr 28 01:03:30 debian2 electrumx_server.py[8122]:   File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
Apr 28 01:03:30 debian2 electrumx_server.py[8122]:   File "<frozen importlib._bootstrap_external>", line 541, in spec_from_file_location
Apr 28 01:03:30 debian2 electrumx_server.py[8122]:   File "/usr/local/lib/python3.5/dist-packages/electrumx-ElectrumX.1.4.3-py3.5.egg/lib/util.py", line 44
Apr 28 01:03:30 debian2 electrumx_server.py[8122]:     return f'[{conn_id}] {msg}', kwargs
Apr 28 01:03:30 debian2 electrumx_server.py[8122]:                               ^
Apr 28 01:03:30 debian2 electrumx_server.py[8122]: SyntaxError: invalid syntax
Apr 28 01:03:30 debian2 systemd[1]: electrumx.service: Main process exited, code=exited, status=1/FAILURE
Apr 28 01:03:30 debian2 systemd[1]: electrumx.service: Unit entered failed state.
Apr 28 01:03:30 debian2 systemd[1]: electrumx.service: Failed with result 'exit-code'.

Thank you for any help

**Comment by wakiyamap** [comment]
Hi.
It seems like you are setting up with python 3.5 .
Electrumx is necessary to use python 3.6 or higher.

**Comment by Rspigler** [comment]
Hmmm, thanks @wakiyamap 

I was going to say no, I don't think that's right, since I compiled Python 3.6 from source.  And I can check this by running:

root@debian2:~# python3.6 --version
Python 3.6.1

But if I just run the general command:

root@debian2:~# python --version
Python 2.7.13

So you're clearly right, my system is defaulting to <3.6, even though it looks like I have both installed?

Do you know how I can resolve this?

**Comment by Rspigler** [comment]
I didn't state this in my initial post, but I should write that I am running Bitcoin Core with the following in the config file:

onion=127.0.0.1:9050
listen=1
externalip=xogaezptw2feox5e.onion
discover=1
server=1
daemon=1
txindex=1
rpcuser=[redacted; obviously matching rpcuser of DAEMON_URL in ElectrumX Environment Variables)
rpcpassword=[redacted; obviously matching rpcpassword of DAEMON_URL in ElectrumX Environment Variables)

And that I have the following lines in my torrc file:

HiddenServiceDir /var/lib/tor/bitcoin-service/
HiddenServicePort 8333 127.0.0.1:8333

HiddenServiceDir /var/lib/tor/electrum-service/
HiddenServicePort 50002 127.0.0.1:50002


The ElectrumX Environment Variable of 'REPORT_HOST_TOR = 7ebps47wb7mr3s5d.onion' and the Bitcoin Core config file line 'externalip=xogaezptw2feox5e.onion' were generated by running:

root@debian2:~# cat /var/lib/tor/electrum-service/hostname
7ebps47wb7mr3s5d.onion

and

root@debian2:~# cat /var/lib/tor/bitcoin-service/hostname
xogaezptw2feox5e.onion

**Comment by wakiyamap** [comment]
I judged that you are using python 3.5 in here.
`Apr 28 01:03:30 debian2 electrumx_server.py[8122]: File "/usr/local/lib/python3.5/dist-packages/electrumx-ElectrumX.1.4.3-py3.5.egg/lib/util.py", line 44`

Did not you write this command during installation?
`sudo python3 setup.py install`

correct
`sudo python3.6 setup.py install`

**Comment by Rspigler** [comment]
Ah, that is exactly my issue, yes, thank you!

So, I have deleted my electrumx directory in order to re-do the install by:
`rm -r electrumx`

Then, started the install:

`git clone https://github.com/kyuupichan/electrumx.git
cd electrumx
python3.6 setup.py install`

This leads to lots of log output, but most importantly ending with:

Searching for aiohttp>=1
Reading https://pypi.python.org/simple/aiohttp/
Download error on https://pypi.python.org/simple/aiohttp/: unknown url type: https -- Some packages may not be found!
Couldn't find index page for 'aiohttp' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: unknown url type: https -- Some packages may not be found!
No local packages or working download links found for aiohttp>=1
error: Could not find suitable distribution for Requirement.parse('aiohttp>=1')

Obviously, when I installed the required Python3.6 dependencies, I messed up in the same way and really used Python3.5  I can confirm this by running, again:

`pip3 install --upgrade pip setuptools wheel`
Requirement already up-to-date: pip in /usr/local/lib/python3.5/dist-packages (10.0.1)
Requirement already up-to-date: setuptools in /usr/local/lib/python3.5/dist-packages (39.1.0)
Requirement already up-to-date: wheel in /usr/local/lib/python3.5/dist-packages (0.31.0)

and

`pip3 install aiohttp pylru leveldb plyvel aiorpcx`
Requirement already satisfied: aiohttp in /usr/local/lib/python3.5/dist-packages (3.1.3)
Requirement already satisfied: pylru in /usr/local/lib/python3.5/dist-packages (1.0.9)
Requirement already satisfied: leveldb in /usr/lib/python3/dist-packages (0.1)
Requirement already satisfied: plyvel in /usr/local/lib/python3.5/dist-packages (1.0.4)
Requirement already satisfied: aiorpcx in /usr/local/lib/python3.5/dist-packages/aiorpcX-0.5.5-py3.5.egg (0.5.5)
aiorpcX requires Python '>=3.6' but the running Python is 3.5.3


However, I can not seem to figure out how to install these dependencies on Python3.6.
`python3.6 -m pip install --upgrade pip setuptools wheel`
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Cache entry deserialization failed, entry ignored
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping
Requirement already up-to-date: pip in /usr/local/lib/python3.6/site-packages
Cache entry deserialization failed, entry ignored
Could not fetch URL https://pypi.python.org/simple/setuptools/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping
Requirement already up-to-date: setuptools in /usr/local/lib/python3.6/site-packages
Collecting wheel
  Cache entry deserialization failed, entry ignored
  Could not fetch URL https://pypi.python.org/simple/wheel/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping
  Could not find a version that satisfies the requirement wheel (from versions: )
No matching distribution found for wheel

and

`python3.6 -m pip install aiohttp pylru leveldb plyvel aiorpcx`
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting aiohttp
  Could not fetch URL https://pypi.python.org/simple/aiohttp/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping
  Could not find a version that satisfies the requirement aiohttp (from versions: )
No matching distribution found for aiohttp

**Comment by Rspigler** [comment]
I really appreciate your help @wakiyamap 

To fix my SSL errors, I said screw it and reinstalled Python3.6 (this time 3.6.5)

`wget https://www.python.org/ftp/python/3.6.5/Python-3.6.5.tar.xz`
`tar xf Python-3.6.5.tar.xz`
`cd Python-3.6.5`
`./configure --enable-optimizations`
`make -j4`
`sudo make altinstall`

Then installed the necessary modules:

`sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev`

Then re-ran the installation:

`make -j4`
`make altinstall`

Thanks to you, correctly installed pip:

`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`
`python get-pip.py`

Updated pip for Python3.6:

`python3.6 -m pip install --upgrade pip`

Installed the required Python3.6 dependencies:

`python3.6 -m pip install aiohttp pylru leveldb plyvel aiorpcx`

Went through the same ElectrumX installation process and environmental variables setup as detailed above.

Log Output had permission issues (even though I was running as root and had `ALLOW_ROOT = 1` in environmental variables), so used `cp -R` to move ElectrumX directory out of /root and fixed all appropriate path files in envionmental variables.  This fixed those errors in log output, but still had Daemon connection error problems.  Realized I was using port 8333 instead of 8332 in DAEMON_URL, but after fixing, this error is still occurring.  Have restarted Bitcoin Core manually and then ElectrumX using `systemctl daemon-reload` and `systemctl start electrumx` but log output still shows:

-- Logs begin at Fri 2018-04-27 18:26:00 EDT. --
Apr 29 14:42:03 debian2 electrumx_server.py[14396]: ERROR:Daemon:connection problem - is your daemon running?  Retrying occasionally...
Apr 29 14:43:03 debian2 electrumx_server.py[14396]: ERROR:Daemon:connection problem - is your daemon running?  Retrying occasionally...

Do you have any idea what this could be?
