### ISSUE TITLE
No module named 'distutils.core'

### ISSUE THREAD

**Issue by wakiyamap** [kyuupichan/electrumx#464]
The following error is displayed during setup.

```
~/electrumx$ sudo python3.6 setup.py install
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    import setuptools
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 5, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils.core'
```
It seems to occur when `ppa:jonathonf/python-3.6` and Ubuntu is used.
As a workaround I had to use `ppa:deadsnakes/ppa` or install python3-distutils.
https://github.com/pypa/pip/issues/5356
https://github.com/pypa/pip/issues/5367

**Comment by kyuupichan** [comment]
Nothing I can do about this distro packaging issue.  Clearly if import setuptools is taking it's nothing to do with ElectrumX

**Comment by wakiyamap** [comment]
ok .
I thought that it would be better to rewrite this shell script and so I reported .
https://github.com/kyuupichan/electrumx/blob/master/contrib/python3.6/python-3.6.sh

thanks!!

**Comment by eighthave** [comment]
`apt-get install python3-distutils`?

**Comment by Guyana345** [comment]
@kshitij-agarwal thanks that helped me

**Comment by YakDriver** [comment]
@eighthave Any idea how this would be done on Windows? All my search keep turning up `apt-get install python3-distutils` but no mention of how to accomplish this on Windows.

**Comment by kshitij-agarwal** [comment]
@YakDriver can you post the error?

**Comment by wvagner** [comment]
Thank you @kshitij-agarwal ! You really helped me!

**Comment by tmimy** [comment]
Thanks solved my problem

**Comment by lengrongfu** [comment]
root@ubt01:~# apt-get install python3-distutils
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python3-distutils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libpython3.6-stdlib

E: Package 'python3-distutils' has no installation candidate

**Comment by insanansharyrasul** [comment]
@lengrongfu do you tried to install with

`apt-get download python3-distutils`

and after that, you can try to install it using Gdebi Installer. I hope it works.

**Comment by kyuupichan** [comment]
I don't use Linux; this is a packing issue on your distro and nothing to do with ElectrumX

**Comment by AlexTheDuck** [comment]
```
The following packages have unmet dependencies:
 libqt5svg5 : Depends: libqt5gui5 (>= 5.15.2+dfsg~) but it is not going to be installed or
                       libqt5gui5-gles (>= 5.15.2+dfsg~) but it is not going to be installed
 libqt5widgets5 : Depends: libqt5gui5 (>= 5.15.1) but it is not going to be installed or
                           libqt5gui5-gles (>= 5.15.1) but it is not going to be installed

```
this is my output
