### ISSUE TITLE
unsupported protocol version request 0.10

### ISSUE THREAD

**Issue by DaSpawn** [kyuupichan/electrumx#466]
I just updated to latest version 1.4.3 and I am now seeing this error constantly in logs

May 11 13:01:36 bitcoin electrumx_server.py[29404]: INFO:ElectrumX:[271] unsupported protocol version request 0.10

My electron wallet (3.2) is able to connect without issue.

is this expected behavior?

**Comment by kyuupichan** [comment]
The line is information, like it says, not an error.  It is old clients requesting an unsupported protocol version.
