### ISSUE TITLE
IRC connection reset message continues after successful IRC reconnect

### ISSUE THREAD

**Issue by shsmith** [kyuupichan/electrumx#47]
In several occasions I have lost IRC connection. Usually when this happens, within a few minutes the electrumx server re-joins the channel and stays in the channel, but afterwards the log continues to show IRC connection resets. It appears it didn't recognize that it did in fact connect.

Here is the log of one such incident:

> .. initial loss of connection
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected
ERROR:IRC:connection error: Not connected.
ERROR:IRC:connection error: Not connected.
ERROR:IRC:connection error: Not connected.
ERROR:IRC:connection error: Not connected.
ERROR:IRC:connection error: Not connected.
ERROR:IRC:connection error: Not connected.
ERROR:IRC:connection error: Not connected.
ERROR:IRC:connection error: Not connected.

> .. re-appears in channel at this point
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected

> .. this pattern of errors continues forever until electrumx is restarted
ERROR:IRC:connection error: Not connected.
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected
ERROR:IRC:connection error: Not connected.
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected
ERROR:IRC:connection error: Not connected.
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected
ERROR:IRC:connection error: Not connected.
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected
INFO:IRC:IRC event type disconnect source irc.freenode.net  args ['Connection reset by peer']
ERROR:IRC:disconnected

**Comment by kyuupichan** [comment]
Thanks for the clear report.  I'll take a look and try and fix for 0.7.11; I'm sure it's dumb and trivial.

**Comment by kyuupichan** [comment]
I don't have IRC connection instability so I cannot be sure this fixes it.  It is just a one-liner, but it looks like a good candidate to me.  Let me know please!
