### ISSUE TITLE
Passing client version protocol string via JSON RPC

### ISSUE THREAD

**Issue by m-schmoock** [kyuupichan/electrumx#473]
From reading the docs (and the code) I couldn't find out how to pass the clients protocol version string correctly via JSON RPC. I need it in oder to use the new optional `verbose` paramter of method `blockchain.transaction.get`.

When I use:

`echo '{"jsonrpc":"2.0", "id":1337, "method" : "blockchain.transaction.get", "params" : { "tx_hash" : "e8044f28dbc720b0e96fedf2f0b86a12fcc592903243ef4027651eebd8d754e9", "verbose" : true } }' | nc localhost 50001
`

`{"jsonrpc": "2.0", "error": {"code": -32602, "message": "method \"blockchain.transaction.get\" does not take parameter \"verbose\""}, "id": 1337}`

I tried a lot of variations, it either ignores the additional parameter (i.e. when passed as last argument of an JSON RPC args array), or complains that it does not take this parameter. Also the client script (`electrumx_rpc.py`) cannot handle the new parameter.

The call seems routed via the deprecated `transaction_get_1_0` function where it does not pass the verbose parameter and thus defaults to `false`.

**Comment by kyuupichan** [comment]
From the docs you will see that verbose is only in protocol 1.2.  Since you connected and didn't request a protocol version, you get the lowest supported, which will probably be 1.0.

After connecting send a protocol version request; see the docs for the server.version RPC command.

**Comment by kyuupichan** [comment]
That's a batch request, which would work but gives you a single array response.  Alternatively seaparate the requests with a newline and get two single responses.
