### ISSUE TITLE
asyncio:socket.accept() out of system resource will write excessively daemon.log and syslog to the point of 100% disk usage, making the server useless

### ISSUE THREAD

**Issue by gits7r** [kyuupichan/electrumx#481]
Running on Debian Stretch with systemd.

It happened to me two times consecutively in 10 days.  When ElectrumX hits the resource limit of open files, instead of terminating it logs excessively syslog and daemon.log until 100% disk is used on the server, making it useless.

Here is the size of my syslog and daemon.log:
`-rw-r----- 1 root       adm  107G May 29 16:06 daemon.log`
`-rw-r----- 1 root       adm  104G May 29 16:06 syslog`

From what I was able to see in the log files it starts by complaining about a daemon connection problem, then about open files but it does not die entirely, it keeps maintaining some existing connections. When the disk gets full, everything collapses:

daemon.log
May 28 04:46:31 bitcoin-electrumx electrumx_server.py[483]: INFO:ElectrumX:[363422] SSL xx.xx.xx.xx:xx, 519 total
May 28 04:46:31 bitcoin-electrumx electrumx_server.py[483]: INFO:ElectrumX:[363423] SSL xx.xx.xx.xx:xx, 520 total
May 28 04:46:31 bitcoin-electrumx electrumx_server.py[483]: INFO:ElectrumX:[363424] SSL xx.xx.xx.xx:xx, 521 total
May 28 04:46:31 bitcoin-electrumx electrumx_server.py[483]: INFO:ElectrumX:[363423] unsupported protocol version request 0.10
May 28 04:46:34 bitcoin-electrumx electrumx_server.py[483]: INFO:ElectrumX:[363422] unsupported protocol version request 0.10
May 28 04:46:35 bitcoin-electrumx electrumx_server.py[483]: ERROR:Daemon:connection problem - is your daemon running?  Retrying occasionally...
May 28 04:46:35 bitcoin-electrumx electrumx_server.py[483]: INFO:Daemon:connection restored
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]: ERROR:Daemon:connection problem - is your daemon running?  Retrying occasionally...
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]: INFO:Daemon:connection restored
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]: INFO:ElectrumX:[363425] SSL xx.xx.xx.xx:xx, 519 total
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]: ERROR:asyncio:socket.accept() out of system resource
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]: socket: <socket.socket fd=18, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('192.168.56.2', 50002)>
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]: Traceback (most recent call last):
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:   File "/usr/lib/python3.6/asyncio/selector_events.py", line 179, in _accept_connection
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:   File "/usr/lib/python3.6/socket.py", line 205, in accept
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]: OSError: [Errno 24] Too many open files
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]: ERROR:asyncio:socket.accept() out of system resource
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]: socket: <socket.socket fd=18, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('192.168.56.2', 50002)>

And another controller error:
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]: ERROR:Controller:uncaught task exception: b'IO error: utxo/394402.ldb: Too many open files'
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]: Traceback (most recent call last):
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/controller.py", line 192, in check_task_exception
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:     task.result()
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/mempool.py", line 139, in main_loop
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:     await process_some(unprocessed)
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/mempool.py", line 168, in process
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:     self.process_raw_txs, raw_txs, deferred)
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/controller.py", line 176, in run_in_executor
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:     return await self.loop.run_in_executor(None, func, *args)
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:     result = self.fn(*self.args, **self.kwargs)
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/mempool.py", line 264, in process_raw_txs
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:     txin_pairs.append(db_utxo_lookup(prev_hash, prev_idx))
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/db.py", line 380, in db_utxo_lookup
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:     hashX, tx_num_packed = self._db_hashX(tx_hash, idx_packed)
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/db.py", line 405, in _db_hashX
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:     for db_key, hashX in self.utxo_db.iterator(prefix=prefix):
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:   File "plyvel/_plyvel.pyx", line 829, in plyvel._plyvel.Iterator.__next__
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:   File "plyvel/_plyvel.pyx", line 874, in plyvel._plyvel.Iterator.real_next
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:   File "plyvel/_plyvel.pyx", line 88, in plyvel._plyvel.raise_for_status
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]: plyvel._plyvel.IOError: b'IO error: utxo/394402.ldb: Too many open files'
May 28 04:46:37 bitcoin-electrumx electrumx_server.py[483]: INFO:ElectrumX:[363426] SSL xx.xx.xx.xx:xx, 520 total
May 28 04:46:37 bitcoin-electrumx electrumx_server.py[483]: INFO:ElectrumX:[363427] SSL xx.xx.xx.xx:xx, 521 total
May 28 04:46:37 bitcoin-electrumx electrumx_server.py[483]: ERROR:Daemon:connection problem - is your daemon running?  Retrying occasionally...
May 28 04:46:37 bitcoin-electrumx electrumx_server.py[483]: INFO:Daemon:connection restored
May 28 04:46:37 bitcoin-electrumx electrumx_server.py[483]: INFO:ElectrumX:[363426] unsupported protocol version request 0.10
May 28 04:46:37 bitcoin-electrumx electrumx_server.py[483]: INFO:ElectrumX:[363428] SSL xx.xx.xx.xx:xx, 520 total

syslog contains similar traceback line so not providing it entirely because it's pointless:
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]: Traceback (most recent call last):
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:   File "/usr/lib/python3.6/asyncio/selector_events.py", line 179, in _accept_connection
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]:   File "/usr/lib/python3.6/socket.py", line 205, in accept
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]: OSError: [Errno 24] Too many open files
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]: ERROR:asyncio:socket.accept() out of system resource
May 28 04:46:36 bitcoin-electrumx electrumx_server.py[483]: socket: <socket.socket fd=18, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('192.168.56.2', 50002)>

What can we do to prevent this from happening? Now I have raised my system max open files limit to 999999 for all users, even non-interactive sessions but we should do something so electrumx if it can't heal by itself from this scenario, not write hundreds of GB of log in few hours.

**Comment by kyuupichan** [comment]
The open files issue is a Python bug fixed in 3.7.

The logging is the responsibility of your logger; this is why I recommend daemontools.  Probably your logging subsystem has a way to limit and/or rotate logs too.

**Comment by vinnyvoo** [comment]
That bug the entire electrumx database 😢. Is there any way i can recover the database state?

**Comment by vinnyvoo** [comment]
I'm a complete noob. Can you please tell me how to to limit / clear logs ?
