### ISSUE TITLE
Can't get Electrum to connect to local ElectrumX installation

### ISSUE THREAD

**Issue by Renben9** [kyuupichan/electrumx#487]
Hi, I'm out of ideas. I installed ElectrumX out of the AUR repository from Archlinux on a virtual instance of Manjaro (Archlinux spin off distro) ( (in VirtualBox).

I think everything worked fine and ElectrumX is running, but an Electrum client won't connect. Neither using one installed on the same machine with the server being 127.0.0.1:50002, nor on the LAN and using the Manjaros LAN IP.

Is having `txindex=1` in the `bitcoin.conf` file a must? 

All iptables policies are ACCEPT, but in addition I explicitly allowed incoming TCP connections on ports 50001 and 50002 using

`iptables -A INPUT -p tcp --dport 50001 -j ACCEPT`
`iptables -A INPUT -p tcp --dport 50002 -j ACCEPT`

Here's a representative output from `systemctl status electrumx`. It looks fine to me, so what am I missing?

[manj ~]# systemctl status electrumx
● electrumx.service - ElectrumX Server
   Loaded: loaded (/usr/lib/systemd/system/electrumx.service; disabled; vendor preset: disabled)
   Active: active (running) since Sun 2018-06-03 16:39:05 CEST; 1h 53min ago
  Process: 4699 ExecStop=/usr/bin/electrumx-rpc -p 8000 stop (code=exited, status=0/SUCCESS)
 Main PID: 4702 (electrumx-serve)
    Tasks: 7 (limit: 4915)
   Memory: 2.9G
   CGroup: /system.slice/electrumx.service
           └─4702 /usr/bin/python /usr/bin/electrumx-server

Jun 03 18:15:45 manj electrumx-server[4702]: INFO:MemPool:2,181 txs touching 34,349 addresses
Jun 03 18:18:19 manj electrumx-server[4702]: INFO:MemPool:2,550 txs touching 36,239 addresses
Jun 03 18:20:53 manj electrumx-server[4702]: INFO:MemPool:2,916 txs touching 38,935 addresses
Jun 03 18:22:03 manj electrumx-server[4702]: INFO:Prefetcher:new block height 525,797 hash 0000000000000000000ecdd4566e0741bc429f6fb9de7a75fd31ecf277223709
Jun 03 18:22:40 manj electrumx-server[4702]: INFO:BlockProcessor:flush #539 took 0.2s.  Height 525,797 txs: 320,145,122
Jun 03 18:22:40 manj electrumx-server[4702]: INFO:BlockProcessor:processed 1 block in 36.3s
Jun 03 18:23:53 manj electrumx-server[4702]: INFO:MemPool:2,044 txs touching 35,201 addresses
Jun 03 18:26:27 manj electrumx-server[4702]: INFO:MemPool:2,601 txs touching 37,483 addresses
Jun 03 18:28:57 manj electrumx-server[4702]: INFO:MemPool:2,952 txs touching 38,926 addresses
Jun 03 18:31:28 manj electrumx-server[4702]: INFO:MemPool:3,365 txs touching 40,834 addresses

**Comment by kyuupichan** [comment]
You cannot connect whilst ElectrumX is syncing from the genesis block.

**Comment by nshCore** [comment]
clear this guy is an idiot who doesn't know anything
