### ISSUE TITLE
Server fail to connect peers

### ISSUE THREAD

**Issue by novelena** [kyuupichan/electrumx#489]
Hello,

I have successfully sync my client to servers, however my servers seems unable to connect to each other

server1                   never  50001 50002 ElectrumX 1.4.4p2  1.1  1.2                Never     09m 34s     1                  env
server2                  never  50001 50002 unknown            0.0  0.0                Never     09m 34s     1             coins.py
server3                never  50001 50002 unknown            0.0  0.0                Never

i tried using nc localhost 50001

{"jsonrpc": "2.0", "error": {"code": -32700, "message": "cannot decode JSON: Expecting value: line 1 column 1 (char 0)"}, "id": null}

this is my conf file   

COIN = Yacoin
DB_DIRECTORY = /home/electrumx/.electrumx/DBB
DAEMON_URL = http://XXXX:XXXX@127.0.0.1:9911
NET = mainnet
USERNAME = electrumx
DB_ENGINE = leveldb
HOST = 127.0.0.1
TCP_PORT = 50001
SSL_PORT = 50002
RPC_PORT = 8000
SSL_CERTFILE=/home/electrumx/.electrumx/server.crt
SSL_KEYFILE=/home/electrumx/.electrumx/server.key
BANNER_FILE = /home/electrumx/.electrumx/banner.txt
DONATION_ADDRESS =
REPORT_HOST = 128.199.145.213

I have allowed ufw all ports that needed to use

what's wrong with my configuration?

**Comment by kyuupichan** [comment]
If there is something that could be improved in the docs so you would have got the setup working sooner, please submit a PR.  Thanks.
