### ISSUE TITLE
Why unknow new altcoin (widecash)

### ISSUE THREAD

**Issue by widecash** [kyuupichan/electrumx#497]
Loaded: loaded (/etc/systemd/system/electrumx.service; enabled; vendor preset: enabled)
Active: inactive (dead) since Mon 2018-06-18 02:44:34 UTC; 2s ago
Process: 10502 ExecStart=/usr/local/bin/electrumx_server.py (code=exited, status=0/SUCCESS)
Main PID: 10502 (code=exited, status=0/SUCCESS)

Jun 18 02:44:33 Electrum69 systemd[1]: Started Electrumx.
Jun 18 02:44:34 Electrum69 electrumx_server.py[10502]: INFO:root:ElectrumX server starting
Jun 18 02:44:34 Electrum69 electrumx_server.py[10502]: Traceback (most recent call last):
Jun 18 02:44:34 Electrum69 electrumx_server.py[10502]: File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/EGG-INFO/scripts/electrumx_serv
Jun 18 02:44:34 Electrum69 electrumx_server.py[10502]: File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/server/env.py", line 36, in __i
Jun 18 02:44:34 Electrum69 electrumx_server.py[10502]: self.coin = Coin.lookup_coin_class(coin_name, network)
Jun 18 02:44:34 Electrum69 electrumx_server.py[10502]: File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/lib/coins.py", line 100, in loo
Jun 18 02:44:34 Electrum69 electrumx_server.py[10502]: .format(name, net))
Jun 18 02:44:34 Electrum69 electrumx_server.py[10502]: lib.coins.CoinError: unknown coin Widecash and network mainnet combination
Jun 18 02:44:34 Electrum69 electrumx_server.py[10502]: CRITICAL:root:ElectrumX server terminated abnormally

**Comment by kyuupichan** [comment]
That coin is not part of the ElectrumX distribution

**Comment by widecash** [comment]
how can be my coin can be using it ?

**Comment by widecash** [comment]
May i get your email or telegram?
