### ISSUE TITLE
Websocket support?

### ISSUE THREAD

**Issue by DaniGuardiola** [kyuupichan/electrumx#499]
Hi, I would like to know if there's websocket support, it would make things much easier for my lightweight wallet. If there is, how do I use it and what are the differences with a standard socket connection? Is there any documentation available? If there isn't, could it be implemented? Is it planned? Would you be open to a PR if you need it? I could get someone to work on it.

Thank you in advance :)

**Comment by kyuupichan** [comment]
See #242 perhaps?  I am not working on these, but will accept a quality PR with tests to implement such a feature.

**Comment by DaniGuardiola** [comment]
@kyuupichan thanks for your response!

Good to know that you will accept a quality PR. Could you write down some basic guidance on where to start and what to check in the code in order to implement this?

Thank you :+1:

**Comment by kyuupichan** [comment]
I don't really know much about websockets.  The code should be asynchronous.  aiohttp might be useful.  It's not clear to me if it should use or be part of the aiorpcX package.

**Comment by DaniGuardiola** [comment]
Where are the TCP sockets currently implemented? It could be a good reference to understand how to provide the websocket connection as well.

**Comment by DaniGuardiola** [comment]
I made this demo / info repo, could you take a look at it and let me know if you have any suggestion? @kyuupichan 

Thanks a lot, I just want to double-check that I have correct and complete information before starting development.

**Comment by kyuupichan** [comment]
Looks like the right idea to me.  Note I'm unsure if the appropriate location for the new code is aiorpcX or electrumX.  Probably the former.  Note aiorpcX has 100% test coverage.

**Comment by kyuupichan** [comment]
I think the websockets package is the right way to do this.  It shouldn't be more than a few lines of code added in aiorpcx.  I'll take a look at it some time in the next month or so.

**Comment by DaniGuardiola** [comment]
@kyuupichan thanks, I've abandoned the project that depended on this, but on the other hand, I've been working with Python so I should be more prepared to help. I'll see if I can find some time to help you out with the PR.

**Comment by kyuupichan** [comment]
I just implemented websockets in https://github.com/kyuupichan/electrumx/commit/a6bfc032674aac71eeffea3457ad10c456c1baa0

See https://electrumx.readthedocs.io/en/latest/environment.html#services

**Comment by DaniGuardiola** [comment]
Thanks a lot @kyuupichan!! Nice work :D

**Comment by kyuupichan** [comment]
@DaniGuardiola have you tried it and confirm it works as you expect?

**Comment by DaniGuardiola** [comment]
@kyuupichan I haven't really worked on my project since I started a new job, but as soon as I can put my hands on it again I'll let you know.
