### ISSUE TITLE
High memory consumption after long uptime

### ISSUE THREAD

**Issue by SomberNight** [kyuupichan/electrumx#508]
I'm on bitcoin (segwit) mainnet, running https://github.com/kyuupichan/electrumx/commit/0dc99d7c63f2fe8e4e6f758afddc9024a239c3ff

I have noticed that e-x is using a significant amount of RAM, currently 10.75 GiB.
```
electrumx_rpc.py getinfo
{
    "closing": 1556,
    "daemon": "172.19.1.10:8332/",
    "daemon_height": 530351,
    "db_height": 530351,
    "errors": 849,
    "groups": 178,
    "logged": 0,
    "paused": 0,
    "peers": {
        "bad": 0,
        "good": 96,
        "never": 1,
        "stale": 8,
        "total": 105
    },
    "pid": 1,
    "requests": 1,
    "sessions": 1688,
    "subs": 16777,
    "txs_sent": 27448,
    "uptime": "84d 06h 51m"
}
```
(actually my server was having temporary connection issues, and in the preceding ~10 minutes of this getinfo call, the session count dropped from approx 2500; but probably not relevant. the memory usage did not change.)

I had originally noticed about a month ago, and from what I said on IRC (as random remark), another data point:
```
how much RAM does e-x normally use? it's at 6.6 GB for me now. 2k sessions, 43k subs, 55 days uptime
```
However, while looking at this, @JustinTArthur made me realise I'm on a relatively old version of CPython..:
```
Python 3.6.1 (default, May 11 2017, 22:14:44)
[GCC 4.9.2] on linux
```
It's from when I first built my docker image for electrumx; turns out every time I rebuilt the image, it reused the local `python:3` image instead of updating (stupid default behaviour imho, but oh well).

**Comment by kyuupichan** [comment]
Please re-open if the same problem occurs with Python 3.7.  3.6 and earlier have the open file bug in Python.  It's unclear if this is related, but likely is.
