### ISSUE TITLE
ERROR:asyncio:Fatal write error on socket transport

### ISSUE THREAD

**Issue by santzi** [kyuupichan/electrumx#52]
I got several this kind of error prints, but server is still up and running:

Nov 28 03:44:49 ubuntu electrumx_server.py[6372]: ERROR:asyncio:Fatal write error on socket transport
Nov 28 03:44:49 ubuntu electrumx_server.py[6372]: protocol: <asyncio.sslproto.SSLProtocol object at 0x7f22cc72b438>
Nov 28 03:44:49 ubuntu electrumx_server.py[6372]: transport: <_SelectorSocketTransport closing fd=21 read=idle write=<idle, bufsize=0>>
Nov 28 03:44:49 ubuntu electrumx_server.py[6372]: Traceback (most recent call last):
Nov 28 03:44:49 ubuntu electrumx_server.py[6372]:   File "/usr/lib/python3.5/asyncio/selector_events.py", line 723, in _write_ready
Nov 28 03:44:49 ubuntu electrumx_server.py[6372]:     n = self._sock.send(self._buffer)
Nov 28 03:44:49 ubuntu electrumx_server.py[6372]: TimeoutError: [Errno 110] Connection timed out

Nov 28 03:45:53 ubuntu electrumx_server.py[6372]: ERROR:asyncio:Fatal write error on socket transport
Nov 28 03:45:53 ubuntu electrumx_server.py[6372]: protocol: <asyncio.sslproto.SSLProtocol object at 0x7f22cc72b898>
Nov 28 03:45:53 ubuntu electrumx_server.py[6372]: transport: <_SelectorSocketTransport closing fd=25 read=idle write=<idle, bufsize=0>>
Nov 28 03:45:53 ubuntu electrumx_server.py[6372]: Traceback (most recent call last):
Nov 28 03:45:53 ubuntu electrumx_server.py[6372]:   File "/usr/lib/python3.5/asyncio/selector_events.py", line 723, in _write_ready
Nov 28 03:45:53 ubuntu electrumx_server.py[6372]:     n = self._sock.send(self._buffer)
Nov 28 03:45:53 ubuntu electrumx_server.py[6372]: TimeoutError: [Errno 110] Connection timed out

Nov 28 04:01:48 ubuntu electrumx_server.py[6372]: ERROR:asyncio:Fatal write error on socket transport
Nov 28 04:01:48 ubuntu electrumx_server.py[6372]: protocol: <asyncio.sslproto.SSLProtocol object at 0x7f22cc767f98>
Nov 28 04:01:48 ubuntu electrumx_server.py[6372]: transport: <_SelectorSocketTransport closing fd=20 read=idle write=<idle, bufsize=0>>
Nov 28 04:01:48 ubuntu electrumx_server.py[6372]: Traceback (most recent call last):
Nov 28 04:01:48 ubuntu electrumx_server.py[6372]:   File "/usr/lib/python3.5/asyncio/selector_events.py", line 723, in _write_ready
Nov 28 04:01:48 ubuntu electrumx_server.py[6372]:     n = self._sock.send(self._buffer)
Nov 28 04:01:48 ubuntu electrumx_server.py[6372]: TimeoutError: [Errno 110] Connection timed out

Is there any way to prevent these error prints?
Reason might be that, some Electrum client does not reply in time?

**Comment by kyuupichan** [comment]
These are annoying; they are not caused by anything I can directly control.  I already check if the connection is disconnecting before I try to send; these are just the python socket layer messages.  You can see there is no backtrace to electrumx code.  However I do not get these any more.

If these keep happening can you look to extending the error suppression code in electrumx_server.py, in such a way that it just gets these errors?  I can then add it in for everyone.

And , as you noticed, nothing is malfunctioning and the server will continue to run fine.

**Comment by kyuupichan** [comment]
Do you still have this issue?  My logs are completely clean.

If you do I can look into suppressing it, but unless this is a widespread issue I'd rather not suppress things arbitrarily.

**Comment by shsmith** [comment]
I still get these, but only a few times a day. Nothing that bothers me.

**Comment by santzi** [comment]
I have seen this error sometimes when using 0.7.16 version. About one per hour, sometimes couple of times per hour. I think this is not so fatal...minor one.
Let's see if someone else see this.

**Comment by kyuupichan** [comment]
@santzi @shsmith can one of you confirm this has indeed been suppressed?  As I never got them I cannot be sure that what I think should stop them actually has done so.

**Comment by santzi** [comment]
I have used version 0.8.0 couple of hours and I haven't seen this error any more.

**Comment by kyuupichan** [comment]
Great, thanks for responding!

**Comment by shsmith** [comment]
Have not seen it since updating.

**Comment by leungdim** [comment]
Hi, I know it has been 3 years, but do you recall what was causing the TimeoutError? You said that they are not caused by things that you can directly control. I have this error on a server that I'm working on and I can't seem to figure out what is causing it. Thank you so much for your time!

**Comment by kyuupichan** [comment]
The asyncio library

**Comment by leungdim** [comment]
What is actually causing the connection timeout that causes asyncio to print the error?
