### ISSUE TITLE
Very high memory consumption at initialization

### ISSUE THREAD

**Issue by imaginaryusername** [kyuupichan/electrumx#522]
Memory consumption was really high at startup; ElectrumX is now consuming 11GB of RAM at block 477000, a continuous growth that doesn't seem to slow down. Not sure if this behavior was observed in 1.4.x. Cache_MB was set to 3072 in electrumx.conf so i don't think that's an issue. Is there another parameter I can tweak so it doesn't consume so much memory at initial sync?

**Comment by kyuupichan** [comment]
I've not seen this myself and it hasn't been reported before

**Comment by imaginaryusername** [comment]
Additonally I stop the sync progress via `electrumx_rpc stop` and restart it, then the memory usage is resetted. Wondering if this could be related to the Python 3.6 vs 3.7 issue you mentioned in the docs.

**Comment by cipig** [comment]
I have a similar problem with 1.8.5, but not at initialization time. Electrumx seems to leak memory. It is not coin related, it happens with all coins. I have to restart the daemon in order to release the memory.

**Comment by kyuupichan** [comment]
Are you using Python3.7 or Python3.6?  Python 3.6 has bugs; I'm only really interested in memory issues happening in released versions of Python 3.7 or higher.

**Comment by cipig** [comment]
I am using Python 3.7.0

**Comment by kyuupichan** [comment]
Please paste a copy of your full logs to pastebin etc.  Thanks.

**Comment by JeffVandrewJr** [comment]
@cipig @a5mo @kyuupichan Did any of you ever resolve this issue? I had the same problem on Python 3.7.2. I just lost all electric as I was troubleshooting, so I can't paste any logs right now.

**Comment by gdassori** [comment]
I can confirm I'm having a similar issue, not only with Python 3.7. 

Looks like the BlockProcessor doesn't flush the data while syncing. To work around I had to stop and restart the daemon, gracefully with the RPC client, quite every 15 minutes during the bootstrap. 

Once the memory limit is hit, all the parsed history is lost, because of an exception and the lack of DB flush.
Experienced with both leveldb and rocksdb,  on the current master and python 3.6.

**Comment by JeffVandrewJr** [comment]
Same as @gdassori stop/restart was my only solution.

**Comment by kyuupichan** [comment]
It intentionally doesn't flush the data when syncing, as this gives a much faster sync.  The cache size is controlled by the environment variable as documented.

**Comment by gdassori** [comment]
Oh, I see. 
Lowering the db_cache helped, actually. 
Thanks.

**Comment by markblundeberg** [comment]
In my experience you need to be careful with memory consumption when syncing testnet, due to how testnet activity is extremely lumpy. It messes with electrumx's cache prediction estimates and causes cache to sometimes grow much larger than the set limits.

Definitely do lower the db_cache
