### ISSUE TITLE
How to move to scripthash

### ISSUE THREAD

**Issue by ymatagne** [kyuupichan/electrumx#536]
HEllo,

I'd like to know how to switch from blockchain.address.get_balance() to blockchain.scripthash.get_balance() when you have just the address.

Have a good day

**Comment by kyuupichan** [comment]
It's all in the docs

**Comment by Teimoon** [comment]
Bad docs.

**Comment by SomberNight** [comment]
See e.g. https://github.com/spesmilo/electrum/blob/16f56ccbf008cdb48d3391c732c55b43db6706e9/electrum/bitcoin.py#L390-L420

**Comment by Teimoon** [comment]
Thank you SomberNight. This is what I was looking for.

**Comment by Teimoon** [comment]
In the ElectrumX Documentation 1.12.0 of Neil Booth, Jul 06, 2019, 
you can read (page 28):

For example, the legacy Bitcoin address from the genesis block:
1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa
has P2PKH script:
76a91462e907b15cbf27d5425399ebf6f0fb50ebb88f1888ac
with SHA256 hash:
6191c3b590bfcfa0475e877c302da1e323497acf3b42c08d8fa28e364edf018b

I got this sha256-hash: 5f3f330fccb56d6b43f19b7e235f5b146ac92add3a3ab99380a39e7f7406959b from 76a91462e907b15cbf27d5425399ebf6f0fb50ebb88f1888ac, 
NOT 6191c3b590bfcfa0475e877c302da1e323497acf3b42c08d8fa28e364edf018b ?

Any idea?

**Comment by Teimoon** [comment]
I solved this using address_to_scripthash(addr)
from electrum.bitcoin import address_to_scripthash

**Comment by kyuupichan** [comment]
You are hashing the hex text which is just a representation; you should be hashing the bytes...

**Comment by Teimoon** [comment]
Uhhh, danm.
Thank u kyuupichan
