### ISSUE TITLE
How to get server info such as block height and network info? 

### ISSUE THREAD

**Issue by MonicaMillerr** [kyuupichan/electrumx#539]
I'm looking for a command such as `getblockchaininfo` in bitcoin-core.

**Comment by MonicaMillerr** [comment]
I'm running my own server and I would like to know as a client how many blocks my server has.

**Comment by kyuupichan** [comment]
The logs help there.  You can also use the RPC commands like getinfo

http://electrumx.readthedocs.io/en/latest/rpc-interface.html

**Comment by AdamSEY** [comment]
Thanks for your reply, Is it possible to know so for public electrum servers as well (servers that I don't have access through RPC_PORT)

**Comment by AdamSEY** [comment]
I have the same question but for servers that I don't have access through RPC_PORT, Is it possible to know each server blocks total?

**Comment by kyuupichan** [comment]
blockchain.headers.subscribe gives you that information; it's how Electrum itself works

**Comment by AdamSEY** [comment]
Thanks a bunch! I don't know how did I miss it.
