### ISSUE TITLE
Request to make Electrum BCD Portable Wallet detect trusted private Nodes / servers

### ISSUE THREAD

**Issue by juanpc2018** [kyuupichan/electrumx#549]
Request Electrum Portable Wallet to see private Nodes / other servers...

im using a Modem that has ports blocked... "Need to change ISP company" to use Noia Network, VNC, etc...
[https://github.com/noia-network/noia-node-gui/releases](https://github.com/noia-network/noia-node-gui/releases)
anyway...
another problem is that im using a router connected to the modem router,
my IP is a: 192.168.137.xxx
and Windows ICS "Internet Connection Sharing"
"basically im behind 3 routers."
the Node & the Portable Wallet are on the same PC &/or same Router..
i cannot use: whatsmyip, unless i open the ports.
[http://www.whatsmyip.org/](http://www.whatsmyip.org/)

i´ve tryed:
```
localhost:7116
localhost:7117
127.0.0.1:7116
127.0.0.1:7117
192.168.137.141:7116
192.168.137.141:7117
bcd.vvpool.com:7116 
bcd.vvpool.com:7117
& :50002
```
Electrum Portable BCD is working ok with:
`seed1.electrum.btcd.io:50002`

BCD Node v1.1 is working ok, with:
`"...\bitcoindiamond-qt.exe" -assumevalid=0 -datadir="D:\...\BitcoinDiamond" -dbcache=10000 -server -rpcuser=rpcusername -rpcpassword=rpcpassword -rpcallowip=192.168.137.141`

it can be done with MoneroXMR daemon + Cake or Monerujo portable wallet, but is tricky.
[https://getmonero.org/resources/user-guides/remote_node_gui.html](url)
[https://moneroworld.com/#nodes](url)
[https://github.com/m2049r/xmrwallet](url)
[https://github.com/fotolockr/CakeWallet](url)
[https://github.com/monero-project/monero](url)

ive tryed different bitcoin.conf settings but Portable does Not see my private node.
[https://en.bitcoin.it/wiki/Running_Bitcoin#Bitcoin.conf_Configuration_File](https://en.bitcoin.it/wiki/Running_Bitcoin#Bitcoin.conf_Configuration_File)
[https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/bitcoin.conf-annotated.txt](https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/bitcoin.conf-annotated.txt)

this is important, because when the seed1 server is offline, coins are unavailable... like there is No Network, No internet, No coins.
The only way to use the limbo / frozen / zombie coins is to recover from private keys to another node wallet, or wait until server is back on-line.
but that can be avoided if Portable Wallet could detect other Nodes, like a Private Node, for example.

its more secure to store coins in a portable wallet, and have a trusted private Node running 24-7...
Portable wallet with only 1 BCD server is a low-medium risk, 
Not a redundant Fail Safe Security Method, like P2P Peer to Peer Decentralized Network, Not Satoshi Nakamoto Original Vision.

https://github.com/eveybcd/electrumx/issues/

**Comment by kyuupichan** [comment]
I think this is the wrong project, you want https://github.com/spesmilo/electrum
