### ISSUE TITLE
aiorpcX version 0.7.x required

### ISSUE THREAD

**Issue by denpamusic** [kyuupichan/electrumx#563]
Got this error doing fresh install of 1.8.1 using `python3 setup.py install`.
I figured out that it's due to this line https://github.com/kyuupichan/electrumx/blob/master/setup.py#L15 requiring `aiorpcX < 0.7.0`, which installs aiorpcX 0.6.2 instead of 0.7.0.
After I changed it to `aiorpcX  <= 0.7.0` everything installs and runs fine.

    Aug 08 16:18:03 electrumx_server[22991]: INFO:Controller:Python version: 3.7.0 (default, Aug  6 2018, 20:07:46)
    Aug 08 16:18:03 electrumx_server[22991]: [GCC 5.4.0 20160609]
    Aug 08 16:18:03 electrumx_server[22991]: ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /usr/local/lib/python3.7/dist-packages/electrumX-1.8.1-py3.7.egg/electrumx/server/controller.py:79> exception=RuntimeError('aiorpcX version 0.7.x required')>
    Aug 08 16:18:03 electrumx_server[22991]: Traceback (most recent call last):
    Aug 08 16:18:03 electrumx_server[22991]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.6.2-py3.7.egg/aiorpcx/util.py", line 118, in check_task
    Aug 08 16:18:03 electrumx_server[22991]:     task.result()
    Aug 08 16:18:03 electrumx_server[22991]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.8.1-py3.7.egg/electrumx/server/controller.py", line 84, in serve
    Aug 08 16:18:03 electrumx_server[22991]:     raise RuntimeError('aiorpcX version 0.7.x required')
    Aug 08 16:18:03 electrumx_server[22991]: RuntimeError: aiorpcX version 0.7.x required
    Aug 08 16:18:03 electrumx_server[22991]: ERROR:TaskGroup:task crashed: <Task finished coro=<Controller.serve() done, defined at /usr/local/lib/python3.7/dist-packages/electrumX-1.8.1-py3.7.egg/electrumx/server/controller.py:79> exception=RuntimeError('aiorpcX version 0.7.x required'                                                    )>
    Aug 08 16:18:03 electrumx_server[22991]: Traceback (most recent call last):
    Aug 08 16:18:03 electrumx_server[22991]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.6.2-py3.7.egg/aiorpcx/util.py", line 118, in check_task
    Aug 08 16:18:03 electrumx_server[22991]:     task.result()
    Aug 08 16:18:03 electrumx_server[22991]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.6.2-py3.7.egg/aiorpcx/util.py", line 118, in check_task
    Aug 08 16:18:03 electrumx_server[22991]:     task.result()
    Aug 08 16:18:03 electrumx_server[22991]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.8.1-py3.7.egg/electrumx/server/controller.py", line 84, in serve
    Aug 08 16:18:03 electrumx_server[22991]:     raise RuntimeError('aiorpcX version 0.7.x required')
    Aug 08 16:18:03 electrumx_server[22991]: RuntimeError: aiorpcX version 0.7.x required

**Comment by SomberNight** [comment]
btw I suggest declaring it as a single item instead of two; such as `"package>=0.7,<0.8"`

**Comment by kipper01** [comment]
I will second this error...

How you change it to iorpcX <= 0.7.0

**Comment by denpamusic** [comment]
I literally changed `install_requires=['aiorpcX >= 0.6.2', 'aiorpcX < 0.7.0', 'attrs>=15',` on line 15 in setup.py to `install_requires=['aiorpcX >= 0.6.2', 'aiorpcX <= 0.7.0', 'attrs>=15',` as quick and dirty fix to complete install.
I would of course be better to use `install_requires=['aiorpcX>=0.7,<0.8', 'attrs>=15',` as suggested by SomberNight above.

**Comment by kipper01** [comment]
@denpamusic worked like a charm!!

**Comment by kyuupichan** [comment]
@SomberNight thanks

**Comment by Talkless** [comment]
I just upgraded to 1.8.5 (with Python3.6 on Debian Stretch), and setup.py did not upgrade `aiorpc`:
```
RuntimeError: aiorpcX version 0.7.x required with x >= 3
```

```
# python3 ./setup.py install | fgrep aiorpc
zip_safe flag not set; analyzing archive contents...
Searching for aiorpcX==0.7.2
Best match: aiorpcX 0.7.2
Processing aiorpcX-0.7.2-py3.6.egg
aiorpcX 0.7.2 is already the active version in easy-install.pth
Using /opt/python3.6/lib/python3.6/site-packages/aiorpcX-0.7.2-py3.6.egg
```

**Comment by kyuupichan** [comment]
Yes, this was fixed in the last commit
