### ISSUE TITLE
Subscription status remains the same for very busy addresses

### ISSUE THREAD

**Issue by erasmospunk** [kyuupichan/electrumx#566]
While researching something for issue #348 I discovered this probably rare bug.

When an address contains too many transactions, the subscription status stops changing on newer transactions.

This threshold depends on the MAX_SEND env variable and in default installation is 10309 transactions. When setting the minimum MAX_SEND = 350000 the limit is 3608 transactions.

An easy way to try it is in regtest by mining to a single address with the `generatetoaddress` RPC call. Once the threshold is passed the `blockchain.*.subscribe` will return the same status hash.

The reason this happens is that session's `::address_status()` function needs the full address history to properly calculate the status while the `ChainState::get_history()` limits the number of history entries depending the MAX_SEND env var.

**Comment by kyuupichan** [comment]
Yeah; I think I consider this more an anti-DoS feature than a bug.  Imagine that address is Satoshi Dice's busy one....

With the new protocol suggested in #348 this wouldn't be an issue

**Comment by kyuupichan** [comment]
Yes I think returning an error is the right thing.  It might take out the clients though!

**Comment by kyuupichan** [comment]
But that's not a reason to avoid doing it; I'll aim to do it for the next release
