### ISSUE TITLE
Log is not verbose enough if server has been fully synced and is now behind

### ISSUE THREAD

**Issue by SuBPaR42** [kyuupichan/electrumx#58]
Once synced to tip the logging is effectively turned off to avoid filling the log with cache and mempool info that we are used to seeing when syncing from genesis.  So if the server falls a few hundred blocks behind it appears nothing is happening as the logging behavior has changed since it was synced in the past.

**Comment by lahlor** [comment]
Logging still works but only ~30-60 minutes each logline...it take soooo long since version > 0.8.0
