### ISSUE TITLE
TaskSet

### ISSUE THREAD

**Issue by shyrwall** [kyuupichan/electrumx#588]
Hi

I could be wrong but it looks like TaskSet was removed from aiorpcx in 0.6.0 but it's still used in electrumx which requires 0.7.3. 

Bug or am I doing it wrong? :)

Installing 0.5.9 and changing the requirement worked.

**Comment by kyuupichan** [comment]
No it hasn't been used in ElectrumX for a while; I suspect you have multiple versions of software installed and the wrong one is being picked up (ElectrumX and/or aiorpcX)
