### ISSUE TITLE
aiorpcx.curio.TaskGroupError: TaskGroupError(TypeError)

### ISSUE THREAD

**Issue by johnnysosa** [kyuupichan/electrumx#592]
After installing ElectrumX 1.8.5 (Ubuntu 16.04), without apparent inconvenience, I can not make it work

electrum@electrum:~$ sudo systemctl status electrumx.service
● electrumx.service - Electrumx
   Loaded: loaded (/lib/systemd/system/electrumx.service; enabled; vendor preset: enabled)
   Active: active (running) since mié 2018-09-05 10:36:38 -04; 1s ago
 Main PID: 1261 (python3)
    Tasks: 6
   Memory: 18.3M
      CPU: 275ms
   CGroup: /system.slice/electrumx.service
           └─1261 python3 /home/electrum/source/electrumx/electrumx_server

sep 05 10:36:38 electrum electrumx_server[1261]:     task.result()
sep 05 10:36:38 electrum electrumx_server[1261]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/util.py", line 118, in check_task
sep 05 10:36:38 electrum electrumx_server[1261]:     task.result()
sep 05 10:36:38 electrum electrumx_server[1261]:   File "/home/electrum/source/electrumx/electrumx/server/block_processor.py", line 659, in fetch_and
sep 05 10:36:38 electrum electrumx_server[1261]:     await group.spawn(self._process_prefetched_blocks())
sep 05 10:36:38 electrum electrumx_server[1261]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 267, in __aexit__
sep 05 10:36:38 electrum electrumx_server[1261]:     await self.join(wait=self._wait)
sep 05 10:36:38 electrum electrumx_server[1261]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 240, in join
sep 05 10:36:38 electrum electrumx_server[1261]:     raise TaskGroupError(bad_tasks)
sep 05 10:36:38 electrum electrumx_server[1261]: aiorpcx.curio.TaskGroupError: TaskGroupError(TypeError)

electrum@electrum:~$ electrumx_rpc getinfo
{
    "closing": 0,
    "daemon": "localhost:34958/",
    "daemon_height": 212933,
    "db_height": -1,
    "errors": 0,
    "groups": 1,
    "logged": 0,
    "paused": 0,
    "peers": {
        "bad": 0,
        "good": 0,
        "never": 0,
        "stale": 0,
        "total": 0
    },
    "pid": 1261,
    "requests": 0,
    "sessions": 1,
    "subs": 0,
    "txs_sent": 0,
    "uptime": "04m 09s",
    "version": "ElectrumX 1.8.5"
}

**Comment by kyuupichan** [comment]
How about logs?

**Comment by johnnysosa** [comment]
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:Controller:Python version: 3.7.0 (default, Aug  6 2018, 20:07:46)
Sep  5 12:49:08 electrum electrumx_server[1559]: [GCC 5.4.0 20160609]
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:Controller:software version: ElectrumX 1.8.5
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:Controller:aiorpcX version: 0.7.3
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:Controller:supported protocol versions: 1.1-1.4
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:Controller:event loop policy: None
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:Controller:reorg limit is 800 blocks
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:Daemon:daemon #1 at localhost:34958/ (current)
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:DB:switching current directory to /home/electrum/.electrumx/
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:DB:using leveldb for DB backend
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:DB:opened UTXO DB (for sync: True)
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:DB:DB version: 6
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:DB:coin: Lkrcoin
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:DB:network: mainnet
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:DB:height: -1
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:DB:tip: 0000000000000000000000000000000000000000000000000000000000000000
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:DB:tx count: 0
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:DB:flushing DB cache at 1,800 MB
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:DB:sync time so far: 00s
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:History:history DB version: 0
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:History:flush count: 0
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:SessionManager:RPC server listening on localhost:8000
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:Prefetcher:catching up to daemon height 213,092 (213,093 blocks behind)
Sep  5 12:49:08 electrum electrumx_server[1559]: ERROR:root:task crashed: <Task finished coro=<Prefetcher.main_loop() done, defined at /home/electrum/source/electrumx/electrumx/server/block_processor.py:48> exception=TypeError('fromhex() argument must be str, not dict')>
Sep  5 12:49:08 electrum electrumx_server[1559]: Traceback (most recent call last):
Sep  5 12:49:08 electrum electrumx_server[1559]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/util.py", line 118, in check_task
Sep  5 12:49:08 electrum electrumx_server[1559]:     task.result()
Sep  5 12:49:08 electrum electrumx_server[1559]:   File "/home/electrum/source/electrumx/electrumx/server/block_processor.py", line 55, in main_loop
Sep  5 12:49:08 electrum electrumx_server[1559]:     if not await self._prefetch_blocks():
Sep  5 12:49:08 electrum electrumx_server[1559]:   File "/home/electrum/source/electrumx/electrumx/server/block_processor.py", line 115, in _prefetch_blocks
Sep  5 12:49:08 electrum electrumx_server[1559]:     blocks = await daemon.raw_blocks(hex_hashes)
Sep  5 12:49:08 electrum electrumx_server[1559]:   File "/home/electrum/source/electrumx/electrumx/server/daemon.py", line 219, in raw_blocks
Sep  5 12:49:08 electrum electrumx_server[1559]:     return [hex_to_bytes(block) for block in blocks]
Sep  5 12:49:08 electrum electrumx_server[1559]:   File "/home/electrum/source/electrumx/electrumx/server/daemon.py", line 219, in <listcomp>
Sep  5 12:49:08 electrum electrumx_server[1559]:     return [hex_to_bytes(block) for block in blocks]
Sep  5 12:49:08 electrum electrumx_server[1559]: TypeError: fromhex() argument must be str, not dict
Sep  5 12:49:08 electrum electrumx_server[1559]: ERROR:TaskGroup:task crashed: <Task finished coro=<Prefetcher.main_loop() done, defined at /home/electrum/source/electrumx/electrumx/server/block_processor.py:48> exception=TypeError('fromhex() argument must be str, not dict')>
Sep  5 12:49:08 electrum electrumx_server[1559]: Traceback (most recent call last):
Sep  5 12:49:08 electrum electrumx_server[1559]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/util.py", line 118, in check_task
Sep  5 12:49:08 electrum electrumx_server[1559]:     task.result()
Sep  5 12:49:08 electrum electrumx_server[1559]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/util.py", line 118, in check_task
Sep  5 12:49:08 electrum electrumx_server[1559]:     task.result()
Sep  5 12:49:08 electrum electrumx_server[1559]:   File "/home/electrum/source/electrumx/electrumx/server/block_processor.py", line 55, in main_loop
Sep  5 12:49:08 electrum electrumx_server[1559]:     if not await self._prefetch_blocks():
Sep  5 12:49:08 electrum electrumx_server[1559]:   File "/home/electrum/source/electrumx/electrumx/server/block_processor.py", line 115, in _prefetch_blocks
Sep  5 12:49:08 electrum electrumx_server[1559]:     blocks = await daemon.raw_blocks(hex_hashes)
Sep  5 12:49:08 electrum electrumx_server[1559]:   File "/home/electrum/source/electrumx/electrumx/server/daemon.py", line 219, in raw_blocks
Sep  5 12:49:08 electrum electrumx_server[1559]:     return [hex_to_bytes(block) for block in blocks]
Sep  5 12:49:08 electrum electrumx_server[1559]:   File "/home/electrum/source/electrumx/electrumx/server/daemon.py", line 219, in <listcomp>
Sep  5 12:49:08 electrum electrumx_server[1559]:     return [hex_to_bytes(block) for block in blocks]
Sep  5 12:49:08 electrum electrumx_server[1559]: TypeError: fromhex() argument must be str, not dict
Sep  5 12:49:08 electrum electrumx_server[1559]: INFO:BlockProcessor:flushing to DB for a clean shutdown...
Sep  5 12:49:08 electrum electrumx_server[1559]: ERROR:root:task crashed: <Task finished coro=<BlockProcessor.fetch_and_process_blocks() done, defined at /home/electrum/source/electrumx/electrumx/server/block_processor.py:642> exception=TaskGroupError([<Task finished coro=<Prefetcher.main_loop() done, defined at /home/electrum/source/electrumx/electrumx/server/block_processor.py:48> exception=TypeError('fromhex() argument must be str, not dict')>])>
Sep  5 12:49:08 electrum electrumx_server[1559]: Traceback (most recent call last):
Sep  5 12:49:08 electrum electrumx_server[1559]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/util.py", line 118, in check_task
Sep  5 12:49:08 electrum electrumx_server[1559]:     task.result()
Sep  5 12:49:08 electrum electrumx_server[1559]:   File "/home/electrum/source/electrumx/electrumx/server/block_processor.py", line 659, in fetch_and_process_blocks
Sep  5 12:49:08 electrum electrumx_server[1559]:     await group.spawn(self._process_prefetched_blocks())
Sep  5 12:49:08 electrum electrumx_server[1559]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 267, in __aexit__
Sep  5 12:49:08 electrum electrumx_server[1559]:     await self.join(wait=self._wait)
Sep  5 12:49:08 electrum electrumx_server[1559]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 240, in join
Sep  5 12:49:08 electrum electrumx_server[1559]:     raise TaskGroupError(bad_tasks)
Sep  5 12:49:08 electrum electrumx_server[1559]: aiorpcx.curio.TaskGroupError: TaskGroupError(TypeError)
Sep  5 12:49:08 electrum electrumx_server[1559]: ERROR:TaskGroup:task crashed: <Task finished coro=<BlockProcessor.fetch_and_process_blocks() done, defined at /home/electrum/source/electrumx/electrumx/server/block_processor.py:642> exception=TaskGroupError([<Task finished coro=<Prefetcher.main_loop() done, defined at /home/electrum/source/electrumx/electrumx/server/block_processor.py:48> exception=TypeError('fromhex() argument must be str, not dict')>])>
Sep  5 12:49:08 electrum electrumx_server[1559]: Traceback (most recent call last):
Sep  5 12:49:08 electrum electrumx_server[1559]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/util.py", line 118, in check_task
Sep  5 12:49:08 electrum electrumx_server[1559]:     task.result()
Sep  5 12:49:08 electrum electrumx_server[1559]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/util.py", line 118, in check_task
Sep  5 12:49:08 electrum electrumx_server[1559]:     task.result()
Sep  5 12:49:08 electrum electrumx_server[1559]:   File "/home/electrum/source/electrumx/electrumx/server/block_processor.py", line 659, in fetch_and_process_blocks
Sep  5 12:49:08 electrum electrumx_server[1559]:     await group.spawn(self._process_prefetched_blocks())
Sep  5 12:49:08 electrum electrumx_server[1559]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 267, in __aexit__
Sep  5 12:49:08 electrum electrumx_server[1559]:     await self.join(wait=self._wait)
Sep  5 12:49:08 electrum electrumx_server[1559]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 240, in join
Sep  5 12:49:08 electrum electrumx_server[1559]:     raise TaskGroupError(bad_tasks)
Sep  5 12:49:08 electrum electrumx_server[1559]: aiorpcx.curio.TaskGroupError: TaskGroupError(TypeError)

**Comment by kyuupichan** [comment]
I don't see lkrcoin in my repo.  This is for bugs in released code, not your dev code
