### ISSUE TITLE
error while starting electrumx

### ISSUE THREAD

**Issue by partylana** [kyuupichan/electrumx#593]
`root@electrumx:~/.bitcoin# service electrumx status
* electrumx.service - Electrumx
   Loaded: loaded (/etc/systemd/system/electrumx.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2018-09-07 15:05:55 UTC; 8s ago
  Process: 8268 ExecStart=/usr/local/bin/electrumx_server (code=exited, status=1/FAILURE)
 Main PID: 8268 (code=exited, status=1/FAILURE)

Sep 07 15:05:55 sexy electrumx_server[8268]:   File "<frozen importlib._bootstrap_external>", line 1096, in _legacy_get_spec
Sep 07 15:05:55 sexy electrumx_server[8268]:   File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
Sep 07 15:05:55 sexy electrumx_server[8268]:   File "<frozen importlib._bootstrap_external>", line 533, in spec_from_file_location
Sep 07 15:05:55 sexy electrumx_server[8268]:   File "/usr/local/lib/python3.5/dist-packages/electrumX-1.8.5-py3.5.egg/electrumx/server/controller.py", line 88
Sep 07 15:05:55 sexy electrumx_server[8268]:     self.logger.info(f'software version: {electrumx.version}')
Sep 07 15:05:55 sexy electrumx_server[8268]:                                                             ^
Sep 07 15:05:55 sexy electrumx_server[8268]: SyntaxError: invalid syntax
Sep 07 15:05:55 sexy systemd[1]: electrumx.service: Main process exited, code=exited, status=1/FAILURE
Sep 07 15:05:55 sexy systemd[1]: electrumx.service: Unit entered failed state.
Sep 07 15:05:55 sexy systemd[1]: electrumx.service: Failed with result 'exit-code'.`

i need help.

**Comment by kyuupichan** [comment]
You need Python 3.6, as documented
