### ISSUE TITLE
add_peer error

### ISSUE THREAD

**Issue by partylana** [kyuupichan/electrumx#599]
Thank you,

I got the below error while adding my another peer.

`ERROR:PeerManager:[server-url.com:50002 SSL] marking bad: (not listed in own hosts list [])`

i created created sll cert by following the procedure at https://media.readthedocs.org/pdf/electrumx/latest/electrumx.pdf.

what might be the reason?

**Comment by kyuupichan** [comment]
server.features does not list your host name.  Probably you set REPORT_HOST wrong.
