### ISSUE TITLE
Question : How to run on TOR?

### ISSUE THREAD

**Issue by vinnyvoo** [kyuupichan/electrumx#607]
Question : How to host server on TOR?

i already got a tor website running but don't know how to host a electrumx server.
i didnt find anything at https://media.readthedocs.org/pdf/electrumx/latest/electrumx.pdf

Thanks :)

**Comment by kyuupichan** [comment]
Sorry this is for bug reports.  The docs tell you how to configure ElectrumX for Tor; you are expected to be able to do the rest.
