### ISSUE TITLE
How to use same electrumx db for two electrumx instances?

### ISSUE THREAD

**Issue by Andthorps** [kyuupichan/electrumx#612]
_**I'm running two instances of elecrum in the same machine. How to use  same electrumx db for two electrumx instances?**_

**Comment by kyuupichan** [comment]
Read the docs - the DB location and settings are controlled by environment variables.  You can run as many as you want without issue.

**Comment by kyuupichan** [comment]
Ah sorry, you can't have 2 share the DB.  LevelDB and RocksDB are for exclusive access to one process for writes.
