### ISSUE TITLE
Generating checkpoints.json for Electrum-client

### ISSUE THREAD

**Issue by samadsajanlal** [kyuupichan/electrumx#613]
What's the best way to generate a checkpoints.json file for a blockchain that can be used as checkpoint data for the latest Electrum client?

Electrumx works great for the coin, and since it has the entire chain synced it seemed appropriate to generate this file from the server. Is there any script or API that allows me to generate this?

Thanks

**Comment by kyuupichan** [comment]
What do you mean by checkpoint?

**Comment by kyuupichan** [comment]
I don't consider this in-scope.  You're free to write something of course; it should probably be part of the Electrum project as others like Electron Cash don't do checkpoints in the same way.

**Comment by laugh26** [comment]
how do you use get_checkpoint_array.py  @samadsajanlal @turcol

**Comment by turcol** [comment]
The way to use it @laugh26 is as follow, assuming the project/token name is CivX/civx (the electrum db is located in /db-civx)
# service electrumx-civx stop
# DB_DIRECTORY=/db-civx COIN=CivX python3.7 ./compact_history.py
# service electrumx-civx start
