### ISSUE TITLE
Level db not present on Electrum leveldb archival server foundry

### ISSUE THREAD

**Issue by vinnyvoo** [kyuupichan/electrumx#617]
Foundry location : https://foundry.electrum.org/
Level db not present @ https://foundry.electrum.org/leveldb-dump/?C=M;O=D . Please update.

**Comment by kyuupichan** [comment]
Where did you get the link from?  I don't believe they are maintained for ElectrumX, and there is no link in ElectrumX docs there.

**Comment by vinnyvoo** [comment]
i got that link from old electrum server docs. But the rocksdb links are working and not level db. **If you know any source to download the Leveldb please let me know.** Thank you.

**Comment by kyuupichan** [comment]
I don't.  I imagine whoever maintains it (I don't know who) uses rocksdb.  Why won't you use rocksdb?

**Comment by vinnyvoo** [comment]
i tried to compiled rocksdb on linux but after 30 mins the compilation fails every time. Are there any compiled rocks db or in debian apt or any good docs to install rocksdb. Thanks.
