### ISSUE TITLE
resume listening after "maximum sessions" drops

### ISSUE THREAD

**Issue by cipig** [kyuupichan/electrumx#621]
I got this error
`INFO:SessionManager:maximum sessions 1,000 reached, stopping new connections until count drops to 950`
and electrumx stopped listening to new connections, but after the count dropped to only a few, it didn't resume listening, even after several hours.

**Comment by kyuupichan** [comment]
I've added a log to state explicity that it's resuming, which might help.  I tested here with small session counts and it works fine.

2018-10-16 16:09:38.908745500 INFO:SessionManager:resuming listening for incoming connections
2018-10-16 16:09:38.909127500 INFO:SessionManager:TCP server listening on 192.168.0.9:50001
2018-10-16 16:09:38.909841500 INFO:SessionManager:SSL server listening on 192.168.0.9:50002

**Comment by cipig** [comment]
`netstat -ntlp` was my "evidence", and my monitoring stuff, no connections were possible on the port for hours, because electrumx was simply not listening on that port anymore. I have set my MAX_SESSIONS to 5000 for that coin
