### ISSUE TITLE
Invalid JSON Response

### ISSUE THREAD

**Issue by x-yggdrasil-x** [kyuupichan/electrumx#623]
Hello, I am trying to test out ElectrumX but am getting this response:
```
curl -d '{"method":"server.version", "params":[], "id":0}' -H "Content-Type: application/json" -X POST localhost:3000
{"jsonrpc": "2.0", "error": {"code": -32700, "message": "invalid JSON"}, "id": null}
```

However, the RPC command seems to run fine:
```
electrumx_rpc -p 8000 getinfo
...
{
    "closing": 0,
    "daemon": "localhost:22101/",
    "daemon_height": 26081,
    "db_height": 26081,
    "errors": 0,
    "groups": 1,
    "logged": 0,
    "paused": 0,
    "peers": {
        "bad": 0,
        "good": 0,
        "never": 0,
        "stale": 0,
        "total": 0
    },
    "pid": 12233,
    "requests": 0,
    "sessions": 1,
    "subs": 0,
    "txs_sent": 0,
    "uptime": "11s",
    "version": "ElectrumX 1.8.7"
}
```

Not sure where in the codebase I can add a debug statement to see what the JSON request comes in looking like, but I tested it locally with a simple NodeJS/Express server and the request object appears as:
```
POST /test 200 0.576 ms - 15
incoming
{ method: 'server.version', params: [], id: 0 }
```

Any help or information here would be great. I've looked through Readthedocs but I don't see any information about formatting a request (unless I misread it somewhere else).

Thanks!

**Comment by kyuupichan** [comment]
It is not an HTTP server; it is just a raw TCP socket.  So use nc or telnet or similar

**Comment by x-yggdrasil-x** [comment]
@kyuupichan Thanks for the clarification!
