### ISSUE TITLE
Question about "BANDWIDTH_LIMIT".

### ISSUE THREAD

**Issue by vinnyvoo** [kyuupichan/electrumx#625]
Document : https://media.readthedocs.org/pdf/electrumx/latest/electrumx.pdf

According to my understanding from above document the `BANDWIDTH_LIMIT` is only 2MB/hour/session. Am i right? If so i think its too small.

**Comment by kyuupichan** [comment]
https://electrumx.readthedocs.io/en/latest/environment.html#envvar-BANDWIDTH_LIMIT

If you read it, it is when the session starts to be deprioritised.  It can still use a lot more than the bandwidth limit.

And, if it's too small, you change it.  That's why it's a setting.

**Comment by vinnyvoo** [comment]
Cool. Thank you.
