### ISSUE TITLE
Tons of high bandwidth use warnings, errors and finally crash

### ISSUE THREAD

**Issue by santzi** [kyuupichan/electrumx#63]
Used version 0.8.6
I have increased file descriptors amount to quite high.
ele@ubuntu:~$ ulimit -Hn; ulimit -Sn; sudo sysctl fs.file-max
500000
300000
fs.file-max = 700000

But I still getting this kind of errors:

Dec  7 23:07:23 ubuntu electrumx_server.py[16158]: ERROR:asyncio:socket.accept() out of system resource
Dec  7 23:07:23 ubuntu electrumx_server.py[16158]: socket: <socket.socket fd=17, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('192.168.1.41', 50$
Dec  7 23:07:23 ubuntu electrumx_server.py[16158]: Traceback (most recent call last):
Dec  7 23:07:23 ubuntu electrumx_server.py[16158]:   File "/usr/lib/python3.5/asyncio/selector_events.py", line 161, in _accept_connection
Dec  7 23:07:23 ubuntu electrumx_server.py[16158]:   File "/usr/lib/python3.5/socket.py", line 195, in accept
Dec  7 23:07:23 ubuntu electrumx_server.py[16158]: OSError: [Errno 24] Too many open files

Before these errors, there were tons of warnings about "high bandwidth use" from different connections (>10) , and there are also this kind of errors
"Dec  8 00:18:23 ubuntu electrumx_server.py[16158]: TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
Dec  8 00:18:23 ubuntu electrumx_server.py[16158]: ERROR:asyncio:Task was destroyed but it is pending!
Dec  8 00:18:23 ubuntu electrumx_server.py[16158]: task: <Task pending coro=<Session.serve_requests() running at /usr/local/lib/python3.5/dist-packages/elec$
Dec  8 00:18:23 ubuntu electrumx_server.py[16158]: ERROR:asyncio:Task was destroyed but it is pending!
Dec  8 00:18:23 ubuntu electrumx_server.py[16158]: task: <Task pending coro=<Session.serve_requests() running at /usr/local/lib/python3.5/dist-packages/elec$
Dec  8 00:18:23 ubuntu electrumx_server.py[16158]: ERROR:asyncio:Task was destroyed but it is pending!
Dec  8 00:18:23 ubuntu electrumx_server.py[16158]: task: <Task pending coro=<Session.serve_requests() running at /usr/local/lib/python3.5/dist-packages/elec$
Dec  8 00:18:23 ubuntu electrumx_server.py[16158]: ERROR:asyncio:Task was destroyed but it is pending!"

And finally Electrumx crashed.
Here is short log about this issue:
http://www.filedropper.com/last11klinesltcwarnerrorcrash
I cutted first 15MB "high bandwidth use" warnings away :)
I could upload whole big log, if you needed.

I have also got this "Too many open files" errors with older Electrumx versions, I don't get it, why this occurred..file descriptors should be enough.
I also checked earlier how many file descriptors electrumx process uses, and it was below 2000.

**Comment by bauerj** [comment]
Do you use systemd? If so, you need to set the open file limit there.

**Comment by SuBPaR42** [comment]
https://www.freedesktop.org/software/systemd/man/systemd.exec.html

Scroll down to table 1 for the setting (LimitNOFILE).  That should go in your electrumx.service file.

**Comment by kyuupichan** [comment]
You're setting the limits in your shell, which affects that shell and child processes.

However your shell is not the parent of the server process, systemd is, so you need to tell systemd what settings to pass on to the server process.

See for example:

https://github.com/kyuupichan/electrumx/pull/64

**Comment by santzi** [comment]
Thank you. I added the LimitNOFILE line to the systemd. Let's see.

**Comment by bauerj** [comment]
You might need to reload the daemon and restart the service

    systemctl daemon-reload
    service electrumx restart
