### ISSUE TITLE
Main process exited, code=exited, status=217/USER

### ISSUE THREAD

**Issue by undead93** [kyuupichan/electrumx#642]
/etc/electrumx.conf
--------------------

DAEMON_URL = http://btcf:btcf1@localhost:5555/
DB_DIRECTORY = /root/electrumx
DB_ENGINE = leveldb
USERNAME = root
ELECTRUMX =  /root/electrumx/electrumx_server
HOST = 127.0.0.1

ANON_LOGS = fuck off :)
BANNER_FILE = /root/.electrumx/banner.txt
DONATION_ADDRESS = 34ie35p4G1npt6GoXR9BDhmMndNwCsiiEr

CACHE_MB = 1800
MAX_SESSIONS = 500

SSL_CERTFILE = /root/.electrumx/server.crt
SSL_KEYFILE = /root/.electrumx/server.key

SSL_PORT = 50002
TCP_PORT = 50001

/lib/systemd/system/electrumx.service
--------------------------------------

[Unit]
Description=Electrumx
After=network.target

[Service]
EnvironmentFile=/etc/electrumx.conf
ExecStart=/root/electrumx/electrumx_server
User=root
LimitNOFILE=8192
TimeoutStopSec=30min

[Install]
WantedBy=multi-user.target

but i get error for starting systemd
-------------------------------------
root@ubuntu:~# service electrumx status
● electrumx.service - Electrumx
   Loaded: loaded (/etc/systemd/system/electrumx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2018-11-11 10:47:54 UTC; 4s ago
  Process: 4134 ExecStart=/root/electrumx/electrumx_server (code=exited, status=217/USER)
 Main PID: 4134 (code=exited, status=217/USER)

**Comment by kyuupichan** [comment]
I don't know what the issue is but I don't think it's ElectrumX.  I'm not familiar with systemd.
