### ISSUE TITLE
check please..have error

### ISSUE THREAD

**Issue by undead93** [kyuupichan/electrumx#643]
https://github.com/bitcoinfinal/BitcoinFinal/blob/master/src/chainparams.cpp

class BitcoinFinal(Coin):
    NAME = "BitcoinFinal"
    SHORTNAME = "BTCF"
    NET = "mainnet"
    XPUB_VERBYTES = bytes.fromhex("043587CF")
    XPRV_VERBYTES = bytes.fromhex("04358394")
    P2PKH_VERBYTE = bytes.fromhex("19")
    P2SH_VERBYTES = [bytes.fromhex("85")]
    WIF_BYTE = bytes.fromhex("99")
    GENESIS_HASH = ('00009ea6784c84c13c4a0647da103b29'
                    '6a6cb6c8d386dfbd003062d53a60494a')
    TX_COUNT = 330000
    TX_COUNT_HEIGHT = 149158
    TX_PER_BLOCK = 2
    RPC_PORT = 20501

error
------

Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:Controller:Python version: 3.7.1 (default, Oct 20 2018, 21:59:34)
Nov 13 02:36:32 ubuntu electrumx_server[5123]: [GCC 5.4.0 20160609]
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:Controller:software version: ElectrumX 1.8.12
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:Controller:aiorpcX version: 0.10.1
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:Controller:supported protocol versions: 1.2-1.4
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:Controller:event loop policy: None
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:Controller:reorg limit is 200 blocks
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:Daemon:daemon #1 at localhost:20501/ (current)
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:DB:switching current directory to /electrumx-db
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:DB:using leveldb for DB backend
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:DB:created new database
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:DB:creating metadata directory
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:DB:DB version: 6
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:DB:coin: BitcoinFinal
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:DB:network: mainnet
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:DB:height: -1
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:DB:tip: 0000000000000000000000000000000000000000000000000000000000000000
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:DB:tx count: 0
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:DB:flushing DB cache at 1,200 MB
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:DB:sync time so far: 00s
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:History:history DB version: 0
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:History:flush count: 0
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:SessionManager:RPC server listening on localhost:8000
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:Prefetcher:catching up to daemon height 149,164 (149,165 blocks behind)
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:BlockProcessor:flushing to DB for a clean shutdown...
Nov 13 02:36:32 ubuntu electrumx_server[5123]: INFO:SessionManager:closing down RPC listening servers
Nov 13 02:36:32 ubuntu electrumx_server[5123]: ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /usr/local/lib/python3.7/dist-packages/electrumx/server/controller.py:81> exception=TypeError('fromhex() argument must be str, not dict')>
Nov 13 02:36:32 ubuntu electrumx_server[5123]: Traceback (most recent call last):
Nov 13 02:36:32 ubuntu electrumx_server[5123]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/util.py", line 118, in check_task
Nov 13 02:36:32 ubuntu electrumx_server[5123]:     task.result()
Nov 13 02:36:32 ubuntu electrumx_server[5123]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/controller.py", line 131, in serve
Nov 13 02:36:32 ubuntu electrumx_server[5123]:     await group.spawn(wait_for_catchup())
Nov 13 02:36:32 ubuntu electrumx_server[5123]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 242, in __aexit__
Nov 13 02:36:32 ubuntu electrumx_server[5123]:     await self.join(wait=self._wait)
Nov 13 02:36:32 ubuntu electrumx_server[5123]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 213, in join
Nov 13 02:36:32 ubuntu electrumx_server[5123]:     raise task.exception()
Nov 13 02:36:32 ubuntu electrumx_server[5123]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 658, in fetch_and_process_blocks
Nov 13 02:36:32 ubuntu electrumx_server[5123]:     await group.spawn(self._process_prefetched_blocks())
Nov 13 02:36:32 ubuntu electrumx_server[5123]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 242, in __aexit__
Nov 13 02:36:32 ubuntu electrumx_server[5123]:     await self.join(wait=self._wait)
Nov 13 02:36:32 ubuntu electrumx_server[5123]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 213, in join
Nov 13 02:36:32 ubuntu electrumx_server[5123]:     raise task.exception()
Nov 13 02:36:32 ubuntu electrumx_server[5123]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 56, in main_loop
Nov 13 02:36:32 ubuntu electrumx_server[5123]:     if not await self._prefetch_blocks():
Nov 13 02:36:32 ubuntu electrumx_server[5123]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 116, in _prefetch_blocks
Nov 13 02:36:32 ubuntu electrumx_server[5123]:     blocks = await daemon.raw_blocks(hex_hashes)
Nov 13 02:36:32 ubuntu electrumx_server[5123]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/daemon.py", line 222, in raw_blocks
Nov 13 02:36:32 ubuntu electrumx_server[5123]:     return [hex_to_bytes(block) for block in blocks]
Nov 13 02:36:32 ubuntu electrumx_server[5123]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/daemon.py", line 222, in <listcomp>
Nov 13 02:36:32 ubuntu electrumx_server[5123]:     return [hex_to_bytes(block) for block in blocks]
Nov 13 02:36:32 ubuntu electrumx_server[5123]: TypeError: fromhex() argument must be str, not dict
Nov 13 02:41:22 ubuntu systemd[1]: Started Session 9 of user root.

**Comment by kyuupichan** [comment]
Looks like your daemon is not compatible with recent bitcoin RPCs.  You may find one of the workarounds in daemon.py works.  This is not an ElectrumX issue.
