### ISSUE TITLE
Crash after Bitcoin Cash upgrade on Nov 15th

### ISSUE THREAD

**Issue by DaSpawn** [kyuupichan/electrumx#645]
My node is crashing at startup after network upgrade: 

```
ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /usr/local/lib/python3.7/dist-packages/electrumX-1.8.12-py3.7.egg/electrumx/server/controller.py:81> exception=AssertionError()>
Nov 15 18:10:48 bitcoin electrumx_server[6044]: Traceback (most recent call last):
Nov 15 18:10:48 bitcoin electrumx_server[6044]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.10.1-py3.7.egg/aiorpcx/util.py", line 118, in check_task
Nov 15 18:10:48 bitcoin electrumx_server[6044]:     task.result()
Nov 15 18:10:48 bitcoin electrumx_server[6044]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.8.12-py3.7.egg/electrumx/server/controller.py", line 131, in serve
Nov 15 18:10:48 bitcoin electrumx_server[6044]:     await group.spawn(wait_for_catchup())
Nov 15 18:10:48 bitcoin electrumx_server[6044]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.10.1-py3.7.egg/aiorpcx/curio.py", line 242, in __aexit__
Nov 15 18:10:48 bitcoin electrumx_server[6044]:     await self.join(wait=self._wait)
Nov 15 18:10:48 bitcoin electrumx_server[6044]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.10.1-py3.7.egg/aiorpcx/curio.py", line 213, in join
Nov 15 18:10:48 bitcoin electrumx_server[6044]:     raise task.exception()
Nov 15 18:10:48 bitcoin electrumx_server[6044]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.8.12-py3.7.egg/electrumx/server/block_processor.py", line 662, in fetch_and_process_blocks
Nov 15 18:10:48 bitcoin electrumx_server[6044]:     await self.flush(True)
Nov 15 18:10:48 bitcoin electrumx_server[6044]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.8.12-py3.7.egg/electrumx/server/block_processor.py", line 335, in flush
Nov 15 18:10:48 bitcoin electrumx_server[6044]:     await self.run_in_thread_with_lock(flush)
Nov 15 18:10:48 bitcoin electrumx_server[6044]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.8.12-py3.7.egg/electrumx/server/block_processor.py", line 191, in run_in_thread_with_lock
Nov 15 18:10:48 bitcoin electrumx_server[6044]:     return await asyncio.shield(run_in_thread_locked())
Nov 15 18:10:48 bitcoin electrumx_server[6044]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.8.12-py3.7.egg/electrumx/server/block_processor.py", line 190, in run_in_thread_locked
Nov 15 18:10:48 bitcoin electrumx_server[6044]:     return await run_in_thread(func, *args)
Nov 15 18:10:48 bitcoin electrumx_server[6044]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.10.1-py3.7.egg/aiorpcx/curio.py", line 61, in run_in_thread
Nov 15 18:10:48 bitcoin electrumx_server[6044]:     return await get_event_loop().run_in_executor(None, func, *args)
Nov 15 18:10:48 bitcoin electrumx_server[6044]:   File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Nov 15 18:10:48 bitcoin electrumx_server[6044]:     result = self.fn(*self.args, **self.kwargs)
Nov 15 18:10:48 bitcoin electrumx_server[6044]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.8.12-py3.7.egg/electrumx/server/block_processor.py", line 334, in flush
Nov 15 18:10:48 bitcoin electrumx_server[6044]:     self.estimate_txs_remaining)
Nov 15 18:10:48 bitcoin electrumx_server[6044]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.8.12-py3.7.egg/electrumx/server/db.py", line 189, in flush_dbs
Nov 15 18:10:48 bitcoin electrumx_server[6044]:     self.assert_flushed(flush_data)
Nov 15 18:10:48 bitcoin electrumx_server[6044]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.8.12-py3.7.egg/electrumx/server/db.py", line 179, in assert_flushed
Nov 15 18:10:48 bitcoin electrumx_server[6044]:     assert not flush_data.block_tx_hashes
Nov 15 18:10:48 bitcoin electrumx_server[6044]: AssertionError

```

**Comment by fireduck64** [comment]
I think I am getting the same thing:

INFO:DB:using rocksdb for DB backend
INFO:DB:opened UTXO DB (for sync: True)
INFO:DB:DB version: 6
INFO:DB:coin: BitcoinCash
INFO:DB:network: mainnet
INFO:DB:height: 556,766
INFO:DB:tip: 00000000000000000102d94fde9bd0807a2cc7582fe85dd6349b73ce4e8d9322
INFO:DB:tx count: 265,546,702
INFO:DB:flushing DB cache at 1,200 MB
INFO:History:history DB version: 0
INFO:History:flush count: 15,271
INFO:SessionManager:RPC server listening on localhost:8000
INFO:Prefetcher:catching up to daemon height 556,770 (4 blocks behind)
INFO:BlockProcessor:flushing to DB for a clean shutdown...
INFO:SessionManager:closing down RPC listening servers
ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /home/nerd/electrumx.git/electrumx/server/controller.py:81> exception=AssertionError()>
Traceback (most recent call last):
  File "/home/nerd/.local/lib/python3.6/site-packages/aiorpcX-0.10.1-py3.6.egg/aiorpcx/util.py", line 118, in check_task
    task.result()
  File "/home/nerd/electrumx.git/electrumx/server/controller.py", line 131, in serve
    await group.spawn(wait_for_catchup())
  File "/home/nerd/.local/lib/python3.6/site-packages/aiorpcX-0.10.1-py3.6.egg/aiorpcx/curio.py", line 242, in __aexit__
    await self.join(wait=self._wait)
  File "/home/nerd/.local/lib/python3.6/site-packages/aiorpcX-0.10.1-py3.6.egg/aiorpcx/curio.py", line 213, in join
    raise task.exception()
  File "/home/nerd/electrumx.git/electrumx/server/block_processor.py", line 662, in fetch_and_process_blocks
    await self.flush(True)
  File "/home/nerd/electrumx.git/electrumx/server/block_processor.py", line 335, in flush
    await self.run_in_thread_with_lock(flush)
  File "/home/nerd/electrumx.git/electrumx/server/block_processor.py", line 191, in run_in_thread_with_lock
    return await asyncio.shield(run_in_thread_locked())
  File "/home/nerd/electrumx.git/electrumx/server/block_processor.py", line 190, in run_in_thread_locked
    return await run_in_thread(func, *args)
  File "/home/nerd/.local/lib/python3.6/site-packages/aiorpcX-0.10.1-py3.6.egg/aiorpcx/curio.py", line 61, in run_in_thread
    return await get_event_loop().run_in_executor(None, func, *args)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/nerd/electrumx.git/electrumx/server/block_processor.py", line 334, in flush
    self.estimate_txs_remaining)
  File "/home/nerd/electrumx.git/electrumx/server/db.py", line 189, in flush_dbs
    self.assert_flushed(flush_data)
  File "/home/nerd/electrumx.git/electrumx/server/db.py", line 179, in assert_flushed
    assert not flush_data.block_tx_hashes
AssertionError

**Comment by shsmith** [comment]
According to Neil, ElectrumX for BCH supports only bitcoin-SV, not bitcoin-ABC.

From https://github.com/kyuupichan/electrumx/blob/master/docs/changelog.rst:

> Bitcoin ABC developers have hastily introduced controversial changes that break ElectrumX's block processing by requiring it to be non-sequential. Unlike others with unique requirements they refused to make their code coin-specific. ElectrumX continues to require blocks be naturally ordered, and is compatible with any non-CToR daemon, such as Bitcoin SV, and Bitcoin Unlimited / Bitcoin XT with CToR disabled.

**Comment by shsmith** [comment]
If you want to run ABC you'll need to run ElectronX which is under the Electron-Cash project on github

**Comment by HostFat** [comment]
https://github.com/Electron-Cash/electrumx
