### ISSUE TITLE
BCH testnet servers

### ISSUE THREAD

**Issue by markblundeberg** [kyuupichan/electrumx#652]
Looks like testnet servers will have to be figured out too. I'm not quite sure what the correct form of inclusion is here, so I'll put this as an issue rather than PR.

Currently I know of the following on BU/ABC post-fork chain:

* bch0.kister.net ssl 51002
* testnet.imaginary.cash ssl 50002
* blackie.c3-soft.com ssl 60002

This one is on ABC 0.17 chain:

* electrum-testnet-abc.criptolayer.net ssl 50112

Not sure if there are any on SV chain, but I suppose peer discovery would not show them?

**Comment by kyuupichan** [comment]
I'm going to close this if there's no PR forthcoming

**Comment by markblundeberg** [comment]
Thanks for reminding me!
