### ISSUE TITLE
Can't remote connect to Electrumx in docker

### ISSUE THREAD

**Issue by AlexVN74** [kyuupichan/electrumx#654]
I'm using Electrum to connect to my local Electrumx server in docker container.
When using 1.8.12 where are no records in log file, but version 1.7 shows an error in log for each connect(certificate error SSL: TLSV1_ALERT_UNKNOWN_CA like #521 ). 
Only way to connect is using ssh tunnel to server to emulate local connection but it's inconvenient for me.

Electrumx Config:
ENV HOME /data
ENV ALLOW_ROOT 1
ENV DB_DIRECTORY /data
ENV TCP_PORT=50001
ENV SSL_PORT=50002
ENV SSL_CERTFILE ${DB_DIRECTORY}/electrumx.crt
ENV SSL_KEYFILE ${DB_DIRECTORY}/electrumx.key
ENV HOST ""
ENV RPC_HOST=127.0.0.1

Docker container port 50002 is open.

**Comment by kyuupichan** [comment]
Sorry but this is not docker support; I doubt your problem is in ElectrumX
