### ISSUE TITLE
Electrumx crashes after formerly crashed bitcoind is responsible again

### ISSUE THREAD

**Issue by freerko** [kyuupichan/electrumx#656]
Hi, running ElectrumX 1.8.12 with Satoshi:0.16.3/Knots:20180730 with Segwit. Bitcoind crashed, I restarted it and as soon as bitcoind catched up its blocks ElectrumX crashes. electrumx_rpc is not longer able to connect but the process is still running, so I had to kill it manually.

> Nov 25 09:47:39 hostname electrumx_server[845]: ERROR:Daemon:connection problem - is your daemon running?  Retrying occasionally...
Nov 25 09:48:39 hostname electrumx_server[845]: ERROR:Daemon:connection problem - is your daemon running?  Retrying occasionally...
Nov 25 09:49:40 hostname electrumx_server[845]: ERROR:Daemon:connection problem - is your daemon running?  Retrying occasionally...
Nov 25 09:50:40 hostname electrumx_server[845]: ERROR:Daemon:connection problem - is your daemon running?  Retrying occasionally...
Nov 25 09:51:40 hostname electrumx_server[845]: ERROR:Daemon:connection problem - is your daemon running?  Retrying occasionally...
Nov 25 09:52:40 hostname electrumx_server[845]: ERROR:Daemon:connection problem - is your daemon running?  Retrying occasionally...
Nov 25 09:53:40 hostname electrumx_server[845]: ERROR:Daemon:connection problem - is your daemon running?  Retrying occasionally...
Nov 25 09:54:40 hostname electrumx_server[845]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Nov 25 09:55:40 hostname electrumx_server[845]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Nov 25 09:56:40 hostname electrumx_server[845]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Nov 25 09:57:41 hostname electrumx_server[845]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Nov 25 09:58:41 hostname electrumx_server[845]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Nov 25 10:02:29 hostname electrumx_server[845]: INFO:Daemon:running normally
Nov 25 10:02:34 hostname electrumx_server[845]: INFO:DB:opened UTXO DB (for sync: True)
Nov 25 10:02:34 hostname electrumx_server[845]: INFO:DB:DB version: 6
Nov 25 10:02:34 hostname electrumx_server[845]: INFO:DB:coin: BitcoinSegwit
Nov 25 10:02:34 hostname electrumx_server[845]: INFO:DB:network: mainnet
Nov 25 10:02:34 hostname electrumx_server[845]: INFO:DB:height: 551,338
Nov 25 10:02:34 hostname electrumx_server[845]: INFO:DB:tip: 0000000000000000000ac9d57b36ed27213b870442ba418f3bdb5522901914b3
Nov 25 10:02:34 hostname electrumx_server[845]: INFO:DB:tx count: 359,433,236
Nov 25 10:02:34 hostname electrumx_server[845]: INFO:DB:flushing DB cache at 1,200 MB
Nov 25 10:02:38 hostname electrumx_server[845]: INFO:History:history DB version: 0
Nov 25 10:02:38 hostname electrumx_server[845]: INFO:History:flush count: 7,106
Nov 25 10:03:12 hostname electrumx_server[845]: INFO:DB:deleted 450 stale undo entries
Nov 25 10:03:19 hostname electrumx_server[845]: INFO:SessionManager:RPC server listening on localhost:8000
Nov 25 10:03:44 hostname electrumx_server[845]: INFO:Prefetcher:caught up to daemon height 551,244
Nov 25 10:03:44 hostname electrumx_server[845]: INFO:BlockProcessor:flushing to DB for a clean shutdown...
Nov 25 10:03:44 hostname electrumx_server[845]: INFO:SessionManager:closing down RPC listening servers
Nov 25 10:03:44 hostname electrumx_server[845]: ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /usr/local/lib/python3.7/dist-pa
Nov 25 10:03:44 hostname electrumx_server[845]: Traceback (most recent call last):
Nov 25 10:03:44 hostname electrumx_server[845]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/util.py", line 118, in check_task
Nov 25 10:03:44 hostname electrumx_server[845]:     task.result()
Nov 25 10:03:44 hostname electrumx_server[845]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.8.12-py3.7.egg/electrumx/server/controller.py", line 13
Nov 25 10:03:44 hostname electrumx_server[845]:     await group.spawn(wait_for_catchup())
Nov 25 10:03:44 hostname electrumx_server[845]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 242, in __aexit__
Nov 25 10:03:44 hostname electrumx_server[845]:     await self.join(wait=self._wait)
Nov 25 10:03:44 hostname electrumx_server[845]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 213, in join
Nov 25 10:03:44 hostname electrumx_server[845]:     raise task.exception()
Nov 25 10:03:44 hostname electrumx_server[845]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.8.12-py3.7.egg/electrumx/server/block_processor.py", li
Nov 25 10:03:44 hostname electrumx_server[845]:     await group.spawn(self._process_prefetched_blocks())
Nov 25 10:03:44 hostname electrumx_server[845]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 242, in __aexit__
Nov 25 10:03:44 hostname electrumx_server[845]:     await self.join(wait=self._wait)
Nov 25 10:03:44 hostname electrumx_server[845]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 213, in join
Nov 25 10:03:44 hostname electrumx_server[845]:     raise task.exception()
Nov 25 10:03:44 hostname electrumx_server[845]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.8.12-py3.7.egg/electrumx/server/block_processor.py", li
Nov 25 10:03:44 hostname electrumx_server[845]:     if not await self._prefetch_blocks():
Nov 25 10:03:44 hostname electrumx_server[845]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.8.12-py3.7.egg/electrumx/server/block_processor.py", li
Nov 25 10:03:44 hostname electrumx_server[845]:     assert count == len(blocks)
Nov 25 10:03:44 hostname electrumx_server[845]: AssertionError

**Comment by SomberNight** [comment]
Looks similar to https://github.com/kyuupichan/electrumx/issues/653
Try git HEAD?

**Comment by kyuupichan** [comment]
Did git HEAD work?

**Comment by freerko** [comment]
Sorry for not replying earlier.
I updated to HEAD and at the same time increased `rpcworkqueue` on my bitcoind which made it stop crashing, so I can not say for sure if c3039db50c772dd48a540d1450b5ee858473b7aa fixed it or not. Will open a new issue if it happens again :)
