### ISSUE TITLE
WARNING:asyncio:socket.send() raised exception

### ISSUE THREAD

**Issue by SuBPaR42** [kyuupichan/electrumx#66]
Something new in 0.8.7 - seeing on both rigs...

Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.
Dec 09 01:41:14 electrumx_server.py[26202]: WARNING:asyncio:socket.send() raised exception.

**Comment by kyuupichan** [comment]
These can be safely ignored

**Comment by SuBPaR42** [comment]
Understood - it was something not seen prior to 0.8.7 was the main point.  I am also seeing 50-75 connections (sessions) lost when this happens - though not every time...

**Comment by kyuupichan** [comment]
OK thanks.  Keep an eye on it.  They might be stale, or attempts at DoS.  No idea of the underlying cause to be honest.  I've seen a few recently.  But they did occur before too.  They're sufficiently infrequent it's hard to know if it's just chance or not.  Kinda like inter-block waiting time :)
