### ISSUE TITLE
Truncate AuxPoW for headers that are covered by a checkpoint

### ISSUE THREAD

**Issue by JeremyRand** [kyuupichan/electrumx#667]
AuxPoW data isn't relevant for headers covered by a checkpoint, since the AuxPoW data isn't needed to compute the block header hash, nor is it needed to verify that the checkpoint commits to the block header.  (I'm assuming that our threat model excludes the possibility of the checkpoint committing to invalid blocks.)  Given this, we could save a lot of bandwidth by truncating AuxPoW data for headers that are covered by a checkpoint (i.e. for headers whose height is less than or equal to `cp_height` in `blockchain.block.header` and `blockchain.block.headers`).  In Namecoin's case, that means truncating everything after the first 80 bytes of each header; I'm not certain whether other AuxPoW coins have a different definition (though I suspect it's likely that some do).

Would a PR be accepted that truncates the AuxPoW data for headers that are covered by a checkpoint?  (The Namecoin devs would probably be willing to code up such a PR if no one else does it first.)

**Comment by JeremyRand** [comment]
CC'ing @erasmospunk since he NACKed a superficially similar change in https://github.com/kyuupichan/electrumx/pull/457#discussion_r185293088 and I don't want to appear to step on any toes.

**Comment by kyuupichan** [comment]
This sounds like an API change?  Or am I misunderstanding?  The server has no checkpoints; they are all client-side.

**Comment by JeremyRand** [comment]
> This sounds like an API change? Or am I misunderstanding? The server has no checkpoints; they are all client-side.

@kyuupichan my issue said "for headers whose height is less than or equal to `cp_height` in `blockchain.block.header` and `blockchain.block.headers`"; that's how I'm defining headers that are covered by a checkpoint.  Sorry if that was unclear.

**Comment by kyuupichan** [comment]
Oh I see, so it would change the nature of the returned value.  Got it.  That would probably need a protocol version bump

**Comment by JeremyRand** [comment]
> That would probably need a protocol version bump

Agreed.  I'm actually not familiar with what's involved in doing a protocol version bump, as I've never submitted one to ElectrumX before... anything notable about what's involved there?

**Comment by kyuupichan** [comment]
Just to update the docs to describe the changes and the three places in the code that refer to the version (setup.py, __init__.py and docs/make.conf).  Since this is a minor change I think it should be 1.4.1 rather than 1.5

**Comment by JeremyRand** [comment]
As discussed over on #namecoin-dev, @ahmedbodi is possibly interested in implementing this.

**Comment by JeremyRand** [comment]
> Since this is a minor change I think it should be 1.4.1 rather than 1.5

@kyuupichan Just to make sure I understand correctly, is version 1.4.1 equivalent to the protocol_tuple `(1, 4, 1)`?

I've got this about 90% implemented now, just need to update the docs and change the three files you mentioned.

**Comment by JeremyRand** [comment]
Actually I'm not even seeing a reference to protocol versions in any of those 3 files.  The only protocol version I've noticed is in `session.py`, where I'm changing the value of `PROTOCOL_MAX`.  AFAICT this is working fine in my testing; am I missing something?

**Comment by kyuupichan** [comment]
Nope, you got it.  I recently bumped the min version to 1.4 and that got rid of a lot of coniditionality.
