### ISSUE TITLE
Assertion error Crashing even after upgrading

### ISSUE THREAD

**Issue by Nagaws** [kyuupichan/electrumx#675]
Electrum Server crashes every time with Incomplete info . Please help me to troubleshoot

Observed DB heaight and daemon height has 4000 blocks difference

komodo asset coin

Dec 21 00:43:34 vps592883 electrumx_server[9836]: INFO:DB:network: mainnet
Dec 21 00:43:34 vps592883 electrumx_server[9836]: INFO:DB:height: 124,089
Dec 21 00:43:34 vps592883 electrumx_server[9836]: INFO:DB:tip: 061ce8d5cf5c1d584927bdde3927ec0bc77c4b981f5f55f565abeda898ea2e5c
Dec 21 00:43:34 vps592883 electrumx_server[9836]: INFO:DB:tx count: 157,197
Dec 21 00:43:34 vps592883 electrumx_server[9836]: INFO:DB:flushing DB cache at 1,200 MB
Dec 21 00:43:34 vps592883 electrumx_server[9836]: INFO:History:history DB version: 0
Dec 21 00:43:34 vps592883 electrumx_server[9836]: INFO:History:flush count: 6
Dec 21 00:43:34 vps592883 electrumx_server[9836]: INFO:SessionManager:RPC server listening on 127.0.0.1:13112
Dec 21 00:43:34 vps592883 electrumx_server[9836]: INFO:Prefetcher:catching up to daemon height 128,108 (4,019 blocks behind)
Dec 21 00:43:34 vps592883 electrumx_server[9836]: INFO:BlockProcessor:flushing to DB for a clean shutdown...
Dec 21 00:43:34 vps592883 electrumx_server[9836]: INFO:SessionManager:closing down RPC listening servers
Dec 21 00:43:34 vps592883 electrumx_server[9836]: ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /usr/local/lib/python3.6/dist-packages/electrumX-1.8.12-py3.6.egg/electrumx/server/controller.py:81> exception=AssertionError()>
Dec 21 00:43:34 vps592883 electrumx_server[9836]: Traceback (most recent call last):
Dec 21 00:43:34 vps592883 electrumx_server[9836]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.10.1-py3.6.egg/aiorpcx/util.py", line 118, in check_task
Dec 21 00:43:34 vps592883 electrumx_server[9836]:     task.result()
Dec 21 00:43:34 vps592883 electrumx_server[9836]:   File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.12-py3.6.egg/electrumx/server/controller.py", line 131, in serve
Dec 21 00:43:34 vps592883 electrumx_server[9836]:     await group.spawn(wait_for_catchup())
Dec 21 00:43:34 vps592883 electrumx_server[9836]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.10.1-py3.6.egg/aiorpcx/curio.py", line 242, in __aexit__
Dec 21 00:43:34 vps592883 electrumx_server[9836]:     await self.join(wait=self._wait)
Dec 21 00:43:34 vps592883 electrumx_server[9836]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.10.1-py3.6.egg/aiorpcx/curio.py", line 213, in join
Dec 21 00:43:34 vps592883 electrumx_server[9836]:     raise task.exception()
Dec 21 00:43:34 vps592883 electrumx_server[9836]:   File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.12-py3.6.egg/electrumx/server/block_processor.py", line 662, in fetch_and_process_blocks
Dec 21 00:43:34 vps592883 electrumx_server[9836]:     await self.flush(True)
Dec 21 00:43:34 vps592883 electrumx_server[9836]:   File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.12-py3.6.egg/electrumx/server/block_processor.py", line 335, in flush
Dec 21 00:43:34 vps592883 electrumx_server[9836]:     await self.run_in_thread_with_lock(flush)
Dec 21 00:43:34 vps592883 electrumx_server[9836]:   File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.12-py3.6.egg/electrumx/server/block_processor.py", line 191, in run_in_thread_with_lock
Dec 21 00:43:34 vps592883 electrumx_server[9836]:     return await asyncio.shield(run_in_thread_locked())
Dec 21 00:43:34 vps592883 electrumx_server[9836]:   File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.12-py3.6.egg/electrumx/server/block_processor.py", line 190, in run_in_thread_locked
Dec 21 00:43:34 vps592883 electrumx_server[9836]:     return await run_in_thread(func, *args)
Dec 21 00:43:34 vps592883 electrumx_server[9836]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.10.1-py3.6.egg/aiorpcx/curio.py", line 61, in run_in_thread
Dec 21 00:43:34 vps592883 electrumx_server[9836]:     return await get_event_loop().run_in_executor(None, func, *args)
Dec 21 00:43:34 vps592883 electrumx_server[9836]:   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Dec 21 00:43:34 vps592883 electrumx_server[9836]:     result = self.fn(*self.args, **self.kwargs)
Dec 21 00:43:34 vps592883 electrumx_server[9836]:   File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.12-py3.6.egg/electrumx/server/block_processor.py", line 334, in flush
Dec 21 00:43:34 vps592883 electrumx_server[9836]:     self.estimate_txs_remaining)
Dec 21 00:43:34 vps592883 electrumx_server[9836]:   File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.12-py3.6.egg/electrumx/server/db.py", line 189, in flush_dbs
Dec 21 00:43:34 vps592883 electrumx_server[9836]:     self.assert_flushed(flush_data)
Dec 21 00:43:34 vps592883 electrumx_server[9836]:   File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.12-py3.6.egg/electrumx/server/db.py", line 179, in assert_flushed
Dec 21 00:43:34 vps592883 electrumx_server[9836]:     assert not flush_data.block_tx_hashes
Dec 21 00:43:34 vps592883 electrumx_server[9836]: AssertionError

**Comment by kyuupichan** [comment]
Sorry I have no idea about your coin.  Your DB might be corrupt.  I suggest you delete the DB directory and try again.

**Comment by Nagaws** [comment]
Thanks kyuupichan, that helps
