### ISSUE TITLE
electrumx Not started

### ISSUE THREAD

**Issue by mariajohnfranklin** [kyuupichan/electrumx#691]
I am getting the following error. How to solve this?
journalctl -u electrumx -f

-- Logs begin at Tue 2019-01-08 14:10:01 UTC. --
Jan 14 06:30:13 dev-perumal-blockchain electrumx_server[12692]:     await self._open_dbs(True, False)
Jan 14 06:30:13 dev-perumal-blockchain electrumx_server[12692]:   File "/electrumx/electrumx/electrumx/server/db.py", line 113, in _open_dbs
Jan 14 06:30:13 dev-perumal-blockchain electrumx_server[12692]:     self.utxo_db = self.db_class('utxo', for_sync)
Jan 14 06:30:13 dev-perumal-blockchain electrumx_server[12692]:   File "/electrumx/electrumx/electrumx/server/storage.py", line 31, in __init__
Jan 14 06:30:13 dev-perumal-blockchain electrumx_server[12692]:     self.open(name, create=self.is_new)
Jan 14 06:30:13 dev-perumal-blockchain electrumx_server[12692]:   File "/electrumx/electrumx/electrumx/server/storage.py", line 83, in open
Jan 14 06:30:13 dev-perumal-blockchain electrumx_server[12692]:     max_open_files=mof)
Jan 14 06:30:13 dev-perumal-blockchain electrumx_server[12692]:   File "plyvel/_plyvel.pyx", line 247, in plyvel._plyvel.DB.__init__
Jan 14 06:30:13 dev-perumal-blockchain electrumx_server[12692]:   File "plyvel/_plyvel.pyx", line 88, in plyvel._plyvel.raise_for_status
Jan 14 06:30:13 dev-perumal-blockchain electrumx_server[12692]: plyvel._plyvel.IOError: b'IO error: utxo/LOCK: No such file or directory'

**Comment by kyuupichan** [comment]
Duplicate
