### ISSUE TITLE
no undo information found for height

### ISSUE THREAD

**Issue by vetal20600** [kyuupichan/electrumx#697]
Hello, community. I have version 1.4 of Electrumx running for altcoin. However I got an error few days ago.
Still figuring out how to fix it. Still do not have a solution. Maybe you can help. 
My database is: plyvel.
Log is below:
```
...
Jan 15 23:51:35 pool1 electrumx_server.py[29878]: INFO:BlockProcessor:reorg limit is 200 blocks
Jan 15 23:51:35 pool1 electrumx_server.py[29878]: INFO:Controller:RPC server listening on localhost:8000
Jan 15 23:51:35 pool1 electrumx_server.py[29878]: INFO:Prefetcher:catching up to daemon height 1,205,320 (12,790 blocks behind)
Jan 15 23:51:35 pool1 electrumx_server.py[29878]: INFO:BlockProcessor:chain reorg detected
Jan 15 23:51:35 pool1 electrumx_server.py[29878]: INFO:BlockProcessor:chain was reorganised replacing 499 blocks at heights 1,192,032-1,192,530
Jan 15 23:51:35 pool1 electrumx_server.py[29878]: ERROR:Controller:uncaught task exception: no undo information found for height 1,192,530
Jan 15 23:51:35 pool1 electrumx_server.py[29878]: Traceback (most recent call last):
```

**Comment by kyuupichan** [comment]
Have you read the lines?  There's a clue right there...

**Comment by vetal20600** [comment]
@vetal20600 unfortunately this is not enough for me to find a solution. 
What I have to fix? Daemon source code?

**Comment by kyuupichan** [comment]
You cannot rescue your DB, you have to rebuild from genesis.  This number, 200:

INFO:BlockProcessor:reorg limit is 200 blocks

is a constant in your coin definition.  Since it seems your coin regularly has reorgs much longer, you need to make that number higher.  The only downside is it takes more disk space.

**Comment by vetal20600** [comment]
I am using Electrumx as «backend» for android wallet for altcoin.
So you are claiming I need to delete everything from my database folder /home/electrumx/database_for_electrum_ ?

As result of deletion I will lose my android wallet balance, other users will.
And there is no way to rescue that balances of each user, isn't it?

**Comment by vetal20600** [comment]
@kyuupichan 
I am using Electrumx as «backend» for android wallet for altcoin.
So you are claiming I need to delete everything from my database folder /home/electrumx/database_for_electrum_ ?

As result of deletion I will lose my android wallet balance, other users will.
And there is no way to rescue that balances of each user, isn't it?

**Comment by kyuupichan** [comment]
No, it's not a wallet, it's a Blockchain index

**Comment by vetal20600** [comment]
@kyuupichan so if I delete electrumx database folder, what I can do to rescue my android wallet balance ?

**Comment by kyuupichan** [comment]
Consider yourself a new ElectrumX user.  You sound confused.
