### ISSUE TITLE
error: assert len(flush_data.block_tx_hashes) == len(flush_data.headers)

### ISSUE THREAD

**Issue by nao20010128nao** [kyuupichan/electrumx#702]
# Summary
While I'm trying to add coin to ElectrumX, I faced the issue that can't be resolved by myself.    

# Full log
See gist below:
https://gist.github.com/nao20010128nao/c1d889580571f970532f688da1f06a1d

# Config file
```
DAEMON_URL = <masked>
DB_DIRECTORY = /home/lesmi/mangas/electrumx-db
COIN = Mangacoin
```

# Reference
Added coin parameter: https://github.com/mangacoin-explore/electrumx/commit/94273ed3c1b18df275af9eb35e4f613ac10a8d0b

**Comment by gvarela90** [comment]
Did you fix this?
