### ISSUE TITLE
MemoryError('dropping message over 1,000,000 bytes and re-synchronizing',)

### ISSUE THREAD

**Issue by sumBTC** [kyuupichan/electrumx#713]
I'm running Electrumx since a long time now and continuously monitor the number of peers. Yesterday I suddenly got strange values. Turned out:

`electrumx_rpc peers`

gave me 

`MemoryError('dropping message over 1,000,000 bytes and re-synchronizing',)`

A restart didn't help. I found out the solution was to add 

`MAX_SEND=10000000`

(default MAX_SEND=1000000)

to 

/etc/electrumx.conf

Electrumx is now running again without problems.

I decided to submit this issue as it might be useful to others.

Question is: shouldn't Electrumx exit with an error message telling what went wrong and how to solve it?

Anyway, a big thank you to all the developers for all the hard work you are doing. Awesome project!

System information:

Ubuntu: 16.04
Electrumx:  1.9.1
COIN: BitcoinSegwit

More info on my [website](http://Bitkoins.nl).

**Comment by kyuupichan** [comment]
I believe the typo just fixed above should fix this issue; let me know...

**Comment by sumBTC** [comment]
I removed the `MAX_SEND=10000000` and the problem is gone. The only thing is: I'm not able to reproduce the issue but if there is a typo that has to be fixed anyway and if you're sure it has something to do with the issue, it's probably solved by this.

Again, thanks for all your efforts.

**Comment by shsmith** [comment]
I think this is related to the ongoing Sybil attack against ElectrumX servers. Recently there have been just under 100 legit servers, but in the last 24 hours we had over 248 servers, which probably exceeded the hardcoded limit. Enough of the malicious servers have gone stale that we are back below the limit. Malicious servers are in the majority now, especially for older vulnerable clients that don't understand protocol version 1.4.

**Comment by kyuupichan** [comment]
My change fixed this; there is not intended to be a limit on local RPC size

**Comment by SomberNight** [comment]
Please reopen. The fix is insufficient. The issue still occurs.

**Comment by SomberNight** [comment]
To test, patch:
```patch
diff --git a/electrumx/lib/text.py b/electrumx/lib/text.py
index 8546eb9..24ce76e 100644
--- a/electrumx/lib/text.py
+++ b/electrumx/lib/text.py
@@ -52,6 +52,7 @@ def peers_lines(data):
     '''A generator returning lines for a list of peers.
 
     data is the return value of rpc_peers().'''
+    return data
     def time_fmt(t):
         if not t:
             return 'Never'
@@ -80,3 +81,4 @@ def peers_lines(data):
                          item['try_count'],
                          item['source'][:20],
                          item['ip_addr'] or '')
+
diff --git a/electrumx/server/peers.py b/electrumx/server/peers.py
index c9ed073..c645689 100644
--- a/electrumx/server/peers.py
+++ b/electrumx/server/peers.py
@@ -518,4 +518,4 @@ class PeerManager(object):
         def peer_key(peer):
             return (peer.bad, -peer.last_good)
 
-        return [peer_data(peer) for peer in sorted(self.peers, key=peer_key)]
+        return [{'asd': "qqq"*100} for _ in range(10000)]
```

and run `./electrumx_rpc peers`

**Comment by kyuupichan** [comment]
I believe this is fixed properly thanks to @SomberNight's work on it
