### ISSUE TITLE
Effective way to obtain "total received" and "tx count"

### ISSUE THREAD

**Issue by uFire** [kyuupichan/electrumx#715]
I am developing a wallet with built in blockchain explorer and looking for a suitable backend. ElectrumX seems to be the best one. But I am stuck with getting data for my bc explorer.

So, is there a resource effective way for obtaining "total received" value and "total tx count" per scripthash other than getting blockchain.scripthash.get_history and calculating/summarizing each and every input?

**Comment by Manbearpixel** [comment]
Maybe this method might be of useful for you:

(blockchain.scripthash.get_balance)[https://electrumx.readthedocs.io/en/latest/protocol-methods.html#blockchain-scripthash-get-balance]

As far as "total tx count" I think your best bet is just running `blockchain.scripthash.get_history` and grabbing the length of the returned array of transactions. At this time there is no pagination so you'll get the entire history sum.

**Comment by uFire** [comment]
@Manbearpixel 
Thank you for your help. But `blockchain.scripthash.get_balance` shows only current confirmed/unconfirmed balance, but there is no way to get the historical data of all outputs to that scripthash in total. So it seems like the only way to get the "total received" value via ElectrumX is requesting `blockchain.scripthash.get_history` and iterating through every transaction's `vout` and summarizing all of them belonging to that scripthash. It is ok when there a few dozen transactions, but if there thousands of them, it consumes a lot of time and load. Maybe I will come up with some kind of caching of that data. 

Also, it would be good if there were a method called, for example, `blockchain.scripthash.get_txcount` acting like `blockchain.scripthash.get_history` but returning only a number, a total count of transactions to that scripthash. It could be useful for wallet developers. Sure, it is possible to call `blockchain.scripthash.get_history` and count all `tx_hash` but if returned data goes beyond the `MAX_SEND` limit, you just get an error message `response too large`. And even if you get a response that fits that limit (say, 1MB), sending up to 1 megabyte to the remote client every time is not a good idea if he only needs a total tx count. Just some ideas. :)

**Comment by kyuupichan** [comment]
At some stage I'll do a 2.0 protocol that fixes the scaling and pagination issues with the current one, but wallet software will need to change, perhaps drastically.  Meanwhile I'll close this as nothing much is going to change with the current protocol

**Comment by cisc2** [comment]
After so much time, was it implemented somehow? get_history takes a very long time, when the limit is exceeded on the server, it gives an empty response. Is there currently a way to get the total number of transactions (as uFire's get_txcount suggested) as fast as the balance (get_balance)? Maybe there is a way to run get_history so that after finding a single transaction (or up to a certain limit) it gives the result?
