### ISSUE TITLE
electrumx_*  not having execute permissions

### ISSUE THREAD

**Issue by luggs-co** [kyuupichan/electrumx#716]
When installing new version from git on debian, the permissions of the scripts in /opt/python/bin/ revert back to

-rw-r--r--

i have to manually 755 them to be able to use them again.

**Comment by kyuupichan** [comment]
This doesn't happen on MacOS; I'm guessing it's something to do with the Debian setup?

**Comment by kyuupichan** [comment]
Well if you're going to open an issue; please investigae your umask and directory flags

**Comment by kyuupichan** [comment]
@luggs-co try installing into a temporary venv in a way that doesn't require priveleges.  If that works with execute permissions then something is likely causing it in your system setup
