### ISSUE TITLE
Investigate a new hash160 indexing scheme

### ISSUE THREAD

**Issue by kyuupichan** [kyuupichan/electrumx#72]
Index by hash160(script_pubkey).  i.e.:

P2PKH: hash160('76a9' + hash160(pubkey) + '88ac')
P2SH: hash160('a9' + hash160(redeem_script) + '87')
P2PubKey: hash160(pubkey + 'ac')

and all strange scripts too.  Would save a byte and be generic.

**Comment by ecdsa** [comment]
yeah, that looks good.
the idea is that we should not have to change the db format when a new address type is added

**Comment by kyuupichan** [comment]
One area where doing this is significantly less efficient is handling address subscriptions.

At present the subscriptions list is just a set of hash168s.  It's easy to convert a hash168 to a bitcoin address.

However, if using the scheme of this issue, then we can see if any of the addresses we're watching have been touched by a mempool update or a new block.  However there is no way to reverse the hash to get the address.

So subscriptions either need to be stored as a map of hash to address, or they need to be stored as a set of addresses, and every subscribed address hash needs to be converted into a hash to find out if a session needs to be notified, each time anything is touched.

The performance implications of the 2nd approach scare me with large subscription lists, so I think the increase in memory cost of subscriptions is the only choice.   My measurements of python memory usage show that cost per sub would rise from 96 bytes to 171 bytes.

**Comment by kyuupichan** [comment]
This could be resolved by the client subscribing to script hashes rather than addresses, which would be a good improvement if we go this way.

**Comment by kyuupichan** [comment]
@ecdsa I initially was doing a hash160 - i.e. ripemd160(sha256(x)).

This turns out to be a little expensive - it was slower than parsing the scripts in Python.
So I'm now trying ripemd160 only.  But it made me think - isn't 160 bits overkill?  Can we not take 96 or 128 bits and use that as our hash for our purposes?  Collisions are still vanishingly unlikely given our data set size (which is nothing like 2^48 in size), but dropping to 96 or even 128 bits would reduce memory consumption and DB size.  We could take the first N bits of the ripemd160.  N can be anything that's a multiple of 8.

**Comment by kyuupichan** [comment]
or the first N bits of sha256.  My only preference would be whichever is faster.

**Comment by kyuupichan** [comment]
python 3.6 has blake2 which is probably the fastest, but I don't want to require 3.6 yet.

**Comment by ecdsa** [comment]
I don't understand our issue with subscriptions. I think the address can be converted to a hash at the moment the subscription is received, and the server can forget about the address. it does not need to hold the address in RAM.

**Comment by kyuupichan** [comment]
The current protocol requires the notifications to give the address, not the hash, so it needs both.

**Comment by ecdsa** [comment]
right, I forgot about that

**Comment by kyuupichan** [comment]
I think the performance I was measuring here was comparing syncs from a while back (0.8.0 or even pre 0.6.0) to the performance issues introduced from around 0.8.3.  They are all resolved in 0.9.11 so I'll take a fresh look at this.  It should be fine.

I'll also look at SHA1 which is 2x faster than RIPEMD and 3x faster than hash160, at least in Python 3.5.

**Comment by kyuupichan** [comment]
So half-way through a sync this looks to be good for ~10% sync improvement with 160 bit hashes vs 0.9.12, the current HEAD and highest performance sync.
As it also shrinks memory usage and DB size, this is a no-brainer.
@ecdsa - as I said I want to bundle this with a bunch of other minor changes to the DB, such as storing total UTXO value.
I also think indexing with 160 bits is overkill - we can further shrink the DB size, memory usage, and sync time by bringing that down.
If I truncated the hash (currently leaning towards SHA256) to 96 bits can you confirm you'd be OK with that?  It would be possible for a client to get the history etc of another address that isn't theirs with a hash collision, but that's true anyway.  I think 96 bits is good enough for ~ 2^48 addrs before we need fear a collision, which is truly a remote prospect for decades to come.  And it's very expensive to brute force a collision, something that only has nuisance value and not spending value.

**Comment by kyuupichan** [comment]
@ecdsa - this means utxo.get_address doesn't work any more.
Do you want to upgrade the protocol to pass hashes, abandon this scheme entirely, abandon that RPC, or what?

**Comment by ecdsa** [comment]
No, I do not want to upgrade the protocol. I am only making a suggestion to improve your database.

My point is only that the software would be better structured if the database does not assume anything about output script types. I believe that script types should be handled at the interface layer, not at the database layer. For example, it would allow to add support for segwit addresses at the interface level, without changing the database.

It would not be different for utxo.get_address; the address can be derived at request time from the output script. Btw, I believe that RPC is not used by the client, so it would not be a big deal if you dont implement it.

This is only a suggestion. If you do not agree with that, just don't do it.

**Comment by kyuupichan** [comment]
@ecdsa I'm hoping to look at this very soon. Should we convert pay to pubkey to P2PKH for the purpose of indexing? If we don't, address lookup won't return those transactions

**Comment by ecdsa** [comment]
Ideally, P2PK should have its own address type, but it does not.
I would not mind dropping support for addresses representing P2PK scripts. 
I am not even sure if they are officially supported in a BIP.

**Comment by kyuupichan** [comment]
Something along these lines is in 0.10.0
