### ISSUE TITLE
Electrumx Stopped . Please Advise

### ISSUE THREAD

**Issue by mariajohnfranklin** [kyuupichan/electrumx#724]
INFO:SessionManager:closing down RPC listening servers
: ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /electrumx/electrumx/server/controller.py:81> exception=AssertionError()>
: Traceback (most recent call last):
:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.10.2-py3.6.egg/aiorpcx/util.py", line 118, in check_task
:     task.result()
:   File "/electrumx/electrumx/server/controller.py", line 134, in serve
:     await group.spawn(wait_for_catchup())
:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.10.2-py3.6.egg/aiorpcx/curio.py", line 231, in __aexit__
:     await self.join()
:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.10.2-py3.6.egg/aiorpcx/curio.py", line 200, in join
:     raise task.exception()
:   File "/electrumx/electrumx/server/block_processor.py", line 716, in fetch_and_process_blocks
:     await self.flush(True)
:   File "/electrumx/electrumx/server/block_processor.py", line 389, in flush
:     await self.run_in_thread_with_lock(flush)
:   File "/electrumx/electrumx/server/block_processor.py", line 197, in run_in_thread_with_lock
:     return await asyncio.shield(run_in_thread_locked())
:   File "/electrumx/electrumx/server/block_processor.py", line 196, in run_in_thread_locked
:     return await run_in_thread(func, *args)
:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.10.2-py3.6.egg/aiorpcx/curio.py", line 61, in run_in_thread
:     return await get_event_loop().run_in_executor(None, func, *args)
:   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
:     result = self.fn(*self.args, **self.kwargs)
:   File "/electrumx/electrumx/server/block_processor.py", line 388, in flush
:     self.estimate_txs_remaining)
:   File "/electrumx/electrumx/server/db.py", line 197, in flush_dbs
:     self.flush_fs(flush_data)
:   File "/electrumx/electrumx/server/db.py", line 239, in flush_fs
:     assert len(flush_data.block_tx_hashes) == len(flush_data.headers)
: AssertionError

I have added some debug line Its showing like this. why it's mismatched
: 33858 -- block_tx_hashes length:
: 33810 -- headers length:

**I have added some debug line Its showing like this. why it's mismatched
Feb  7 11:31:08 ubuntu-s-4vcpu-8gb-ams3-01 electrumx_server[13941]: 33858 -- block_tx_hashes length:
Feb  7 11:31:08 ubuntu-s-4vcpu-8gb-ams3-01 electrumx_server[13941]: 33810 -- headers length:**

**Comment by mariajohnfranklin** [comment]
def spend_utxo(self, tx_hash, tx_idx):  returns none

**: 0000d453894a75f7aa5931a4ca4aae59bacdc743b81cc76a579e6fd0b944da4b49ce -- advance_txs rev 3.1.1 reversed packed :
Feb  7 17:02:31 ubuntu-s-4vcpu-8gb-ams3-01 electrumx_server[15842]: None -- advance_txs rev 3.1.1 hash packed :**

**Comment by gvarela90** [comment]
Same issue here. These was already reported but it was closed by the same guy who opened it. https://github.com/kyuupichan/electrumx/issues/702

**Comment by kyuupichan** [comment]
Please post all your logs from ElectrumX startup

**Comment by kyuupichan** [comment]
I'm closing this; I suspect you're runnning an altcoin (why are you afraid to say?) and it's not correctly implemented

**Comment by mariajohnfranklin** [comment]
Hi. 
    One block data was corrupted.  Electrum stopped when processed that block. 
    How to skip selected block in my case block height 33220 having some corrupted transaction.

**Comment by kyuupichan** [comment]
Just delete your DB and restart.  33,000 blocks is nothing (a few seconds?).  If it happens again at the same point, then something is wrong in your coin code, or your bitcoind has a corrupt block database (this has happened several times).

**Comment by mariajohnfranklin** [comment]
bitcoind has a corrupt block how to solve.

**Comment by kyuupichan** [comment]
Delete the DB and start again

**Comment by mariajohnfranklin** [comment]
I have tried so many times still same issue

**Comment by mariajohnfranklin** [comment]
Is there any option to skip selected block in electrumx.

**Comment by kyuupichan** [comment]
No, that makes no sense and makes your DB worthless.  I suggest you are misunderstanding something or your coin is broken.

**Comment by g574** [comment]
Hi, is there any news about this issue? I'm running electrumX with Dash and it crashed with the exact same error message mariajohnfranklin mentioned before. Is it the Dash or the ElectrumX DB that you suggested to delete?

**Comment by kyuupichan** [comment]
I suggest you delete the ElectrumX DB.
