### ISSUE TITLE
With peer discovery disabled, other servers can still add themselves

### ISSUE THREAD

**Issue by SomberNight** [kyuupichan/electrumx#731]
I haven't actually tested, but Selavi on IRC said that he has `PEER_DISCOVERY=off` set, and his server was reporting many peers regardless (including those not on the e-x default list).

I think the explanation is that other peers can still register themselves, even if you disable discovery.
Note that Selavi's server is on the e-x default list, so other peers WILL try to add themselves.

I think there should be a test for this in `on_add_peer`.
https://github.com/kyuupichan/electrumx/blob/ed59ea9f517b95d68e73442d624aa1da2196c7fa/electrumx/server/peers.py#L445

For example:
```python
if self.env.peer_discovery != self.env.PD_ON:
    return False
```

**Comment by peleion** [comment]
I can also confirm this using PEER_DISCOVERY=self. Additionally, the blacklist is not downloaded so phish servers show up as peers in this case.
