### ISSUE TITLE
Time to exclude version <1.9 from peer list?

### ISSUE THREAD

**Issue by peleion** [kyuupichan/electrumx#732]
I've been trying to play whack-a-mole on my public facing electrumx server to exclude malicious servers from even connecting. So far, ipsets at the firewall level worked (until last night) where the good known peers were 90-100 out of 400ish possible.

Last night I went to bed with 94 good peers but more than 100 new malicious ones popped up overnight - blocking the malicious CIDR ranges is becoming too hit and miss and there appear to be ones in large US based blocks now. 

[blacklist.json CIDR format (updated) #5091](https://github.com/spesmilo/electrum/issues/5091)

Is it time to restrict the peer list to version 1.9 and higher? My list shows 75 good servers right now. While I hate to think of legitimate servers running less than 1.9 not being able to join, 100% of the malicious ones are using 1.8.12 that I can see and there are enough that have upgraded to keep the network running. Undoubtedly more will come online as legitimate servers upgrade.

(Edit: URL)

**Comment by SomberNight** [comment]
Why couldn't malicious servers upgrade too?
Or why couldn't they just spoof their version string?
Protections that are trivial to counteract are not worth the time.
