### ISSUE TITLE
Feature request: $DONATION_ADDRESS_TOR

### ISSUE THREAD

**Issue by buttha** [kyuupichan/electrumx#734]
Hi, I'm running electrumx both on clearnet and as onion v3 hidden service.
I'd like these two services to appear like two totally unrelated services.
There's already TOR_BANNER_FILE environment var, but there's not a
DONATION_ADDRESS_TOR
Since DONATION_ADDRESS is the same, is easy to understand that tor hidden service and clearnet service are the same one.
I think
TOR_BANNER_FILE + DONATION_ADDRESS_TOR
would be a privacy enhancement feature.

**Comment by SomberNight** [comment]
> I'd like these two services to appear like two totally unrelated services.

There are all kinds of correlation attacks that apply. E.g. if one server is behind by 1-2 blocks, the other will be too.

Also, note that your ssl cert is shared.

**Comment by buttha** [comment]
> Also, note that your ssl cert is shared

good point, you're right
