### ISSUE TITLE
Implementing another connection mechanism

### ISSUE THREAD

**Issue by eabz** [kyuupichan/electrumx#740]
Hello @kyuupichan 
We are trying to use electrumx server as the main UTXO tracker for our app. 
The thing is, there is no way to connect an Ionic app to electrumx using TCP. And we want the user to be able to connect to any electrum node.
Is there any easy way to create another connection mechanism? We can use any other, http, websocket, rpc...

**Comment by kyuupichan** [comment]
https://github.com/kyuupichan/electrumx/issues/499

Lots of people ask, no one does the work...

**Comment by eabz** [comment]
@kyuupichan 
True... 
I am not good at python, but tell me. Should we work directly on electrumx or on aiorpcX.
Also, is websockets a good idea?

**Comment by kyuupichan** [comment]
Yes I think websockets would be useful; there is an excellent async Python package for that.  I'm unclear if it's better in aiorpcX or ElectrumX; don't worry too much about that

**Comment by kyuupichan** [comment]
I just implemented websockets in https://github.com/kyuupichan/electrumx/commit/a6bfc032674aac71eeffea3457ad10c456c1baa0

See https://electrumx.readthedocs.io/en/latest/environment.html#services
