### ISSUE TITLE
Should blacklisted peers still be visible in "electrumx_rpc peers" command?

### ISSUE THREAD

**Issue by sumBTC** [kyuupichan/electrumx#746]
I'm running Electrumx 1.9.5 (COIN = BitcoinSegwit). 

If I understand it well, peers are automatically blacklisted if they appear in https://electrum.org/blacklist.json. One of those is "*.electrupdate.pro" but when I do `electrumx_rpc peers` they are still visible. Is it normal that blacklisted peers are still visible with this command?

**Comment by sumBTC** [comment]
Oh, they have label "bad". Closing issue and sorry.

**Comment by peleion** [comment]
Yes:
https://github.com/spesmilo/electrum/issues/5091#issuecomment-464345295

**Comment by sumBTC** [comment]
Thanks for the answer. I'll close this issue.

**Comment by sumBTC** [comment]
Issue is solved in #753.
