### ISSUE TITLE
plyvel._plyvel.CorruptionError: b'Corruption: 12 missing files

### ISSUE THREAD

**Issue by santzi** [kyuupichan/electrumx#75]
Version 0.9.9
ElectrumX runnning on VM (Ubuntu) and host crashed to kernel panic (Debian).
I started host and VM again, but ElectrumX BTC does not start anymore (LTC and DASH started ok)
Is there any possibility to fix this database or should I start from scratch?

-- Logs begin at Fri 2016-12-16 20:13:00 EET. --
Dec 16 20:14:40 ubuntu systemd[1]: Started Electrumx-btc.
Dec 16 20:14:42 ubuntu electrumx_server.py[1073]: INFO:root:ElectrumX server starting
Dec 16 20:14:42 ubuntu electrumx_server.py[1073]: INFO:BlockProcessor:switching current directory to /home/santzi/debian_shares/electrumx_db/BTC/
Dec 16 20:14:42 ubuntu electrumx_server.py[1073]: INFO:BlockProcessor:reorg limit is 200 blocks
Dec 16 20:14:43 ubuntu electrumx_server.py[1073]: Traceback (most recent call last):
Dec 16 20:14:43 ubuntu electrumx_server.py[1073]:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.9-py3.5.egg/EGG-INFO/scripts/electrumx_server.py", line 68, in main
Dec 16 20:14:43 ubuntu electrumx_server.py[1073]:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.9-py3.5.egg/EGG-INFO/scripts/electrumx_server.py", line 49, in main_loop
Dec 16 20:14:43 ubuntu electrumx_server.py[1073]:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.9-py3.5.egg/server/protocol.py", line 57, in __init__
Dec 16 20:14:43 ubuntu electrumx_server.py[1073]:     self.bp = BlockProcessor(env)
Dec 16 20:14:43 ubuntu electrumx_server.py[1073]:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.9-py3.5.egg/server/block_processor.py", line 142, in __init__
Dec 16 20:14:43 ubuntu electrumx_server.py[1073]:     super().__init__(env)
Dec 16 20:14:43 ubuntu electrumx_server.py[1073]:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.9-py3.5.egg/server/db.py", line 54, in __init__
Dec 16 20:14:43 ubuntu electrumx_server.py[1073]:     self.reopen_db(True)
Dec 16 20:14:43 ubuntu electrumx_server.py[1073]:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.9-py3.5.egg/server/db.py", line 86, in reopen_db
Dec 16 20:14:43 ubuntu electrumx_server.py[1073]:     self.db = open_db(db_name, self.env.db_engine, max_open_files)
Dec 16 20:14:43 ubuntu electrumx_server.py[1073]:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.9-py3.5.egg/server/storage.py", line 24, in open_db
Dec 16 20:14:43 ubuntu electrumx_server.py[1073]:     return db_class(name, for_sync)
Dec 16 20:14:43 ubuntu electrumx_server.py[1073]:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.9-py3.5.egg/server/storage.py", line 34, in __init__
Dec 16 20:14:43 ubuntu electrumx_server.py[1073]:     self.open(name, create=self.is_new, for_sync=for_sync)
Dec 16 20:14:43 ubuntu electrumx_server.py[1073]:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.9-py3.5.egg/server/storage.py", line 85, in open
Dec 16 20:14:43 ubuntu electrumx_server.py[1073]:     max_open_files=mof, compression=None)
Dec 16 20:14:43 ubuntu electrumx_server.py[1073]:   File "_plyvel.pyx", line 236, in plyvel._plyvel.DB.__init__ (plyvel/_plyvel.cpp:3129)
Dec 16 20:14:43 ubuntu electrumx_server.py[1073]:   File "_plyvel.pyx", line 83, in plyvel._plyvel.raise_for_status (plyvel/_plyvel.cpp:1733)
Dec 16 20:14:43 ubuntu electrumx_server.py[1073]: plyvel._plyvel.CorruptionError: b'Corruption: 12 missing files; e.g.: Bitcoin-mainnet/872883.ldb'
Dec 16 20:14:43 ubuntu electrumx_server.py[1073]: CRITICAL:root:ElectrumX server terminated abnormally

**Comment by kyuupichan** [comment]
No that's not recoverable.   This seems to indicate either levelDB is relying on the host O/S saying data is written to disk and the O/S or disk is lying, or that levelDB isn't relying on such a call (like fsync) at all.

I'm not sure which applies here.  It will perhaps also depend on your file system and its configuration.  Can you tell us what the file system is, and whether it was mounted async?

**Comment by kyuupichan** [comment]
Closing this as it's not an ElectrumX bug in that nothing I can do in the code can prevent this.

Please let us know your file system details and setup though, so we can perhaps correlate these issues and understand if some settings or FSs are dangerous.

**Comment by santzi** [comment]
Host Debian 8 (Jessie) 16GB RAM, AMD FX 4300 4xCores (3.8GHz)
Daemons running on this host. (daemons' databases are located to sdc1 and electrumx leveldb to sdb7) 
/dev/sdb7 on /ele_db type xfs (rw,nosuid,noatime,attr2,inode64,noquota)
/dev/sdc1 on /media/santzi/blockchains type xfs (rw,nosuid,nodev,relatime,attr2,inode64,noquota)
Sdb7 is on SSD and sdc1 on HDD.

Vmware Ubuntu 16.04 LTS (5GB RAM, 2xCore)
ElectrumX servers running on this VM (VM files located on HDD).
/dev/sda1 on / type ext4 (rw,relatime,errors=remount-ro,data=ordered)
No any databases located here.

I'm not sure about async mount on sdb7, async might be default, but on my fstab file says:
UUID=5abdbdda-a754-4af5-b702-f86fad35299b /ele_db         xfs     noatime,nosuid  0       2
So sync mount is recommended to this partition?

I forgot to take backups my electrumx's databases on last week...little bit more work now.

**Comment by kyuupichan** [comment]
Reopening because

https://plyvel.readthedocs.io/en/latest/api.html#DB.write_batch

we should probably be passing sync=True and it might have prevented this.
