### ISSUE TITLE
Extra fields for blockchain.scripthash.history

### ISSUE THREAD

**Issue by JeremyRand** [kyuupichan/electrumx#752]
Some suggestions for `blockchain.scripthash.history`:

* It would be useful to be able to specify an optional `end_height` argument.  Motivation: Namecoin name lookups usually prefer not to trust transactions with fewer than 12 confirmations; such clients would specify an `end_height` equal to the chain tip height minus 12.
* It would be useful to be able to specify an optional `count` argument.  Motivation: Namecoin name lookups only care about the most recent transaction in the list; such clients would specify a `count` of 1.  The `count` argument would need to prioritize more recent transactions.  (Maybe there are use cases for prioritizing less recent transactions, in which case an `order` argument could be used to choose.  Namecoin doesn't need that though.)
* It would be useful to be able to specify an optional `header` and `cp_height` argument.  If set, the header and (if `cp_height` is nonzero) checkpoint Merkle branch would be returned along with each transaction.  Motivation: Namecoin name lookups are extremely sensitive to latency (since web page loading is blocked while the lookup occurs, and the lookup is frequently done over Tor); being able to get the header and checkpoint Merkle branch without extra round trips would greatly improve lookup latency.  I don't think this will produce any significant extra load on the server, since the status quo is that the client asks for this information anyway.
* It would be useful to be able to specify an optional `tx` and `tx_merkle` argument.  If set, the transaction (and optionally the transaction Merkle branch) are returned instead of the transaction hash.  Motivation: same as `header` and `cp_height`; these shouldn't produce any extra load on the server either since the client will ask for this information anyway.  (Maybe there's a use case for a `tx_verbose` argument, but I don't think Namecoin needs it.)
* If there are concerns about these extra features being used as a DoS vector, I can think of 2 mitigations:
    * Only allow `header`, `cp_height`, `tx`, and `tx_merkle` to be used if `count` == 1.  This shouldn't impact legitimate usage by Namecoin name lookups.
    * Allow specific blockchains to opt into allowing `header`, `cp_height`, `tx`, and `tx_merkle`.  The Namecoin community is willing to deal with the extra load since it serves a purpose that's core to Namecoin's mission, but since most blockchains are a lot less sensitive to latency, it's totally reasonable to disable these features for chains that haven't opted in.

As usual for Namecoin-related protocol requests, I have no objection to coding these changes myself, I'm just reaching out to see if there would be any concerns about merging a PR for them.

**Comment by kyuupichan** [comment]
Hmm, I'm not sure about these to be honest
