### ISSUE TITLE
running core without txindex

### ISSUE THREAD

**Issue by sidhujag** [kyuupichan/electrumx#754]
Hello now that bitcoin core allows you to query getrawtransaction with block hash + tx hash to get a raw transaction without txindex enabled can electrum support that so that core doesn't need txindex which is a large storage cost?

It reads the tx from disk so you just need to ensure that pruning is disabled or set to something large based on how far back you want to be able to query. Thoughts?

**Comment by kyuupichan** [comment]
No, the places that want to get transactions don't have the block hash.  If the tx index space is a worry, perhaps you shouldn't be running a server.  Honestly the data is going to get so much bigger in future.
