### ISSUE TITLE
Designing for high availability

### ISSUE THREAD

**Issue by AlexanderPavlenko** [kyuupichan/electrumx#757]
Is it feasible to split ElectrumX into two processes?
1. Front server with read-only DB access to handle API requests
2. Back worker to write data from coin daemon into DB

This should allow to work around GIL limitation and run as many front servers as there are CPU cores, while having a single copy of DB, which could be put into a networked filesystem and replicated to all machines in a cluster, if remote DB access is not possible.

**Comment by kyuupichan** [comment]
Sure.  Where's the PR for review?  :)

**Comment by AlexanderPavlenko** [comment]
Thanks for the answer and readiness to review!

While PR is on its way, I have another question: how overload is handled currently? Like when MAX_SESSIONS limit happens to be too high. I guess, requests get queued?

I also observed `electrumx_rpc` throwing "cannot connect" and "error making request: CancelledError()" even when ElectrumX has zero load. I wonder how this could be fixed?

**Comment by kyuupichan** [comment]
If your max sessions limit is reached the external-facing listening sockets for new connections are closed until the session count falls below a watermark.  The RPC server is not closed.

I'm not sure why electrumx_rpc is behaving as you state.

**Comment by kyuupichan** [comment]
Closing this - high availability is nice, but to the extent I work on it it won't be MIT licensed.  And I don't see anyone else stepping up to the plate.
