### ISSUE TITLE
Blacklist should not be case sensitive

### ISSUE THREAD

**Issue by shsmith** [kyuupichan/electrumx#762]
The blacklist works on DNS, which is not case sensitive (https://tools.ietf.org/html/rfc4343).

This logic is case sensitive, allowing sybils to escape detection by varying the case of hostnames.

https://github.com/kyuupichan/electrumx/blob/5e5f97c2a32eb9cf32025e6f945fa8120cb2602b/electrumx/server/peers.py#L156-L158

Some examples:
     *.Electrumance.com
     *.ElecTrumance.com
     *.ElectrUmance.com
     *.ElectrumAnce.com
     *.elecTrumance.com

**Comment by bjd** [comment]
Noticed the same thing as I had some bypass the blacklist on my server.
I've just created a pull request for this, see PR#736

**Comment by kyuupichan** [comment]
@bjd 's PR is merged; reopen if issue persists
