### ISSUE TITLE
Electrumx_RPC CancelledError()

### ISSUE THREAD

**Issue by joesixpack** [kyuupichan/electrumx#783]
This started occuring on 1.9.0.  Server is fine according to the log.  Any ideas?

![image](https://user-images.githubusercontent.com/23145642/55518125-aeed2080-5627-11e9-884e-967e5c9c713e.png)

**Comment by kyuupichan** [comment]
Read "Timeout"

**Comment by joesixpack** [comment]
What?  Where?  :thinking:

**Comment by SomberNight** [comment]
He means "read it as a timeout".
I'm assuming you get this after it hangs for 15+ seconds.

Maybe the timeout should be increased though; during recent DDOS, even my datacenter-based server reached it occasionally.

-------- Original Message --------

**Comment by joesixpack** [comment]
I'm referencing this here so others can find it: https://github.com/kyuupichan/electrumx/issues/781
