### ISSUE TITLE
Incorrect History on Regtest

### ISSUE THREAD

**Issue by MyNameIsOka** [kyuupichan/electrumx#784]
Hello everybody,

I am having a problem getting the correct history output from one wallet on Regtest.
Here is what I did:
1. Setting up Bitcoind on Regtest
2. Setting up ElectrumX and connect it to the Regtest node
3. Sending BTC back and forth between "Account1" and "okamikun"

The transactions that are **incoming** are registered with blockchain.scripthash.get_history and blockchain.scripthash.get_balance
However, **outgoing** transactions are not registered.
This screenshot shows 2 incoming transactions, however in between there was 1 outgoing transaction:
![image](https://user-images.githubusercontent.com/18796117/55539290-4a02fa80-56fb-11e9-8f1d-c6a844961edf.png)

If I directly request the current balance from bitcoind, I get:
<img width="474" alt="Screenshot 2019-04-04 at 17 04 47" src="https://user-images.githubusercontent.com/18796117/55539547-df9e8a00-56fb-11e9-9fba-58dc5847192c.png">

What am I missing here? How do I get the outgoing transactions to show up, to get the correct balance?

Sorry if there is some info missing or if this is a stupid mistake, I am still in the very beginning of my journey^^.

Regards,
Oka

**Comment by kyuupichan** [comment]
There is no way to debug regtest - it's different for everyone.  I'm dubious of this claim given that no other user reports this issue.  If you can reproduce on a BSV, BCH or BTC mainnet please re-open.
