### ISSUE TITLE
EstimateFee requires an argument

### ISSUE THREAD

**Issue by checksum0** [kyuupichan/electrumx#788]
I know it's not the most useful function cosidering the algorithm of EstimateFee, but ElectrumX requires an argument for EstimateFee() for the target confirmation times, while some Bitcoin nodes deprecated the argument and return an error if one is provided.

Would you consider a PR to allow passing no arguments to the daemon?

**Comment by kyuupichan** [comment]
Sure

**Comment by gits7r** [comment]
@checksum0 can you please provide more information about what you mean here?
I use a version of bitcoin daemon where estimatefee is deprecated, and estimatesmartfee WITHOUT an argument (numeric between 1 and 1008 which stands for target blocks) returns an error:

Daemon:_send: unexpected exception: <class 'electrumx.server.daemon.DaemonError'> {'code': -1, 'message': 'estimatesmartfee conf_target ( "estimate_mode" )
Estimates the approximate fee per kilobyte needed for a transaction to begin confirmation within conf_target blocks if possible and return the number of blocks\nfor which the estimate is valid. Uses virtual transaction size as defined\nin BIP 141 (witness data is discounted).\n\nArguments:\n1. conf_target      (numeric, required) Confirmation target in blocks (1 - 1008)\n2. estimate_mode    (string, optional, default=CONSERVATIVE) The fee estimate mode.\n                    Whether to return a more conservative estimate which also satisfies\n                    a longer history. A conservative estimate potentially returns a\n                    higher feerate and is more likely to be sufficient for the desired\n                    target, but is not as responsive to short term drops in the\n                    prevailing fee market.  Must be one of:\n                    "UNSET"\n                    "ECONOMICAL"\n                    "CONSERVATIVE"\n\nResult:\n{\n  "feerate" : x.x,     (numeric, optional) estimate fee rate in BTC/kB\n  "errors": [ str... ] (json array of strings, optional) Errors encountered during processing\n  "blocks" : n         (numeric) block number where estimate was found\n}\n\nThe request target will be clamped between 2 and the highest target\nfee estimation is able to return based on how long it has been running.\nAn error is returned if not enough transactions and blocks\nhave been observed to make an estimate for any number of blocks.\n\nExample:\n> bitcoin-cli estimatesmartfee 6.

So what do you mean by passing no arguments to the daemon, where the daemon expects and requires at least 1 parameter (number, target blocks)? I think we should discard requests without the required parameter and not pass them to the daemon.

**Comment by kyuupichan** [comment]
@checksum0 this report is too vague.  What daemon code?  What bitcoind RPC?

**Comment by gits7r** [comment]
I  have consulted the ElectrumX protocol. The argument required for estimatefee  is filtered at ElectrumX level and discarded if missing argument, it is not passed blindly to bitcoin daemon as I thought based on your description.  So, from my point of view there is no bug and it is as it should.

**Comment by kyuupichan** [comment]
Agreed, closing
