### ISSUE TITLE
error making request: not enough values to unpack (expected 14, got 13)

### ISSUE THREAD

**Issue by shsmith** [kyuupichan/electrumx#791]
On git-head the sessions rpc is broken:
```
$ electrumx_rpc sessions
ID     Flags            Client Proto    Cost  Reqs   Txs    Subs    Recv Recv KB    Sent Sent KB      Time                  Peer
error making request: not enough values to unpack (expected 14, got 13)
```

**Comment by shsmith** [comment]
My bad. The old version daemon was still running.

**Comment by kyuupichan** [comment]
Yeah it's when the server software mismatches the electrumx_rpc version.  I'll be releasing more stuff today that costs by groups as well - connection-time groups and ip address groups
