### ISSUE TITLE
Current commit fails on start

### ISSUE THREAD

**Issue by freerko** [kyuupichan/electrumx#797]
Hi,

updating electrumx to the current commit and airorpcx to 1.14.0 on Ubuntu 18.04 with Python 3.7 results in electrumx not starting:

> Apr 15 18:47:11 hostname systemd[1]: Started Electrumx.
Apr 15 18:47:11 hostname electrumx_server[1546]: Traceback (most recent call last):
Apr 15 18:47:11 hostname electrumx_server[1546]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.10.1-py3.7.egg/EGG-INFO/scripts/electrumx_server", line 29, in main
Apr 15 18:47:11 hostname electrumx_server[1546]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.10.1-py3.7.egg/electrumx/server/env.py", line 34, in __init__
Apr 15 18:47:11 hostname electrumx_server[1546]:     self.obsolete(["MAX_SUBSCRIPTIONS", "MAX_SUBS", "MAX_SESSION_SUBS", "BANDWIDTH_LIMIT"])
Apr 15 18:47:11 hostname electrumx_server[1546]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.10.1-py3.7.egg/electrumx/lib/env_base.py", line 72, in obsolete
Apr 15 18:47:11 hostname electrumx_server[1546]:     .format(bad))
Apr 15 18:47:11 hostname electrumx_server[1546]: electrumx.lib.env_base.EnvBase.Error: remove obsolete environment variables ['MAX_SUBS', 'MAX_SESSION_SUBS']
Apr 15 18:47:11 hostname electrumx_server[1546]: CRITICAL:root:ElectrumX server terminated abnormally

**Comment by kyuupichan** [comment]
Read the penultimate line; there's a clue
