### ISSUE TITLE
Enhancement: Include last fully processed block in getinfo RPC

### ISSUE THREAD

**Issue by shsmith** [kyuupichan/electrumx#80]
The getinfo RPC seems to report "blocks" as the highest block number seen by the prefetcher, but it does not report the highest fully processed block number, so it is not easy to tell when processing of a new block has completed. It would be be helpful add a "deamonblocks" key that reports the daemon/prefetcher block and have "blocks" report the last fully processed block.

**Comment by kyuupichan** [comment]
I believe it reports the processed height - do you have evidence to the contrary?

I will rename it to db_height and add a daemon_height.

**Comment by shsmith** [comment]
I was wrong. I looked more closely and it appears to be reporting only fully processed blocks.
