### ISSUE TITLE
Help please. 'TaskSet' from 'aiorpcx'

### ISSUE THREAD

**Issue by skakyn34** [kyuupichan/electrumx#801]
Hello. Can you help me? After starting the electrumx server I get an error. I could not find a solution.
-- Logs begin at Fri 2019-04-19 16:24:29 MSK. --
electrumx_server[410]:   File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
electrumx_server[410]:     self.require(requires)[0].run_script(script_name, ns)
electrumx_server[410]:   File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 1460, in run_script
electrumx_server[410]:     exec(script_code, namespace, namespace)
electrumx_server[410]:   File "/usr/local/lib/python3.7/dist-packages/electrumX_kyuupichan-1.5.1-py3.7.egg/EGG-INFO/scripts/electrumx_server", line 16, in <module>
electrumx_server[410]:   File "/usr/local/lib/python3.7/dist-packages/electrumX_kyuupichan-1.5.1-py3.7.egg/electrumx/__init__.py", line 1, in <module>
electrumx_server[410]:   File "/usr/local/lib/python3.7/dist-packages/electrumX_kyuupichan-1.5.1-py3.7.egg/electrumx/server/controller.py", line 22, in <module>
electrumx_server[410]: ImportError: cannot import name 'TaskSet' from 'aiorpcx' (/usr/local/lib/python3.7/dist-packages/aiorpcx/__init__.py)
systemd[1]: electrumx.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: electrumx.service: Failed with result 'exit-code'.

**Comment by kyuupichan** [comment]
Wow that's old.  Please update both.
