### ISSUE TITLE
electrumx.server.db.DB.DBError

### ISSUE THREAD

**Issue by skakyn34** [kyuupichan/electrumx#802]
Faced an error, could not find a solution. Can anyone help?

-- Logs begin at Fri 2019-04-19 16:24:29 MSK. --
await self.join()
File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.16.0-py3.7.egg/aiorpcx/curio.py", line 211, in join
raise task.exception()
File "/usr/local/lib/python3.7/dist-packages/electrumX-1.11.0-py3.7.egg/electrumx/server/db.py", line 175, in populate_header_merkle_cache
await self.header_mc.initialize(length)
File "/usr/local/lib/python3.7/dist-packages/electrumX-1.11.0-py3.7.egg/electrumx/lib/merkle.py", line 216, in initialize
self.level = self._level(await self.source_func(0, length))
File "/usr/local/lib/python3.7/dist-packages/electrumX-1.11.0-py3.7.egg/electrumx/server/db.py", line 448, in fs_block_hashes
'{:,d}'.format(headers_count, height, count))
electrumx.server.db.DB.DBError: only got 0 headers starting at 0, not 1

**Comment by skakyn34** [comment]
I use Config:
COIN = Primestone
DB_DIRECTORY = /root/.electrumx/db
DAEMON_URL = http://hidden:hidden@127.0.0.1:34126
NET = mainnet
DB_ENGINE = leveldb
ALLOW_ROOT = 1
HOST = hidden
TCP_PORT = 50001
SSL_PORT = 50002
SSL_CERTFILE=/root/.electrumx/server.crt
SSL_KEYFILE=/root/.electrumx/server.key
BANNER_FILE = /root/.electrumx/banner_file.txt
DONATION_ADDRESS = hidden
REPORT_HOST = hidden
and Class:
class Primestone(Coin):
    NAME = "Primestone"
    SHORTNAME = "PSC"
    NET = "mainnet"
    XPUB_VERBYTES = bytes.fromhex("022D2533")
    XPRV_VERBYTES = bytes.fromhex("0221312B")
    P2PKH_VERBYTE = bytes.fromhex("1e")
    P2SH_VERBYTES = [bytes.fromhex("0d")]
    WIF_BYTE = bytes.fromhex("d4")
    GENESIS_HASH = ('00000fe79c10addf7e023042d3ef98ce'
                    '24d36262ae7c05c46c085c1ee14434d1')
    BASIC_HEADER_SIZE = 80
    HDR_V4_SIZE = 112
    HDR_V4_HEIGHT = 863787
    HDR_V4_START_OFFSET = HDR_V4_HEIGHT * BASIC_HEADER_SIZE
    TX_COUNT = 2930206
    TX_COUNT_HEIGHT = 1299212
    TX_PER_BLOCK = 2
    RPC_PORT = 34126

    @classmethod
    def static_header_offset(cls, height):
        assert cls.STATIC_BLOCK_HEADERS
        if height >= cls.HDR_V4_HEIGHT:
            relative_v4_offset = (height - cls.HDR_V4_HEIGHT) * cls.HDR_V4_SIZE
            return cls.HDR_V4_START_OFFSET + relative_v4_offset
        else:
            return height * cls.BASIC_HEADER_SIZE

    @classmethod
    def header_hash(cls, header):
        version, = util.unpack_le_uint32_from(header)
        if version >= 4:
            return super().header_hash(header)
        else:
            import quark_hash
            return quark_hash.getPoWHash(header)

**Comment by KrzysztofPrimeStone** [comment]
Primestone config:
base58Prefixes[PUBKEY_ADDRESS] = std::vector<unsigned char>(1, 56);     //starts with 'P'
        base58Prefixes[SCRIPT_ADDRESS] = std::vector<unsigned char>(1, 118);    //starts with 'p'
        base58Prefixes[SECRET_KEY] = std::vector<unsigned char>(1, 212);
        base58Prefixes[EXT_PUBLIC_KEY] = boost::assign::list_of(0x02)(0x2D)(0x25)(0x33).convert_to_container<std::vector<unsigned char> >();
        base58Prefixes[EXT_SECRET_KEY] = boost::assign::list_of(0x02)(0x21)(0x31)(0x2B).convert_to_container<std::vector<unsigned char> >();
        // 	BIP44 coin type is from https://github.com/satoshilabs/slips/blob/master/slip-0044.md
        base58Prefixes[EXT_COIN_TYPE] = boost::assign::list_of(0x80)(0x00)(0x00)(0x77).convert_to_container<std::vector<unsigned char> >();

**Comment by kyuupichan** [comment]
This coin seems to be your own work.
