### ISSUE TITLE
Closing session sometimes never close

### ISSUE THREAD

**Issue by krausedj** [kyuupichan/electrumx#803]
I have been trying to root cause an issue, that seems new from 1.10, to 1.11 under python 3.6

It seems there is a difference between a clean closed session, and a timeout type closed session.
Clean session closures from good clients works well.
Timeout sessions seem to hang forever in the SCX state. (This was fine in 1.10)

My reproduction of this is to ban an IP address connection coming into the server (in iptables), so it will timeout.  This results in the timeout occuring, but even after directly issuing a disconnect of the session, it will stay in closing (SCX) forever.  This may be a 1 direction ban though (client -> server)

**Comment by kyuupichan** [comment]
Thanks, I believe aiorpcX 0.16.2 fixes this
