### ISSUE TITLE
Initial sync with BSV stuck

### ISSUE THREAD

**Issue by samr7** [kyuupichan/electrumx#814]
While trying to set up an ElectrumX 1.11.0 BSV server, my install got stuck syncing at block height 556,740.  It just kept logging:

ERROR:Daemon:disconnected.  Retrying occasionally...

While this was happening, the bitcoind was pegged at 100-200% CPU and 4-6GB resident set size.  A more typical RSS would be under 400MB.

It would appear that when performing an initial sync, ElectrumX requests block data in batches of up to 100 blocks.  It also appears to have a relatively short timeout on these requests, or at least relatively short for my modest environment.  Certain recent bitcoin forks can have very large blocks, and requesting 100 of them in a single JSON-RPC appears to overburden bitcoind.  Any way to lower this maximum?  When I reduced it to 10, the sync completed smoothly and bitcoind did not exceed 2GB RSS.

**Comment by kyuupichan** [comment]
Yeah this is an issue as the blogs get big; not sure what the best approach is.  It should perhaps try to reduce the count if a higher count fails.

**Comment by kyuupichan** [comment]
I've reduced the total to 10.  Really this code needs to be smarter and to back off
