### ISSUE TITLE
RESTful API support

### ISSUE THREAD

**Issue by megumin2019** [kyuupichan/electrumx#816]
example https://github.com/MicroBitcoinOrg/ElectrumX/blob/master/api.md

**Comment by itwysgsl** [comment]
@megumin2019 full implementation of JSON RPC API is available here
https://github.com/MicroBitcoinOrg/ElectrumX/blob/master/rpcd.py

It's rather simple, so I think it's going to work with any version of electrumx :)

**Comment by megumin2019** [comment]
I need them for bitcoin full node, I would like to check the api for bitcoin use :)

**Comment by megumin2019** [comment]
@itwysgsl Can you make a PR here to merge both MBC support and RESTful API?

**Comment by kyuupichan** [comment]
Not sure if it's what you're looking for, but I just implemented websockets in https://github.com/kyuupichan/electrumx/commit/a6bfc032674aac71eeffea3457ad10c456c1baa0

See https://electrumx.readthedocs.io/en/latest/environment.html#services

**Comment by itwysgsl** [comment]
@kyuupichan I made simple http server which made direct requests to electrumx via rpc like [this](this). Nothing special I think 😅
