### ISSUE TITLE
Connection issues related to json encoding

### ISSUE THREAD

**Issue by eloyesp** [kyuupichan/electrumx#819]
I'm starting a electrumx server but when I try to connect the connection is rejected.

On the client the debug message is `failed to connect [Errno 111] Conexión rehusada`. On the server, I get:

    DEBUG:ElectrumX:[16] (-32700, 'messages must be encoded in UTF-8')
    DEBUG:ElectrumX:[16] (-32700, 'invalid JSON')

The versions on the server are:

```
Package       Version
------------- -------
aiohttp       3.5.4
aiorpcX       0.15.0
async-timeout 3.0.1
attrs         19.1.0
chardet       3.0.4
electrumX     1.11.0
idna          2.8
multidict     4.5.2
pip           19.1.1
pkg-resources 0.0.0
plyvel        1.1.0
pylru         1.2.0
setuptools    41.0.1
wheel         0.33.1
yarl          1.3.0
```

And the client trying to connect is electrum 3.0.5 (electrumfair for faircoin).

It seems that electrum is not encoding properly, but it was working a week ago and didn't change nothing on the client-side, so it seems that the server-side has changed something there. I would prefer to change things on the server side (relaxing the restriction) instead of requiring an upgrade on the client (as it would make the server less useful).

Any ideas on how to solve this?

**Comment by kyuupichan** [comment]
What client is this?

**Comment by eloyesp** [comment]
[electrumfair](https://github.com/faircoin/electrumfair) for [faircoin](https://faircoin.world/).

It's electrum 3.0.5 with minor modifications.

I've also tested with [this version](https://www.faircoin.co/download/ElectrumFair-3.3.4.tar.gz) that is forked from version 3.3.4 of electrum.

Anyway, I'm asking here because I did no change on the client. I've been trying to put an electrumx server online something like 3 weeks ago, it worked like a charm for two weeks, after that, when I restarted it stopped working because on an error that I found it was that electrumx didn't like the python version on my system after a upgrade (devuan unstable) so I've installed python from source and it worked again, but with this error error.

So it might be a change on python itself, or a change on electrumx or a change on one of the dependencies (I've reinstalled everything).

Does it makes sense?

**Comment by kyuupichan** [comment]
Well there's nothing wrong with ElectrumX; it's JSON RPC code hasn't changed for a long time.

**Comment by minioff** [comment]
I am seeing the same issue when I point a Electrum Bitcoin client 3.3.6 to ElectrumX 1.12.0 server:

```
DEBUG:ElectrumX:[6] (-32700, 'messages must be encoded in UTF-8')
DEBUG:ElectrumX:[6] (-32700, 'invalid JSON')
```

Client side I tried running it on Ubuntu and Windows and I see the same error on the server for both.

Server side, its install on a fresh/clean machine. `Python 3.6.7` on `Ubuntu 18.04.2 LTS`.

```
> pip3 freeze                                                                
aiohttp==3.5.4                                                                                      
aiorpcX==0.18.3                                                                                     
asn1crypto==0.24.0                                                                                  
async-timeout==3.0.1                                                                                
attrs==17.4.0                                                                                       
Automat==0.6.0
blinker==1.4
certifi==2018.1.18
chardet==3.0.4
click==6.7
cloud-init==19.1
colorama==0.3.7
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.1.4
distro-info===0.18ubuntu0.18.04.1
httplib2==0.9.2
hyperlink==17.3.1
idna==2.6
idna-ssl==1.1.0
incremental==16.10.1
Jinja2==2.10
jsonpatch==1.16
jsonpointer==1.10
jsonschema==2.6.0
keyring==10.6.0
keyrings.alt==3.0
language-selector==0.1
MarkupSafe==1.0
multidict==4.5.2
oauthlib==2.0.6
PAM==0.4.2
plyvel==1.1.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycrypto==2.6.1
pygobject==3.26.1
PyJWT==1.5.3
pylru==1.2.0
pyOpenSSL==17.5.0
pyserial==3.4
python-apt==1.6.4
python-debian==0.1.32
pyxdg==0.25
PyYAML==3.12
requests==2.18.4
requests-unixsocket==0.1.5
SecretStorage==2.3.1
service-identity==16.0.0
six==1.11.0
ssh-import-id==5.7
systemd-python==234
Twisted==17.9.0
typing-extensions==3.7.2
ufw==0.36
unattended-upgrades==0.1
urllib3==1.22
yarl==1.3.0
zope.interface==4.3.2
```

**Comment by minioff** [comment]
Running eg. `./electrumx_rpc getinfo` works fine btw.

**Comment by kyuupichan** [comment]
Looks to me like you're connecting to an SSL port and not using SSL, or vice versa.

**Comment by minioff** [comment]
I tried `SERVICES` configured as `rpc`, `tcp` and `ws` on various ports, with no change if behavior.

**Comment by kakobrekla** [comment]
I tapped into this line https://github.com/kyuupichan/aiorpcX/blob/master/aiorpcx/jsonrpc.py#L227 and in case of error the data on the line comes as `b'\x16\x03\x01\x02\x00\x01\x0.....`

So trying your suggestion (adding SSL) the results are:
```
tcp ... :10000 > barfs: 'messages must be encoded in UTF-8'
ssl ....:10000 > works!
ws  ....:10000 > doesnt work, silence in logs
wss ....:10000 > doesnt work, silence in logs
rpc ... :10000 > barfs: 'messages must be encoded in UTF-8'
```

I am still exploring the websocket silence, likely issue on client side.

But what I do not understand is why non-SSL connections do not work. Port 10000 is some arbitrary number and I have tried others as well. I have read through the documentation and I don't have any ideas. Any hint what to try?

**Comment by minioff** [comment]
I tapped into this line https://github.com/kyuupichan/aiorpcX/blob/master/aiorpcx/jsonrpc.py#L227 and in case of error the data on the line comes as `b'\x16\x03\x01\x02\x00\x01\x0.....`

So trying your suggestion (adding SSL) the results are:
```
tcp ... :10000 > barfs: 'messages must be encoded in UTF-8'
ssl ....:10000 > works!
ws  ....:10000 > doesnt work, silence in logs
wss ....:10000 > doesnt work, silence in logs
rpc ... :10000 > barfs: 'messages must be encoded in UTF-8'
```

I am still exploring the websocket silence, likely issue on client side.

But what I do not understand is why non-SSL connections do not work. Port 10000 is some arbitrary number and I have tried others as well. I have read through the documentation and I don't have any ideas. Any hint what to try?

**Comment by eloyesp** [comment]
> Looks to me like you're connecting to an SSL port and not using SSL, or vice versa.

Is there a way to have a more verbose debug? Reading the message as it is received could help understanding what is the problem. I'll check on the JSON-RPC code if there is a flag to have some debugging information.

I've read a report from a trisquel user (that is also a libre-distro as mine) with the same issue so I think it could be related to some python build flag.

**Comment by x86txt** [comment]
I'm seeing this issue as well form the macOS client, running ElectrumX 1.12.0. I've been trying to stand up a public electrumX node and have been banging my head against the wall, as TCP, WSS, nor SSL will work.

With SSL I don't get any sort of response, but here is what happens when I attempt to connect via TCP:

Aug  3 19:50:27 electrum electrumx_server: INFO:ElectrumX:[121] TCP 10.5.24.178:50873, 2 total
Aug  3 19:50:27 electrum electrumx_server: DEBUG:ElectrumX:[121] (-32700, 'messages must 
be encoded in UTF-8')  
Aug  3 19:50:27 electrum electrumx_server: INFO:ElectrumX:[121] changing task concurrency from 10 to 0  
Aug  3 19:50:27 electrum electrumx_server: DEBUG:ElectrumX:[121] (-32700, 'messages must be encoded in UTF-8')  
Aug  3 19:50:27 electrum electrumx_server: DEBUG:ElectrumX:[121] (-32700, 'invalid JSON')`

**Comment by kyuupichan** [comment]
Have you guys tried adding a print or log to the code to see what your client is sending?
