### ISSUE TITLE
Configure ElectrumX to the maximum performance

### ISSUE THREAD

**Issue by uFire** [kyuupichan/electrumx#821]
Hi All

I have been playing around with the following env variables
```
COST_SOFT_LIMIT
COST_HARD_LIMIT
REQUEST_SLEEP
INITIAL_CONCURRENT
BANDWIDTH_UNIT_COST
```
but it seems like it makes no difference under hundreds of parallel JSON requests. I have a pretty powerful server (2x12core CPUs, 256GB RAM and SSD RAID6) and want to get ElectrumX to work at its maximum performance, with throttling fully disabled. What values should I set to these variables to achieve my goal? How to disable throttling completely?

Thanks

**Comment by peleion** [comment]
So far, setting 
```
COST_SOFT_LIMIT=0
COST_HARD_LIMIT=0
```
seems to disable subscription (storage IO?) cost limits. [(previous discussion)](https://github.com/kyuupichan/electrumx/issues/817#issuecomment-490866428)

There doesn't seem to be a way to disable bandwidth costs using BANDWIDTH_UNIT_COST - you could try setting it to a large number. It would be nice if setting it to 0 disabled it completely but does not.

You also might try setting BLACKLIST_URL to an empty strng to disable (or at least minimze) blacklist processing if you have a private server that does not announce or connect to other peers

Unfortunately there is no current way to whitelist a client or IP/range to bypass resource limits entirely right now although this has been proposed.

**Comment by uFire** [comment]
@peleion thank you for your response. Yes, I did set both variables to zero after reading that discussion but this makes no expected effect. I see that my hardware could be performing way way much better but requests still getting throttled. I wish there were a variable which disables any limits/throttling completely and brings all the load to the hardware so one can use its full potential.

Unfortunately, I am not so good with Python to solve this by myself so I hope developers could come up with some solution in that direction in some upcoming versions of the ElectrumX.

**Comment by kyuupichan** [comment]
Nothing forth-coming
