### ISSUE TITLE
Bounty: support CryptoCondition for KMD

### ISSUE THREAD

**Issue by cipig** [kyuupichan/electrumx#828]
Komodo (KMD) is offering a bounty of 500 KMD for adding CryptoConditions support to KMD.

this the vout of such a transaction:
```
    {
      "value": 100.00000000,
      "valueZat": 10000000000,
      "n": 0,
      "scriptPubKey": {
        "asm": "a22c8020e029c511da55523565835887e412e5a0c9b920801b007000df45e545f25028248103120c008203000401 OP_CHECKCRYPTOCONDITION",
        "hex": "2ea22c8020e029c511da55523565835887e412e5a0c9b920801b007000df45e545f25028248103120c008203000401cc",
        "reqSigs": 1,
        "type": "cryptocondition",
        "addresses": [
          "R9zHrofhRbub7ER77B7NrVch3A63R39GuC"
        ]
      }
    },
```

some additional info from our lead dev
> most all of them will be the same size: a22c8020e029c511da55523565835887e412e5a0c9b920801b007000df45e545f25028248103120c008203000401
> with OP_CRYPTOCONDITION, but there is a new variant where additional data is added past the OP_CRYPTOCONDITION
> probably a filter on scriptPubKey that looks for the 0xcc opcode at the same offset will detect a CC vout

Please contact us in Discord: https://komodoplatform.com/discord
`siu - Chainmakers#3920`or me `cipi#4502`

**Comment by ca333** [comment]
Adding another 1000 KMD to the bounty

**Comment by DanielMazurFL4RE** [comment]
How this support have to look a like? It have to mark a 0xcc transactions in some way? Too few information :/

**Comment by akshaynexus** [comment]
Is this still open?

**Comment by ca333** [comment]
Yes this is still open - we increased the current bounty amount from 1500 to 2000 KMD + 3777 USD for full CC transaction compatibility in electrumX. @dimxy is one of the CC lead developers and can provide you details ref. CC transaction structure, validation logic and general implementation requirements.

**Comment by pungotoken** [comment]
Great looking forward to it, is anyone working on this?

**Comment by dimxy** [comment]
Sorry, the requirements are not defined yet.
We need some more time for this.

**Comment by kyuupichan** [comment]
Altcoins no longer supported
