### ISSUE TITLE
AuxPoW Abstraction

### ISSUE THREAD

**Issue by JeremyRand** [kyuupichan/electrumx#83]
Merge-mined blockchains such as Namecoin and Dogecoin use a different proof of work scheme (AuxPoW), in which a block header and coinbase transaction from a parent chain (usually Bitcoin or Litecoin) is included in the Namecoin or Dogecoin block header.  This extra data (referred to as an AuxPoW header) is required in order to verify the PoW (meaning that SPV cannot work without this data).

As far as I can tell, ElectrumX does not currently support sending AuxPoW headers when it sends block headers to a client.  As a result, ElectrumX servers cannot be used with Electrum clients that validate AuxPoW, which makes ElectrumX's support for Namecoin and Dogecoin basically useless unless the client fully trusts the server to serve the chain with the most work.

Is there any chance this could be added?  I'm not too familiar with the ElectrumX codebase, but at first glance it looks like overriding the [`electrum_header` method](https://github.com/kyuupichan/electrumx/blob/7b8119d78749c30df521bd652fcd960c66b01e4a/lib/coins.py#L239) might be a reasonable way of doing it.

**Comment by kyuupichan** [comment]
Sure;  please feel free to submit a PR.  I'm not familiar with this stuff - but presumably you have Electrum clients that expect an enhanced electrum header?
I assume these coins have working electrum-server implementations?

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Neil:
> Sure;  please feel free to submit a PR.

I'm happy to look into submitting a PR when I have a few minutes of
downtime.

> I'm not familiar with this stuff - but presumably you have Electrum
> clients that expect an enhanced electrum header? I assume these
> coins have working electrum-server implementations?

The only existing implementation I'm aware of is this:
https://github.com/electrumalt/electrum-doge and
https://github.com/electrumalt/electrum-doge-server .

Given that that implementation is more than 2 years old, and to my
knowledge is not in usage by anyone at the moment (not to mention I'm
unimpressed by its code quality), I would have no objection to
modifying the protocol used for AuxPoW with Electrum if there are any
issues with the protocol used by that implementation.

(There's interest in producing a new Namecoin fork of Electrum based
on the current Electrum codebase, but I'm not sure when exactly that
will happen.  It might make sense to wait until that makes progress
before worrying too much about AuxPoW in ElectrumX.)

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYXs6xAAoJELPy0WV4bWVw94EP/j8Or743T6EPK/g0UfFR9C2K
kngMXhhbjDUzMuop4M09Id2yysXMqGDKJCbQ6QoHSAalnr1SdqI7mQmuc0sbwyu2
cOOMcydhKfrk9Xv6Fdc4DHar6idBGQWlrqdIA9TIg4mow2sGmP+dlChXmdQriqCr
CdZ/t6eyClW37KsdGI3sSJ1jYaqyjDZ0B01WWjcDV9k/YLpH446bU0/GwgjUu6bv
aItNhs1xM45RpvJZkH7tgf4/goOAnNURxBhnd6QGFAomk7C+dUxH3Mwk8WZ9nBFs
6W5yvebvIJDzyckXXMkxHFI2DfqFmUc++zWv5DOKzKU9LqrGpqG25tQK8lnp7Mi3
wJLEdeKgRoHjrr89raGL7cWHHOTkKCRe/QSpZQZxsIobRO3LBKr+wo0OZ2LlEIs0
3cqHxb0MA7xrdq8+TmwPsIvhONuaearWu8uj3X25bqF9rfHgY/7WKbf/0mwwuyv/
cVI0zkU/qaYEqK+Pq3PbklDbOWBtkoA2pFWRDnAj+8kpATgaIn3DKmtluEqDRdrS
1b+0pzQT266+z/G7dnteyq0yA1GynnINFA+fUDpuojA89iw3CFKjrQnKbNbWQL9O
Wg8UWXzlNCWyYvQV47V6Yqm+CNtzPjvwFBLsXjDnmhMzcnlijgrt5jTq6PBRyadn
bXV9ZVoGe1Zhky5LZeL8
=ERuc
-----END PGP SIGNATURE-----

**Comment by protonn** [comment]
@JeremyRand 

I have a working Electrum port for Argentum currently without AuxPoW implementation. Argentum is multi-algorithm Scrypt and SHA256 both supporting AuxPoW. I have a few concerns with the lack of AuxPoW implementation in Electrum and would like additional input. Argentum is almost entirely merge mined and I've experienced no issues thus far.

I'm currently working on ElectrumX for Argentum and DigiByte so I will be following this repo closely.

https://github.com/argentumproject/electrum-arg
https://github.com/argentumproject/electrum-arg-server

**Comment by Infernoman** [comment]
Didn't want to add a new issue for this as I think it may be related to auxpow extraction. I was trying to setup electrumx for Crown. Electrumx seems to be a much faster server than any of the older auxpow clients. I noticed Doge was on here as well, So i assume that the chain is able to sync?

Part way through the sync the server errors during an assertion check in read_block of lib/tx.py.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Alastair Clark:
> Didn't want to add a new issue for this as I think it may be
> related to auxpow extraction. I was trying to setup electrumx for
> Crown. Electrumx seems to be a much faster server than any of the
> older auxpow clients. I noticed Doge was on here as well, So i
> assume that the chain is able to sync?
> 
> Part way through the sync the server errors during an assertion
> check in read_block of lib/tx.py.

AFAIK missing AuxPoW support will just result in PoW validation not
being performed by the client.  If your server is hitting an assertion
then it's probably unrelated to this issue (although if your block
headers have a nonstandard structure due to AuxPoW you might need to
do something to adjust for that).


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYpAy5AAoJELPy0WV4bWVwcV4QANJNuFTobcfqm71uY68qZjA6
JLZdc++NXxUNTrEeAFJaGRzQM0qkTD5LgZh/VYWwKFgYaOUXmvtXW5oPlTyOyHK7
N2RyVaxaudLMW0DWkWBC8+mSnr9HFJfNpK81qJrkXLzAmJ2tqQ55qASwlm3KPGVq
s0Pl0KpnE5hFRJ9OeONoTmDC0f+FKRZJxavSJrNH4gQm89Z0w3SvyZ5hmsjV+Dx6
G8AdvJfXsFSutmJuz+o9gWRrIAyafH/8YH4nVzD4I5kGNHWqn6rmq5QgMIpMAgHF
XxjTbfhlZOBHi7H9xec9u8cQGY+DCSauWLgL2jd/HOpBmcnhpf06kiFP97XAzcWq
z1GoXubldFi5XrN3iXJZi4LS6KGyLYKTqk0HV+nJJICvmu3Z82kvmMfc05p07+RB
DHEMUV1lRnqDIvhw1uLLQSpdmaBdI08LLiewiq9SIQraBmI9mKtAv8+vO9OWzfLz
EvaXqzuaFpWbcKnCvoWsMlcTqB+42rk+PR3GMPUbw1P+RQCx7Z5xDidt7NkGJpyu
rnulQmhINQilrQUOF39yTaHgf/1PsO4wEVP/QFCA3kMCjp5VKPfSFT73D7zvlMA2
ozCbhlM/P5zj+yscvASUgWZva1HiL/9zD0Wxl5hmi8Dj3zyEuJxuRQMYeG3pN0d/
UWgS9zT4MF1GyH9fyvCZ
=8/bQ
-----END PGP SIGNATURE-----

**Comment by Infernoman** [comment]
The block in question that it stop's on is after a few aux blocks have already been mined, I can't see any change in the block header, or coinbase header, Possible you could point me toward anything that may help with debugging our issue? Found the block in question. https://chainz.cryptoid.info/crw/block.dws?453220.htm

**Comment by Infernoman** [comment]
Still a bit confused as to how dogecoin has no issues now? Considering they also have support for merged mining? Older versions of electrum work with our chain just fine. And we would love to use electrumx as opposed to electrum-server because of the performance benefits of electrumx

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Alastair Clark:
> Still a bit confused as to how dogecoin has no issues now? 
> Considering they also have support for merged mining? Older 
> versions of electrum work with our chain just fine. And we would 
> love to use electrumx as opposed to electrum-server because of the 
> performance benefits of electrumx

I suspect that you've encountered an issue unrelated to AuxPoW, but
Dogecoin's initial implementation of AuxPoW was slightly more
restrictive than Namecoin's, which caused Dogecoin-based AuxPoW code
to detect errors when parsing the Namecoin blockchain.  (This was
fixed in libdohj after I reported the issue.)  The errors being
detected were in the coinbase commitments, so I really don't think the
issue you're seeing is related, since AFAIK ElectrumX doesn't even try
to parse the AuxPoW coinbase commitments.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYpbWmAAoJELPy0WV4bWVwQn8P/0z6OmJvyCiTRW/WKo2/rVXi
/k++IUyMwvCTFN0OD52VvblyXELS98q0mbZdgWKJGMCR3azMI7spO8AIxVukOD0u
1dtTyZfD9pZ0QmVwjUE/CtAI0s0InLmQYz/VFfNhKZw8mcKWDyr0TH5TyqXOXRVJ
/Ko+sQNTEiTfItEIudCswy0tVVmbgSb5bwTDGrdwP7sCJQXgQj76DZMrzvGYREOb
9ySxuB8Ndqk2rjd+vZVbxgizvlQGluzeeDwyOKm7Yyx414E1QcfcADpEd0jB2vwS
c8vYfhdmyB7fEXAbGrstrcof9pMO2dVT1CHcpklZHzjip5cZ+QpR/JpQDBR4jtuo
EXnUztL2IhkmoPIUtYX4C0HSr4o0w2W4m88AY5jS8WEzTQCe3n8KgaqfMlOIce3g
F5jUThkK12crglQaCn82TXDUtkvspqQiBHziVCndTw9m3Heq17c5kSRrKYVPQWyG
WmSdWv0BDpBjy3fn/2RH+gyuLXixilmVWgWLzohDveC6dp/aWmM6SGu4f8zuLT+/
mpOmcSOiEZZn/xp6N01Aw0gE4ugAVtMKpZp34m8a+Q9JFJoh80AUyKEMMpXb4eNl
fQQi+ODoNzvojFUzna7uM4fbdsdnQ7iwgh4cG5WbWJ+pq9DwyTHmuxmK8DBD0jIJ
HYKlL7zb/dki/2j/cvWz
=NSIz
-----END PGP SIGNATURE-----

**Comment by Infernoman** [comment]
I'm almost sure this is related to auxpow, as it seems that the first block with the change in the coinbase transaction hash. fails to get checked in electrumx, We seem to use a similar coinbase hash to namecoins, and had domob implement the code originally.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Alastair Clark:
> I'm almost sure this is related to auxpow, as it seems that the
> first block with the change in the coinbase transaction hash. fails
> to get checked in electrumx, We seem to use a similar coinbase hash
> to namecoins, and had domob implement the code originally.

Hmm, I just glanced at the relevant ElectrumX code, and I think you're
right, I don't see how Dogecoin and Namecoin would be able to sync.

In
https://github.com/kyuupichan/electrumx/blob/7b8119d78749c30df521bd652fc
d960c66b01e4a/lib/coins.py#L226
, HEADER_LEN is 80, and AuxPoW blocks have a header size greater than
80, so the transaction serializer is trying to parse part of the block
header as transactions (which I assume would result in an assertion
failure).

Good catch.  :)


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYpcCOAAoJELPy0WV4bWVw4akP/RWbPS/z2Zk6fc3iKDnroaoM
4nRylN8OunfgvirLyrNGCa33euUTr24x6hF865xEJMpXj/SpnVHbjWE6c3OTS8MF
1wUilXkh9tUUTfC/jiQ4qIvRf2HlbkhXMM9nAm0ngmaADC2UzXJPO5L/wgt9lH1D
/JHZ7vHnMOCTnSvaSDcx+wmtC7LUG5ndMthJuOPszTwZhP+ZIXdJcmjx7y/xtZx0
cSYBSjMJHCKg+bVok65Qucgp5dX6c5/6txXIwAth1dEiDP2kErAXR5Sqrk7c1Sb/
8o3VBcXaKFQD99vyDHmSM2Sh3zx4MI0gcqCkmZT5e3yfVVxrUXQJO0kQ/5bD+Vod
33fLJTF02rNuCL1KtCfR2X9qsCl4DuGqYMfzii3I2veoPEo3g6yN6BBZtghaz5Eu
XXKvq+lQTjeLSBFEk7aPvEhHKhruauM9UDVb8ITAA5ekvo2ccsLhkpxLOHr2hLgd
ECKdW9GOkc00g++KlK9GwxMMewy8pEaxmZF8+P03OhEWXrb5q4B8fHQpLJBC3WSe
lXGNKnKqnJ3L2Drh+9aE00/R/YMtYVyHOlt+4FJHsrifgwVpBLkLTqAt2gdU6KNM
bIrq9s9SF37icwkyLwTpmRl/fcsEgZSE2+j6x43Cr63TkVm6PCWnfjEAw8B5+QKy
Z2q88ZsZVdKsFRuzcdh5
=ffN/
-----END PGP SIGNATURE-----

**Comment by Infernoman** [comment]
Thanks, I'll create an issue and see if we can get it sorted then :)

**Comment by kyuupichan** [comment]
To be clear, I'm not going to fix this, as I don't use these coins and so am unable to test what is and isn't working. 
I will accept a pull request that fixes the issue(s). It sounds like the main issue might be as simple as bumping the header size at the right height, all that is needed there is a simple change to the coin definition in coins.py

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Neil:
> To be clear, I'm not going to fix this, as I don't use these coins
> and so am unable to test what is and isn't working. I will accept a
> pull request that fixes the issue(s). It sounds like the main issue
> might be as simple as bumping the header size at the right height,
> all that is needed there is a simple change to the coin definition
> in coins.py

It's not that simple; the header size of AuxPoW blocks is variable
depending on things such as the size of the parent block's coinbase
transaction.  Some amount of parsing is needed to figure out the size
of the header.

For anyone who wants to look at fixing this, the libdohj source code
is reasonably easy to read and will probably be helpful.  I can't
vouch for the various Dogecoin ports of Electrum.

I might look into fixing this, but if I do it probably won't be very
soon, so anyone who wants it sooner will have to do it themselves.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYplCSAAoJELPy0WV4bWVwypMP/R2/uSYqIPH1Yw6rQMhiPxEK
oBF/925VGEvcEBzTSTU5LyKW+r+Is2TiTtfJrNclITvcKnTS29zWeuAANgt93S26
HskwkM+LeIMMtA9DtwVsnTe/sIc4e509Y50/bYtL2gQK7feIsr17+je0WKHld1hD
m00iLzzgOEMDbJHA80upTkfhgZGXtX4V9WQLLgdFvIn9hCCIAkGKh+B6j8xVVAQI
kNRAzbzTg0rhoiJfXoVeyCE00QH8kVQrtcJTHolAcm41TneZx6a8uvU6ZgselEHG
oyZZaq9n9jxlYnXp1lmIKHq5/TPS4dN1S4fhGwh3fNBHSLO74wGiq3zMkeg1yU3R
1z7yXq0XXWaC5N1moZrjOoLUF+XgS9SwBwm3lKe7XP+2hogBK3AMVC1j94Fr8t5T
RdA5EJYQMBz14Z9I6bzgXkkGzk+t48X0E8v9sYkXnqBC9ZMiwzKAo+RhahOzZlUZ
R6+I17c2juItom8FTG+9Uf5fJAgYtsH9l64Mq+jKyE8tUBcfdnLEe8k/0rotlT7x
22OkqH00n9Y8OhW4VCzB4DNMfP0iruTD1qJ7/maVVwwX8pzqVpkrKG5BhmEwMDe6
KAYIcsgUrDNZErfOcGVwxOavn353S4NUlub92oa3gMNrHVRpGXqR9YnWfVSbsIxl
ZOLfshvFRa0zwKFNC4pi
=mxXj
-----END PGP SIGNATURE-----
