### ISSUE TITLE
 Traceback (most recent call last):

### ISSUE THREAD

**Issue by morodoskillo** [kyuupichan/electrumx#833]
hello this is my .conf 
# default /etc/electrumx.conf for systemd

# REQUIRED
DB_DIRECTORY = /db
# Bitcoin Node RPC Credentials
DAEMON_URL = http://pesetacoinrpc:9TfoqkaQbPN4By8jyWLYA1JuqoavqaG4nYJQdFzNJfXZ@127.0.0.1:16638/

# See http://electrumx.readthedocs.io/en/latest/environment.html for
# information about other configuration settings you probably want to consider.

DB_ENGINE= rocksdb

#SSL_CERTFILE=/etc/electrumx/server.crt
#SSL_KEYFILE=/etc/electrumx/server.key
TCP_PORT= 50001
#SSL_PORT=50002
# Listen on all interfaces:
HOST= hidden
NET= mainnet

and this is my error

root@vmi268686:~# journalctl -u electrumx -f
-- Logs begin at Wed 2019-05-29 23:16:44 CEST. --
May 30 21:04:59 vmi268686.contaboserver.net electrumx_server[17863]: INFO:electrumx:ElectrumX server starting
May 30 21:04:59 vmi268686.contaboserver.net electrumx_server[17863]: CRITICAL:electrumx:ElectrumX server terminated abnormally
May 30 21:04:59 vmi268686.contaboserver.net electrumx_server[17863]: Traceback (most recent call last):
May 30 21:04:59 vmi268686.contaboserver.net electrumx_server[17863]:   File "/usr/local/bin/electrumx_server", line 29, in main
May 30 21:04:59 vmi268686.contaboserver.net electrumx_server[17863]:     env = Env()
May 30 21:04:59 vmi268686.contaboserver.net electrumx_server[17863]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/env.py", line 39, in __init__
May 30 21:04:59 vmi268686.contaboserver.net electrumx_server[17863]:     "REPORT_TCP_PORT_TOR", "REPORT_SSL_PORT_TOR"])
May 30 21:04:59 vmi268686.contaboserver.net electrumx_server[17863]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/env_base.py", line 70, in obsolete
May 30 21:04:59 vmi268686.contaboserver.net electrumx_server[17863]:     .format(bad))
May 30 21:04:59 vmi268686.contaboserver.net electrumx_server[17863]: electrumx.lib.env_base.EnvBase.Error: remove obsolete environment variables ['HOST', 'TCP_PORT']

**Comment by SomberNight** [comment]
Read the last line: `remove obsolete environment variables ['HOST', 'TCP_PORT']`

See https://electrumx.readthedocs.io/en/latest/environment.html
