### ISSUE TITLE
_is_rpc_available using wrong initializer?

### ISSUE THREAD

**Issue by smogm** [kyuupichan/electrumx#838]
Shouldn't `available` be initialized with `False` here, as long as we don't know whether the RPC method is available or not?

https://github.com/kyuupichan/electrumx/blob/a614e4f4cbe09215653b3360dc54b7012d81a4f9/electrumx/server/daemon.py#L200-L209

**Comment by SomberNight** [comment]
Do you see a code execution path where it could end up with the incorrect value?

You could move it to a try-else in a PR if it bothers you.

```python
 if available is None: 
    try: 
        await self._send_single(method) 
    except DaemonError as e: 
        err = e.args[0] 
        error_code = err.get("code") 
        available = error_code != JSONRPC.METHOD_NOT_FOUND
    else:
        available = True 
    self.available_rpcs[method] = available 
return available 
```
