### ISSUE TITLE
estimatefee on Bitcoin Cash

### ISSUE THREAD

**Issue by david4neblio** [kyuupichan/electrumx#845]
See #788 for reference.

Bitcoin Cash has removed estimatesmartfee (https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/release-notes/release-notes-0.17.2.md)

Bitcoin Cash still has estimatefee but returns error upon being provided arguments. It requests calling estimatefee without arguments. ElectrumX protocol requires blockchain.estimatefee to have arguments.

Based on this code in the codebase:
```
    async def estimatefee(self, block_count):
        '''Return the fee estimate for the block count.  Units are whole
        currency units per KB, e.g. 0.00000995, or -1 if no estimate
        is available.
        '''
        args = (block_count, )
        if await self._is_rpc_available('estimatesmartfee'):
            estimate = await self._send_single('estimatesmartfee', args)
            return estimate.get('feerate', -1)
return await self._send_single('estimatefee', args)
```
Although the Electrum server will default to estimatefee if estimatesmartfee doesn't exist, it is not possible to call estimatefee without an argument.

**Comment by kyuupichan** [comment]
This doesn't seem to be reflected in the Electron-Cash/electrumx fork the ABC guys maintain.  When they implement it I will too.  Otherwise a PR is welcome.

**Comment by kyuupichan** [comment]
Closing owing to apparent lack of interest, either here or in ElectronX
