### ISSUE TITLE
Do not flush every block

### ISSUE THREAD

**Issue by streetcrypto7** [kyuupichan/electrumx#853]
Hello,

I am running electrumx with my 5s block time testnet.

Is there any options to not process db flush on every block?

For example making electrumx flush per 1000 block.

By flushing db every block will increace the chance of overflow that is described here https://github.com/kyuupichan/electrumx/issues/185.

Thanks.

**Comment by kyuupichan** [comment]
No there is no such feature.  5-second blocks are not a good idea.
