### ISSUE TITLE
Possible load for ElectrumX server

### ISSUE THREAD

**Issue by MyNameIsOka** [kyuupichan/electrumx#863]
Hi everybody,

I am still in the learning phase about ElectrumX so I hope this question isn't too vague or not reasonable.

I wonder how much load an ElectrumX server could take before becoming unresponsive. Or rather, what would be the most likely situations where it would become unresponsive or go offline?

What would be a way for me to test the maximum of my server?
My setup is an AWS t3.medium instance on which also the bitcoind node is running.

Thank you for your help and insights.

**Comment by kyuupichan** [comment]
A reasonable box can handle a few thousand connections without sweating, if they are not deliberately abusive connections
