### ISSUE TITLE
Crash when BitcoinCore 0.18 is restarted

### ISSUE THREAD

**Issue by kamk** [kyuupichan/electrumx#866]
I've upgraded Core version from 0.16 to 0.18 and noticed when daemon is restarted, the ElectrumX server crashes:

```
electrumx_server[17729]: ERROR:Daemon:<HTML><HEAD>
electrumx_server[17729]: <TITLE>503 Service Unavailable</TITLE>
electrumx_server[17729]: </HEAD><BODY>
electrumx_server[17729]: <H1>Service Unavailable</H1>
electrumx_server[17729]: </BODY></HTML>
electrumx_server[17729]: INFO:Prefetcher:cancelled; prefetcher stopping
electrumx_server[17729]: INFO:BlockProcessor:flushing to DB for a clean shutdown...
electrumx_server[17729]: INFO:SessionManager:closing down TCP, RPC listening servers
electrumx_server[17729]: ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at electrumx/server/controller.py:81> exception=DaemonError('<HTML><HEAD>\n<TITLE>503 Service Unavailable</TITLE>\n</HEAD><BODY>\n<H1>Service Unavailable</H1>\n</BODY></HTML>')>
```

They must have changed their RPC server or something.

**Comment by SomberNight** [comment]
I am using ElectrumX with Bitcoin Core 0.18 without issues, though I remember I also had some troubles when upgrading to 0.18. Can't remember exactly what it was; I think in my case, I had to add `rpcbind=0.0.0.0:8332` to `bitcoin.conf` (but this might have been specific to my setup; and note that I have made sure not to actually expose the RPC to the internet via firewall rules)

**Comment by kyuupichan** [comment]
Are the 2 or 3 lines of logs available before that?  Do they give any clue what it was doing?

**Comment by kamk** [comment]
Just normal mempool size and fee histogram reports.
However, there's traceback right after that:

```
Jul 10 16:22:37 <host> electrumx_server[17729]: Traceback (most recent call last):
Jul 10 16:22:37 <host> electrumx_server[17729]: File "<home>/.pyenv/versions/3.7.3/lib/python3.7/site-packages/aiorpcx/util.py", line 91, in check_task
Jul 10 16:22:37 <host> electrumx_server[17729]: task.result()
Jul 10 16:22:37 <host> electrumx_server[17729]: File "<home>/.pyenv/versions/3.7.3/lib/python3.7/site-packages/electrumx/server/controller.py", line 134, in serve
Jul 10 16:22:37 <host> electrumx_server[17729]: await group.spawn(wait_for_catchup())
Jul 10 16:22:37 <host> electrumx_server[17729]: File "<home>/.pyenv/versions/3.7.3/lib/python3.7/site-packages/aiorpcx/curio.py", line 242, in __aexit__
Jul 10 16:22:37 <host> electrumx_server[17729]: await self.join()
Jul 10 16:22:37 <host> electrumx_server[17729]: File "<home>/.pyenv/versions/3.7.3/lib/python3.7/site-packages/aiorpcx/curio.py", line 211, in join
Jul 10 16:22:37 <host> electrumx_server[17729]: raise task.exception()
Jul 10 16:22:37 <host> electrumx_server[17729]: File "<home>/.pyenv/versions/3.7.3/lib/python3.7/site-packages/electrumx/server/mempool.py", line 335, in keep_synchronized
Jul 10 16:22:37 <host> electrumx_server[17729]: await group.spawn(self._logging(synchronized_event))
Jul 10 16:22:37 <host> electrumx_server[17729]: File "<home>/.pyenv/versions/3.7.3/lib/python3.7/site-packages/aiorpcx/curio.py", line 242, in __aexit__
Jul 10 16:22:37 <host> electrumx_server[17729]: await self.join()
Jul 10 16:22:37 <host> electrumx_server[17729]: File "<home>/.pyenv/versions/3.7.3/lib/python3.7/site-packages/aiorpcx/curio.py", line 211, in join
Jul 10 16:22:37 <host> electrumx_server[17729]: raise task.exception()
Jul 10 16:22:37 <host> electrumx_server[17729]: File "<home>/.pyenv/versions/3.7.3/lib/python3.7/site-packages/electrumx/server/mempool.py", line 219, in _refresh_hashes
Jul 10 16:22:37 <host> electrumx_server[17729]: if height != await self.api.height():
Jul 10 16:22:37 <host> electrumx_server[17729]: File "<home>/.pyenv/versions/3.7.3/lib/python3.7/site-packages/electrumx/server/daemon.py", line 274, in height
Jul 10 16:22:37 <host> electrumx_server[17729]: self._height = await self._send_single('getblockcount')
Jul 10 16:22:37 <host> electrumx_server[17729]: File "<home>/.pyenv/versions/3.7.3/lib/python3.7/site-packages/electrumx/server/daemon.py", line 172, in _send_single
Jul 10 16:22:37 <host> electrumx_server[17729]: return await self._send(payload, processor)
Jul 10 16:22:37 <host> electrumx_server[17729]: File "<home>/.pyenv/versions/3.7.3/lib/python3.7/site-packages/electrumx/server/daemon.py", line 130, in _send
Jul 10 16:22:37 <host> electrumx_server[17729]: result = await self._send_data(data)
Jul 10 16:22:37 <host> electrumx_server[17729]: File "<home>/.pyenv/versions/3.7.3/lib/python3.7/site-packages/electrumx/server/daemon.py", line 107, in _send_data
Jul 10 16:22:37 <host> electrumx_server[17729]: raise DaemonError(text)
Jul 10 16:22:37 <host> electrumx_server[17729]: electrumx.server.daemon.DaemonError: <HTML><HEAD>
Jul 10 16:22:37 <host> electrumx_server[17729]: <TITLE>503 Service Unavailable</TITLE>
Jul 10 16:22:37 <host> electrumx_server[17729]: </HEAD><BODY>
Jul 10 16:22:37 <host> electrumx_server[17729]: <H1>Service Unavailable</H1>
Jul 10 16:22:37 <host> electrumx_server[17729]: </BODY></HTML>
```

**Comment by Quaternioneer** [comment]
# String to be appended to bitcoin.conf:
rpcauth=odysseus:DONT_USE_THIS_YOU_WILL_GET_ROBBED_8ak1gI
#Your password:
#long_string_
#
I was able to reproduce the problem. I copied fresh ElectrumX and bitcoind config files from the respective docs and copied the lines I needed from my old configs. That seemed to fix it.

This has changed in bitcoin.conf. I have not been updating religiously, so I do not know if this was changed in 0.18 of bitcoin core. 

# The config option `rpcauth` can be added to server startup argument. It is set at initialization time
# using the output from the script in share/rpcauth/rpcauth.py after providing a username:
#
# ./share/rpcauth/rpcauth.py alice
# String to be appended to bitcoin.conf:
# rpcauth=alice:f7efda5c189b999524f151318c0c86$d5b51b3beffbc02b724e5d095828e0bc8b2456e9ac8757ae3211a5d9b16a22ae
# Your password:
# DONT_USE_THIS_YOU_WILL_GET_ROBBED_8ak1gI25KFTvjovL3gAM967mies3E=

**Comment by Quaternioneer** [comment]
I was able to reproduce the problem. I copied fresh ElectrumX and bitcoind config files from the respective docs and copied the lines I needed from my old configs. That seemed to fix it.

This has changed in bitcoin.conf. I have not been updating religiously, so I do not know if this was changed in 0.18 of bitcoin core.

# The config option `rpcauth` can be added to server startup argument. It is set at initialization time
`# using the output from the script in share/rpcauth/rpcauth.py after providing a username:
#
# ./share/rpcauth/rpcauth.py alice
# String to be appended to bitcoin.conf:
# rpcauth=alice:f7efda5c189b999524f151318c0c86$d5b51b3beffbc02b724e5d095828e0bc8b2456e9ac8757ae3211a5d9b16a22ae
# Your password:
# DONT_USE_THIS_YOU_WILL_GET_ROBBED_8ak1gI25KFTvjovL3gAM967mies3E=`

**Comment by Quaternioneer** [comment]
I was able to reproduce the problem. I copied fresh ElectrumX and bitcoind config files from the respective docs and copied the lines I needed from my old configs. That seemed to fix it.

This has changed in bitcoin.conf. I have not been updating religiously, so I do not know if this was changed in 0.18 of bitcoin core.

```# The config option `rpcauth` can be added to server startup argument. It is set at initialization time
# using the output from the script in share/rpcauth/rpcauth.py after providing a username:
#
# ./share/rpcauth/rpcauth.py alice
# String to be appended to bitcoin.conf:
# rpcauth=alice:f7efda5c189b999524f151318c0c86$d5b51b3beffbc02b724e5d095828e0bc8b2456e9ac8757ae3211a5d9b16a22ae
# Your password:
# DONT_USE_THIS_YOU_WILL_GET_ROBBED_8ak1gI25KFTvjovL3gAM967mies3E=
```

**Comment by Quaternioneer** [comment]
I was able to reproduce the problem. I copied fresh ElectrumX and bitcoind config files from the respective docs and copied the lines I needed from my old configs. That seemed to fix it.

This has changed in bitcoin.conf. I have not been updating religiously, so I do not know if this was changed in 0.18 of bitcoin core.

```bash
# The config option `rpcauth` can be added to server startup argument. It is set at initialization time
# using the output from the script in share/rpcauth/rpcauth.py after providing a username:
#
# ./share/rpcauth/rpcauth.py alice
# String to be appended to bitcoin.conf:
# rpcauth=alice:f7efda5c189b999524f151318c0c86$d5b51b3beffbc02b724e5d095828e0bc8b2456e9ac8757ae3211a5d9b16a22ae
# Your password:
# DONT_USE_THIS_YOU_WILL_GET_ROBBED_8ak1gI25KFTvjovL3gAM967mies3E=
```
