### ISSUE TITLE
Electrum X keeps looping

### ISSUE THREAD

**Issue by DarkRavenCrypto** [kyuupichan/electrumx#871]
This is the error I am getting.

INFO:electrumx:ElectrumX server starting
WARNING:Env:lowered maximum sessions from 1,000 to 674 because your open file limit is 1,024
INFO:electrumx:logging level: INFO
INFO:Controller:Python version: 3.7.4 (default, Jul  9 2019, 15:11:16)  [GCC 7.4.0]
INFO:Controller:software version: ElectrumX 1.12
INFO:Controller:aiorpcX version: 0.18.3
INFO:Controller:supported protocol versions: 1.4-1.4.2
INFO:Controller:event loop policy: None
INFO:Controller:reorg limit is 200 blocks
INFO:Daemon:daemon #1 at localhost:8849/ (current)
INFO:DB:switching current directory to /db
INFO:DB:using leveldb for DB backend
INFO:DB:opened UTXO DB (for sync: True)
INFO:DB:DB version: 6
INFO:DB:coin: NativeCoin
INFO:DB:network: mainnet
INFO:DB:height: -1
INFO:DB:tip: 0000000000000000000000000000000000000000000000000000000000000000
INFO:DB:tx count: 0
INFO:DB:flushing DB cache at 1,200 MB
INFO:DB:sync time so far: 00s
INFO:History:history DB version: 0
INFO:History:flush count: 0
INFO:Prefetcher:catching up to daemon height 71,577 (71,578 blocks behind)
INFO:Prefetcher:verified genesis block with hash 00000b7892e23de3b819bb38f04cd3ff340e48ad7c379822a4ffa2b6a957eb9c
WARNING:BlockProcessor:daemon blocks do not form a chain; resetting the prefetcher
INFO:Prefetcher:catching up to daemon height 71,577 (71,578 blocks behind).

I have ensured that I installed the proper hash algo. I have been doing some trouble shooting but not sure were else to look. I was hoping to find some help here.

Thank you.

**Comment by SomberNight** [comment]
`WARNING:BlockProcessor:daemon blocks do not form a chain; resetting the prefetcher`

^ you need to figure out why you are getting this error

**Comment by DarkRavenCrypto** [comment]
Yes I understand that, I believe I have corrected this issue in the coins.py. I am going to close this ticket.
