### ISSUE TITLE
ERROR:Daemon:daemon error: Response payload is not completed  Retrying occasionally...

### ISSUE THREAD

**Issue by program-enginer-ck** [kyuupichan/electrumx#872]
hello,Why is this happening? The height of my leveldb is always unable to catch up with the height of the chain, and it will stop when it is synchronized to a certain height.

**Comment by kyuupichan** [comment]
If you want a response, some details would help

**Comment by Papabyte** [comment]
> hello,Why is this happening? The height of my leveldb is always unable to catch up with the height of the chain, and it will stop when it is synchronized to a certain height.

I had this error when trying to synchronize from scratch. My setup uses a distant Bitcoind daemon hosted on a low-end server, I guess there is a bottleneck somewhere and timeout was reached before all requested blocks can be transmitted.
To fix the issue I replaced this line: https://github.com/kyuupichan/electrumx/blob/master/electrumx/server/block_processor.py#L109
with `count = min(10, max(count, 0))`
Now the Electrum server requests at most 10 blocks in one request and is syncing without interruption.

**Comment by kyuupichan** [comment]
I've made that change
