### ISSUE TITLE
ElectrumX connects to denariusd but rcp unavailable.

### ISSUE THREAD

**Issue by Roxas240** [kyuupichan/electrumx#876]
So I setup denariusd from 0 without using chain data and ElectrumX was able to connect to it and I saw it sync with the daemon in the logs but anytime I try to connect to ElectrumX via rcp, I get connection failed. I looked at the output of netstat and port 8000 isn't even open. This is using the version the setup script is using, not a docker image.

**Comment by equisde** [comment]
you should add rpc ip and port to SERVICES env var in your electrumx.conf file
like this 

> SERVICES=tcp://:50001,ssl://:50002,wss://:50004,rpc://127.0.0.1:8000
