### ISSUE TITLE
Re-org failue at 445,009

### ISSUE THREAD

**Issue by SuBPaR42** [kyuupichan/electrumx#88]
Dec 25 09:17:19.257361 electrumx_server.py[5148]: INFO:Prefetcher:new block height 445,010 hash 0000000000000000023b7c4fa3c63af8531f801b686021d007d5d1ef83b0737c
Dec 25 09:17:19.408463 electrumx_server.py[5148]: INFO:BlockProcessor:chain reorg detected
Dec 25 09:17:19.412650 electrumx_server.py[5148]: INFO:BlockProcessor:chain was reorganised: 1 blocks at heights 445,009-445,009 were replaced
Dec 25 09:17:19.586467 electrumx_server.py[5148]: INFO:BlockProcessor:backed up to height 445,008
Dec 25 09:17:22.845821 electrumx_server.py[5148]: INFO:BlockProcessor:backing up removed 1,599 history entries from 7,232 addresses
Dec 25 09:17:22.854726 electrumx_server.py[5148]: INFO:BlockProcessor:backup flush #1,942 took 3.3s.  Height 445,008 txs: 181,961,759

**Comment by kyuupichan** [comment]
Where is the failure? That log is quite normal

**Comment by kyuupichan** [comment]
Though the history numbers seem reversed

**Comment by SuBPaR42** [comment]
That is all that was in the log (as noted - didn't see anything "bad").  I was on the wrong side it seemed per FD's monitoring page...

**Comment by kyuupichan** [comment]
Yeah something isn't right. But what's really weird is every server seems
to have recovered!?! I have no idea without a log.  I don't have remote
access to my machine either, which was also on the wrong side.

**Comment by shsmith** [comment]
All of my servers all got "stuck" after the reorg. Had to to kill each. They seemed ok after re-launch.
Log is here: https://hastebin.com/afukoyofas.sql

After the reorg it continued logging 
>INFO:Prefetcher:new block height 445,013 hash 000000000000000001a45f72f89a1385202a0a847057c3d318a8e3b453f1cadc
INFO:MemPool:4,460 txs touching 10,900 addresses

It was not logging "BlockProcessor:processed" any more.

After I sent the kill signal, it logged that the reorg block finished processing:

>WARNING:root:received SIGTERM signal, shutting down
INFO:ServerManager:cleanly closing client sessions, please wait...
INFO:ServerManager:listening sockets closed, waiting up to 30 seconds for socket cleanup
INFO:Prefetcher:reset to height
**INFO:BlockProcessor:processed 1 block in 1228.3s**
INFO:ServerManager:0 sessions remaining

There were no tracebacks logged, other than the usual post-kill asyncio "Event loop is closed" stuff.

**Comment by lahlor** [comment]
Same here. Can´t find any interesting in the logs.

**Comment by kyuupichan** [comment]
@shsmith thanks, that's very useful. I'll fix it when I'm back on 2nd

**Comment by kyuupichan** [comment]
Figured it out. Nothing is fundamentally broken, just waiting ages for a semaphore.  Recovery will happen naturally after a random amount of time, which must be what happened to my machine. 

https://github.com/kyuupichan/electrumx/blob/master/server/block_processor.py#L116

This sleep needs to be moved to the caller outside the semaphore hold. If someone wants to submit a PR against master I can merge it. I cannot create the PR myself. I'll specify the steps in the next comment

**Comment by kyuupichan** [comment]
1) have _prefetch_blocks return True at the bottom and false at line 117.
2) remove the sleep at line 117
3) have line 92 save the return value from 1 in a local variable called fetched.
4) outside the semaphore and before waiting on refill event, put 
  if not fetched:
         await asyncio.sleep(5)

If you could bump the version to 0.9.19 and update RELEASE-NOTES that would be awesome. 
Anyone up for this?

**Comment by shsmith** [comment]
I made the 0.9.19 changes here: https://github.com/shsmith/electrumx/commit/62eded55bb701e31cbe62f6d51667dab4662fbe8
After testing a bit I will submit the PR.

**Comment by kyuupichan** [comment]
Fixed in 0.9.19
