### ISSUE TITLE
 Is it possible to do bulk payments?

### ISSUE THREAD

**Issue by bumbumpaw07** [kyuupichan/electrumx#883]
Is it possible to do bulk/batch/mass payments like the available functionality in electrum client that allows users to export csv or input multiple lines for addresses?

https://electrum.readthedocs.io/en/latest/faq.html#can-i-do-bulk-payments-with-electrum

https://electrum.readthedocs.io/en/latest/_images/paytomany.png

**Comment by kyuupichan** [comment]
I'm not really sure what you are expecting but the JSON RPC interface is fully documented in https://electrumx.readthedocs.io/en/latest/ and JSON RPC v2 array requests are fully supported.
