### ISSUE TITLE
Accept and broadcast 0-fee transactions

### ISSUE THREAD

**Issue by kk215a887q** [kyuupichan/electrumx#888]
I am running electrumx using this installation : https://github.com/chris-belcher/electrum-personal-server/ as a local node

I want to change electrumx settings to accept and broadcast 0 fee transactions, I do not want to pay the 1 sat/byte fee.
I am aware that miners may chose to not include the transaction, that's alright.

How does one achieve that ?

**Comment by kyuupichan** [comment]
Set your bitcoind to do that
