### ISSUE TITLE
Large number of transactions in the block could result in excessively large RPC batch request

### ISSUE THREAD

**Issue by maciejzaleski** [kyuupichan/electrumx#892]
We're using a privately mined chain for testing purposes at Stratis. When testing ElectrumX integration with Stratis FullNode using the private chain I've noticed that when a block with large number of transactions is queried for transactions it seems to be generating a RPC batch request for all the transactions in the block.

In the tested scenario the batch request contained 4000 invocations of the method `getrawtransaction` which seems to be taking substantial amount of time to complete in case of our node implementation.

It might be better to split the batch requests into a smaller chunks so that the RPC batch request doesn't send more than N items per batch. It would be nice to have a way to set that parameter in `coins.py` if not than a hard-coded sensible value would be fine as well.

See Stratis issue for more information: https://github.com/stratisproject/StratisBitcoinFullNode/issues/3921

**Comment by kyuupichan** [comment]
This only is done for LegacyRPCdaemon; improve your daemon so it returns a raw block like others...
