### ISSUE TITLE
How can I make synchronizing addresses faster?

### ISSUE THREAD

**Issue by rurouni22** [kyuupichan/electrumx#898]
I have 50k addresses on my Electrum client. I have a local ElectrumX server working and synced lastly. Disabled soft and hard limits and made bandwith like 500 million bytes. But still when i open Electrum it synchronizes like 15 addresses per second. Can I improve this by any setting? Server is local and only serves to 1 client. 

Thanks.

**Comment by kyuupichan** [comment]
Easy.  1. Better client.  2.  Better server.   3. Better protocol.

**Comment by rurouni22** [comment]
I think client is fine but server is on a raspberry pi 4 2gb. I was worried if it isnt using its maximum because when i look with top command it shows that it's using %12 of cpu.
