### ISSUE TITLE
Electrum client says "server is lagging x blocks"

### ISSUE THREAD

**Issue by santzi** [kyuupichan/electrumx#90]
version 0.9.18
I noticed that Electrum clients for LTC and DASH (mostly LTC, sometimes DASH, never BTC) complains that ElectrumX server lagging x blocks (now LTC 360 blocks behind and increasing all the time).
When I check the server's log, block height is correct, but client still says that server is behind.
All is ok for awhile when I restart electrumx server.
Sometimes this happen also to DASH, but never to BTC.
I don't know what kind of logs I should share.

**Comment by kyuupichan** [comment]
What is the output of getinfo using the RPC client? What height do you
expect to see?

**Comment by kyuupichan** [comment]
I suspect you had just had a reorg, see issue #88.  @shsmith is about to submit a fix.

**Comment by kyuupichan** [comment]
Fixed with 0.9.19 I expect, if not please re-open

**Comment by santzi** [comment]
Now it working very well. No lagging anymore.

**Comment by kyuupichan** [comment]
Great, thanks for the confirmation
