### ISSUE TITLE
server stopped

### ISSUE THREAD

**Issue by h2o10** [kyuupichan/electrumx#901]
server stopped after 2months.
error log:

<img width="1422" alt="Screenshot 2019-19-09 at 11 42 59 AM" src="https://user-images.githubusercontent.com/46250897/65820732-3ec3fe00-e24a-11e9-9b65-cdad42348dde.png">

**Comment by kyuupichan** [comment]
Something went wrong with leveldb; I don't think the cause is ElectrumX per-se
