### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by wartjugger** [kyuupichan/electrumx#904]
Last lines of log:
>Oct 05 00:45:36 electrumx_server[4932]: INFO:BlockProcessor:our height: 233,485 daemon: 459,204 UTXOs 1,013MB hist 183MB
Oct 05 00:46:07 electrumx_server[4932]: INFO:BlockProcessor:our height: 233,552 daemon: 459,234 UTXOs 1,023MB hist 193MB
Oct 05 00:46:07 electrumx_server[4932]: INFO:DB:flushed filesystem data in 0.17s
Oct 05 00:46:14 electrumx_server[4932]: INFO:History:flushed history in 6.4s for 851,917 addrs
Oct 05 00:46:21 electrumx_server[4932]: terminate called after throwing an instance of 'std::bad_alloc'
Oct 05 00:46:21 electrumx_server[4932]:   what():  std::bad_alloc
Oct 05 00:46:21 systemd[1]: electrumx.service: Main process exited, code=killed, status=6/ABRT
Oct 05 00:46:21 systemd[1]: electrumx.service: Failed with result 'signal'.

After restarting the service, electrumx deletes "excess history" and starts from genesis.

I have 4GB memory and 340 GB SSD. Running on Debian 10. Using systemd to run the service.

bitcoin.conf:
>txindex=1
server=1
daemon=1
rpcuser=[redacted]
rpcpassword=[redacted]

Coin is BitcoinSegwit

**Comment by wartjugger** [comment]
/etc/electrumx.conf:

>COIN = BitcoinSegwit
DB_DIRECTORY = /home/electrumx/electrumx_db/
DAEMON_URL = http://[redacted]:[redacted]@localhost:8332/

**Comment by cipig** [comment]
4 GB are not enough to run BTC electrumx. bitcoind uses 800MB RAM and electrumx for BTC 3GB.
If you are rebuilding BTC electrumx DB, is uses much more RAM during the rebuild. Maybe you could run it with 4GB, but certainly not building the DB.

**Comment by wartjugger** [comment]
> 4 GB are not enough to run BTC electrumx. bitcoind uses 800MB RAM and electrumx for BTC 3GB.
> If you are rebuilding BTC electrumx DB, is uses much more RAM during the rebuild. Maybe you could run it with 4GB, but certainly not building the DB.

Thanks for the quick reply. What is the minimal requirement then?

**Comment by cipig** [comment]
I don't know how much RAM it uses during the DB rebuild, very long time passed since i had to do that. Can you configure some swap space, just for the time till the DB is ready? It can take a long time though to build the DB wih swap space.

**Comment by wartjugger** [comment]
Ok, I configured 16GB of swap, will see how it goes.
I see 6GB RAM + 16GB swap was working well in Nov. 2016 (https://github.com/kyuupichan/electrumx/issues/21) but the blockchain has gone a long way since then. Will appreciate if anyone can confirm this spec or similar is sufficient today.

**Comment by wartjugger** [comment]
I stopped getting this error after allocating the swap, but indeed it was very slow. I then added 4 GB of RAM (total 8 GB now), removed the swap, let the daemon complete its IBD, then launched electrumx again. After two days of electrumx catching up, the 340 GB SDD is full, the daemon shuts down and electrumx crashes.  I thought 340 GB will be enough for now, evidently with the indexes it isn't. I've got nothing else besides the requirements and a minimal debian installation on the machine.

**Comment by wartjugger** [comment]
With even more storage space and same RAM, started over and finally managed to get it synchronized in a net time of 9 days.

**Comment by Furunodo** [comment]
I had `bad_alloc` crashes, so I added 4GB swap:

![image](https://user-images.githubusercontent.com/52054596/80278250-aa8d1d00-86ec-11ea-8ddc-a2c25962a82d.png)

Yet I keep getting `bad_alloc` crashes. And the swap is hardly used.

```
Apr 25 11:52:10 pi electrumx_server[707]: INFO:BlockProcessor:our height: 368,520 daemon: 627,551 UTXOs 1,178MB hist 70MB
Apr 25 11:52:10 pi electrumx_server[707]: INFO:DB:flushed filesystem data in 0.06s
Apr 25 11:52:13 pi electrumx_server[707]: INFO:History:flushed history in 2.6s for 329,101 addrs
Apr 25 11:52:35 pi electrumx_server[707]: terminate called after throwing an instance of 'std::bad_alloc'
Apr 25 11:52:35 pi electrumx_server[707]:   what():  std::bad_alloc
Apr 25 11:52:35 pi systemd[1]: electrumx.service: Main process exited, code=killed, status=6/ABRT
Apr 25 11:52:36 pi systemd[1]: electrumx.service: Failed with result 'signal'.
```

What can I try now?

**Comment by akhavr** [comment]
Workaround.  

If you're bootstrapping electrumx on a low memory device (like RasPi), and get this error, add a cron restart electumx every, say, two hours.  This way you will spend less time on restarts than on rechecking the unnecessary flushes every crash.

There's definitely a memory leak somewhere in the code.  It's not visible when running on a 8Gb memory or more, or in a regular mode, but when catching up with the blockchain it spoils the whole process.
