### ISSUE TITLE
SSL only solves repeated "3.2.2 crash" requests?

### ISSUE THREAD

**Issue by wartjugger** [kyuupichan/electrumx#914]
I started with both TCP and SSL services. As in https://github.com/kyuupichan/electrumx/issues/842, I got requests from 3.2.2 clients all the time, making my server very busy trying to crash them. I then removed the TCP service and I get no such requests anymore. The number of total sessions now climbs at a much higher rate. 

What is the reason? did 3.2.2 not use SSL or are those requests today mainly DDoS attempts, and why are they only targeting TCP? What is the reason actually to provide TCP service except for onion?

**Comment by SomberNight** [comment]
There's no good reason to provide TCP services, feel free to disable it.

Re DDOS, in practice AFAICT, only servers that were on the electrum client default list at some point are getting DDOSed. Is this the case for yours?

**Comment by SomberNight** [comment]
No, I meant the default list; i.e. this: https://github.com/spesmilo/electrum/blob/master/electrum/servers.json
and (mainly) older versions of that list.

**Comment by spiccioli** [comment]
Hi,
bluewallet.io uses electrum servers as well, not sure though if it causes the 3.2.2 message when connecting.
