### ISSUE TITLE
why are eletrumx queries not returned in json format?

### ISSUE THREAD

**Issue by viraladmin** [kyuupichan/electrumx#922]
If i issue "electrumx_rpc getinfo" it will return a perfect json array as a reply as one might expect from a json rpc interface.
 
Example:
{
    "coin": "BitcoinSegwit",
    "daemon": "127.0.0.1:8332/",
    "daemon height": 603079,
    "db height": 603079,
    "groups": 2,
    "history cache": "0 lookups 0 hits 0 entries",
    "merkle cache": "0 lookups 0 hits 0 entries",
    "peers": {
        "bad": 0,
        "good": 60,
        "never": 2,
        "stale": 3,
        "total": 65
    },
    "pid": 14027,
    "request counts": {
        "getinfo": 5,
        "query": 4
    },
......... // clipping here as point made.

Yet when issuing query commands this is not the case....

 electrumx_rpc query items 1Nm5GjXAdEFyZ1rs7T5VT88MvkWhpj3NyK

Instead of a json array it will return:

Address: 1Nm5GjXAdEFyZ1rs7T5VT88MvkWhpj3NyK
History #0: height 601,059 tx_hash a7e054ef4be2dda35503dcedaa9b8dec97b7ccb1147508f4a0bddc98784613c7
History #1: height 602,799 tx_hash ea0d75e956511b380bfaae11a99fb60a720f2b67dbfe771dfc3289d1655d71ab
No UTXOs found
Balance: 0 BTC

Why would this data not be in a json array format? Its considerably harder to parse this data as it's not a json array. 

Is there any way to get this to return as a proper json array?

**Comment by kyuupichan** [comment]
Happy to take a patch.  The main reason was probably for easier human readability
