### ISSUE TITLE
Only ssl socket works with php-cli?

### ISSUE THREAD

**Issue by viraladmin** [kyuupichan/electrumx#923]
I am using php-cli (not going through a webserver). 

I have tcp, ssl, and rpc ports open and working. I can telnet to all 3 and issue json calls. 

When using php-cli I am able to connect to all three ports just fine, but only the ssl port seems to allow me to issue commands and receive replies.

This means I can't issue commands like 

`{"id": 1, "method": "getinfo", "params": []}`

I am wondering if anyone knows why I can't issue any commands on the tcp or rpc ports?

An example of the php code I am using is:

     $message = '{"id": 1, "method": "getinfo", "params": []}';
     $socket = fsockopen("localhost", "7406", $errno, $errstr); // 7406 is my electrumx rpc port
     fputs($socket, "get /$message");
     $buffer = "";
     while(!feof($socket)){
       $buffer .=fgets($socket, 4096);
     }
     print_r($buffer);
 
     var_dump($buffer);
     fclose($socket);

I tried asking on stackoverflow but no one there seems to have any answers.

**Comment by kyuupichan** [comment]
"get /$message" looks like you're doing something HTTP.  ElectrumX RPC does not use HTTP.
