### ISSUE TITLE
strange warning while shuttingdown

### ISSUE THREAD

**Issue by h2o10** [kyuupichan/electrumx#928]
Below is an error everytime comes after shutdown.

`INFO:Controller:shutting down

INFO:Prefetcher:cancelled; prefetcher stopping 
INFO:BlockProcessor:flushing to DB for a clean shutdown...
INFO:SessionManager:closing down server for ws://0.0.0.0:2222
INFO:SessionManager:closing down server for tcp://0.0.0.0:2223
INFO:SessionManager:closing down server for rpc://localhost:2224
INFO:SessionManager:closing down server for ssl://0.0.0.0:2225
INFO:Controller:shutdown complete
INFO:electrumx:ElectrumX server terminated normally
**/usr/local/lib/python3.6/dist-packages/aiohttp-4.0.0a1-py3.6-linux-x86_64.egg/aiohttp/client.py:977: RuntimeWarning: coroutine 'noop' was never awaited
  self._resp.release()**`

**Comment by kyuupichan** [comment]
Seems to be an aiohttp problem from the backtrace.  Do you have the latest version of it?
