### ISSUE TITLE
IRC flood

### ISSUE THREAD

**Issue by petrkr** [kyuupichan/electrumx#93]
Because server asks for everyone on IRC for /who information, it being kicked by freenode server by flood protection:

> * E_petrkr (~E_petrkr@....) has joined #electrum
> * E_petrkr has quit (Excess Flood)
> * E_petrkr (~E_petrkr@...) has joined #electrum
> * E_petrkr has quit (Excess Flood)

I did workaround which instead asking peer one by one uses who on whole channel in one requests and filtering interested peers in who reply.

Patch file here https://hastebin.com/kebatekibo.py

**Comment by petrkr** [comment]
Other version of patch https://hastebin.com/lumejeweki.py
Uses regex nickname instead startswith so it would not be triggered whenever someone with same nick arrives (like E_petrkr_test) so E_petrkr startswith will match.

**Comment by petrkr** [comment]
Version with regex https://hastebin.com/jijuguwici.py

**Comment by shsmith** [comment]
@petrkr thanks for the patch.
Please submit a PR for this.
