### ISSUE TITLE
ElectrumX on BitcoinSegwit coin dies with exception=error("'H' format requires 0 <= number <= 65535")>

### ISSUE THREAD

**Issue by gits7r** [kyuupichan/electrumx#937]
On network BitcoinSegwit, a server running an older ElectrumX died after so much uptime. All that I found in journalctl was:

Dec 14 18:16:56 project-management electrumx_server[513]:     self.estimate_txs_remaining)
Dec 14 18:16:56 project-management electrumx_server[513]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.9.5-py3.7.egg/electrumx/server/db.py", line 200, in flush_dbs
Dec 14 18:16:56 project-management electrumx_server[513]:     self.flush_history()
Dec 14 18:16:56 project-management electrumx_server[513]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.9.5-py3.7.egg/electrumx/server/db.py", line 269, in flush_history
Dec 14 18:16:56 project-management electrumx_server[513]:     self.history.flush()
Dec 14 18:16:56 project-management electrumx_server[513]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.9.5-py3.7.egg/electrumx/server/history.py", line 129, in flush
Dec 14 18:16:56 project-management electrumx_server[513]:     flush_id = pack_be_uint16(self.flush_count)
Dec 14 18:16:56 project-management electrumx_server[513]: struct.error: 'H' format requires 0 <= number <= 65535

Since it was dead, I have pulled the latest git master from here and also upgraded pip and related stuff (aiohttp, aiorpcx, etc.). Tried to boot back up the latest git master over 5 times, and every time it processes some blocks than it dies like this:

Dec 16 17:48:31 project-management electrumx_server[30085]: INFO:BlockProcessor:our height: 608,415 daemon: 608,426 UTXOs 166MB hist 254MB
Dec 16 17:48:31 project-management electrumx_server[30085]: INFO:DB:flushed filesystem data in 0.01s
Dec 16 17:48:31 project-management electrumx_server[30085]: INFO:Prefetcher:cancelled; prefetcher stopping
Dec 16 17:48:31 project-management electrumx_server[30085]: INFO:BlockProcessor:flushing to DB for a clean shutdown...
Dec 16 17:48:31 project-management electrumx_server[30085]: INFO:DB:flushed filesystem data in 0.00s
Dec 16 17:48:31 project-management electrumx_server[30085]: ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /usr/local/lib/python3.7/site-packages/electrumX-1.13.0-py3.7.egg/electrumx/server/controller.py:81> exception=error("'H' format requires 0 <= number <= 65535")>
Dec 16 17:48:31 project-management electrumx_server[30085]: Traceback (most recent call last):
Dec 16 17:48:31 project-management electrumx_server[30085]:   File "/usr/local/lib/python3.7/site-packages/aiorpcX-0.18.4-py3.7.egg/aiorpcx/util.py", line 309, in check_task
Dec 16 17:48:31 project-management electrumx_server[30085]:     task.result()
Dec 16 17:48:31 project-management electrumx_server[30085]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.13.0-py3.7.egg/electrumx/server/controller.py", line 134, in serve
Dec 16 17:48:31 project-management electrumx_server[30085]:     await group.spawn(wait_for_catchup())
Dec 16 17:48:31 project-management electrumx_server[30085]:   File "/usr/local/lib/python3.7/site-packages/aiorpcX-0.18.4-py3.7.egg/aiorpcx/curio.py", line 242, in __aexit__
Dec 16 17:48:31 project-management electrumx_server[30085]:     await self.join()
Dec 16 17:48:31 project-management electrumx_server[30085]:   File "/usr/local/lib/python3.7/site-packages/aiorpcX-0.18.4-py3.7.egg/aiorpcx/curio.py", line 211, in join
Dec 16 17:48:31 project-management electrumx_server[30085]:     raise task.exception()
Dec 16 17:48:31 project-management electrumx_server[30085]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.13.0-py3.7.egg/electrumx/server/block_processor.py", line 669, in fetch_and_process_blocks
Dec 16 17:48:31 project-management electrumx_server[30085]:     await self.flush(True)
Dec 16 17:48:31 project-management electrumx_server[30085]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.13.0-py3.7.egg/electrumx/server/block_processor.py", line 342, in flush
Dec 16 17:48:31 project-management electrumx_server[30085]:     await self.run_in_thread_with_lock(flush)
Dec 16 17:48:31 project-management electrumx_server[30085]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.13.0-py3.7.egg/electrumx/server/block_processor.py", line 198, in run_in_thread_with_lock
Dec 16 17:48:31 project-management electrumx_server[30085]:     return await asyncio.shield(run_in_thread_locked())
Dec 16 17:48:31 project-management electrumx_server[30085]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.13.0-py3.7.egg/electrumx/server/block_processor.py", line 197, in run_in_thread_locked
Dec 16 17:48:31 project-management electrumx_server[30085]:     return await run_in_thread(func, *args)
Dec 16 17:48:31 project-management electrumx_server[30085]:   File "/usr/local/lib/python3.7/site-packages/aiorpcX-0.18.4-py3.7.egg/aiorpcx/curio.py", line 68, in run_in_thread
Dec 16 17:48:31 project-management electrumx_server[30085]:     return await get_event_loop().run_in_executor(None, func, *args)
Dec 16 17:48:31 project-management electrumx_server[30085]:   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Dec 16 17:48:31 project-management electrumx_server[30085]:     result = self.fn(*self.args, **self.kwargs)
Dec 16 17:48:31 project-management electrumx_server[30085]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.13.0-py3.7.egg/electrumx/server/block_processor.py", line 341, in flush
Dec 16 17:48:31 project-management electrumx_server[30085]:     self.estimate_txs_remaining)
Dec 16 17:48:31 project-management electrumx_server[30085]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.13.0-py3.7.egg/electrumx/server/db.py", line 210, in flush_dbs
Dec 16 17:48:31 project-management electrumx_server[30085]:     self.flush_history()
Dec 16 17:48:31 project-management electrumx_server[30085]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.13.0-py3.7.egg/electrumx/server/db.py", line 279, in flush_history
Dec 16 17:48:31 project-management electrumx_server[30085]:     self.history.flush()
Dec 16 17:48:31 project-management electrumx_server[30085]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.13.0-py3.7.egg/electrumx/server/history.py", line 133, in flush
Dec 16 17:48:31 project-management electrumx_server[30085]:     flush_id = pack_be_uint16(self.flush_count)
Dec 16 17:48:31 project-management electrumx_server[30085]: struct.error: 'H' format requires 0 <= number <= 6553

**Comment by SomberNight** [comment]
It's db flush count overflow. See https://github.com/kyuupichan/electrumx/issues/185
You should run the [history compaction script](https://github.com/kyuupichan/electrumx/blob/ff492d307624b655ad1ab485dc3a1e4f00d24ecf/electrumx_compact_history).

**Comment by gits7r** [comment]
Correct. And thanks for your help in how to use the script.
I will close this for now as it's obviously not a bug and I'll submit a simple HOWTO for the electrumx_compact_history because if it's run directly it complains about missing ENV variables.
Might make sense to default to /etc/electrumx.conf like electrumx_service (main script) does.

**Comment by kyuupichan** [comment]
Well it is a bug but it's not going to be fixed
