### ISSUE TITLE
Allow proper ISO8601 datetime format in logs

### ISSUE THREAD

**Issue by schildbach** [kyuupichan/electrumx#938]
Currently electrumx uses 

```
2019-12-19 11:19:36,925
```

if you use `LOG_FORMAT=%(asctime)s…`. It would be nice to be able to customize it like this

```
2019-12-19T11:19:47Z
```

because that's how every other logfile looks like.

**Comment by SomberNight** [comment]
What you are seeing is simply the default of the python logging module.

To get a custom format, see https://docs.python.org/3.8/library/logging.html#logging.Formatter

What you want can be achieved either by specifying `datefmt` here:
https://github.com/kyuupichan/electrumx/blob/ff492d307624b655ad1ab485dc3a1e4f00d24ecf/electrumx_server#L24
Or overriding `formatTime` in e.g. `CompactFormatter`: https://github.com/kyuupichan/electrumx/blob/ff492d307624b655ad1ab485dc3a1e4f00d24ecf/electrumx/lib/util.py#L50

This can be an easy PR for whoever has the time.

**Comment by kyuupichan** [comment]
Note that ElectrumX was written without the intention of timestamps; they can / should be added by whatever is processing the logs.  See multilog in daemontools for example.
