### ISSUE TITLE
sync with client

### ISSUE THREAD

**Issue by Hser2bio** [kyuupichan/electrumx#943]
Hi there

thanks for your job! in other hand, i got runing fine the electrumx in my server with the daemon, but now trying to get connect with some client, and i got this error

20200115T103048.502002Z |     INFO | network | connecting toxxx.xx.xxx.xxx:50002:s as new interface
20200115T103048.851835Z |     INFO | interface.[xxx.xx.xxx.xxx:50002] | connection established. version: ['ElectrumX 1.13.0', '1.4']
20200115T103048.906559Z |     INFO | interface.[xxx.xx.xxx.xxx:50002] | set blockchain with height -1
20200115T103048.906559Z |     INFO | interface.[xxx.xx.xxx.xxx:50002] | can't connect 570044
20200115T103048.907567Z |     INFO | interface.[xxx.xx.xxx.xxx:50002] | requesting block header 1 in mode backward
20200115T103048.908566Z |     INFO | network | switching toxxx.xx.xxx.xxx:50002:s
20200115T103048.960531Z |     INFO | interface.[xxx.xx.xxx.xxx:50002] | requesting block header 0 in mode backward
20200115T103049.082893Z |     INFO | interface.[xxx.xx.xxx.xxx:50002] | disconnecting due to GracefulDisconnect('server chain conflicts with checkpoints',)

i dont have checkpoints in the client config, some idea?

thanks

**Comment by kyuupichan** [comment]
GracefulDisconnect and checkpoints are not part of ElectrumX

**Comment by Hser2bio** [comment]
Ok, could u said me which client is compatible with electrumx?
