### ISSUE TITLE
Ambiguity in server.version spec

### ISSUE THREAD

**Issue by gandrewstone** [kyuupichan/electrumx#944]
https://electrumx.readthedocs.io/en/latest/protocol-methods.html#server-version
returns an array of 2 strings.

https://electrumx.readthedocs.io/en/latest/protocol-methods.html#server-features
returns a field server_version that is: "A string that identifies the server software. Should be the same as the result to the server.version() RPC call."

The confusion is that these two lines claim that the return value is both a string AND an array of 2 strings (by being the same as server.version()).

**Comment by SomberNight** [comment]
Maybe the phrasing is confusing but look at the examples.

The response to `server.version` should be `[server_software_version, protocol_version]`, e.g. `["ElectrumX 1.2.1", "1.2"]`

While as part of the response to `server.features`:
```
{
    ...
    "server_version": "ElectrumX 1.0.17",
    ...
}
```

**Comment by kyuupichan** [comment]
Please submit a PR for a suggested improvement

**Comment by gandrewstone** [comment]
@SomberNight thanks for pointing that out.  I hadn't looked at the examples so that resolves my question.  But I still think we might as well clarify this since examples are not supposed to be authoritative in specs.

@kyuupichan How about "A string that identifies the server software. Should be the same content as the server.version() RPC call but formatted as a single concatenated, space-separated string"?  This is a trivial change so if you are working in this repo would you mind applying the change as part of some other work?

**Comment by SomberNight** [comment]
> server.version() RPC call but formatted as a single concatenated, space-separated string

You misunderstand. There is no concatenation here...
`server.version` returns a tuple: `[server_software_version, protocol_version]`
while `server_version` in `server.features` is just `server_software_version` (i.e. the first element of the tuple)

**Comment by gandrewstone** [comment]
@SomberNight ah ok, thanks!
