### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by blockinator** [kyuupichan/electrumx#946]
Hi I have Electrumx v1.13 installed on an Ubuntu 16.04 server that is fully synced with the BitcoinZ blockchain and I am getting the following errors when trying to connect with it from my electrum client:

**Server error:**
changing task concurrency
disconnected whilst throttled

**Electrum wallet error:**
[get_server] [Errno 111] Connection refused
connection closed remotely

The ssl was created with letsencrypt, ports 50001 and 50002 are open and I removed previous certs from electrum's certs directory.

**Comment by annaparker** [comment]
@blockinator I see you've closed the issue. How did you solve it out? I am experiencing same problem with "disconnected whilst throttled" message.

**Comment by CircuitBreaker88** [comment]
@blockinator What was your solution
