### ISSUE TITLE
Missing id key at returned data from subscribtion?

### ISSUE THREAD

**Issue by YanDevDe** [kyuupichan/electrumx#947]
Hey everyone. 

I just noticed that if I send json rpc with id to 
"blockchain.headers.subscribe" or "blockchain.scripthash.subscribe" then somehow the id at returned data doesn't exists. It works well on other methods which doesn't have the "subscribe" functionality.

As example I'm following sending this data to **blockchain.headers.subscribe**
 ```json
{
    "jsonrpc": "2.0",
    "method": "blockchain.headers.subscribe",
    "params": [],
    "id": "A-Example-Unique-ID"
}
```
As return (from subscription), I get that:

```json
{
    "jsonrpc": "2.0",
    "method": "blockchain.headers.subscribe",
    "params": [
        {
            "hex": "0000002035ceb41c8fac5afa91fdade4c96ac54b6924d20312bf4d56dc0c666036842df4a5a4b558b54c66797662ea2f46816aaf2e60da003adef2c028c6e4f1e528b1deab3a2b5e156c0a1900000000",
            "height": 394032
        }
    ]
}
```
As you can see, the id doesn't exists at all at returned data.
Any reason for that? I'm using WebSocket protocol, but I can imagine that this behavior also appears on other protocols too.

Thanks

**Comment by kyuupichan** [comment]
Notifications don't have an ID; this is JSON RPC; please read the docs.
