### ISSUE TITLE
Can't connect electrum wallet to local electrum server.

### ISSUE THREAD

**Issue by pedr0-fr** [kyuupichan/electrumx#950]
I have a running electrumx server with a working RPC that allows me to do queries. However, I am not able to connect my electrum wallet to my server running on the same machine. Here is my electrum.conf:

```
DB_DIRECTORY = /media/pedro/Portable_2TB/Bitcoin/electrumx/data
DAEMON_URL = http://user:password@127.0.0.1
COIN = "BitcoinSegwit"
NET = "mainnet"
ALLOW_ROOT=1

PEER_DISCOVERY= on
SERVICES = rpc://localhost:8000,tcp://localhost:50001
```
On my electrum wallet, when I try to connect to localhost, 127.0.0.1 or 192.168.1.9 on port 50001, the wallet says it's not connected with a red dot in the lower right corner.

This is what I see in log:
```
Jan 29 18:42:23 lenovoW541 electrumx_server[12284]: INFO:SessionManager:TCP server listening on localhost:50001
Jan 29 18:44:36 lenovoW541 electrumx_server[12284]: INFO:ElectrumX:[17] TCP 127.0.0.1:36122, 0 total
Jan 29 18:44:36 lenovoW541 electrumx_server[12284]: INFO:ElectrumX:[17] changing task concurrency from 10 to 0
Jan 29 18:44:36 lenovoW541 electrumx_server[12284]: INFO:ElectrumX:[17] disconnected whilst throttled
Jan 29 18:44:46 lenovoW541 electrumx_server[12284]: INFO:ElectrumX:[18] TCP 127.0.0.1:36130, 0 total
Jan 29 18:44:46 lenovoW541 electrumx_server[12284]: INFO:ElectrumX:[18] changing task concurrency from 10 to 0
Jan 29 18:44:46 lenovoW541 electrumx_server[12284]: INFO:ElectrumX:[18] disconnected whilst throttled
Jan 29 18:44:56 lenovoW541 electrumx_server[12284]: INFO:ElectrumX:[19] TCP 127.0.0.1:36140, 0 total
Jan 29 18:44:56 lenovoW541 electrumx_server[12284]: INFO:ElectrumX:[19] changing task concurrency from 10 to 0
Jan 29 18:44:56 lenovoW541 electrumx_server[12284]: INFO:ElectrumX:[19] disconnected whilst throttled
Jan 29 18:45:06 lenovoW541 electrumx_server[12284]: INFO:ElectrumX:[20] TCP 127.0.0.1:36146, 0 total
Jan 29 18:45:06 lenovoW541 electrumx_server[12284]: INFO:ElectrumX:[20] changing task concurrency from 10 to 0
Jan 29 18:45:06 lenovoW541 electrumx_server[12284]: INFO:ElectrumX:[20] disconnected whilst throttled
Jan 29 18:45:16 lenovoW541 electrumx_server[12284]: INFO:ElectrumX:[21] TCP 127.0.0.1:36152, 0 total
Jan 29 18:45:16 lenovoW541 electrumx_server[12284]: INFO:ElectrumX:[21] changing task concurrency from 10 to 0
Jan 29 18:45:16 lenovoW541 electrumx_server[12284]: INFO:ElectrumX:[21] disconnected whilst throttled
Jan 29 18:45:27 lenovoW541 electrumx_server[12284]: INFO:ElectrumX:[22] TCP 127.0.0.1:36160, 0 total
Jan 29 18:45:27 lenovoW541 electrumx_server[12284]: INFO:ElectrumX:[22] changing task concurrency from 10 to 0
Jan 29 18:45:27 lenovoW541 electrumx_server[12284]: INFO:ElectrumX:[22] disconnected whilst throttled
```

Any ideas on how to solve this?

**Comment by kyuupichan** [comment]
I imagine you have a very large wallet?

**Comment by pedr0-fr** [comment]
No, I created a new wallet from a new random seed and no transactions on electrum wallet.

**Comment by kyuupichan** [comment]
You probably need to relax your resource consumption limits.  I don't think Electrum uses checkpoints so it probably hammers the server

**Comment by rapierce** [comment]
I had this same issue.  As it turns out Electrum Wallet doesn't like the non-ssl port.  I solved the issue by creating a cert and using the 50002 port.

**Comment by leshacat** [comment]
same issue, enabling SSL does not work

**Comment by youssefgh** [comment]
@leshacat try adding :t at the end of the server URL
Example: tcp://localhost:50001:t

**Comment by sirnicolas21** [comment]
> @leshacat try adding :t at the end of the server URL
> Example: tcp://localhost:50001:t

doesn't load with it

**Comment by youssefgh** [comment]
> > @leshacat try adding :t at the end of the server URL
> > Example: tcp://localhost:50001:t
> 
> service doesn't load with it

@sirnicolas21 try to connect to your electrum server outside electrum client ex: nc localhost 50001
And make sure you are using the same network electrum client is expecting
If localhost 50001 is a testnet electrum server then you should start electrum client  with --testnet param

**Comment by sirnicolas21** [comment]
> > > @leshacat try adding :t at the end of the server URL
> > > Example: tcp://localhost:50001:t
> > 
> > 
> > service doesn't load with it
> 
> @sirnicolas21 try to connect to your electrum server outside electrum wallet ex: nc localhost 50001
> And make sure you are using the same network electrum wallet is expecting
> If localhost 50001 is a testnet electrum server then you should start electrum wallet with --testnet param

the problem is located on the wrong ssl produced, enabling electrum logs gives the message

`disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1091)`

regular rpc(using the tcp service) on the server works fine remotely, electrum doesn't connect however

**Comment by kyuupichan** [comment]
Blow your Electrum certificate cache; that might be it

**Comment by johnnyasantoss** [comment]
I'm having the same issue with eletrumx 1.16 and electrum wallet 4.1.5 running on local network.

Using my server as the manual server for my local wallet, I get these logs:
```logs
I/n | network | connecting to myserver:50002:s as new interface
I/i | interface.[myserver:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(ConnectionRefusedError(111, "Connect call failed ('10.1.1.2', 50002)")))
I/n | network | couldn't launch iface myserver:50002:s -- CancelledError()
```

I tried using a LetsEncrypt certificate, local generated certificate and nothing worked.
