### ISSUE TITLE
RPC queries don't return mempool transactions. 

### ISSUE THREAD

**Issue by pedr0-fr** [kyuupichan/electrumx#951]
I am running electrumx 1.13.0 and I am able to run queries but electrumx is not returning any data related to mempool transactions even though the transactions I am querying are in my node's mempool (v0.18.0) and they have been imported into electrumx.

Let's see an example:
The transaction `6ff3087a05442cfa306af697513224f863f8e5310020bcdb5b214cd73204972f` is my node's mempool as confirmed by:
```
>bitcoin-cli getrawmempool | grep 6ff3087a05442cfa306af697513224f863f8e5310020bcdb5b214cd73204972f
  "6ff3087a05442cfa306af697513224f863f8e5310020bcdb5b214cd73204972f",
```
[This transaction](https://www.smartbit.com.au/tx/6ff3087a05442cfa306af697513224f863f8e5310020bcdb5b214cd73204972f) spends from the address `12QEwFVcHFM9gj7mba3ofqiw4rXcqMQ5K3` and sends to `
1A4fG6NbeAEF7o4wypMhDwtYV4H4jL8Fj9`. However both queries return this transaction:

```
>electrumx_rpc query 12QEwFVcHFM9gj7mba3ofqiw4rXcqMQ5K3
Address: 12QEwFVcHFM9gj7mba3ofqiw4rXcqMQ5K3
History #0: height 615,098 tx_hash 0115c73b9663d6bfc9e9ad4c3c438a897b89afdc146411b04597ecdbf3020fc7
UTXO #1: tx_hash 0115c73b9663d6bfc9e9ad4c3c438a897b89afdc146411b04597ecdbf3020fc7 tx_pos 1 height 615,098 value 20,545,995
Balance: 0.20545995 BTC

>electrumx_rpc query 1A4fG6NbeAEF7o4wypMhDwtYV4H4jL8Fj9
Address: 1A4fG6NbeAEF7o4wypMhDwtYV4H4jL8Fj9
No history found
No UTXOs found
Balance: 0 BTC
```

After this transaction is included in a block, the queries return this transaction. I know this transaction had been imported into electrumx while it was still in the mempool because I checked the size of the mempool in my node:
```
bitcoin-cli getrawmempool | wc -l
3377
```
And compared it to the size of the mempool imported into electrumx as seen in the logs:
```
Jan 30 00:23:36 lenovoW541 electrumx_server[22584]: INFO:MemPool:3,248 txs 0.84 MB touching 7,848 addresses
Jan 30 00:23:42 lenovoW541 electrumx_server[22584]: INFO:LocalRPC:[12] RPC 127.0.0.1:60068, 0 total
Jan 30 00:24:39 lenovoW541 electrumx_server[22584]: INFO:MemPool:3,450 txs 0.89 MB touching 8,341 addresses
```

This issue might be the exact same as https://github.com/kyuupichan/electrumx/issues/948 but creating a new one due to the extra information.

**Comment by kyuupichan** [comment]
electrumx_rpc query does not look in the mempool, only in confirmed blocks

**Comment by pedr0-fr** [comment]
Didn't know this was expected behaviour. Closing.

**Comment by kyuupichan** [comment]
The query command is intended to query the DB (to find if data is corrupt etc).  The mempool isn't indexed in the same way and queries would be slow.
