### ISSUE TITLE
Electrum fails to connect to Electrumx server. 

### ISSUE THREAD

**Issue by blockinator** [kyuupichan/electrumx#953]
Hi I installed ElectrumX onto an Ubuntu server. When I try to connect to it from an electrum client I get this error:

`
[Network] connecting to electrum.blocktorial.com:50002:s as new interface
[electrum.blocktorial.com] failed to connect [Errno 111] Connection refused
`
Do you have an idea what could be the issue? Ports 50001 and 50002 are open.

**Comment by kyuupichan** [comment]
Probably Electrum's crappy cert caching

**Comment by blockinator** [comment]
Do you have an idea how I could fix it?

**Comment by kyuupichan** [comment]
delete the problematic cert

**Comment by blockinator** [comment]
I tried deleting the certs in the cert directory but it has the same issue when I try to connect.

**Comment by kyuupichan** [comment]
Nothing useful to add, sorry
