### ISSUE TITLE
tx broadcast via tor?

### ISSUE THREAD

**Issue by anonproject** [kyuupichan/electrumx#956]
It is unclear from the [documentation](https://electrumx.readthedocs.io/en/latest/environment.html#envvar-TOR_PROXY_HOST)  if setting the parameters TOR_PROXY_HOST and TOR_PROXY_PORT would be enough to broadcast transactions via tor.

**Comment by anonproject** [comment]
It is unclear even via what electrumx is broadcasting the transaction.  The brief look at server/daemon.py shows that it sends the data to self.urls[self.url_index]. But what that actually suppose to mean?

From my understanding electrumx should have a list of full bitcoin nodes to send a transaction to them and there should be an option to do that via tor.  How exactly I should do that?

**Comment by anonproject** [comment]
Uh oh.  So self.urls is related to DAEMON_URL which points to RPC of bitcoin core.  So ElectrumX just broadcasting the transaction via bitcoin core node then.

So I have to run bitcoind via tor to broadcast transactions via tor.

Correct?

**Comment by SomberNight** [comment]
>  So ElectrumX just broadcasting the transaction via bitcoin core node then.
So I have to run bitcoind via tor to broadcast transactions via tor.
Correct?

Yes, ElectrumX does not implement any bitcoin p2p; it just uses bitcoind via RPC.
