### ISSUE TITLE
Contradiction in docs/environment?

### ISSUE THREAD

**Issue by AlexanderPavlenko** [kyuupichan/electrumx#957]
https://github.com/kyuupichan/electrumx/blob/master/docs/environment.rst says:
> Here are some examples of valid services:
> wss://h3ubaasdlkheryasd.onion:50001   # Host as a Tor ".onion" address
> …
> Tor **onion** addresses are invalid in :envvar:`SERVICES`.

I guess, it means Tor URLs are only valid in the `REPORT_SERVICES`?

**Comment by kyuupichan** [comment]
Nope, services need not be in SERVICES
