### ISSUE TITLE
Unable to sync transactions over the default newline framing size

### ISSUE THREAD

**Issue by rt121212121** [kyuupichan/electrumx#967]
When fetching a large transaction emptying a wallet with lots of UTXOs via `blockchain.transaction.get`, it hit the "response too large" message for > 1,000,000. I then set the `MAX_SEND` environment variable to 10,000,000. Now it gives `MemoryError('dropping message over 1,000,000 bytes and re-synchronizing')`.  This is due to the newline framer having 4 x 250,000 as it's `max_size`.

Is it possible to add an environment variable to configure this limit, or also apply `MAX_SEND` to it?

**Comment by kyuupichan** [comment]
Oh yuk, let me take a look.  Thanks for reporting this

**Comment by kyuupichan** [comment]
Your first message is server-side, right?  And your second is client-side.  I don't think this has anything to do with ElectrumX?  I think you can change it in the client.

**Comment by SomberNight** [comment]
See https://github.com/spesmilo/electrum/commit/787ac5fe994086b994524201fec4b63f876c7c85
