### ISSUE TITLE
Encountered a stale tx_hashes cache after a reorg

### ISSUE THREAD

**Issue by rt121212121** [kyuupichan/electrumx#969]
Multiple attempts to sync a given wallet on the BitcoinSV scaling testnet resulted in a loop where ElectrumSV failed to fetch merkle roots with the following error for transactions in a given block:

> 2020-03-04 14:08:05,769:ERROR:network:getting proof for 63f23bd7d175256e9b535faa145e2937508fa180cc303a0b5b88829de2ee94f4: (1, 'tx 63f23bd7d175256e9b535faa145e2937508fa180cc303a0b5b88829de2ee94f4 not in block at height 18,901')

There was a reorg at block 18,901, with current height 18,925 and no further reorgs:

> Mar 04 02:02:57 electrumx-stn electrumx_server[12664]: INFO:BlockProcessor:chain was reorganised replacing 3 blocks at heights 18,901-18,903

Restarting the electrumx server resulted in wallet syncing working correctly, which provides supporting evidence it was the tx_hashes cache that was invalid and stale, and somehow had not been flushed following the reorg.

**Comment by rt121212121** [comment]
Forgot to include the link to the transaction:
https://stn.whatsonchain.com/tx/63f23bd7d175256e9b535faa145e2937508fa180cc303a0b5b88829de2ee94f4
> Block 0000000025c55372a18668b0e84d71db0fb2bd820e5f3cee1108f9deb3174848 (#18901)

**Comment by kyuupichan** [comment]
I think this is fixed in git HEAD
