### ISSUE TITLE
ElectrumX is drilling hard drive

### ISSUE THREAD

**Issue by maltokyo** [kyuupichan/electrumx#971]
I have a relatively new 1TB Sata (spinning HDD, not SSD) drive, that stores bitcoin core and ElectrumX DBs.  It is fully synced and operational since months, works well.  But when ElectrumX is up and running, the hard drive makes horrible noises all day and night, the ElectrumX server seems to cause HUGE HDD activity, and it's relentless.  It is not failing hard drive noise, but rather like its constantly copying a large number of small files to it.  Normal, but constant noise 24/7!

That is fine and everything, but I don't think the hard drive will live long like this..  is it normal?  Can anything be done?

**Comment by kyuupichan** [comment]
The blockchain is big and its growth is relentless.  This is just a fact of life.  Try an SSD.
