### ISSUE TITLE
Help with blockchain.address.getbalance

### ISSUE THREAD

**Issue by merclyn** [kyuupichan/electrumx#972]
I know blockchain.address.getbalance is deprecated, and replaced with blockchain.scripthash.getbalance, but im struggling to figure out how to perform a getbalance when I only have an address. How do I convert an address or list of addresses to use with blockchain.scripthash.getbalance

I wont always have access to xpub's, but can always get to addresses (I would want to send all supported addresses including bech32.

Can someone share how to take an address and (I guess) turn it into a scripthash.

Thx in advance, Im sure im missing something simple, need to get over a hump.
(Also sorry to post this as an issue, I know its not)

**Comment by kyuupichan** [comment]
Please see the protocol basics part of the documentation, it gives a simple example.  Or you can look at the old ElectrumX code which did the conversion (for P2SH and P2PKH only).
