### ISSUE TITLE
elif hprevs[0] != chain[0]: not handling multiple orphan blocks in sequence.

### ISSUE THREAD

**Issue by frndxyz** [kyuupichan/electrumx#976]
I am running electrumX for altcoin.

when orphan block occour it first send to electrum-client and then reorg chain.

i fix a way to handle reorg before sending to client.

but it handle only when only 1 orphan block in sequence. but not when multiple orphan blocks in sequence. 

 i mean it send orphan data to client when multiple orphan blocks in sequence.

` async def check_and_advance_blocks(self, raw_blocks):
       
        if not raw_blocks:
            return
        first = self.height + 1
        blocks = [self.coin.block(raw_block, first + n)
                  for n, raw_block in enumerate(raw_blocks)]
        headers = [block.header for block in blocks]
        hprevs = [self.coin.header_prevhash(h) for h in headers]
        chain = [self.tip] + [self.coin.header_hash(h) for h in headers[:-1]]

        if hprevs[0] != chain[0]:
            await self.reorg_chain()
        elif hprevs == chain:
            start = time.time()
            await self.run_in_thread_with_lock(self.advance_blocks, blocks)
            await self._maybe_flush()
            if not self.db.first_sync:
                s = '' if len(blocks) == 1 else 's'
                blocks_size = sum(len(block) for block in raw_blocks) / 1_000_000
                self.logger.info(f'processed {len(blocks):,d} block{s} size {blocks_size:.2f} MB '
                                 f'in {time.time() - start:.1f}s')
            if self._caught_up_event.is_set():
                await self.notifications.on_block(self.touched, self.height)
            self.touched = set()
        else:
            # It is probably possible but extremely rare that what
            # bitcoind returns doesn't form a chain because it
            # reorg-ed the chain as it was processing the batched
            # block hash requests.  Should this happen it's simplest
            # just to reset the prefetcher and try again.
            self.logger.warning('daemon blocks do not form a chain; '
                                'resetting the prefetcher')
            await self.prefetcher.reset_height(self.height) `

here is log: 

INFO:MemPool:1 txs 0.00 MB touching 2 addresses
INFO:Prefetcher:new block height 1,078,320 hash c0b5b33b02af1efae4329327742c8dc1cfd898e2530e9a7a91029233929e6407
INFO:DB:flush #13,192 took 0.0s.  Height 1,078,320 txs: 2,695,021 (+3)
INFO:BlockProcessor:processed 1 block size 0.00 MB in 0.0s
INFO:Prefetcher:new block height 1,078,322 hash c5641e8f26c1d1a406c50319ed269157ec0ca70a31c9ca4967d8a4db1576b0b1
INFO:DB:flush #13,193 took 0.0s.  Height 1,078,322 txs: 2,695,025 (+4)
INFO:BlockProcessor:processed 2 blocks size 0.00 MB in 0.0s
INFO:MemPool:0 txs 0.00 MB touching 0 addresses
INFO:ElectrumX:[1] SSL 103.250.163.73:13135, 0 total
INFO:MemPool:1 txs 0.00 MB touching 2 addresses
INFO:Prefetcher:new block height 1,078,323 hash b26a88b070db3ca73a481535feffc1d3b6f81a41d352693685c5f91f4732d7b1
INFO:BlockProcessor:chain reorg detected
INFO:BlockProcessor:chain was reorganised replacing 2 blocks at heights 1,078,321-1,078,322
INFO:BlockProcessor:read 2 blocks from disk
INFO:BlockProcessor:backed up to height 1,078,320
INFO:History:backing up removed 8 history entries
INFO:DB:backup flush #13,194 took 0.0s.  Height 1,078,320 txs: 2,695,021 (-4)
INFO:Prefetcher:catching up to daemon height 1,078,323 (3 blocks behind)
INFO:Prefetcher:new block height 1,078,323 hash b26a88b070db3ca73a481535feffc1d3b6f81a41d352693685c5f91f4732d7b1

**Comment by kyuupichan** [comment]
This seems to be working fine; it's not clear what you think is wrong or what you think it should do

**Comment by frndxyz** [comment]
> This seems to be working fine; it's not clear what you think is wrong or what you think it should do

I want that it isnt brodcast block to electrum-client if block is orphaned.
