### ISSUE TITLE
No DashRegtest coin

### ISSUE THREAD

**Issue by Moliholy** [kyuupichan/electrumx#977]
Hello!

I've been testing several coins locally in my project, and to check the behaviour is correct I need regtest versions of all of them. It so happened that I didn't find a candidate for Dash, i.e.: "DashRegtest".

Is there any special reason for this?

**Comment by kyuupichan** [comment]
Because you've not submitted a patch

**Comment by Moliholy** [comment]
That was... straight to the point, so as my PR! https://github.com/kyuupichan/electrumx/pull/978
