### ISSUE TITLE
electrumx_rpc query does not return info

### ISSUE THREAD

**Issue by Pega88** [kyuupichan/electrumx#984]
Hi,

Not sure if I'm doing anything wrong, just following the example:
`electrumx_rpc query --limit 5 76a91462e907b15cbf27d5425399ebf6f0fb50ebb88f1888ac`

Does just return this:

```
script 
history 
utxos
balance

```
So I thought it was maybe the hash. A direct netcat call:
```
echo '{"id": 1, "method": "blockchain.scripthash.get_balance", "params": ["b3308ec9eb6b94b333e6aba375f681ad5a9630e823eb82c68e3f1cc38f9ea3fa"]}' | nc localhost 50001 -i 1
```
cleanly returns the balance public explorers also show:
```
{"jsonrpc": "2.0", "result": {"confirmed": 920702874737, "unconfirmed": 0}, "id": 1}
```

however, 

```
electrumx_rpc query b3308ec9eb6b94b333e6aba375f681ad5a9630e823eb82c68e3f1cc38f9ea3fa
```
or any alternations don't give any useful result, it only shows:
```
script
history
utxos
balance
```
as output. Maybe I'm misreading the usage of this 'query' command but from the docs it seems I should be able to use it to read address balance?

**Comment by kyuupichan** [comment]
The query interface doesn't take the hash of a script.  It takes an address or the script in hex.
