### ISSUE TITLE
No module named 'distutils.dir_util'

### ISSUE THREAD

**Issue by Mrshahhaxor** [kyuupichan/electrumx#985]
While i Click on : python3 HiddenEye.py

it gives an Error : 

 Traceback (most recent call last):
  File "HiddenEye.py", line 7, in <module>
    from Defs.Actions import *
  File "/home/mrshah/HiddenEye/Defs/Actions.py", line 6, in <module>
    from distutils.dir_util import copy_tree
ModuleNotFoundError: No module named 'distutils.dir_util'

**Comment by wakiyamap** [comment]
Maybe need this command.
`sudo apt install python3-distutils`

and maybe the place to listen is different.

here?
https://github.com/DarkSecDevelopers/HiddenEye

**Comment by Mrshahhaxor** [comment]
While I Enter the : sudo apt install python3-distutils

it says : 
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 70393 (apt-get)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?


Also installed the new version of HiddenEye from Your given link still have the same problem
