### ISSUE TITLE
Server Reports wrong version

### ISSUE THREAD

**Issue by oitdmser** [kyuupichan/electrumx#998]
I just upgraded to 1.14.0 and I noticed it still reports the version string 1.13.0.

I stopped electrumx, replaced the old electrumx_server with the electrumx_server from the 1.14.0 tree and started the daemon. Both $SERVER_SUBVERSION and $SERVER_VERSION report 1.13

**Comment by SomberNight** [comment]
You might have two versions installed and running the old one.

Run `python3 -m pip uninstall electrumx` multiple times, until it says it cannot find electrumx anymore, and then reinstall.

**Comment by oitdmser** [comment]
Thanks for the follow-up. I thought I had installed it manually by downloading the git repository, running setup.py and copying the resulting files to /usr/local/bin. The files in /usr/local/bin were even exactly the same as in the build/ directory.

I ran `python3 -m pip uninstall electrumx` and the command line reported 1.13 was installed. Perhaps I used pip last time? Anyway, I simply ran python3 -m pip install electrumx -U to upgrade and it is now upgrading the database, indicating to me it updated to 1.14.

To clarify, if electrumx was installed with PIP I cannot upgrade it by downloading the GIT repository and copying the resulting python files to /usr/local/bin?

**Comment by SomberNight** [comment]
> To clarify, if electrumx was installed with PIP I cannot upgrade it by downloading the GIT repository and copying the resulting python files to /usr/local/bin?

You should not manually copy files.
Let pip do its thing.
You can either use pip and rely on PyPI; (e.g. `python3 -m pip install --user electrumx`),
or you can git clone and have an editable install with pip (e.g. `python3 -m pip install --user -e .`).

**Comment by oitdmser** [comment]
> You should not manually copy files.
Let pip do its thing.

Gotcha, thanks, that's very helpful. The HOWTO at [https://electrumx.readthedocs.io/en/latest/HOWTO.html](https://electrumx.readthedocs.io/en/latest/HOWTO.html) doesn't mention pip, so the thought never came to mind. I'm not super familiar with python so I kind of have to bumble around a bit.

Thanks for your help, sorry for the hassle.
